objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>BR_Audit_Authenticity_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only when authenticity of audit statement has been confirmed </inlineHelpText>
        <label>BR Audit Authenticity Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Auth_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only when authenticity of audit statement has been confirmed </inlineHelpText>
        <label>EV Code Signing Audit Auth Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EV_SSL_Audit_Authenticity_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only when authenticity of audit statement has been confirmed </inlineHelpText>
        <label>EV SSL Audit Authenticity Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Authenticity_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only when authenticity of audit statement has been confirmed </inlineHelpText>
        <label>Standard Audit Authenticity Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RootCaseAddUpdateRootCertsControllerTest.cls
/*
    Description: test class for RootCaseAddUpdateRootCertsController
*/
@isTest
private class RootCaseAddUpdateRootCertsControllerTest {
    static testmethod void testAuditFileMethod(){ 
        
        Account caOwnerAcc = TestUtils.getCAOwner();
        insert caOwnerAcc;
        
        Case caseSO = TestUtils.getCase(caOwnerAcc.Id);
        caseSO.Standard_Audit_Authenticity_Confirmed__c = True;
        caseSO.BR_Audit_Authenticity_Confirmed__c = True;
        caseSO.EV_Code_Signing_Audit_Auth_Confirmed__c = True;
        caseSO.EV_SSL_Audit_Authenticity_Confirmed__c = True;
        insert caseSO;
        
        // create the child account - record type = Root
        Account childAccount = TestUtils.getRootCertificate(caOwnerAcc.id);
        childAccount.Name = 'child root account 1';
        childAccount.Status__c = 'Included';
        insert childAccount;
        
        RootCaseAddUpdateRootCertsController newauditrootcases = new RootCaseAddUpdateRootCertsController(new apexpages.standardcontroller(caseSO));
        newauditrootcases.NextToRootCase();
        if(newauditrootcases.lstWrapAllRootCases.size() > 0){
            newauditrootcases.lstWrapAllRootCases[0].objRootCase.Apply_Standard_Audit__c = true;
            newauditrootcases.lstWrapAllRootCases[0].isSelected = true;    
        }
        newauditrootcases.NextToRootCase();
    }
}