objects/Account.object
<CustomObject>
    <fields>
        <fullName>CRL_URL_s__c</fullName>
        <inlineHelpText>URL(s) at which the CRL(s) may be obtained -- for end-entity certs and for intermediate CAs.</inlineHelpText>
        <label>CRL URL(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Common_Name__c</fullName>
        <label>Certificate Issuer Common Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organization__c</fullName>
        <label>Certificate Issuer Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organizational_Unit__c</fullName>
        <label>Certificate Issuer Organizational Unit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Serial_Number__c</fullName>
        <label>Certificate Serial Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Common_Name__c</fullName>
        <description>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</description>
        <inlineHelpText>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</inlineHelpText>
        <label>Certificate Subject Common Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Organization_Unit__c</fullName>
        <label>Certificate Subject Organization Unit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Organization__c</fullName>
        <label>Certificate Subject Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Version__c</fullName>
        <label>Certificate Version</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Extended_Key_Usage__c</fullName>
        <label>Extended Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Extraction_Results__c</fullName>
        <label>Extraction Results</label>
        <length>6000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Issuer__c</fullName>
        <inlineHelpText>Certificate Issuer Common Name + Certificate Issuer Organizational Unit + Certificate Issuer Organization + Certificate Issuer Country</inlineHelpText>
        <label>Issuer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Key_Usage__c</fullName>
        <label>Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Public_Key_Algorithm__c</fullName>
        <label>Public Key Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RSA 1024 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2045 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2046 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2047 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2048 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 3072 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 4096 bits</fullName>
                </value>
                <value>
                    <fullName>EC secp256r</fullName>
                </value>
                <value>
                    <fullName>EC secp256r1</fullName>
                </value>
                <value>
                    <fullName>EC secp384r1</fullName>
                </value>
                <value>
                    <fullName>EC secp512r1</fullName>
                </value>
                <value>
                    <fullName>unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies similar logical certificates in different CA Hierarchies. SHA256(der(spki))</inlineHelpText>
        <label>SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Signature_Hash_Algorithm__c</fullName>
        <label>Signature Hash Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ecdsaWithSHA256</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA384</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA512</fullName>
                </value>
                <value>
                    <fullName>MD2WithRSA</fullName>
                </value>
                <value>
                    <fullName>MD5WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA1WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA256WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA384WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA512WithRSA</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies same logical certificates in different CA Hierarchies. SHA256(der(subject)+der(spki))</inlineHelpText>
        <label>Subject + SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Valid_From_GMT__c</fullName>
        <inlineHelpText>The date from which the root CA certificate is valid.</inlineHelpText>
        <label>Valid From (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Root_Case__c.object
<CustomObject>
    <fields>
        <fullName>Certificate_Issuer_Common_Name__c</fullName>
        <label>Certificate Issuer Common Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Serial_Number__c</fullName>
        <label>Certificate Serial Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Common_Name__c</fullName>
        <label>Certificate Subject Common Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Extended_Key_Usage__c</fullName>
        <label>Extended Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Extraction_Results__c</fullName>
        <label>Extraction Results</label>
        <length>6000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Issuer__c</fullName>
        <inlineHelpText>Certificate Issuer Common Name + Certificate Issuer Organizational Unit + Certificate Issuer Organization + Certificate Issuer Country</inlineHelpText>
        <label>Issuer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Key_Usage__c</fullName>
        <label>Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OU_From_Issuer_Field__c</fullName>
        <description>Organizational Unit</description>
        <inlineHelpText>Organizational Unit</inlineHelpText>
        <label>OU From Issuer Field</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OU_From_Subject_Field__c</fullName>
        <label>OU From Subject Field</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>O_From_Issuer_Field__c</fullName>
        <inlineHelpText>The Organization Name and CN in the Issuer must have sufficient information about the CA Organization.</inlineHelpText>
        <label>O From Issuer Field</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>O_From_Subject_Field__c</fullName>
        <label>O From Subject Field</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Public_Key_Algorithm__c</fullName>
        <label>Public Key Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RSA 1024 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2045 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2046 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2047 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2048 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 3072 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 4096 bits</fullName>
                </value>
                <value>
                    <fullName>EC secp256r</fullName>
                </value>
                <value>
                    <fullName>EC secp256r1</fullName>
                </value>
                <value>
                    <fullName>EC secp384r1</fullName>
                </value>
                <value>
                    <fullName>EC secp512r1</fullName>
                </value>
                <value>
                    <fullName>unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies similar logical certificates in different CA Hierarchies. SHA256(der(spki))</inlineHelpText>
        <label>SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Signature_Hash_Algorithm__c</fullName>
        <label>Signature Hash Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ecdsaWithSHA256</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA384</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA512</fullName>
                </value>
                <value>
                    <fullName>MD2WithRSA</fullName>
                </value>
                <value>
                    <fullName>MD5WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA1WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA256WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA384WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA512WithRSA</fullName>
                </value>
                <value>
                    <fullName>unknown</fullName>
                </value>
                <value>
                    <fullName>md2WithRSAEncryption</fullName>
                    <isActive>false</isActive>
                    <label>md2WithRSAEncryption</label>
                </value>
                <value>
                    <fullName>md5WithRSAEncryption</fullName>
                    <isActive>false</isActive>
                    <label>md5WithRSAEncryption</label>
                </value>
                <value>
                    <fullName>sha1WithRSAEncryption</fullName>
                    <isActive>false</isActive>
                    <label>sha1WithRSAEncryption</label>
                </value>
                <value>
                    <fullName>sha256WithRSAEncryption</fullName>
                    <isActive>false</isActive>
                    <label>sha256WithRSAEncryption</label>
                </value>
                <value>
                    <fullName>sha384WithRSAEncryption</fullName>
                    <isActive>false</isActive>
                    <label>sha384WithRSAEncryption</label>
                </value>
                <value>
                    <fullName>sha512WithRSAEncryption</fullName>
                    <isActive>false</isActive>
                    <label>sha512WithRSAEncryption</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies same logical certificates in different CA Hierarchies. SHA256(der(subject)+der(spki))</inlineHelpText>
        <label>Subject + SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Root Case</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Root Case No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RootCasePEMParserBatch.cls
/*
    Description: Batch program to parse PEM info using PEMParserController
    
    If PEM info (x509 field) is not null then add to the batch processing
*/

global class RootCasePEMParserBatch implements Database.Batchable<sObject>,Database.AllowsCallouts{

    global final String Query;
    
    global RootCasePEMParserBatch(String q){
        Query = q;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Root_Case__c> lstRootCases){
        
        List<Root_Case__c> lstRootCasesToUpdate = new List<Root_Case__c>();
        
        for(Root_Case__c rootCase : lstRootCases){
            
            if(rootCase.X_509_Certificate_PEM__c != null) {
                
                Root_Case__c rootCaseToUpdate = new Root_Case__c();
                Account tempAccount = PEMParserController.parsePEM(rootCase.X_509_Certificate_PEM__c);
                rootCaseToUpdate.Extraction_Results__c = tempAccount.Extraction_Results__c;
                
                // Issuer Info
                rootCaseToUpdate.Certificate_Issuer_Common_Name__c = tempAccount.Certificate_Issuer_Common_Name__c;
                rootCaseToUpdate.O_From_Issuer_Field__c = tempAccount.Certificate_Issuer_Organization__c;
                rootCaseToUpdate.OU_From_Issuer_Field__c = tempAccount.Certificate_Issuer_Organizational_Unit__c;
                rootCaseToUpdate.Issuer__c = tempAccount.Issuer__c;
                
                // Subject Info
                rootCaseToUpdate.Certificate_Subject_Common_Name__c = tempAccount.Certificate_Subject_Common_Name__c;              
                rootCaseToUpdate.OU_From_Subject_Field__c = tempAccount.Certificate_Subject_Organization_Unit__c;
                rootCaseToUpdate.O_From_Subject_Field__c = tempAccount.Certificate_Subject_Organization__c;
                rootCaseToUpdate.Subject__c = tempAccount.Subject__c;
                
                // Fingerprint Info      
                rootCaseToUpdate.SHA_1_Fingerprint__c = tempAccount.SHA_1_Fingerprint__c;
                rootCaseToUpdate.SHA_256_Fingerprint__c = tempAccount.SHA_256_Fingerprint__c;
                rootCaseToUpdate.SPKI_SHA256__c = tempAccount.SPKI_SHA256__c;
                rootCaseToUpdate.Subject_SPKI_SHA256__c = tempAccount.Subject_SPKI_SHA256__c;
                
                // Valid From and To Dates
                rootCaseToUpdate.Valid_From__c = tempAccount.Valid_From_GMT__c;
                rootCaseToUpdate.Valid_To__c = tempAccount.Valid_To_GMT__c;
                
                // Common fields              
                rootCaseToUpdate.Public_Key_Algorithm__c = tempAccount.Public_Key_Algorithm__c ;            
                rootCaseToUpdate.Signature_Hash_Algorithm__c = tempAccount.Signature_Hash_Algorithm__c;
                rootCaseToUpdate.Certificate_Serial_Number__c = tempAccount.Certificate_Serial_Number__c; 
                //rootCaseToUpdate.Certificate_Fingerprint__c = tempAccount.Certificate_ID__c;
                //rootCaseToUpdate.Certificate_Version__c = tempAccount.Certificate_Version__c;
                rootCaseToUpdate.Key_Usage__c = tempAccount.Key_Usage__c ;
                rootCaseToUpdate.Extended_Key_Usage__c = tempAccount.Extended_Key_Usage__c;        
                
                //crl urls
                //rootCaseToUpdate.CRL_URL_s__c = tempAccount.CRL_URL_s__c;
                
                //Technally constrained
                rootCaseToUpdate.Technically_Constrained__c = tempAccount.Technically_Constrained__c;
                
                rootCaseToUpdate.Id = rootCase.Id;
                lstRootCasesToUpdate.add(rootCaseToUpdate);
            }
        }
        if(lstRootCasesToUpdate.size() > 0){
            update lstRootCasesToUpdate;
        }
    }
    
    global void finish(Database.BatchableContext BC){
    }
}