objects/Account.object
<CustomObject>
    <fields>
        <fullName>Extended_Key_Usage__c</fullName>
        <label>Extended Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Microsoft_Root_Status__c</fullName>
        <inlineHelpText>This is Root Status on Intermediate Cert, updated via batch program</inlineHelpText>
        <label>Microsoft Root Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mozilla_Root_Status__c</fullName>
        <inlineHelpText>This is Root Status on Intermediate Cert, updated via batch program</inlineHelpText>
        <label>Mozilla Root Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies same logical certificates in different CA Hierarchies. SHA256(der(subject)+der(spki))</inlineHelpText>
        <label>Subject + SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Technically_Constrained__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Technically Constrained</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DoppelgangerReportControllerTest.cls
/*******************************************************************************************************
 Name: DoppelgangerReportControllerTest

 Dependencies: DoppelgangerReportController controller class, DoppelgangerReport vf page, RSHomePageControllerTest test class

 Revision History:
 
     10/9/2019 - Created new class
 ******************************************************************************************************/
 
@isTest
public with sharing class DoppelgangerReportControllerTest {
    
    static testmethod void TestDoppelgangerReport() {
        Lead lead = new Lead(LastName = 'Test Lead',Company = 'Test Company', Email = 'test@gmail.com');
        insert lead;
        
        Account acc = TestUtils.getCAOwner();
        acc.Status__c = 'Included';
        insert acc;
        
        // create a ROOT CA
        Account rootCA = TestUtils.getRootCertificate(acc.Id); 
        rootCa.X_509_Certificate_PEM__c = 'Root';
        rootCa.Status__c = 'Included';
        rootCa.Trust_Bits__c = 'Websites';
        rootCa.Subject_SPKI_SHA256__c = 'C90FBC2664485F6D3175055A45EF10D2EB6E6C7E027DF1A1D526458C42F42696';
        rootCa.Mozilla_Root_Status__c = 'Included';
        rootCa.Microsoft_Root_Status__c = 'Included';
        insert rootCa;
        
        Test.startTest(); 
        
        // create intermediate CA
        Account testAccount = TestUtils.getIntermediateCertificate(rootCa.Id);
        testAccount.X_509_Certificate_PEM__c = 'Inter Cert 1';
        testAccount.Subject_SPKI_SHA256__c = 'C90FBC2664485F6D3175055A45EF10D2EB6E6C7E027DF1A1D526458C42F42697';
        testAccount.Extended_Key_Usage__c = 'ExtKeyUsageEmailProtection,ExtKeyUsageClientAuth';
        testAccount.SHA_1_Fingerprint__c = '1234567890123456789012345678901234596352';
        testAccount.Revocation_Status__c = 'Not Revoked';
        testAccount.Valid_To_GMT__c = System.Today().addYears(1);
        testAccount.Technically_Constrained__c  = true;
        testAccount.Mozilla_Root_Status__c = 'Included';
        testAccount.Microsoft_Root_Status__c = 'Included';
        insert testAccount; 
        
        testAccount = TestUtils.getIntermediateCertificate(rootCa.Id);
        testAccount.X_509_Certificate_PEM__c = 'Inter Cert 2';
        testAccount.Subject_SPKI_SHA256__c = 'C90FBC2664485F6D3175055A45EF10D2EB6E6C7E027DF1A1D526458C42F42697';
        testAccount.Extended_Key_Usage__c = 'ExtKeyUsageEmailProtection,ExtKeyUsageClientAuth';
        testAccount.SHA_1_Fingerprint__c = '12345678901234567890123456789012345753185';
        testAccount.Revocation_Status__c = 'Not Revoked';
        testAccount.Valid_To_GMT__c = System.Today().addYears(1);
        testAccount.Mozilla_Root_Status__c = 'Included';
        testAccount.Microsoft_Root_Status__c = 'Included';
        insert testAccount; 
        
        DoppelgangerReportController controller = new DoppelgangerReportController();
        
        Test.stopTest(); 
    }
    
}