objects/Account.object
<CustomObject>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRL_URL_s__c</fullName>
        <inlineHelpText>URL(s) at which the CRL(s) may be obtained -- for end-entity certs and for intermediate CAs.</inlineHelpText>
        <label>CRL URL(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Common_Name__c</fullName>
        <label>Certificate Issuer Common Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organization__c</fullName>
        <label>Certificate Issuer Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organizational_Unit__c</fullName>
        <label>Certificate Issuer Organizational Unit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Serial_Number__c</fullName>
        <label>Certificate Serial Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Common_Name__c</fullName>
        <description>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</description>
        <inlineHelpText>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</inlineHelpText>
        <label>Certificate Subject Common Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Organization_Unit__c</fullName>
        <label>Certificate Subject Organization Unit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Organization__c</fullName>
        <label>Certificate Subject Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_of_Revocation__c</fullName>
        <label>Date of Revocation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_Warning_or_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by VF page to display warnings or messages</description>
        <label>Display Warning or Message</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Webservice_Failed_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by Account trigger helper class</description>
        <label>Display Webservice Failed Message</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Webservice_Not_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by Account trigger helper class</description>
        <label>Display Webservice Not Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Extended_Key_Usage__c</fullName>
        <label>Extended Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Extraction_Results__c</fullName>
        <label>Extraction Results</label>
        <length>6000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Key_Usage__c</fullName>
        <label>Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Public_Key_Algorithm__c</fullName>
        <label>Public Key Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RSA 1024 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2045 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2046 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2047 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2048 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 3072 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 4096 bits</fullName>
                </value>
                <value>
                    <fullName>EC secp256r</fullName>
                </value>
                <value>
                    <fullName>EC secp256r1</fullName>
                </value>
                <value>
                    <fullName>EC secp384r1</fullName>
                </value>
                <value>
                    <fullName>EC secp512r1</fullName>
                </value>
                <value>
                    <fullName>unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFC_5280_Revocation_Reason_Code__c</fullName>
        <inlineHelpText>Provide the reason for the certificate revocation. Value 7 is not being used.</inlineHelpText>
        <label>RFC 5280 Revocation Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>(0) unspecified</fullName>
                </value>
                <value>
                    <fullName>(1) keyCompromise</fullName>
                </value>
                <value>
                    <fullName>(2) cACompromise</fullName>
                </value>
                <value>
                    <fullName>(3) affiliationChanged</fullName>
                </value>
                <value>
                    <fullName>(4) superseded</fullName>
                </value>
                <value>
                    <fullName>(5) cessationOfOperation</fullName>
                </value>
                <value>
                    <fullName>(6) certificateHold</fullName>
                </value>
                <value>
                    <fullName>(8) removeFromCRL</fullName>
                </value>
                <value>
                    <fullName>(9) privilegeWithdrawn</fullName>
                </value>
                <value>
                    <fullName>(10) aACompromise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Signature_Hash_Algorithm__c</fullName>
        <label>Signature Hash Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ecdsaWithSHA256</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA384</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA512</fullName>
                </value>
                <value>
                    <fullName>MD2WithRSA</fullName>
                </value>
                <value>
                    <fullName>MD5WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA1WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA256WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA384WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA512WithRSA</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technically_Constrained__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Technically Constrained</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Valid_From_GMT__c</fullName>
        <inlineHelpText>The date from which the root CA certificate is valid.</inlineHelpText>
        <label>Valid From (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Migrate_Certs__c.object
<CustomObject>
    <description>Staging object to migrate certificates</description>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Revocation__c</fullName>
        <label>Date of Revocation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Extraction_Results__c</fullName>
        <label>Extraction Results</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RFC_5280_Revocation_Reason_Code__c</fullName>
        <label>RFC 5280 Revocation Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>(0) unspecified</fullName>
                </value>
                <value>
                    <fullName>(1) keyCompromise</fullName>
                </value>
                <value>
                    <fullName>(2) cACompromise</fullName>
                </value>
                <value>
                    <fullName>(3) affiliationChanged</fullName>
                </value>
                <value>
                    <fullName>(4) superseded</fullName>
                </value>
                <value>
                    <fullName>(5) cessationOfOperation</fullName>
                </value>
                <value>
                    <fullName>(6) certificateHold</fullName>
                </value>
                <value>
                    <fullName>(8) removeFromCRL</fullName>
                </value>
                <value>
                    <fullName>(9) privilegeWithdrawn</fullName>
                </value>
                <value>
                    <fullName>(10) aACompromise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Added to OneCRL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <label>Migrate Cert</label>
    <nameField>
        <label>Migrate Cert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Migrate Certs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MigrateCertBatchHelper.cls
/*
MigrateCertBatchHelper used by MigrateCertsBatch

Populate account from Certificate checker web service and Migrate Certs object

*/

public class MigrateCertBatchHelper{

    /**
    @Method : Populates data in existing certificate record with data provided by CertificateChecker utility and Migrate Certs object
    **/
     public static Account populateInterCertAccount(Account acct, String certName, String pemInfo, Id parentId, Id recTypeId, Migrate_Certs__c migCert){
         Account acctToUpdate = new Account();
         acctToUpdate.Name = certName;
         acctToUpdate.ParentId = parentId;
         acctToUpdate.RecordTypeId = recTypeId;
         acctToUpdate.Extraction_Results__c = acct.Extraction_Results__c ;
         acctToUpdate.Display_Warning_or_Message__c = acct.Display_Warning_or_Message__c;
         acctToUpdate.Display_Webservice_Not_Available__c = acct.Display_Webservice_Not_Available__c;
         acctToUpdate.Display_Webservice_Failed_Message__c = acct.Display_Webservice_Failed_Message__c;
         acctToUpdate.Certificate_Issuer_Common_Name__c = acct.Certificate_Issuer_Common_Name__c;
         acctToUpdate.Certificate_Issuer_Organizational_Unit__c = acct.Certificate_Issuer_Organizational_Unit__c;
         acctToUpdate.Certificate_Issuer_Organization__c = acct.Certificate_Issuer_Organization__c;
         acctToUpdate.Certificate_Subject_Common_Name__c = acct.Certificate_Subject_Common_Name__c;
         acctToUpdate.Certificate_Subject_Organization_Unit__c = acct.Certificate_Subject_Organization_Unit__c;
         acctToUpdate.Certificate_Subject_Organization__c = acct.Certificate_Subject_Organization__c;
         acctToUpdate.SHA_1_Fingerprint__c = acct.SHA_1_Fingerprint__c;
         acctToUpdate.SHA_256_Fingerprint__c= acct.SHA_256_Fingerprint__c;
         //acctToUpdate.Certificate_ID__c= acct.Certificate_ID__c;
         acctToUpdate.Valid_From_GMT__c = acct.Valid_From_GMT__c;
         acctToUpdate.Valid_To_GMT__c = acct.Valid_To_GMT__c;
         // to be deleted acctToUpdate.Signing_Key_Parameters__c = acct.Signing_Key_Parameters__c;
         // to be deleted  acctToUpdate.Signature_Algorithm__c = acct.Signature_Algorithm__c; 
         acctToUpdate.Signature_Hash_Algorithm__c = acct.Signature_Hash_Algorithm__c;
         acctToUpdate.Certificate_Serial_Number__c = acct.Certificate_Serial_Number__c;                        
         //acctToUpdate.Basic_Constraints__c = acct.Basic_Constraints__c;
         acctToUpdate.Public_Key_Algorithm__c = acct.Public_Key_Algorithm__c;
         acctToUpdate.Key_Usage__c = acct.Key_Usage__c;
         acctToUpdate.Extended_Key_Usage__c = acct.Extended_Key_Usage__c;
         //acctToUpdate.OCSP_URL_s__c = acct.OCSP_URL_s__c;
         acctToUpdate.CRL_URL_s__c = acct.CRL_URL_s__c;
         acctToUpdate.Technically_Constrained__c = acct.Technically_Constrained__c;        
         
         acctToUpdate.Status__c = 'Provided by CA';
         
         if(acct.Revocation_Status__c == 'None'){
             acctToUpdate.Revocation_Status__c = 'Not Revoked';
         }
         else{
             acctToUpdate.Revocation_Status__c = migCert.Revocation_Status__c;
         }
                 
        acctToUpdate.Date_of_Revocation__c = migCert.Date_of_Revocation__c ;        
        acctToUpdate.RFC_5280_Revocation_Reason_Code__c = migCert.RFC_5280_Revocation_Reason_Code__c;
        acctToUpdate.Audits_Same_as_Parent__c = migCert.Audits_Same_as_Parent__c;
        acctToUpdate.Standard_Audit__c = migCert.Standard_Audit__c;
        acctToUpdate.Standard_Audit_Type__c = migCert.Standard_Audit_Type__c;
        acctToUpdate.Standard_Audit_Statement_Date__c = migCert.Standard_Audit_Statement_Date__c;
        acctToUpdate.BR_Audit__c = migCert.BR_Audit__c;
        acctToUpdate.BR_Audit_Type__c = migCert.BR_Audit_Type__c;
        acctToUpdate.BR_Audit_Statement_Date__c = migCert.BR_Audit_Statement_Date__c; 
        acctToUpdate.Auditor__c = migCert.Auditor__c;
        acctToUpdate.Auditor_Website__c = migCert.Auditor_Website__c;
        acctToUpdate.Auditor_Qualifications__c = migCert.Auditor_Qualifications__c;
        //acctToUpdate.Management_Assertions_By__c = migCert.Management_Assertions_By__c;
        acctToUpdate.EV_Audit__c = migCert.EV_Audit__c;
        acctToUpdate.EV_Audit_Type__c = migCert.EV_Audit_Type__c;
        acctToUpdate.EV_Audit_Statement_Date__c = migCert.EV_Audit_Statement_Date__c; 
        acctToUpdate.CP_CPS_Same_as_Parent__c = migCert.CP_CPS_Same_as_Parent__c; 
        acctToUpdate.Policy_Documentation__c = migCert.Policy_Documentation__c;
        acctToUpdate.CA_Document_Repository__c = migCert.CA_Document_Repository__c;
        acctToUpdate.Certificate_Policy_CP__c = migCert.Certificate_Policy_CP__c;
        acctToUpdate.Certification_Practice_Statement_CPS__c = migCert.Certification_Practice_Statement_CPS__c;
        acctToUpdate.Description = migCert.Description__c;
        acctToUpdate.Comments__c = migCert.Comments__c;
        acctToUpdate.X_509_Certificate_PEM__c = pemInfo;
        acctToUpdate.Display_PEM_Info_Warning_Message__c = False;
        if (migCert.Migrated_Certs_OwnerId__c != null)
            acctToUpdate.OwnerId = migCert.Migrated_Certs_OwnerId__c;
         
        return acctToUpdate;
     
     }
     
     public static Account populateRootCertAccount(Id recordId, Account pemInfo, String pemString){
     
         Account acctToUpdate = new Account();      
         
         acctToUpdate.id = recordId;
         acctToUpdate.Certificate_Issuer_Common_Name__c = pemInfo.Certificate_Issuer_Common_Name__c;
         acctToUpdate.Certificate_Issuer_Organizational_Unit__c = pemInfo.Certificate_Issuer_Organizational_Unit__c;
         acctToUpdate.Certificate_Issuer_Organization__c = pemInfo.Certificate_Issuer_Organization__c;
         acctToUpdate.Certificate_Subject_Common_Name__c = pemInfo.Certificate_Subject_Common_Name__c;
         acctToUpdate.Certificate_Subject_Organization_Unit__c = pemInfo.Certificate_Subject_Organization_Unit__c;
         acctToUpdate.Certificate_Subject_Organization__c = pemInfo.Certificate_Subject_Organization__c;
         acctToUpdate.Subject__c = pemInfo.Subject__c; 
         acctToUpdate.SHA_1_Fingerprint__c = pemInfo.SHA_1_Fingerprint__c;
         acctToUpdate.SHA_256_Fingerprint__c= pemInfo.SHA_256_Fingerprint__c;
         //acctToUpdate.Certificate_ID__c= pemInfo.Certificate_ID__c;
         acctToUpdate.Valid_From_GMT__c = pemInfo.Valid_From_GMT__c;
         acctToUpdate.Valid_To_GMT__c = pemInfo.Valid_To_GMT__c;
         // to be deleted acctToUpdate.Signing_Key_Parameters__c = pemInfo.Signing_Key_Parameters__c;         
         // to be deleted acctToUpdate.Signature_Algorithm__c = pemInfo.Signature_Algorithm__c; 
         acctToUpdate.Certificate_Serial_Number__c = pemInfo.Certificate_Serial_Number__c;
         acctToUpdate.Signature_Hash_Algorithm__c = pemInfo.Signature_Hash_Algorithm__c;
         //acctToUpdate.Basic_Constraints__c = pemInfo.Basic_Constraints__c;
         acctToUpdate.Public_Key_Algorithm__c = pemInfo.Public_Key_Algorithm__c;
         acctToUpdate.Key_Usage__c = pemInfo.Key_Usage__c;
         acctToUpdate.Extended_Key_Usage__c = pemInfo.Extended_Key_Usage__c;
         //acctToUpdate.OCSP_URL_s__c = pemInfo.OCSP_URL_s__c;
         acctToUpdate.CRL_URL_s__c = pemInfo.CRL_URL_s__c;
         acctToUpdate.Technically_Constrained__c = pemInfo.Technically_Constrained__c;      
         acctToUpdate.X_509_Certificate_PEM__c = pemString;
         acctToUpdate.Extraction_Results__c = pemInfo.Extraction_Results__c ;
         acctToUpdate.Display_PEM_Info_Warning_Message__c = False;
         acctToUpdate.Display_Warning_or_Message__c = pemInfo.Display_Warning_or_Message__c;
         acctToUpdate.Display_Webservice_Not_Available__c = pemInfo.Display_Webservice_Not_Available__c;
         acctToUpdate.Display_Webservice_Failed_Message__c = pemInfo.Display_Webservice_Failed_Message__c;
      
         return acctToUpdate;
     }
     
     public static String CheckForNullFields (Account ExistingRoot, Account MigrateRoot){
     
         String NullFieldErrorMessage = '';
       
         if (ExistingRoot.Name != null &&
             MigrateRoot.Name == null) {
             NullFieldErrorMessage += 'Certificate Name ';
         }
         
         if (ExistingRoot.Certificate_Subject_Common_Name__c != null &&
             MigrateRoot.Certificate_Subject_Common_Name__c == null) {
             NullFieldErrorMessage += 'Certificate Subject Common Name ';
         }
         
         if (ExistingRoot.Certificate_Subject_Organization__c != null &&
             MigrateRoot.Certificate_Subject_Organization__c == null) {
             NullFieldErrorMessage += 'Certificate Subject Organization ';
         }
         
         if (ExistingRoot.Certificate_Subject_Organization_Unit__c != null &&
             MigrateRoot.Certificate_Subject_Organization_Unit__c == null) {
             NullFieldErrorMessage += 'Certificate Subject Organization Unit ';
         }
         
         if (ExistingRoot.Certificate_Issuer_Common_Name__c != null &&
             MigrateRoot.Certificate_Issuer_Common_Name__c == null) {
             NullFieldErrorMessage += 'Certificate Issuer Common Name ';
         }
         
         if (ExistingRoot.Certificate_Issuer_Organization__c != null &&
             MigrateRoot.Certificate_Issuer_Organization__c == null) {
             NullFieldErrorMessage += 'Certificate Issuer Organization ';
         }
         
         if (ExistingRoot.Certificate_Issuer_Organizational_Unit__c != null &&
             MigrateRoot.Certificate_Issuer_Organizational_Unit__c == null) {
             NullFieldErrorMessage += 'Certificate Issuer Organizational Unit ';
         }
         
         if (ExistingRoot.Subject__c != null &&
             MigrateRoot.Subject__c == null) {
             NullFieldErrorMessage += 'Subject ';
         }
         
         if (ExistingRoot.SHA_1_Fingerprint__c != null &&
             MigrateRoot.SHA_1_Fingerprint__c == null) {
             NullFieldErrorMessage += 'SHA-1 Fingerprint ';
         }
         
         if (ExistingRoot.SHA_256_Fingerprint__c != null &&
             MigrateRoot.SHA_256_Fingerprint__c == null) {
             NullFieldErrorMessage += 'SHA-56 Fingerprint ';
         }
         
         /*if (ExistingRoot.Certificate_ID__c != null &&
             MigrateRoot.Certificate_ID__c == null) {
             NullFieldErrorMessage += 'Certificate ID ';
         }*/
         
         if (ExistingRoot.Valid_From_GMT__c != null &&
             MigrateRoot.Valid_From_GMT__c == null) {
             NullFieldErrorMessage += 'Valid From GMT ';
         }
         
         if (ExistingRoot.Valid_To_GMT__c != null &&
             MigrateRoot.Valid_To_GMT__c == null) {
             NullFieldErrorMessage += 'Valid To GMT ';
         }
         
         if (ExistingRoot.Certificate_Serial_Number__c != null &&
             MigrateRoot.Certificate_Serial_Number__c == null) {
             NullFieldErrorMessage += 'Certificate Serial Number ';
         }
         
         if (ExistingRoot.Signature_Hash_Algorithm__c != null &&
             MigrateRoot.Signature_Hash_Algorithm__c == null) {
             NullFieldErrorMessage += 'Signature Hash Algorithm ';
         }
         
         /*if (ExistingRoot.Basic_Constraints__c != null &&
             MigrateRoot.Basic_Constraints__c == null) {
             NullFieldErrorMessage += 'Basic Constraints ';
         }*/
         
         if (ExistingRoot.Public_Key_Algorithm__c != null &&
             MigrateRoot.Public_Key_Algorithm__c == null) {
             NullFieldErrorMessage += 'Public Key Algorithm ';
         }
         
         /*if (ExistingRoot.OCSP_URL_s__c != null &&
             MigrateRoot.OCSP_URL_s__c == null) {
             NullFieldErrorMessage += 'OCSP URL(s) ';
         }*/
         
         if (ExistingRoot.CRL_URL_s__c != null &&
             MigrateRoot.CRL_URL_s__c == null) {
             NullFieldErrorMessage += 'CRL URL(s) ';
         }
         
       
         if (NullFieldErrorMessage != '')
             NullFieldErrorMessage = 'Exisiting root has data but the migrating cert has following field(s) null: ' + NullFieldErrorMessage;
              
         return NullFieldErrorMessage;
     }
}