objects/Account.object
<CustomObject>
    <fields>
        <fullName>CA_Email_Alias_1__c</fullName>
        <inlineHelpText>CA Email Alias 1 and 2 are used to reach more than one person in your organization tol receive notifications in case the primary contact is out of the office or leaves the organization.</inlineHelpText>
        <label>CA Email Alias 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CA_Email_Alias_2__c</fullName>
        <inlineHelpText>CA Email Alias 1 and 2 are used to reach more than one person in your organization tol receive notifications in case the primary contact is out of the office or leaves the organization.</inlineHelpText>
        <label>CA Email Alias 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CA_Owner_ID__c</fullName>
        <description>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</description>
        <inlineHelpText>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</inlineHelpText>
        <label>CA Owner ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Website__c</fullName>
        <inlineHelpText>Website URL</inlineHelpText>
        <label>Company Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Geographic_Focus__c</fullName>
        <label>Geographic Focus</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Organizational_Type__c</fullName>
        <inlineHelpText>Indicate the type of organization operating this CA.</inlineHelpText>
        <label>Organizational Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Private Corporation</fullName>
                </value>
                <value>
                    <fullName>Public Corporation</fullName>
                </value>
                <value>
                    <fullName>Government Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Organization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Market_Customer_Base__c</fullName>
        <inlineHelpText>Indicates what types of customers does the CA serve?
Are there particular vertical market segments in which it operates?
Does the CA focus its activities on a particular country or other geographic region?</inlineHelpText>
        <label>Primary Market / Customer Base</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Valid_From_GMT__c</fullName>
        <inlineHelpText>The date from which the root CA certificate is valid.</inlineHelpText>
        <label>Valid From (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CA_Email_Alias_1__c</fullName>
        <inlineHelpText>CA Email Alias 1 and 2 is needed so that more than one person in your organization will receive notifications in case the primary contact is out of the office or leaves the organization.</inlineHelpText>
        <label>CA Email Alias 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Company_Website__c</fullName>
        <defaultValue>&quot;http://NEED: URL to company website&quot;</defaultValue>
        <description>Website URL</description>
        <inlineHelpText>Website URL</inlineHelpText>
        <label>Company Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Geographic_Focus__c</fullName>
        <defaultValue>&quot;NEED: Country or geographic region where CA typically sells certs.&quot;</defaultValue>
        <label>Geographic Focus</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Organizational_Type__c</fullName>
        <inlineHelpText>Indicate the type of organization operating this CA.</inlineHelpText>
        <label>Organizational Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Private Corporation</fullName>
                </value>
                <value>
                    <fullName>Public Corporation</fullName>
                </value>
                <value>
                    <fullName>Government Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Organization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Market_Customer_Base__c</fullName>
        <defaultValue>&quot;NEED:&quot; + BR() + 
&quot;- Which types of customers does the CA serve? &quot; + BR() + 
&quot;- Are there particular vertical market segments in which it operates? &quot; + BR() + 
&quot;- Does the CA focus its activities on a particular country or other geographic region?&quot;</defaultValue>
        <inlineHelpText>Which types of customers does the CA serve?
Are there particular vertical market segments in which it operates?
Does the CA focus its activities on a particular country or other geographic region?</inlineHelpText>
        <label>Primary  Market / Customer Base</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CA_Email_Alias_1__c</fullName>
        <formula>Account.CA_Email_Alias_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CA Email Alias 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CA_Email_Alias_2__c</fullName>
        <formula>Account.CA_Email_Alias_2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CA Email Alias 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>A CA may have more than one person filling the role of Primary Point of Contact (POC), and may use a contractor as one of the POCs.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary POC</fullName>
                </value>
                <value>
                    <fullName>POC</fullName>
                </value>
                <value>
                    <fullName>Auditor</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mass_Email__c.object
<CustomObject>
    <fields>
        <fullName>CC_To__c</fullName>
        <label>CC To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Primary POCs</fullName>
                </value>
                <value>
                    <fullName>All POCs</fullName>
                </value>
                <value>
                    <fullName>CA Email Alias 1</fullName>
                </value>
                <value>
                    <fullName>CA Email Alias 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <inlineHelpText>This field holds the &quot;Display Name&quot; from the Organization-Wide Email Addresses defined in your org.</inlineHelpText>
        <label>From</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CCADB Support</fullName>
                    <default>true</default>
                    <label>CCADB Support</label>
                </value>
                <value>
                    <fullName>Apple CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Cisco CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Google CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Microsoft CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Mozilla CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Current User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reply_To__c</fullName>
        <label>Reply To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reply-To Apple CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Reply-To Cisco CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Reply-To Google CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Reply-To Microsoft CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Reply-To Mozilla CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Current User</fullName>
                    <default>true</default>
                    <label>Current User</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOQL_Filter_Conditions__c</fullName>
        <label>SOQL Filter Conditions</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Send_To__c</fullName>
        <label>Send To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Primary POCs</fullName>
                </value>
                <value>
                    <fullName>All POCs</fullName>
                </value>
                <value>
                    <fullName>CA Email Alias 1</fullName>
                </value>
                <value>
                    <fullName>CA Email Alias 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <label>Mass Email</label>
    <nameField>
        <displayFormat>E{0000}</displayFormat>
        <label>Mass Email Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassEmailControllerTest.cls
/**

Test Case for the following Controller Extension:
MassEmailController
MassEmailBatch
MassEmailBatchHelper
MassEmailAccountFilterController

**/

@isTest 
public class MassEmailControllerTest{

    static testMethod void validateMassEmailAccountFilter() {
    
        PageReference pref = Page.MassEmailAccountFilter;
        Test.setCurrentPage(pref);
        Test.setCurrentPageReference(pref); 
        Mass_Email__c massEmailSo=    createMassEmail();
        System.currentPageReference().getParameters().put('id', massEmailSo.id);
        MassEmailAccountFilterController mafc = new MassEmailAccountFilterController();
        mafc.fetchAccounts();
        mafc.goBackToMassEmailRecord();
        ApexPages.StandardController sc = new ApexPages.StandardController(massEMailSo);
        MassEmailAccountFilterController mafc2 = new MassEmailAccountFilterController(sc);
        
        system.assertNotEquals(mafc.myComponentController,null);
    }
    
    static testMethod void validateMassEmailProgram() {
    
        PageReference pref = Page.MassEmail;
        Test.setCurrentPage(pref);
        Test.setCurrentPageReference(pref); 
        Mass_Email__c massEmailSo=    createMassEmail();
        System.currentPageReference().getParameters().put('id',massEmailSo.id );
        System.currentPageReference().getParameters().put('isPreview', 'false');
        
        Account parentAccount =  getParentAccount();
        insert parentAccount;   
        Contact primaryPOC =getParentContact(parentAccount.id,'Primary POC');
        insert primaryPOC;
        Contact poc = getParentContact(parentAccount.id,'POC');
        insert poc;
        
        MassEmailController mec = new MassEmailController(new Apexpages.standardcontroller(massEmailSo));
        //mec.massEmailHandler();
        mec.cancel();
        mec.startBatchConfirmation();
        
        mec.startBatch();
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', UserName= DateTime.now().getTime() +'standarduser@testorg.com');
        insert u;
        MassEmailBatchHelper.createTask('test','test',u.id,parentAccount.id);
    }
  
    static testMethod void validateMassEmailProgram2() {
  
        PageReference pref = Page.MassEmail;
        Test.setCurrentPage(pref);
        Test.setCurrentPageReference(pref); 
        Mass_Email__c massEmailSo =    createMassEmail2();
        System.currentPageReference().getParameters().put('id',massEmailSo.id );
        System.currentPageReference().getParameters().put('isPreview', 'false');
        
        Account parentAccount =  getParentAccount();
        insert parentAccount;   
        Account rootAccount =  getRootAccount();
        rootAccount.ca_owner_id__c = parentAccount.id;
        insert rootAccount;   
        
        Contact primaryPOC =getParentContact(parentAccount.id,'Primary POC');
        insert primaryPOC;
        Contact poc = getParentContact(parentAccount.id,'POC');
        insert poc;
        
        MassEmailController mec = new MassEmailController(new Apexpages.standardcontroller(massEmailSo));
        //mec.massEmailHandler();
        mec.cancel();
        mec.startBatchConfirmation();
        mec.startBatch();
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName= DateTime.now().getTime() +'standarduser@testorg.com');
        insert u;
        MassEmailBatchHelper.createTask('test','test',u.id,parentAccount.id);
    }
   
    
    Public static Mass_Email__c createMassEmail() {
  
        Mass_Email__c massEmailSo = new Mass_Email__c();
        massEmailSo.CC_To__c = 'All POCs;CA Email Alias 2';
        // massEmailSo.From__c = 'abc@xyz.com';
        massEmailSo.from__c = 'Mozilla CA Program Manager';
        massEmailSo.message__c = 'Dear Someone,Testing custom mass emails. Regards,Mozilla';
        massEmailSo.reply_to__c = 'Mozilla CA Program Manager ';
        massEmailSo.Send_To__c = 'All Primary POCs;CA Email Alias 1';
        
        massEmailSo.Subject__c = 'Testing Mass Email';
        insert massEmailSo;
        return massEmailSo;
    }

    Public static Mass_Email__c createMassEmail2() {
        Mass_Email__c massEmailSo = new Mass_Email__c();
        massEmailSo.CC_To__c = 'All POCs;CA Email Alias 2';
        // massEmailSo.From__c = 'abc@xyz.com';
        massEmailSo.from__c = 'Mozilla CA Program Manager';
        massEmailSo.message__c = 'Dear Someone,Testing custom mass emails. Regards,Mozilla';
        massEmailSo.reply_to__c = 'Current User';
        massEmailSo.Send_To__c = 'All Primary POCs;CA Email Alias 1';
        massEmailSo.SOQL_Filter_Conditions__c = 'Record_Type_Name__c=\'Intermediate Certificate\'';
        massEmailSo.Subject__c = 'Testing Mass Email';
        insert massEmailSo;
        return massEmailSo;
    }
  
    public static Account getParentAccount()
    {
        Account parentAccount = new Account();
        parentAccount.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('CA Owner').getRecordTypeID();
        parentAccount.name = 'ParentAccount1';
        parentAccount.type = 'Owner';
        parentAccount.phone='2128425500';
        parentAccount.website  = 'https//www.test.com';
        parentAccount.valid_From_GMT__c= date.today()+1;
        parentAccount.valid_to_GMT__c= date.today()+10;
        parentAccount.company_website__c=  'https//www.test.com';
        parentAccount.organizational_type__c=  'Or ganizational Type';
        parentAccount.geographic_focus__c=  'Geographic focus';
        parentAccount.primary_market_customer_base__c = 'Primary Market';
        parentAccount.CA_Email_Alias_1__c = 'abc@xyz.com';
        parentAccount.CA_Email_Alias_2__c = 'abc@xyz.com';
        return parentAccount;
    }
    
    
    public static Account getRootAccount()
    {
        Account parentAccount = new Account();
        parentAccount.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Root Certificate').getRecordTypeID();
        parentAccount.name = 'ParentAccount2';
        parentAccount.type = 'Owner';
        parentAccount.phone='2128425500';
        parentAccount.website  = 'https//www.test.com';
        parentAccount.valid_From_GMT__c= date.today()+1;
        parentAccount.valid_to_GMT__c= date.today()+10;
        parentAccount.company_website__c=  'https//www.test.com';
        parentAccount.organizational_type__c=  'Organizational Type';
        parentAccount.geographic_focus__c=  'Geographic focus';
        parentAccount.primary_market_customer_base__c = 'Primary Market';
        parentAccount.CA_Email_Alias_1__c = 'abc@xyz.com';
        parentAccount.CA_Email_Alias_2__c = 'abc@xyz.com';
        return parentAccount;
    }
    public static Contact getParentContact(ID accountid, String typeStr)
    {
        Contact parentContact = new Contact();
        parentcontact.firstname = 'FirstName';
        parentcontact.accountid = accountId;
        parentcontact.lastname = 'LastName';
        parentcontact.email= 'LastName@firstname.com';
        parentcontact.phone= '456786588';
        parentcontact.type__c= typeStr;
       
        return parentContact;
    }
}