objects/Account.object
<CustomObject>
    <fields>
        <fullName>Approval_Bug__c</fullName>
        <label>Mozilla Approval Bug</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <description>This field is hyperlink to Account Name. Mainly used in reports.</description>
        <formula>HYPERLINK(Id, Name, &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Certificate Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firefox_Release_When_First_Included__c</fullName>
        <label>Firefox Release When First Included</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firefox_Release_When_Removed__c</fullName>
        <label>Firefox Release When Removed</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSS_Release_When_First_Included__c</fullName>
        <label>NSS Release When First Included</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSS_Release_When_Removed__c</fullName>
        <label>NSS Release When Removed</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OneCRL_Status__c</fullName>
        <label>OneCRL Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to Add</fullName>
                </value>
                <value>
                    <fullName>Added to OneCRL</fullName>
                </value>
                <value>
                    <fullName>Cert Expired</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Removal_Bug_No_or_Date__c</fullName>
        <label>Mozilla Removal Bug No. or Date</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/File_Archive__c.object
<CustomObject>
    <fields>
        <fullName>Audit_Statement_Date__c</fullName>
        <label>Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CA Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>File Archive</relationshipLabel>
        <relationshipName>File_Archive</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Audit</fullName>
                </value>
                <value>
                    <fullName>Code Signing Audit</fullName>
                </value>
                <value>
                    <fullName>BR Audit</fullName>
                </value>
                <value>
                    <fullName>EV SSL Audit</fullName>
                </value>
                <value>
                    <fullName>EV Code Signing Audit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Link__c</fullName>
        <label>External Link</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Internal_Link__c</fullName>
        <label>Internal Link</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Internal_Link_for_CAs__c</fullName>
        <formula>SUBSTITUTE(Internal_Link__c, &quot;my.salesforce&quot;, &quot;force&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Internal Link for CAs</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period_End_Date__c</fullName>
        <label>Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Start_Date__c</fullName>
        <label>Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>File Archive</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Archive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Archive</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/File_Archive_Association__c.object
<CustomObject>
    <fields>
        <fullName>Audit_Statement_Date__c</fullName>
        <formula>File_Archive__r.Audit_Statement_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certificate Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>File Archive Associations</relationshipLabel>
        <relationshipName>File_Archive_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>IF (INCLUDES (File_Archive__r.Document_Type__c , &quot;Standard Audit&quot; ), &quot;Standard Audit; &quot;, null) &amp; 
IF (INCLUDES (File_Archive__r.Document_Type__c, &quot;Code Signing Audit&quot; ), &quot;Code Signing Audit; &quot;, null) &amp;
IF (INCLUDES (File_Archive__r.Document_Type__c, &quot;BR Audit&quot; ), &quot;BR Audit; &quot;, null) &amp; 
IF (INCLUDES (File_Archive__r.Document_Type__c , &quot;EV SSL Audit&quot; ), &quot;EV SSL Audit; &quot;, null) &amp; 
IF (INCLUDES (File_Archive__r.Document_Type__c, &quot;EV Code Signing Audit&quot; ), &quot;EV Code Signing Audit; &quot;, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Archive__c</fullName>
        <label>Archive ID</label>
        <referenceTo>File_Archive__c</referenceTo>
        <relationshipLabel>File Archive Associations</relationshipLabel>
        <relationshipName>File_Archive_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Period_End_Date__c</fullName>
        <formula>File_Archive__r.Period_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Start_Date__c</fullName>
        <formula>File_Archive__r.Period_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period Start Date</label>
        <type>Date</type>
    </fields>
    <label>File Archive Association</label>
    <nameField>
        <displayFormat>AD{000000}</displayFormat>
        <label>Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Archive Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AllAuditHistoryController.cls
/*******************************************************************************************************
 Name: AllAuditHistoryController

 Dependencies:  AllAuditHistoryController controller class, AllAuditHistoryControllerTest, AllAuditHistory vf page

 Description: This report generates data from File Archive & association records for root and
 intermeduate certs.
 
 Sort by CA Owner Name, then Audit Statement Date, then Audit ExternalLink, then certificate type

 Instructions:  None

 *******************************************************************************************************
 Revision History:
 
     6/27/2020 - Created new
     7/7/2020 - Updated class to without sharing
     7/29/2020 - Added new field to the report 'Internal Link For CAs'

 ******************************************************************************************************/

public without sharing class AllAuditHistoryController {
    
    public transient List<File_Archive_Association__c> lstFAAssociation {get; set;}
    
    public AllAuditHistoryController(){
        lstFAAssociation = [SELECT Id, Name, Certificate_Name__r.CA_Owner__c, File_Archive__r.External_Link__c, 
                File_Archive__r.Internal_Link__c, File_Archive__r.Internal_Link_For_CAs__c, File_Archive__r.Document_Type__c, 
                File_Archive__r.Audit_Statement_Date__c, File_Archive__r.Period_Start_Date__c, 
                File_Archive__r.Period_End_Date__c, Certificate_Name__r.Name, Certificate_Name__r.RecordType.Name,
                Certificate_Name__r.SHA_256_Fingerprint__c, Certificate_Name__c, Certificate_Name__r.OneCRL_Status__c, 
                Certificate_Name__r.Status__c, Certificate_Name__r.Trust_Bits__c,  
                Certificate_Name__r.Approval_Bug__c, Certificate_Name__r.NSS_Release_When_First_Included__c, 
                Certificate_Name__r.Firefox_Release_When_First_Included__c, Certificate_Name__r.NSS_Release_When_Removed__c, 
                Certificate_Name__r.Firefox_Release_When_Removed__c, Certificate_Name__r.Removal_Bug_No_or_Date__c
                FROM File_Archive_Association__c ORDER BY Certificate_Name__r.CA_Owner__c, File_Archive__r.Audit_Statement_Date__c, 
                File_Archive__r.External_Link__c, Certificate_Name__r.RecordType.Name];
        
    }
}