objects/Account.object
<CustomObject>
    <fields>
        <fullName>CA_Owner_ID__c</fullName>
        <description>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</description>
        <inlineHelpText>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</inlineHelpText>
        <label>CA Owner ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Derived_Trust_Bits__c</fullName>
        <label>Derived Trust Bits</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Extended_Key_Usage__c</fullName>
        <label>Extended Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Microsoft_Root_Status__c</fullName>
        <inlineHelpText>This is Root Status on Intermediate Cert, updated via batch program</inlineHelpText>
        <label>Microsoft Root Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Microsoft_Trust_Bits__c</fullName>
        <label>Microsoft Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Server Authentication</fullName>
                </value>
                <value>
                    <fullName>Client Authentication</fullName>
                </value>
                <value>
                    <fullName>Code Signing</fullName>
                </value>
                <value>
                    <fullName>Document Signing</fullName>
                </value>
                <value>
                    <fullName>Encrypting File System</fullName>
                </value>
                <value>
                    <fullName>IP Security End System</fullName>
                </value>
                <value>
                    <fullName>IP Security IKE Intermediate</fullName>
                </value>
                <value>
                    <fullName>IP Security Tunnel Termination</fullName>
                </value>
                <value>
                    <fullName>IP Security User</fullName>
                </value>
                <value>
                    <fullName>OCSP Signing</fullName>
                </value>
                <value>
                    <fullName>Private Key Archival</fullName>
                </value>
                <value>
                    <fullName>Secure Email</fullName>
                </value>
                <value>
                    <fullName>Time Stamping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mozilla_Root_Status__c</fullName>
        <inlineHelpText>This is Root Status on Intermediate Cert, updated via batch program</inlineHelpText>
        <label>Mozilla Root Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Summary__c</fullName>
        <formula>&quot;Mozilla: &quot; + Text(Status__c) + &quot;; Microsoft: &quot; + Text(Microsoft_Status__c) + &quot;; Apple: &quot; + Text(Apple_Status__c)

/* &quot;Mozilla: &quot; + Text(Status__c) + &quot;; Microsoft: &quot; + Text(Microsoft_Status__c) + &quot;; Cisco: &quot; + Text(Cisco_Status__c) + &quot;; Google: &quot; + Text(Google_Status__c)*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ICDerivedTrustBitsListController.cls
/*******************************************************************************************************
 Name: ICDerivedTrustBitsListController

 Dependencies: ICDerivedTrustBitsListController controller class, ICDerivedTrustBitsList vf page, 
 ICDerivedTrustBitsListControllerTest test class

 Description: Displays all Intermediate Certs with Dervied Trust Bits. It was created for data verification
 purpose. The main logic for Derived Trust Bits is in UpdateDerivedTrustBits & GetDerivedTrustBits method in
 AccountTriggerHelper.
 
 Instructions: None
 *******************************************************************************************************
 Revision History:
 
     09/21/2020 - Created new class
     
 ******************************************************************************************************/ 

public class ICDerivedTrustBitsListController {

    public transient List<Account> lstAccounts {get; set;}
 
    //constructor method for standard controller
    public ICDerivedTrustBitsListController() {  
        lstAccounts =  [select Name,CA_Owner__c,CA_Owner_ID__c,Extended_Key_Usage__c, Derived_Trust_Bits__c,ParentId,
                                Parent.Name, Parent.RecordType.Name, Parent.Derived_Trust_Bits__c,
                                Parent.Trust_Bits__c, Parent.Microsoft_Trust_Bits__c, Parent.Status_Summary__c,
                                Parent.Revocation_Status__c, Parent.Valid_To_GMT__c
                                FROM Account
                                WHERE ( Mozilla_Root_Status__c In ('Included','Change Requested') OR
                                Microsoft_Root_Status__c In ('Included','Change Requested')) 
                                and RecordType.Name In ('Intermediate Certificate') and Valid_To_GMT__c > TODAY
                                Order by CA_Owner__c,Parent.Name, Name];
    }
  
     
    String CurrentDate = ' ';
 
    // Get current Datetime in long date format   
    public String getCurrentDate() {
        Datetime cDT = System.now();
        CurrentDate = cDT.format('MMMM d, yyyy');
        return CurrentDate;
    }
    
}