objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Website__c</fullName>
        <inlineHelpText>Website URL</inlineHelpText>
        <label>Company Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Geographic_Focus__c</fullName>
        <label>Geographic Focus</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Organizational_Type__c</fullName>
        <inlineHelpText>Indicate the type of organization operating this CA.</inlineHelpText>
        <label>Organizational Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Private Corporation</fullName>
                </value>
                <value>
                    <fullName>Public Corporation</fullName>
                </value>
                <value>
                    <fullName>Government Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Organization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Market_Customer_Base__c</fullName>
        <inlineHelpText>Indicates what types of customers does the CA serve?
Are there particular vertical market segments in which it operates?
Does the CA focus its activities on a particular country or other geographic region?</inlineHelpText>
        <label>Primary Market / Customer Base</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From_GMT__c</fullName>
        <inlineHelpText>The date from which the root CA certificate is valid.</inlineHelpText>
        <label>Valid From (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Company_Website__c</fullName>
        <defaultValue>&quot;http://NEED: URL to company website&quot;</defaultValue>
        <description>Website URL</description>
        <inlineHelpText>Website URL</inlineHelpText>
        <label>Company Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Geographic_Focus__c</fullName>
        <defaultValue>&quot;NEED: Country or geographic region where CA typically sells certs.&quot;</defaultValue>
        <label>Geographic Focus</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Organizational_Type__c</fullName>
        <inlineHelpText>Indicate the type of organization operating this CA.</inlineHelpText>
        <label>Organizational Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Private Corporation</fullName>
                </value>
                <value>
                    <fullName>Public Corporation</fullName>
                </value>
                <value>
                    <fullName>Government Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Organization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Market_Customer_Base__c</fullName>
        <defaultValue>&quot;NEED:&quot; + BR() + 
&quot;- Which types of customers does the CA serve? &quot; + BR() + 
&quot;- Are there particular vertical market segments in which it operates? &quot; + BR() + 
&quot;- Does the CA focus its activities on a particular country or other geographic region?&quot;</defaultValue>
        <inlineHelpText>Which types of customers does the CA serve?
Are there particular vertical market segments in which it operates?
Does the CA focus its activities on a particular country or other geographic region?</inlineHelpText>
        <label>Primary  Market / Customer Base</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UploadFileControllerTest.cls
/*
* test class for 'UploadFileController'
*/
@isTest(SeeAllData = false)
public class UploadFileControllerTest{    /****   UNUSED TEST CLASS  *****
    
    static testmethod void testErrorCondition(){
        
        Account caOwnerAcc = getCAOwnerAccount();
        insert caOwnerAcc;
        
        Case caseSO = getCase(caOwnerAcc.Id);
        insert caseSO;
        
        PageReference pref = Page.UploadFile;
        pref.getParameters().put('id', caseSO.Id);
        pref.getParameters().put('documentType', 'Standard Audit');
        Test.setCurrentPage(pref);
        
        ApexPages.standardController stdCon = new ApexPages.standardController(caseSO);
        UploadFileController obj = new UploadFileController(stdCon);
        
        PageReference redirectURL = obj.uploadFile();
        
        System.assertEquals(redirectURL, null);
    }
    
    static testmethod void testStdAuditFileUpload(){
        
        Account caOwnerAcc = getCAOwnerAccount();
        insert caOwnerAcc;
        
        Case caseSO = getCase(caOwnerAcc.Id);
        insert caseSO;
        
        PageReference pref = Page.UploadFile;
        pref.getParameters().put('id', caseSO.Id);
        pref.getParameters().put('documentType', 'Standard Audit');
        Test.setCurrentPage(pref);
        
        Blob body = Blob.valueOf('test document');
        
        ApexPages.standardController stdCon = new ApexPages.standardController(caseSO);
        UploadFileController obj = new UploadFileController(stdCon);
        obj.fileData = body;
        obj.fileName = 'Standard Audit document';
        
        PageReference redirectURL = obj.uploadFile();
        
        //System.assertEquals([SELECT Name FROM Document WHERE Name = 'Standard Audit document' LIMIT 1][0].Name, 'Standard Audit document');
        System.assertEquals([SELECT Name FROM Attachment WHERE Name = 'Standard Audit document' LIMIT 1][0].Name, 'Standard Audit document');
    }
    
    static testmethod void testBRAuditFileUpload(){
        
        Account caOwnerAcc = getCAOwnerAccount();
        insert caOwnerAcc;
        
        Case caseSO = getCase(caOwnerAcc.Id);
        insert caseSO;
        
        PageReference pref = Page.UploadFile;
        pref.getParameters().put('id', caseSO.Id);
        pref.getParameters().put('documentType', 'BR Audit');
        Test.setCurrentPage(pref);
        
        Blob body = Blob.valueOf('test document');
        
        ApexPages.standardController stdCon = new ApexPages.standardController(caseSO);
        UploadFileController obj = new UploadFileController(stdCon);
        obj.fileData = body;
        obj.fileName = 'BR Audit document';
        
        PageReference redirectURL = obj.uploadFile();
        
        System.assertEquals([SELECT Name FROM Attachment WHERE Name = 'BR Audit document' LIMIT 1][0].Name, 'BR Audit document');
    }
    
    static testmethod void testEVAuditFileUpload(){
        
        Account caOwnerAcc = getCAOwnerAccount();
        insert caOwnerAcc;
        
        Case caseSO = getCase(caOwnerAcc.Id);
        insert caseSO;
        
        PageReference pref = Page.UploadFile;
        pref.getParameters().put('id', caseSO.Id);
        pref.getParameters().put('documentType', 'EV Audit');
        Test.setCurrentPage(pref);
        
        Blob body = Blob.valueOf('test document');
        
        ApexPages.standardController stdCon = new ApexPages.standardController(caseSO);
        UploadFileController obj = new UploadFileController(stdCon);
        obj.fileData = body;
        obj.fileName = 'EV Audit document';
        
        PageReference redirectURL = obj.uploadFile();
        
        System.assertEquals([SELECT Name FROM Attachment WHERE Name = 'EV Audit document' LIMIT 1][0].Name, 'EV Audit document');
    }
    
    static testmethod void testCPAuditFileUpload(){
        
        Account caOwnerAcc = getCAOwnerAccount();
        insert caOwnerAcc;
        
        Case caseSO = getCase(caOwnerAcc.Id);
        insert caseSO;
        
        PageReference pref = Page.UploadFile;
        pref.getParameters().put('id', caseSO.Id);
        pref.getParameters().put('documentType', 'CP');
        Test.setCurrentPage(pref);
        
        Blob body = Blob.valueOf('test document');
        
        ApexPages.standardController stdCon = new ApexPages.standardController(caseSO);
        UploadFileController obj = new UploadFileController(stdCon);
        obj.fileData = body;
        obj.fileName = 'CP Audit document';
        
        PageReference redirectURL = obj.uploadFile();
        
        System.assertEquals([SELECT Name FROM Attachment WHERE Name = 'CP Audit document' LIMIT 1][0].Name, 'CP Audit document');
    }
    
    static testmethod void testCPSAuditFileUpload(){
        
        Account caOwnerAcc = getCAOwnerAccount();
        insert caOwnerAcc;
        
        Case caseSO = getCase(caOwnerAcc.Id);
        insert caseSO;
        
        PageReference pref = Page.UploadFile;
        pref.getParameters().put('id', caseSO.Id);
        pref.getParameters().put('documentType', 'CPS');
        Test.setCurrentPage(pref);
        
        Blob body = Blob.valueOf('test document');
        
        ApexPages.standardController stdCon = new ApexPages.standardController(caseSO);
        UploadFileController obj = new UploadFileController(stdCon);
        obj.fileData = body;
        obj.fileName = 'CPS Audit document';
        
        PageReference redirectURL = obj.uploadFile();
        
        System.assertEquals([SELECT Name FROM Attachment WHERE Name = 'CPS Audit document' LIMIT 1][0].Name, 'CPS Audit document');
    }
    
    public static Account getCAOwnerAccount(){

        Account parentAccount = new Account();
        parentAccount.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('CA Owner').getRecordTypeID();
        parentAccount.name = 'ParentAccount';
        parentAccount.type = 'Owner';
        parentAccount.status__c= 'Included';
        parentAccount.Revocation_Status__c = 'Included';
        parentAccount.phone='2128425500';
        parentAccount.website  = 'https//www.test.com';
        parentAccount.valid_From_GMT__c= date.today()+1;
        parentAccount.valid_to_GMT__c= date.today()+10;
        parentAccount.company_website__c=  'https//www.test.com';
        parentAccount.organizational_type__c=  'Organizational Type';
        parentAccount.geographic_focus__c=  'Geographic focus';
        parentAccount.primary_market_customer_base__c = 'Primary Market';
        return parentAccount;
    }
    
    public static Case getCase(Id accountId){
        Case caseSO = new Case(AccountId = accountId);
        caseSO.subject = 'test audit request case';
        caseSO.Status = 'Open';
        return caseSO;
    }   *****/
}