objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PEMOnlyReportControllerTest.cls
/********************* THIS PRORGAM HAS BEEN REPLACE BY IncludedRootsPEMControllerTest ********************/

/*******************************************************************************************************
 Name: PEMOnlyReportControllerTest

 Dependencies: PEMOnlyReportController controller class, PEMOnlyCSV vf page, PEMOnlyReportControllerTest test class

 Description: This report generates single column report on PEM. It takes in parametrized url.
 
 .../PEMOnlyCSV?TrustBitsInclude=Websites      <= look for 'Websites' included in Mozilla Trust Bits
 .../PEMOnlyCSV?TrustBitsInclude=Email         <= look for 'Email included in Mozilla Trust Bits
      
 Instructions: None
 *******************************************************************************************************
 Revision History:
 
     10/3/2020 - Created new.
     
 ******************************************************************************************************/
@isTest
public with sharing class PEMOnlyReportControllerTest {
    static testmethod void TestReport(){
        Account accountSo = TestUtils.getCAOwner();
        insert accountSo;
        
        //create a ROOT CA
        Account rootCA = TestUtils.getRootCertificate(accountSo.Id);
        rootCA.Status__c = 'Included';
        rootCA.Trust_Bits__c = 'Websites;Email';
        insert rootCa;
        
        Apexpages.currentpage().getparameters().put('TrustBitsInclude','Websites');
        PEMOnlyReportController controller = new PEMOnlyReportController();
    }
}