objects/Account.object
<CustomObject>
    <fields>
        <fullName>CA_Email_Alias_1__c</fullName>
        <inlineHelpText>CA Email Alias 1 and 2 are used to reach more than one person in your organization tol receive notifications in case the primary contact is out of the office or leaves the organization.</inlineHelpText>
        <label>CA Email Alias 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CA_Email_Alias_2__c</fullName>
        <inlineHelpText>CA Email Alias 1 and 2 are used to reach more than one person in your organization tol receive notifications in case the primary contact is out of the office or leaves the organization.</inlineHelpText>
        <label>CA Email Alias 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CA_Owner_ID__c</fullName>
        <description>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</description>
        <inlineHelpText>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</inlineHelpText>
        <label>CA Owner ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mass_Email__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Status__c</fullName>
        <label>Batch Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Started</fullName>
                    <default>true</default>
                    <label>Not Yet Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_To__c</fullName>
        <label>CC To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Primary POCs</fullName>
                </value>
                <value>
                    <fullName>All POCs</fullName>
                </value>
                <value>
                    <fullName>CA Email Alias 1</fullName>
                </value>
                <value>
                    <fullName>CA Email Alias 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <inlineHelpText>This field holds the &quot;Display Name&quot; from the Organization-Wide Email Addresses defined in your org.</inlineHelpText>
        <label>From</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CCADB Support</fullName>
                    <default>true</default>
                    <label>CCADB Support</label>
                </value>
                <value>
                    <fullName>Apple CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Cisco CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Google CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Microsoft CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Mozilla CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Current User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>No_of_Emails_Failed__c</fullName>
        <label>Number of Emails Failed</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Emails_Sent__c</fullName>
        <label>Number of Emails Sent</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reply_To__c</fullName>
        <label>Reply To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reply-To Apple CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Reply-To Cisco CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Reply-To Google CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Reply-To Microsoft CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Reply-To Mozilla CA Program Manager</fullName>
                </value>
                <value>
                    <fullName>Current User</fullName>
                    <default>true</default>
                    <label>Current User</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOQL_Filter_Conditions__c</fullName>
        <label>SOQL Filter Conditions</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Send_To__c</fullName>
        <label>Send To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All Primary POCs</fullName>
                </value>
                <value>
                    <fullName>All POCs</fullName>
                </value>
                <value>
                    <fullName>CA Email Alias 1</fullName>
                </value>
                <value>
                    <fullName>CA Email Alias 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <label>Mass Email</label>
    <nameField>
        <displayFormat>E{0000}</displayFormat>
        <label>Mass Email Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassEmailBatch.cls
global class MassEmailBatch implements Database.Batchable<sObject>, Database.stateful {

    global String massEmailRecordId = '';
    
    global Mass_Email__c massEmailSo = null;
    global Map<Id,Set<String>>  toEmailAddressMap;
    global Map<Id,Set<String>>  ccEmailAddressMap;
    
    public MassEmailBatch (String massEmailRecordIdParam,   Map<Id,Set<String>> toMap ,   Map<Id,Set<String>> ccMap) {
        massEmailRecordId = massEmailRecordIdParam;
        toEmailAddressMap  = toMap;
        ccEmailAddressMap = ccMap;
        massEmailSo = [select Id,From__c,SOQL_Filter_Conditions__c, OwnerId, Name, No_of_Emails_Sent__c, No_of_Emails_Failed__c,
                Error_Message__c, Subject__c, Reply_To__c, Message__c, Send_To__c, CC_To__c from Mass_Email__c where id =:massEmailRecordId];
        massEmailSo.Error_Message__c = '';
        massEmailSo.No_of_Emails_Sent__c = 0;
        massEmailSo.No_of_Emails_Failed__c = 0;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = '';
        set<Id> setCAOwnerIds = new set<Id>();
        if(toEmailAddressMap.size() > 0){
            setCAOwnerIds.addall(toEmailAddressMap.keyset());
        }
        if(ccEmailAddressMap.size() > 0){
            setCAOwnerIds.addall(ccEmailAddressMap.keyset());
        }
        query = 'select id, name, CA_Owner_ID__c, CA_Email_Alias_1__c , CA_Email_Alias_2__c from account where id in :setCAOwnerIds';
        /*Commented because I don't think we need to query it again
        Boolean fetchOwnerAccounts = false;
        List<Account> accountSoLst; 
        String query = 'select id, CA_Owner_ID__c, CA_Email_Alias_1__c , CA_Email_Alias_2__c from account ';
        if(massEmailSo.SOQL_Filter_Conditions__c!=null && massEmailSo.SOQL_Filter_Conditions__c.length() > 0)  { 
        query = query + ' where ' + massEmailSo.SOQL_Filter_Conditions__c;
        accountSoLst = Database.query(query);
        String rootCertFilter = 'Record_Type_Name__c=RootCertificate';
          String interCertFilter = 'Record_Type_Name__c=IntermediateCertificate';
          String filterConditions = massEmailSo.SOQL_Filter_Conditions__c;
          
            filterConditions= filterConditions.trim();
            
            filterConditions= filterConditions.replaceAll('(\\s+)', '');
            filterConditions= filterConditions.replaceAll('\'', '');

              if( filterConditions.contains(rootCertFilter) || filterConditions.contains(interCertFilter))
              {
                fetchOwnerAccounts = true;
              }
        }
        
        if(fetchOwnerAccounts && accountSoLst!=null && accountSoLst.size() > 0)
        {
          Set<String> ownerAccountIdSet = New Set<String>();
          
          for(Account accountSo : accountSoLst)
          {
            ownerAccountIdSet.add(accountSo.ca_owner_id__c);
          }
          // system.debug('OwnerSet==' + ownerAccountIdSet);
          query = 'select id, name, CA_Owner_ID__c, CA_Email_Alias_1__c , CA_Email_Alias_2__c from account where id in :ownerAccountIdSet';
          return Database.getQueryLocator(query);
        }*/
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope){
        MassEmailBatchHelper batchHelper = new MassEmailBatchHelper ();
        massEmailSo = batchHelper.processOwnerRecords(scope, massEmailSo, toEmailAddressMap, ccEmailAddressMap);
    }
    
    global void finish(Database.BatchableContext BC)  { 
        if(string.isblank(massEmailSo.Error_Message__c)){
            massEmailSo.Batch_Status__c = 'Completed';
        } else {
            massEmailSo.Batch_Status__c = 'Failed';
        }
        update massEmailSo;
    }
}