objects/Account.object
<CustomObject>
    <fields>
        <fullName>Test_Website_Expired__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with an expired TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Expired</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Website_Revoked__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with a revoked TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Revoked</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Website_Valid__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with a valid TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Valid</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>BR_Audit_Authenticity_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only when authenticity of audit statement has been confirmed </inlineHelpText>
        <label>BR Audit Authenticity Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Auth_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only when authenticity of audit statement has been confirmed </inlineHelpText>
        <label>EV Code Signing Audit Auth Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EV_SSL_Audit_Authenticity_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only when authenticity of audit statement has been confirmed </inlineHelpText>
        <label>EV SSL Audit Authenticity Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>Information verification phases</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit_Authenticity_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only when authenticity of audit statement has been confirmed </inlineHelpText>
        <label>Standard Audit Authenticity Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Root_Case__c.object
<CustomObject>
    <fields>
        <fullName>Apply_BR_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BR Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_EV_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EV SSL Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_Standard_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CA_Owner_Name_Existing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Previously called Included CA Owner Name</description>
        <label>CA Owner Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Owner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Root Cases</relationshipLabel>
        <relationshipName>Root_Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_No__c</fullName>
        <label>Case No</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Root Cases</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Root_Certificate_Name_Existing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Previously called Included Certificate Name</description>
        <inlineHelpText>The Root Certificate that this Root Case applies to.</inlineHelpText>
        <label>Certificate Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Root</value>
            </filterItems>
            <filterItems>
                <field>Account.Parent.Id</field>
                <operation>equals</operation>
                <valueField>$Source.CA_Owner_Name_Existing__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Root Cases (Included Certificate)</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Website_Expired__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with an expired TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Expired</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Website_Revoked__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with a revoked TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Revoked</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Website_Valid__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with a valid TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Valid</label>
        <type>TextArea</type>
    </fields>
    <label>Root Case</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Root Case No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RootCasesEditTestWebsitesControllerTest.cls
/*
    Description: test class for RootCasesEditTestWebsitesController
*/
@isTest
private class RootCasesEditTestWebsitesControllerTest {
    
    static testmethod void testTestWebsitesMethod(){ 
        
        Account caOwnerAcc = TestUtils.getCAOwner();
        insert caOwnerAcc;
        
        Case caseSO = TestUtils.getCase(caOwnerAcc.Id);
        caseSO.Standard_Audit_Authenticity_Confirmed__c = True;
        caseSO.BR_Audit_Authenticity_Confirmed__c = True;
        caseSO.EV_Code_Signing_Audit_Auth_Confirmed__c = True;
        caseSO.EV_SSL_Audit_Authenticity_Confirmed__c = True;
        insert caseSO;
        
        // create the child account - record type = Root
        Account childAccount = TestUtils.getRootCertificate(caOwnerAcc.id);
        childAccount.Name = 'child root account 1';
        insert childAccount;
        
        Root_Case__c rootCaseA1 = TestUtils.getRootCase(caseSO.id,caOwnerAcc.Id);
        rootCaseA1.request_status__c   = 'Initial Request Received';         
        rootCaseA1.Apply_Standard_Audit__c = true;
        rootCaseA1.Apply_BR_Audit__c = true;
        rootCaseA1.Apply_EV_Audit__c = true;         
        rootCaseA1.Case_No__c = caseSO.Id;
        rootCaseA1.CA_Owner_Name_Existing__c = caOwnerAcc.Id;
        rootCaseA1.Root_Certificate_Name_Existing__c = childAccount.Id;
        rootCaseA1.RecordTypeId = Schema.SObjectType.Root_Case__c.getRecordTypeInfosByName().get('CA Audit Update Request').getRecordTypeID();
        insert rootCaseA1;
        
        RootCasesEditTestWebsitesController editctrl = new RootCasesEditTestWebsitesController(new Apexpages.standardcontroller(caseSO));
        editctrl.UpdateRootCases();
        if(editctrl.lstAllRootCases.size() > 0){
            editctrl.lstAllRootCases[0].Test_Website_Valid__c = '';
            editctrl.UpdateRootCases();
            editctrl.lstAllRootCases[0].Test_Website_Valid__c = 'test.com';
            editctrl.lstAllRootCases[0].Test_Website_Revoked__c = 'test.com';
            editctrl.lstAllRootCases[0].Test_Website_Expired__c = 'test.com';
            editctrl.UpdateRootCases();
            editctrl.lstAllRootCases[0].Test_Website_Valid__c = 'https://comodocertificationauthority-ev.comodoca.com/';
            editctrl.lstAllRootCases[0].Test_Website_Revoked__c = 'https://comodocertificationauthority-ev.comodoca.com:442/';
            editctrl.lstAllRootCases[0].Test_Website_Expired__c = 'https://comodocertificationauthority-ev.comodoca.com:444/';
            editctrl.UpdateRootCases();
        }
    }
}