objects/Account.object
<CustomObject>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <description>This field is hyperlink to Account Name. Mainly used in reports.</description>
        <formula>HYPERLINK(Id, Name, &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Certificate Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Policy_Identifiers__c</fullName>
        <label>Policy Identifiers</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Policy_Document_Association_On_Case__c.object
<CustomObject>
    <description>Policy Document Association records on Case</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>Updated by custom process to indicate the action taken on the Policy Document Association record</inlineHelpText>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Policy_Document_Associations_On_Case</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certificate Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Policy_Document_Associations_On_Case</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <formula>Policy_Document__r.Document_Link__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>TEXT (Policy_Document__r.Document_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_Document__c</fullName>
        <label>Document Id</label>
        <referenceTo>Policy_Document_On_Case__c</referenceTo>
        <relationshipName>Policy_Document_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Policy Document Association (On Case)</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Document Associations (On Case)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Policy_Document_On_Case__c.object
<CustomObject>
    <description>Policy Documents on Case</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>Used by custom program to record action performed by the user on the Policy Document record</inlineHelpText>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Additional_Policy_Identifiers__c</fullName>
        <inlineHelpText>Additional Policy Identifiers</inlineHelpText>
        <label>Additional Policy Identifiers</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Associated_Trust_Bits__c</fullName>
        <inlineHelpText>Associated Trust Bits</inlineHelpText>
        <label>Associated Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Secure Email</fullName>
                </value>
                <value>
                    <fullName>Server Authentication</fullName>
                </value>
                <value>
                    <fullName>Client Authentication</fullName>
                </value>
                <value>
                    <fullName>Code Signing</fullName>
                </value>
                <value>
                    <fullName>Document Signing</fullName>
                </value>
                <value>
                    <fullName>Encrypting File System</fullName>
                </value>
                <value>
                    <fullName>IP Security End System</fullName>
                </value>
                <value>
                    <fullName>IP Security IKE Intermediate</fullName>
                </value>
                <value>
                    <fullName>IP Security Tunnel Termination</fullName>
                </value>
                <value>
                    <fullName>IP Security User</fullName>
                </value>
                <value>
                    <fullName>OCSP Signing</fullName>
                </value>
                <value>
                    <fullName>Private Key Archiva</fullName>
                </value>
                <value>
                    <fullName>Time Stamping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Policy Documents (On Case)</relationshipLabel>
        <relationshipName>Policy_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Last_Updated_Date__c</fullName>
        <inlineHelpText>Policy document Last Updated Date must be filled for policy document link</inlineHelpText>
        <label>Document Last Updated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <inlineHelpText>URL to policy documentation specific to the listed root certs. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Document Link</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CP/CPS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Verified__c</fullName>
        <label>Document Verified?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Verified</fullName>
                    <default>true</default>
                    <label>Not Verified</label>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>System Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Identifiers__c</fullName>
        <label>Policy Identifiers</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Policy Document (On Case)</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Policy Doc Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Documents (On Case)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PolicyDocumentAssociation_On_Certificate__c.object
<CustomObject>
    <fields>
        <fullName>Source_Policy_Doc_Assoc_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Document Association (On Case)</label>
        <referenceTo>Policy_Document_Association_On_Case__c</referenceTo>
        <relationshipLabel>Policy Document Associations</relationshipLabel>
        <relationshipName>Policy_Document_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WRONG_Source_Policy_Doc_Assoc_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WRONG Case Policy Doc Assoc Id</label>
        <referenceTo>PolicyDocumentAssociation_On_Certificate__c</referenceTo>
        <relationshipLabel>Policy Document Associations</relationshipLabel>
        <relationshipName>Policy_Document_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Policy Document Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Document Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Root_Case__c.object
<CustomObject>
    <fields>
        <fullName>Case_No__c</fullName>
        <label>Case No</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Root Cases</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <label>Root Case</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Root Case No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PrintViewCaseController.cls
/*
    Controller: Created a controller for Case Print View
*/

//public with sharing class PrintViewCaseController {

public class PrintViewCaseController {
  public transient Case objCase { get; set; }

  public transient List<Policy_Document_On_Case__c> lstPolicyDocumentsOnCases {
    get;
    set;
  }
  public transient List<Root_Case__c> lstRootCases { get; set; }

  public PrintViewCaseController(Apexpages.standardcontroller controller) {
    lstPolicyDocumentsOnCases = new List<Policy_Document_On_Case__c>();
    objCase = new Case();
    lstRootCases = new List<Root_Case__c>();
    Id caseid = controller.getId();
    if (
      caseid != null ||
      Apexpages.currentPage().getParameters().get('CaseNumber') != null
    ) {
      string casenumber = string.valueof(
        Apexpages.currentPage().getParameters().get('CaseNumber')
      );
      // get case details
      Map<String, Schema.SObjectField> caseFields = Schema.getGlobalDescribe()
        .get('Case')
        .getDescribe()
        .fields.getMap();
      string strCaseQuery = 'SELECT';
      for (String s : caseFields.keySet()) {
        strCaseQuery += ' ' + s + ',';
      }
      strCaseQuery += ' Case.Account.Name,';
      // Strip off the last comma if it exists.
      if (
        strCaseQuery.subString(
          strCaseQuery.Length() - 1,
          strCaseQuery.Length()
        ) == ','
      ) {
        strCaseQuery = strCaseQuery.subString(0, strCaseQuery.Length() - 1);
      }

      strCaseQuery += ' FROM Case Where Id =: caseid or CaseNumber =: casenumber';
      system.debug('strCaseQuery  :: ' + strCaseQuery);
      List<Case> lstCase = Database.Query(strCaseQuery);
      if (lstCase.size() > 0) {
        objCase = lstCase[0];
        caseid = objCase.Id;
      }

      // get case details
      Map<String, Schema.SObjectField> rootcaseFields = Schema.getGlobalDescribe()
        .get('Root_Case__c')
        .getDescribe()
        .fields.getMap();
      string strRootCaseQuery = 'SELECT';
      for (String s : rootcaseFields.keySet()) {
        strRootCaseQuery += ' ' + s + ',';
      }
      // Strip off the last comma if it exists.
      if (
        strRootCaseQuery.subString(
          strRootCaseQuery.Length() - 1,
          strRootCaseQuery.Length()
        ) == ','
      ) {
        strRootCaseQuery = strRootCaseQuery.subString(
          0,
          strRootCaseQuery.Length() - 1
        );
      }
      strRootCaseQuery += ' FROM Root_Case__c Where Case_No__c =: caseid ';
      system.debug('strRootCaseQuery :: ' + strRootCaseQuery);
      lstRootCases = Database.Query(strRootCaseQuery);

      //fill Policy Document
      lstPolicyDocumentsOnCases = new List<Policy_Document_On_Case__c>(
        [
          SELECT
            Document_Type__c,
            Document_Verified__c,
            Document_Link__c,
            Document_Last_Updated_Date__c,
            Associated_Trust_Bits__c,
            Policy_Identifiers__c,
            Additional_Policy_Identifiers__c,
            Comments__c,
            (
              SELECT
                id,
                Certificate_Name__r.SHA_256_Fingerprint__c,
                Certificate_Name__c,
                Certificate_Name__r.Name
              FROM Policy_Document_Associations__r
              WHERE Action__c != 'Delete'
              ORDER BY Certificate_Name__r.Name
            )
          FROM Policy_Document_On_Case__c
          WHERE Case__c = :caseid AND Action__c != 'Delete'
        ]
      );
    }
  }
}