objects/Account.object
<CustomObject>
    <fields>
        <fullName>CA_Email_Alias_1__c</fullName>
        <inlineHelpText>CA Email Alias 1 and 2 are used to reach more than one person in your organization tol receive notifications in case the primary contact is out of the office or leaves the organization.</inlineHelpText>
        <label>CA Email Alias 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CA_Email_Alias_2__c</fullName>
        <inlineHelpText>CA Email Alias 1 and 2 are used to reach more than one person in your organization tol receive notifications in case the primary contact is out of the office or leaves the organization.</inlineHelpText>
        <label>CA Email Alias 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Microsoft_Trust_Bits__c</fullName>
        <label>Microsoft Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Server Authentication</fullName>
                </value>
                <value>
                    <fullName>Client Authentication</fullName>
                </value>
                <value>
                    <fullName>Code Signing</fullName>
                </value>
                <value>
                    <fullName>Document Signing</fullName>
                </value>
                <value>
                    <fullName>Encrypting File System</fullName>
                </value>
                <value>
                    <fullName>IP Security End System</fullName>
                </value>
                <value>
                    <fullName>IP Security IKE Intermediate</fullName>
                </value>
                <value>
                    <fullName>IP Security Tunnel Termination</fullName>
                </value>
                <value>
                    <fullName>IP Security User</fullName>
                </value>
                <value>
                    <fullName>OCSP Signing</fullName>
                </value>
                <value>
                    <fullName>Private Key Archival</fullName>
                </value>
                <value>
                    <fullName>Secure Email</fullName>
                </value>
                <value>
                    <fullName>Time Stamping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sponsored_By__c</fullName>
        <label>Sponsored By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Microsoft</fullName>
                </value>
                <value>
                    <fullName>Mozilla</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From_GMT__c</fullName>
        <inlineHelpText>The date from which the root CA certificate is valid.</inlineHelpText>
        <label>Valid From (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CA_Email_Alias_1__c</fullName>
        <inlineHelpText>CA Email Alias 1 and 2 is needed so that more than one person in your organization will receive notifications in case the primary contact is out of the office or leaves the organization.</inlineHelpText>
        <label>CA Email Alias 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Case_Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Progress__c</fullName>
        <label>Case Progress</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add Audit data</fullName>
                </value>
                <value>
                    <fullName>Add Audit/CP/CPS data</fullName>
                </value>
                <value>
                    <fullName>Add Root Cases</fullName>
                </value>
                <value>
                    <fullName>Update Policy Documents</fullName>
                </value>
                <value>
                    <fullName>Update Test Websites</fullName>
                </value>
                <value>
                    <fullName>Verify Test Websites</fullName>
                </value>
                <value>
                    <fullName>Run ALV</fullName>
                </value>
                <value>
                    <fullName>Verification by Root Store</fullName>
                </value>
                <value>
                    <fullName>Verify Audit Info</fullName>
                </value>
                <value>
                    <fullName>Verify Policy Documents</fullName>
                </value>
                <value>
                    <fullName>Sync Policy Documents</fullName>
                </value>
                <value>
                    <fullName>Sync Audit Info</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Latest_Case_Comment__c</fullName>
        <description>Update by workflow and field update</description>
        <label>Latest Case Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>Information verification phases</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CP_CPS_document_URLs__c</fullName>
        <inlineHelpText>URLs to the CA’s CP/CPS documents.</inlineHelpText>
        <label>CP/CPS document URLs</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Organization_Type__c</fullName>
        <description>Organization Type</description>
        <label>Organization Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Private Corporation</fullName>
                </value>
                <value>
                    <fullName>Public Corporation</fullName>
                </value>
                <value>
                    <fullName>Government Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Organization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sponsored_By__c</fullName>
        <inlineHelpText>Which root store you are sponsored by, or will be applying for inclusion to.</inlineHelpText>
        <label>Sponsored By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Microsoft</fullName>
                </value>
                <value>
                    <fullName>Mozilla</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                    <isActive>false</isActive>
                    <label>Apple</label>
                </value>
                <value>
                    <fullName>Cisco</fullName>
                    <isActive>false</isActive>
                    <label>Cisco</label>
                </value>
                <value>
                    <fullName>Google</fullName>
                    <isActive>false</isActive>
                    <label>Google</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/RSHomePageControllerMSFT.cls
/*******************************************************************************************************
 Name: RSHomePageControllerMSFT

 Dependencies: RSHomePageControllerMSFT controller class, RSHomePageMSFT vf page, RSHomePageControllerMSFTTest test class

 Description: This is Microsoft's Root Store's Task List report (added to home page). It generates
 various reports wih record count. Detail report is only displayed when the 
 record count is greater than 1.
    
    Report sections showing the following ...
    
    1) Open Leads assigned to Microsoft
    2) Open Audit Cases assigned to Microsoft
    3) Expired Root Certificates in Microsoft’s program
    
 Instructions: Add the VF page to Root Store's home page
 *******************************************************************************************************
 Revision History:
     9/3/2019 - Created new class.
     9/9/2019 - Adding a new section '“CAs with no Included Roots”'
     9/23/2019 - Added a new section 'CAs Missing Emails'
 ******************************************************************************************************/
 
public with sharing class RSHomePageControllerMSFT {
    
    public List<Lead> lstOpenLeads {get; set;}
    public List<Case> lstAuditCases {get; set;}
    public List<Account> lstExpiredRootCertificates {get; set;}
    public List<Account> lstCAswithNoIncludedRootCerts {get; set;}
    public List<Account> lstCAsMissingEmails {get; set;}
    
    public RSHomePageControllerMSFT(){
    
        lstOpenLeads = new List<Lead>([select Id, Name, Website, Company, Organization_Type__c, CP_CPS_document_URLs__c, Sponsored_By__c 
                                       from Lead where Status != 'Denied' and IsConverted = false and Sponsored_By__c = 'Microsoft' 
                                       Order by Sponsored_By__c desc]);
                    
        lstAuditCases = new List<Case>([select ID, CaseNumber, AccountId, Account.Name, Case_Progress__c, Request_Status__c,Latest_Case_Comment__c,
                        Case_Assigned_To__c, Case_Assigned_To__r.Name, Subject, LastModifiedDate, LastModifiedById, LastModifiedBy.Name
                        From Case Where RecordType.Name = 'CA Audit Update Request' AND Request_Status__c != 'Complete'
                        And Case_Assigned_To__r.Name = 'Karina Sirota'
                        Order by LastModifiedDate]);
        
        lstExpiredRootCertificates = new List<Account>([select Id, Name, ParentId, Parent.Name, Valid_From_GMT__c, Valid_To_GMT__c, 
                        Microsoft_Trust_Bits__c, Microsoft_Status__c from Account WHERE RecordType.Name = 'Root Certificate' 
                        AND Microsoft_Status__c in ('Included') 
                        AND Valid_To_GMT__c < TODAY Order by Parent.Name,Name]);
        
        //find CAs with No Included Root certs
        List<Account> lstCAOwners = new List<Account>([select Id,Name,(Select Id, Name, ParentId, Parent.Name, 
                                Parent.Microsoft_Status__c, Comments__c ,Microsoft_Status__c FROM ChildAccounts Where 
                                RecordType.Name = 'Root Certificate' AND Microsoft_Status__c in ('Included')) 
                                FROM Account Where RecordType.Name = 'CA Owner' 
                                AND Microsoft_Status__c in ('Included')]);
        set<Id> setOfCAOwnerId = new set<Id>();                        
        for(Account acc: lstCAOwners){
            if(acc.ChildAccounts.size() == 0){
                setOfCAOwnerId.add(acc.Id);
            }
        }         
        lstCAswithNoIncludedRootCerts = new List<Account>([Select Id, Name, ParentId, Parent.Name, 
                        Parent.Microsoft_Status__c, Comments__c ,Microsoft_Status__c 
                        FROM Account Where ParentId =: setOfCAOwnerId
                        Order by Parent.Name, Name]);
        
        lstCAsMissingEmails = new List<Account>([select Id,Name,Microsoft_Status__c from Account Where RecordType.Name = 'CA Owner'
                        AND Microsoft_Status__c in ('Included') AND CA_Email_Alias_1__c = null AND CA_Email_Alias_2__c = null
                        Order by Name]);
    }
}