objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Website__c</fullName>
        <inlineHelpText>Website URL</inlineHelpText>
        <label>Company Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Geographic_Focus__c</fullName>
        <label>Geographic Focus</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Organizational_Type__c</fullName>
        <inlineHelpText>Indicate the type of organization operating this CA.</inlineHelpText>
        <label>Organizational Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Private Corporation</fullName>
                </value>
                <value>
                    <fullName>Public Corporation</fullName>
                </value>
                <value>
                    <fullName>Government Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Organization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Market_Customer_Base__c</fullName>
        <inlineHelpText>Indicates what types of customers does the CA serve?
Are there particular vertical market segments in which it operates?
Does the CA focus its activities on a particular country or other geographic region?</inlineHelpText>
        <label>Primary Market / Customer Base</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Problem_Reporting_Mechanism__c</fullName>
        <inlineHelpText>Email address or URL for reporting suspected Private Key Compromise, Certificate misuse, or other types of fraud, compromise, misuse, inappropriate conduct, or any other matter related to Certificates.</inlineHelpText>
        <label>Problem Reporting Mechanism</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recognized_CAA_Domains__c</fullName>
        <inlineHelpText>Certification Authority Authorization (CAA) domain names recognized in a CAA record&apos;s issue and issue wild property tags. Comma-separated list.</inlineHelpText>
        <label>Recognized CAA Domains</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CAAAndProblemReportingReportController.cls
/********************************************************************************************************************
  THIS CONTROLLER CLASS IS NOT IN USE. IT HAS BEEN REPLACED BY CAInformationReportController
  CAAAndProblemReportingReportController is a controller for CAAAndProblemReportingReport VF pages to list CA Owners. 
  Report name used is 'Mozilla CAA Domains & Problem Reporting Mechanism'. 
  
 *********************************************************************************************************************/

public class CAAAndProblemReportingReportController{

public List<Account> accountSoLst {get;set;}
 
    // constructor method for standard controller
    public CAAAndProblemReportingReportController() {   
                                                                  
           accountSoLst =  [select  Name,
                                    Organizational_Type__c,
                                    Geographic_Focus__c,
                                    Primary_Market_Customer_Base__c,
                                    Company_Website__c,
                                    Recognized_CAA_Domains__c,
                                    Problem_Reporting_Mechanism__c                    
                             from  Account
                             where Status__c In ('Included','Change Requested') and RecordType.Name In ('CA Owner')
                             order by Name];  
                            
          PreventEmailSpoofing(accountSoLst);                     
     }
     
     
    // Find email and replace @ with [at] and . with [dot]
    public static void PreventEmailSpoofing(List<Account> lstAccounts) {
        Pattern emailPattern = Pattern.compile('([a-zA-Z0-9_\\-\\.]+)@(((\\[a-z]{1,3}\\.[a-z]{1,3}\\.[a-z]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3}))');
        
        for(Account objAcc: lstAccounts){
            if(objAcc.Problem_Reporting_Mechanism__c != null){
               
                Matcher emailMatcher = emailPattern.matcher(objAcc.Problem_Reporting_Mechanism__c);
                
                while (emailMatcher.find()) {  // loop until no more emails to transform 
                
                    string emailmatch = emailMatcher.group();
                    string newemailmatch = emailmatch.replace('@','[at]').replace('.','[dot]');
                    string emailString = objAcc.Problem_Reporting_Mechanism__c;
                    objAcc.Problem_Reporting_Mechanism__c = emailString.replace(emailmatch,newemailmatch);
                }               
                
            }
        }
    }     
  
     
     String CurrentDate = ' ';
 
    // Get current Datetime in long date format   
    public String getCurrentDate() {

      Datetime cDT = System.now();
      CurrentDate = cDT.format('MMMM d, yyyy');

      return CurrentDate;

   }

     
}