objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auditor_New__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Name of Auditor who issued the standard audit statement. See &apos;List All Auditors&apos; below for choices. Send email to support@ccadb.org if your auditor is not listed.</inlineHelpText>
        <label>Auditor</label>
        <referenceTo>Auditor__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BR_Audit__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>BR Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Owner_ID__c</fullName>
        <description>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</description>
        <inlineHelpText>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</inlineHelpText>
        <label>CA Owner ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CP_CPS_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if this cert does not have separate policy documentation from the parent cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if this cert does not have separate policy documentation from the parent cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>CP/CPS Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Common_Name__c</fullName>
        <label>Certificate Issuer Common Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organization__c</fullName>
        <label>Certificate Issuer Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Policy_CP__c</fullName>
        <description>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certificate Policy (CP)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Serial_Number__c</fullName>
        <label>Certificate Serial Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Common_Name__c</fullName>
        <description>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</description>
        <inlineHelpText>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</inlineHelpText>
        <label>Certificate Subject Common Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Organization__c</fullName>
        <label>Certificate Subject Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certification_Practice_Statement_CPS__c</fullName>
        <description>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certification Practice Statement (CPS)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Extended_Key_Usage__c</fullName>
        <label>Extended Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Public_Key_Algorithm__c</fullName>
        <label>Public Key Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RSA 1024 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2045 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2046 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2047 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2048 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 3072 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 4096 bits</fullName>
                </value>
                <value>
                    <fullName>EC secp256r</fullName>
                </value>
                <value>
                    <fullName>EC secp256r1</fullName>
                </value>
                <value>
                    <fullName>EC secp384r1</fullName>
                </value>
                <value>
                    <fullName>EC secp512r1</fullName>
                </value>
                <value>
                    <fullName>unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Signature_Hash_Algorithm__c</fullName>
        <label>Signature Hash Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ecdsaWithSHA256</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA384</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA512</fullName>
                </value>
                <value>
                    <fullName>MD2WithRSA</fullName>
                </value>
                <value>
                    <fullName>MD5WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA1WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA256WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA384WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA512WithRSA</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Dt__c</fullName>
        <description>This formula field converts regular date field to display date in YYYY. MM.DD format. Eg: &quot;7/9/1999&quot; shows as &quot;1999.07.09&quot;</description>
        <formula>IF ( NOT ISBLANK(Standard_Audit_Statement_Date__c),  

TEXT(YEAR(Standard_Audit_Statement_Date__c)) &amp; &quot;.&quot; &amp;

IF (LEN(TEXT(MONTH(Standard_Audit_Statement_Date__c))) = 1,&quot;0&quot; &amp; TEXT(MONTH(Standard_Audit_Statement_Date__c)),TEXT(MONTH(Standard_Audit_Statement_Date__c))) 
&amp; &quot;.&quot; &amp;

IF (LEN(TEXT(DAY(Standard_Audit_Statement_Date__c))) = 1,&quot;0&quot; &amp; TEXT(DAY(Standard_Audit_Statement_Date__c)),TEXT(DAY(Standard_Audit_Statement_Date__c))),

NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Standard Audit Statement Dt</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies same logical certificates in different CA Hierarchies. SHA256(der(subject)+der(spki))</inlineHelpText>
        <label>Subject + SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Technically_Constrained__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Technically Constrained</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From_YYYY_MMM_DD__c</fullName>
        <description>This formula field converts regular date field to display date in YYYY MMM DD format. Eg: &quot;7/9/1999&quot; shows as &quot;1999 Jul 09&quot;</description>
        <formula>IF ( NOT ISBLANK(Valid_From_GMT__c), 

TEXT(YEAR(Valid_From_GMT__c)) &amp; &quot; &quot; &amp;

CASE(MONTH(Valid_From_GMT__c),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
NULL) &amp; &quot; &quot; &amp;
 
IF (LEN(TEXT(DAY(Valid_From_GMT__c))) = 1,&quot;0&quot; &amp; TEXT(DAY(Valid_From_GMT__c)),TEXT(DAY(Valid_From_GMT__c))),

NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid From [GMT]</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_To_YYYY_MMM_DD__c</fullName>
        <description>This formula field converts regular date field to display date in YYYY MMM DD format. Eg: &quot;7/9/1999&quot; shows as &quot;1999 Jul 09&quot;</description>
        <formula>IF ( NOT ISBLANK(Valid_To_GMT__c),

TEXT(YEAR(Valid_To_GMT__c)) &amp; &quot; &quot; &amp;

CASE(MONTH(Valid_To_GMT__c),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
NULL) &amp; &quot; &quot; &amp;

IF (LEN(TEXT(DAY(Valid_To_GMT__c))) = 1,&quot;0&quot; &amp; TEXT(DAY(Valid_To_GMT__c)),TEXT(DAY(Valid_To_GMT__c))),

NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid To [GMT]</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auditor__c.object
<CustomObject>
    <label>Auditor</label>
    <nameField>
        <label>Auditor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auditors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PublicIntermediateCertsController.cls
/********************************************************************************************************************
  PublicIntermediateCertsController is a controller for PublicIntermediateCerts and PublicIntermediateCertsCSVFormat
  VF pages to shows Intermediate Certs (Non-revoked) in hierarchy. 
  
  When no parameters are passed - an error will be thrown as the parameter is mandatory
  When the parameter is passed like CAOwnerName=Tesla - program lists records related to 'Tesla'
  When a blank parameter is passed CAOwnerName= -  the follow error message is displayed "No records found 
  in database. Please pass a valid CA Owner Name as url parameter."
  When the parameter is passed and no records are found then following error message is displayed - "No records found
  in database or invalid CA Owner Name passed as url parameter."
  
  Report name used is 'Public Intermediate Certs Hierarchy' 
  
 *********************************************************************************************************************/

public class PublicIntermediateCertsController {


  //private List<Account> allAccountSoLst;
  //private List<Account> revokedAccountSoLst;
 
  public transient List<Account> accountHierarchySoLst {get;set;}
  //private List<Account> accountHierarchySoLst2;
  
  // URL Parameter. If this parameter is provided then the records are fetched only for this CA Owner
  private String CAOwnerNameStr= '';
    
  Public String CurrentDate = ' ';
 
    
    public PublicIntermediateCertsController() {   
    
     // initialize all lists    
     accountHierarchySoLst = New List<account>();   
    // allAccountSoLst = New List<account>();   
     List<account> revokedAccountSoLst = New List<account>();   
    
    // get the ca owner name from the url 
    CAOwnerNameStr = ApexPages.CurrentPage().getParameters().get('CAOwnerName');
     
  
    
    String revocationStatus = 'Not Revoked';
    String recordTypeName = 'Intermediate Certificate';

    // query to get intermediate certs
    String queryStr = 'select name, type, status__c, record_type_name__c,CA_Owner_ID__c, parentid, Certificate_Issuer_Common_Name__c, Certificate_Issuer_Organization__c, Certificate_Subject_Common_Name__c, Certificate_Subject_Organization__c, SHA_256_Fingerprint__c, Certificate_Serial_Number__c, Subject_SPKI_SHA256__c, Valid_From_YYYY_MMM_DD__c, Valid_To_YYYY_MMM_DD__c, Public_Key_Algorithm__c, Signature_Hash_Algorithm__c,Certificate_Policy_CP__c, Certification_Practice_Statement_CPS__c, Standard_Audit__c, BR_Audit__c, Auditor_New__r.Name, Standard_Audit_Statement_Dt__c, CP_CPS_Same_as_Parent__c, Audits_Same_as_Parent__c,Extended_Key_Usage__c, Technically_Constrained__c From Account where lastmodifieddate!=null and Revocation_Status__c = :revocationStatus and name != \'<Fill in Cert Name>\' and technically_constrained__c != true and record_type_name__c = :RecordTypeName order by name  ';                    
    // query which gets all accounts
    String queryStr2 = 'select CA_Owner_ID__c,name, type, status__c, record_type_name__c, parentid, Certificate_Issuer_Common_Name__c, Certificate_Issuer_Organization__c, Certificate_Subject_Common_Name__c, Certificate_Subject_Organization__c, SHA_256_Fingerprint__c, Certificate_Serial_Number__c, Subject_SPKI_SHA256__c, Valid_From_YYYY_MMM_DD__c, Valid_To_YYYY_MMM_DD__c, Public_Key_Algorithm__c, Signature_Hash_Algorithm__c,Certificate_Policy_CP__c, Certification_Practice_Statement_CPS__c, Standard_Audit__c, BR_Audit__c, Auditor_New__r.Name, Standard_Audit_Statement_Dt__c, CP_CPS_Same_as_Parent__c, Audits_Same_as_Parent__c, Extended_Key_Usage__c, Technically_Constrained__c From Account where lastmodifieddate!=null  and name != \'<Fill in Cert Name>\' and technically_constrained__c != true   order by name  ';                    
    
    
    // execute the soqls and get all the revoked intermediate certs and all the accounts    
    revokedAccountSoLst= Database.query(queryStr);
    List<Account> allAccountSoLst = Database.query(queryStr2);
 
    List<Id> ownerAccountIdLst = New List<Id>();
    
    if(allaccountSoLst == null || allaccountSoLst.size() == 0 )                
    {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'No Records found.'));
    }
    else
    {
            // iterate over intermediate certs and get owner 
            for(Account accountSo: revokedAccountSoLst)
                {  
                    // getOwnerAccounts(accountSo, allAccountSoLst);
                    ownerAccountIdLst.add(accountSo.CA_Owner_ID__c);
                }
    }

  
   List<Account>  ownerAccountLst ;

     
    /**
    1) When no parameters are passed - we throw an error message as the parameter is mandatory 

    2) When the parameter is passed like CAOwnerName=Tesla - program lists records related to 'Tesla'

    3) When a blank parameter is passed CAOwnerName= -  the follow error message is displayed "No records found in database. Please pass a valid CA Owner Name as url parameter."

    4) If the parameter is passed and no records are found then following error message is displayed - "No records found in database or invalid CA Owner Name passed as url parameter."

    **/
     if(CAOwnerNameStr==null)
     {
      // ownerAccountLst = [select name, type, status__c,record_type_name__c,CA_Owner_ID__c, parentid, Certificate_Issuer_Common_Name__c, Certificate_Issuer_Organization__c, Certificate_Subject_Common_Name__c, Certificate_Subject_Organization__c, SHA_256_Fingerprint__c, Certificate_Serial_Number__c, Subject_SPKI_SHA256__c, Valid_From_YYYY_MMM_DD__c, Valid_To_YYYY_MMM_DD__c, Public_Key_Algorithm__c, Signature_Hash_Algorithm__c,Certificate_Policy_CP__c, Certification_Practice_Statement_CPS__c, Standard_Audit__c, BR_Audit__c, Auditor_New__r.Name, Standard_Audit_Statement_Dt__c, CP_CPS_Same_as_Parent__c, Audits_Same_as_Parent__c, Extended_Key_Usage__c, Technically_Constrained__c from Account where id in :ownerAccountIdLst order by name];  
       ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'CAOwnerName paramter is missing in the URL. Please make sure that you pass this parameter with a value that must be an exact match to the CA Owner Name in Salesforce.'));
     }
     else if(CaOwnerNameStr=='')
     { 

       ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'CA Owner Name in the URL must be an exact match to the CA Owner Name in Salesforce.'));
     }
     
     else
     {      
      
      ownerAccountLst = [select name, type, status__c, record_type_name__c,CA_Owner_ID__c, parentid, Certificate_Issuer_Common_Name__c, Certificate_Issuer_Organization__c, Certificate_Subject_Common_Name__c, Certificate_Subject_Organization__c, SHA_256_Fingerprint__c, Certificate_Serial_Number__c, Subject_SPKI_SHA256__c, Valid_From_YYYY_MMM_DD__c, Valid_To_YYYY_MMM_DD__c, Public_Key_Algorithm__c, Signature_Hash_Algorithm__c,Certificate_Policy_CP__c, Certification_Practice_Statement_CPS__c, Standard_Audit__c, BR_Audit__c, Auditor_New__r.Name, Standard_Audit_Statement_Dt__c, CP_CPS_Same_as_Parent__c, Audits_Same_as_Parent__c, Extended_Key_Usage__c, Technically_Constrained__c from Account where name = :CAOwnerNameStr and id in :ownerAccountIdLst order by name];  
      
      if(ownerAccountlst!=NULL && ownerAccountlst.size() == 0)
       {
               // check to see if it is a valid owner name, as we do not need to display any error message if the CA owner name is valid and no root/inter records are found
               ownerAccountLst = [select name, type, status__c, record_type_name__c,CA_Owner_ID__c, parentid, Certificate_Issuer_Common_Name__c, Certificate_Issuer_Organization__c, Certificate_Subject_Common_Name__c, Certificate_Subject_Organization__c, SHA_256_Fingerprint__c, Certificate_Serial_Number__c, Subject_SPKI_SHA256__c, Valid_From_YYYY_MMM_DD__c, Valid_To_YYYY_MMM_DD__c, Public_Key_Algorithm__c, Signature_Hash_Algorithm__c,Certificate_Policy_CP__c, Certification_Practice_Statement_CPS__c, Standard_Audit__c, BR_Audit__c, Auditor_New__r.Name, Standard_Audit_Statement_Dt__c, CP_CPS_Same_as_Parent__c, Audits_Same_as_Parent__c, Extended_Key_Usage__c, Technically_Constrained__c from Account where name = :CAOwnerNameStr order by name];
               
               if(ownerAccountlst==NULL ||( ownerAccountlst!=NULL && ownerAccountlst.size() == 0))
                   {                 
                       ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'CA Owner Name in the URL must be an exact match to the CA Owner Name in Salesforce.'));
                   }
       }
     }


  // iterate over all the owner accounts and get the child records 
   if(ownerAccountlst!=NULL && ownerAccountlst.size() > 0)
      {
          
        for(Account ownerAccountSo: ownerAccountLst)
        {
                accountHierarchySoLst.add(ownerAccountSo);
                // get the child records for the current owner and add this owner to the display list 
                getChildAccounts(ownerAccountSo, allaccountSoLst);
        }
      
      }
  

  
  
  // iterate over the generated list and add only those records in the list which have a valid parent
  if(accountHierarchySoLst.size() > 0)
  {
    List<Account> accountHierarchySoLst2 = New List<Account>();
    Boolean parentFound;
    for(Account accountSo: accountHierarchySoLst)
    {
     
      if(accountSo.record_type_name__c == 'Root Certificate') 
      {
        
        parentFound = false; 
        for(Account childAccountSo: accountHierarchySoLst)
          {
            
           if(childAccountSo.record_type_name__c == 'Intermediate Certificate' && childAccountSo.parentId == accountSo.id)
           {
             parentFound = true;
           }
       
          } // for loop
          
         
     }
     
     //if(accountSo.record_type_name__c != 'Root Certificate' || (accountSo.record_type_name__c == 'Root Certificate' && parentFound)){

     /*For the following requirement, we can use the if condition below to mark the root certs 
     which have the trustbits = website but dont have any inter certs. 
     Requirement: If the root has the websites trust bit enabled (Trust Bits = Websites), then it must have intermediate certs. 
       So, any root (with the websites trust bit enabled) with no intermediate certs would be a red flag.
      But let's not display error message in the report. We'll wait until the community users get all the data entered. 
      */
         // if(accountSo.record_type_name__c != 'Root Certificate' || (accountSo.record_type_name__c == 'Root Certificate' && accountSo.Trust_Bits__c == 'Websites' && !parentFound)){
             accountHierarchySoLst2.add(accountSo);
    
       }
   
      accountHierarchySoLst = accountHierarchySoLst2;
    
    }
       // if we are generating a CSV file then we need to replace the double quotes in all text fields with null
       if((ApexPages.currentPage().getUrl().contains('CSV') && accountHierarchySoLst !=null && accountHierarchySoLst.size() > 0) || Test.isRunningTest())
       {
          for(Account accountSo : accountHierarchySoLst)
          {
              if(accountSo.name !=null && accountSo.name.length() > 0) 
                   accountSo.name = accountSo.name.replace('"',''); 
              if(accountSo.Certificate_Issuer_Common_Name__c !=null && accountSo.Certificate_Issuer_Common_Name__c.length() > 0) 
                   accountSo.Certificate_Issuer_Common_Name__c = accountSo.Certificate_Issuer_Common_Name__c.replace('"',''); 
              if(accountSo.Certificate_Issuer_Organization__c !=null && accountSo.Certificate_Issuer_Organization__c.length() > 0) 
                   accountSo.Certificate_Issuer_Organization__c = accountSo.Certificate_Issuer_Organization__c.replace('"',''); 
              if(accountSo.Certificate_Subject_Common_Name__c !=null && accountSo.Certificate_Subject_Common_Name__c.length() > 0) 
                   accountSo.Certificate_Subject_Common_Name__c = accountSo.Certificate_Subject_Common_Name__c.replace('"',''); 
              if(accountSo.Certificate_Subject_Organization__c !=null && accountSo.Certificate_Subject_Organization__c.length() > 0) 
                   accountSo.Certificate_Subject_Organization__c = accountSo.Certificate_Subject_Organization__c.replace('"',''); 
              if(accountSo.SHA_256_Fingerprint__c !=null && accountSo.SHA_256_Fingerprint__c.length() > 0) 
                   accountSo.SHA_256_Fingerprint__c = accountSo.SHA_256_Fingerprint__c.replace('"',''); 
              if(accountSo.Extended_Key_Usage__c !=null && accountSo.Extended_Key_Usage__c.length() > 0) 
                   accountSo.Extended_Key_Usage__c = accountSo.Extended_Key_Usage__c.replace('"','');  
              if(accountSo.Certificate_Policy_CP__c !=null && accountSo.Certificate_Policy_CP__c.length() > 0) 
                   accountSo.Certificate_Policy_CP__c = accountSo.Certificate_Policy_CP__c.replace('"','');                      
              if(accountSo.Certification_Practice_Statement_CPS__c !=null && accountSo.Certification_Practice_Statement_CPS__c.length() > 0) 
                   accountSo.Certification_Practice_Statement_CPS__c = accountSo.Certification_Practice_Statement_CPS__c.replace('"','');
              if(accountSo.Standard_Audit__c !=null && accountSo.Standard_Audit__c.length() > 0) 
                   accountSo.Standard_Audit__c = accountSo.Standard_Audit__c.replace('"','');
              if(accountSo.BR_Audit__c !=null && accountSo.BR_Audit__c.length() > 0) 
                   accountSo.BR_Audit__c = accountSo.BR_Audit__c.replace('"','');       
              if(accountSo.Auditor_New__r.Name !=null && accountSo.Auditor_New__r.Name.length() > 0) 
                   accountSo.Auditor_New__r.Name = accountSo.Auditor_New__r.Name.replace('"',''); 
              /*if(accountSo.Management_Assertions_By__c !=null && accountSo.Management_Assertions_By__c.length() > 0) 
                   accountSo.Management_Assertions_By__c= accountSo.Management_Assertions_By__c.replace('"','');*/ 
           }
        }
    
 }
 
    
  /**  private void getOwnerAccounts(Account accountSo, List<account> allAccountSoLst )
    {
       
      for(Account allAccountSo : allAccountSoLst )
       {
         
         // get the parent account
         if(accountSo.parentId == allAccountSo.id)
         {
            // if the parent is of type owner then get all the child accounts of this owner
            if(allAccountSo.Record_Type_Name__c == 'CA Owner' && allAccountSo.name.contains('Microsec'))
              {
                     accountHierarchySoLst.add(allAccountSo);
                     getChildAccounts(allAccountSo, allaccountSoLst);
                     
              }
            else
             {
                // else continue and get the parent account until we dont find the owner
                 getOwnerAccounts(allAccountSo,allAccountSoLst);
             }
         }
        
        
       }
    
    }
**/

    private void getChildAccounts(Account accountSo, List<account> accountSoLst)
    {
     
       for(Account childAccountSo : accountSoLst)
       {
           
         if(childAccountSo.record_type_name__c !='Root Certificate' || (childAccountSo.record_type_name__c =='Root Certificate' && (childAccountSo.Status__c == 'Included' || childAccountSo.status__c =='Change Requested') ))  
         
         {
             if(childAccountSo.parentId == accountSo.id )
             {
               
              accountHierarchySoLst.add(childAccountSo);
              getChildAccounts(childAccountSo, accountSoLst);
             }
         }           
      }
    }
    
    
    // Get current Datetime in long date format   

    public String getCurrentDate() {

      Datetime cDT = System.now();
      CurrentDate = cDT.format('MMMM d, yyyy');

      return CurrentDate;

   }
    
 }