objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auditor_Location_New__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Country where the Auditor who issued the standard audit statement is based out of. See &apos;List All Auditors&apos; below for choices. Send email to support@ccadb.org if your auditor is not listed.</inlineHelpText>
        <label>Auditor Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Auditor_Location__c.Auditor__c</field>
                <operation>equals</operation>
                <valueField>$Source.Auditor_New__c</valueField>
            </filterItems>
            <infoMessage>Not a valid value for selected Auditor Company</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Auditor_Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auditor_New__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Name of Auditor who issued the standard audit statement. See &apos;List All Auditors&apos; below for choices. Send email to support@ccadb.org if your auditor is not listed.</inlineHelpText>
        <label>Auditor</label>
        <referenceTo>Auditor__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auditor_Qualifications__c</fullName>
        <description>URL to website attesting to the qualifications of this Auditor to issue the Standard Audit Statement</description>
        <inlineHelpText>URL to website attesting to the qualifications of this Auditor to issue the Standard Audit Statement</inlineHelpText>
        <label>Auditor Qualifications</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Auditor_Website__c</fullName>
        <description>URL to information about this Auditor</description>
        <inlineHelpText>URL to information about this Auditor</inlineHelpText>
        <label>Auditor Website</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Auditor__c</fullName>
        <description>Name of Auditor who issued the Standard Audit Statement</description>
        <inlineHelpText>Name of Auditor who issued the Standard Audit Statement</inlineHelpText>
        <label>Auditor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EV_Policy_OID_s__c</fullName>
        <label>Mozilla EV Policy OID(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auditor__c.object
<CustomObject>
    <fields>
        <fullName>Auditor_Status__c</fullName>
        <inlineHelpText>Auditor status as evaluated by Root Store Managers</inlineHelpText>
        <label>Auditor Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>Confidence - High</fullName>
                </value>
                <value>
                    <fullName>Confidence - Medium</fullName>
                </value>
                <value>
                    <fullName>Confidence - Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auditor_Website__c</fullName>
        <label>Auditor Website</label>
        <type>TextArea</type>
    </fields>
    <label>Auditor</label>
    <nameField>
        <label>Auditor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auditors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auditor_Location__c.object
<CustomObject>
    <fields>
        <fullName>Auditor_Location_Status__c</fullName>
        <inlineHelpText>Auditor status as evaluated by Root Store Managers</inlineHelpText>
        <label>Auditor Location Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>Confidence - High</fullName>
                </value>
                <value>
                    <fullName>Confidence - Medium</fullName>
                </value>
                <value>
                    <fullName>Confidence - Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auditor_Qualifications__c</fullName>
        <inlineHelpText>URL to third-party website attesting to the qualifications of this Auditor to issue WebTrust, ETSI EN 319 411, or ETSI TS 102 042 audit statements.</inlineHelpText>
        <label>Auditor Qualifications</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Auditor__c</fullName>
        <label>Auditor</label>
        <referenceTo>Auditor__c</referenceTo>
        <relationshipLabel>Auditor Locations</relationshipLabel>
        <relationshipName>Auditor_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Auditor Location</label>
    <nameField>
        <label>Auditor Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auditor Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MassUpdateAuditCPCPSDataTest.cls
@isTest
public class MassUpdateAuditCPCPSDataTest {

    
    static testmethod void testMassUpdateAuditCPCPSData1(){
        Auditor__c auditor = new Auditor__c();
        auditor.Name = 'WebTrust';
        auditor.Auditor_Status__c = 'Confidence - High';
        auditor.Auditor_Website__c = 'http://www.google.com';
        insert auditor;
        
        Auditor_Location__c auditorlocation = new Auditor_Location__c();
        auditorlocation.Name = 'US';
        auditorlocation.Auditor__c = auditor.Id;
        auditorlocation.Auditor_Location_Status__c = 'Confidence - High';
        insert auditorlocation;
        
        Account acc = new Account(Name = 'test 1', Status__c = 'Included', Type = 'Root',
                                  SHA_1_Fingerprint__c = '12:34:56:78:90:12:34:56:78:90:12:34:56:78:90:12:34:56:78:90',
                                  Auditor__c = 'WebTrust', Auditor_Qualifications__c = 'Qualifications',
                                  Auditor_Website__c = 'www.website.com', Auditor_New__c = auditor.Id, 
                                  Auditor_Location_New__c = auditorlocation.Id,
                                  EV_Policy_OID_s__c = 'Not EV', Trust_bits__c = 'All Trust Bits Turned Off');
        
        

        Account acc1 = new Account(Name = 'test 2', Auditor__c = 'WebTrust');
        Account acc2 = new Account(Name = 'test 3', Auditor__c = 'WebTrust');
        insert new List<Account>{acc, acc1, acc2};
        
        PageReference pref = Page.MassUpdateAuditCPCPSData;
        Test.setCurrentPage(pref);
        
        ApexPages.currentPage().getParameters().put('Id', acc.Id);
        
        ApexPages.standardController stdCon = new ApexPages.standardController(acc);
        MassUpdateAuditCPCPSDataController obj = new MassUpdateAuditCPCPSDataController(stdCon);
        
        obj.redirectToAccount();
       // obj.syncAccount();
    }
    
    static testmethod void testMassUpdateAuditCPCPSData2(){
        
        Account acc = new Account(Name = 'test 1', Type = 'Intermediate Certificate', 
        SHA_1_Fingerprint__c = '12:34:56:78:90:12:34:56:78:90:12:34:56:78:90:12:34:56:78:92',
        Status__c = 'Included', Audits_Same_As_Parent__c = True);
        insert acc;
        
        Account acc1 = new Account(Name = 'test 2', ParentId = acc.Id, Type = 'Intermediate Certificate');
        Account acc2 = new Account(Name = 'test 3', ParentId = acc.Id, Type = 'Intermediate Certificate');
        insert new List<Account>{acc1, acc2};
        
        PageReference pref = Page.MassUpdateAuditCPCPSData;
        Test.setCurrentPage(pref);
        
        ApexPages.currentPage().getParameters().put('Id', acc.Id);
        
        ApexPages.standardController stdCon = new ApexPages.standardController(acc);
        MassUpdateAuditCPCPSDataController obj = new MassUpdateAuditCPCPSDataController(stdCon);
        
        obj.syncStdAuditFieldsOnTargetAccount();
        obj.syncBRAuditFieldsOnTargetAccount();
        obj.syncEVSSLAuditFieldsOnTargetAccount();
        obj.syncEVCodeSigningAuditFieldsOnTargetAccount();
        obj.syncPolicyFieldsOnTargetAccount();
        obj.syncMozillaFieldsOnTargetAccount();
        obj.syncMicrosoftFieldsOnTargetAccount();
        obj.redirectToNextAccount();
        obj.redirectTosourceAccount();
    }
    
    static testmethod void testMassUpdateAuditCPCPSData3(){
        
        Auditor__c auditor = new Auditor__c();
        auditor.Name = 'WebTrust';
        auditor.Auditor_Status__c = 'Confidence - High';
        auditor.Auditor_Website__c = 'http://www.google.com';
        insert auditor;
        
        Auditor_Location__c auditorlocation = new Auditor_Location__c();
        auditorlocation.Name = 'US';
        auditorlocation.Auditor__c = auditor.Id;
        auditorlocation.Auditor_Location_Status__c = 'Confidence - High';
        insert auditorlocation;
        
        Account parentAcc = new Account(Name = 'test 1', Type = 'Intermediate Certificate', 
        SHA_1_Fingerprint__c = '12:34:56:78:90:12:34:56:78:90:12:34:56:78:90:12:34:56:78:01',
        Auditor__c = 'Auditor', Auditor_Qualifications__c = 'Qualifications',
        Auditor_Website__c = 'www.website.com', Status__c = 'Included' );
        insert parentAcc;
        
        Account acc1 = new Account(Name = 'test 2', ParentId = parentAcc.Id, Type = 'Intermediate Certificate', 
        SHA_1_Fingerprint__c = '12:34:56:78:90:12:34:56:78:90:12:34:56:78:90:12:34:56:78:02',
        Auditor__c = 'Auditor', Auditor_Qualifications__c = 'Qualifications',
        Auditor_New__c = auditor.Id, Auditor_Location_New__c = auditorlocation.Id,
        Auditor_Website__c = 'www.website.com', Status__c = 'Included');
        
        Account acc2 = new Account(Name = 'test 3', ParentId = parentAcc.Id, Type = 'Intermediate Certificate', 
        SHA_1_Fingerprint__c = '12:34:56:78:90:12:34:56:78:90:12:34:56:78:90:12:34:56:78:03',
        Auditor__c = 'WebTrust', Auditor_Qualifications__c = 'Qualifications',
        Auditor_New__c = auditor.Id, Auditor_Location_New__c = auditorlocation.Id,
        Auditor_Website__c = 'www.website.com', Status__c = 'Included');
        insert new List<Account>{acc1, acc2};
        
        PageReference pref = Page.MassUpdateAuditCPCPSData;
        Test.setCurrentPage(pref);
        
        ApexPages.currentPage().getParameters().put('Id', acc1.Id);
        
        ApexPages.standardController stdCon = new ApexPages.standardController(acc1);
        MassUpdateAuditCPCPSDataController obj = new MassUpdateAuditCPCPSDataController(stdCon);
        //obj.GetAllCertificates(); 
        obj.syncStdAuditFieldsOnTargetAccount();
        obj.syncAuditorNewFieldsOnTargetAccount();
        obj.syncCodeSigningAuditFieldsOnTargetAccount();
        obj.syncBRAuditFieldsOnTargetAccount();
        obj.syncEVSSLAuditFieldsOnTargetAccount();
        obj.syncEVCodeSigningAuditFieldsOnTargetAccount();
        obj.syncPolicyFieldsOnTargetAccount();
        obj.syncMozillaFieldsOnTargetAccount();
        obj.syncMicrosoftFieldsOnTargetAccount();
        obj.redirectToNextAccount();
        obj.redirectTosourceAccount();
        obj.checkPortalUserValidation();
        obj.redirectFromLandingPage();
    }
    
}