objects/Account.object
<CustomObject>
    <fields>
        <fullName>Approval_Bug__c</fullName>
        <label>Mozilla Approval Bug</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Auditor__c</fullName>
        <description>Name of Auditor who issued the Standard Audit Statement</description>
        <inlineHelpText>Name of Auditor who issued the Standard Audit Statement</inlineHelpText>
        <label>Auditor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BR_Audit__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>BR Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organization__c</fullName>
        <label>Certificate Issuer Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organizational_Unit__c</fullName>
        <label>Certificate Issuer Organizational Unit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Policy_CP__c</fullName>
        <description>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certificate Policy (CP)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Serial_Number__c</fullName>
        <label>Certificate Serial Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certification_Practice_Statement_CPS__c</fullName>
        <description>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certification Practice Statement (CPS)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Company_Website__c</fullName>
        <inlineHelpText>Website URL</inlineHelpText>
        <label>Company Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>EV_Audit__c</fullName>
        <description>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>EV SSL Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Policy_OID_s__c</fullName>
        <label>Mozilla EV Policy OID(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Firefox_Release_When_First_Included__c</fullName>
        <label>Firefox Release When First Included</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firefox_Release_When_Removed__c</fullName>
        <label>Firefox Release When Removed</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geographic_Focus__c</fullName>
        <label>Geographic Focus</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mozilla_Applied_Constraints__c</fullName>
        <label>Mozilla Applied Constraints</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NSS_Release_When_First_Included__c</fullName>
        <label>NSS Release When First Included</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSS_Release_When_Removed__c</fullName>
        <label>NSS Release When Removed</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_Key_Algorithm__c</fullName>
        <label>Public Key Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RSA 1024 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2045 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2046 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2047 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2048 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 3072 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 4096 bits</fullName>
                </value>
                <value>
                    <fullName>EC secp256r</fullName>
                </value>
                <value>
                    <fullName>EC secp256r1</fullName>
                </value>
                <value>
                    <fullName>EC secp384r1</fullName>
                </value>
                <value>
                    <fullName>EC secp512r1</fullName>
                </value>
                <value>
                    <fullName>unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Removal_Bug_No_or_Date__c</fullName>
        <label>Mozilla Removal Bug No. or Date</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Signature_Hash_Algorithm__c</fullName>
        <label>Signature Hash Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ecdsaWithSHA256</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA384</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA512</fullName>
                </value>
                <value>
                    <fullName>MD2WithRSA</fullName>
                </value>
                <value>
                    <fullName>MD5WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA1WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA256WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA384WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA512WithRSA</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit_Type__c</fullName>
        <label>Standard Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 101 456</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 101 456</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies same logical certificates in different CA Hierarchies. SHA256(der(subject)+der(spki))</inlineHelpText>
        <label>Subject + SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From_GMT__c</fullName>
        <inlineHelpText>The date from which the root CA certificate is valid.</inlineHelpText>
        <label>Valid From (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auditor__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Public comments</inlineHelpText>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Auditor</label>
    <nameField>
        <label>Auditor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auditors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PolicyDocumentAssociation_On_Certificate__c.object
<CustomObject>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certificate Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Policy Document Associations (On Certificate)</relationshipLabel>
        <relationshipName>Policy_Document_Associations_OnCert</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Last_Update_Date__c</fullName>
        <formula>Policy_Document__r.Document_Last_Updated_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Last Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <formula>Policy_Document__r.Document_Link__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>Text (Policy_Document__r.Document_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted?</label>
        <type>Checkbox</type>
    </fields>
    <label>Policy Document Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Document Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RemovedCACertificateReportController.cls
/********************************************************************************************************************
  RemovedCACertificateReportController is a controller for RemovedCACertificateReport, RemovedCACertificateReportCSVFormat
  and RemovedCACertificateReportPEMCSV VF pages to lists Mozilla'd removed root certs. 
  Report name used is 'Mozilla Removed CA Certificate List' 
  
  8/12/2020 - Updated code changed consider CP links when document type is CP and CPS for CPS and CP/CPS for policy documents.
 *********************************************************************************************************************/

public class RemovedCACertificateReportController{

    public transient List<wrapAccounts> lstwrapAccounts {get; set;}
 
    //constructor method for standard controller
    public RemovedCACertificateReportController() {   
        lstwrapAccounts = new List<wrapAccounts>();           
        List<Account> accountSoLst =  [select  Parent.Name,
                            Certificate_Issuer_Organization__c,
                            Certificate_Issuer_Organizational_Unit__c,
                            Name,
                            SHA_256_Fingerprint__c, 
                            Certificate_Serial_Number__c, 
                            Valid_From_GMT__c, 
                            Valid_To_GMT__c,       
                            Subject_SPKI_SHA256__c,                                                                  
                            Public_Key_Algorithm__c,
                            Signature_Hash_Algorithm__c,
                            Trust_Bits__c,
                            EV_Policy_OID_s__c, 
                            Removal_Bug_No_or_Date__c,
                            Approval_Bug__c,
                            NSS_Release_When_First_Included__c,
                            Firefox_Release_When_First_Included__c,
                            NSS_Release_When_Removed__c,
                            Firefox_Release_When_Removed__c,
                            Mozilla_Applied_Constraints__c, 
                            Parent.Company_Website__c,
                            Parent.Geographic_Focus__c,
                            //Certificate_Policy_CP__c,
                            //Certification_Practice_Statement_CPS__c,
                            Standard_Audit__c,
                            BR_Audit__c, 
                            EV_Audit__c,
                            Auditor__c,
                            Standard_Audit_Type__c,
                            X_509_Certificate_PEM__c,
                            Comments__c,
                            (Select Id, Document_Link__c, Document_Type__c from Policy_Document_Associations_OnCert__r Where Is_Deleted__c = false
                                Order by Document_Last_Update_Date__c desc)  
                            from  Account
                            where Status__c In ('Removed') and RecordType.Name In ('Root Certificate')
                            order by Parent.Name, Name];
     
        //if we are generating a CSV file then we need to replace the double quotes in all text fields with null
        if(Test.isRunningTest() || (accountSoLst !=null && accountSoLst.size() > 0)){
            for(Account accountSo : accountSoLst){
                if(Test.isRunningTest() || ApexPages.currentPage().getUrl().contains('CSV')) { // additional Test.isRunningTest() for test class to work
                    if(accountSo.Parent.Name !=null && accountSo.Parent.Name.length() > 0) 
                        accountSo.Parent.Name = accountSo.Parent.Name.replace('"',''); 
                    if(accountSo.name !=null && accountSo.name.length() > 0) 
                        accountSo.name = accountSo.name.replace('"',''); 
                    if(accountSo.Certificate_Issuer_Organization__c !=null && accountSo.Certificate_Issuer_Organization__c.length() > 0) 
                        accountSo.Certificate_Issuer_Organization__c = accountSo.Certificate_Issuer_Organization__c.replace('"','');                                        
                    if(accountSo.Certificate_Issuer_Organizational_Unit__c !=null && accountSo.Certificate_Issuer_Organizational_Unit__c.length() > 0) 
                        accountSo.Certificate_Issuer_Organizational_Unit__c = accountSo.Certificate_Issuer_Organizational_Unit__c.replace('"','');  
                    if(accountSo.SHA_256_Fingerprint__c !=null && accountSo.SHA_256_Fingerprint__c.length() > 0) 
                        accountSo.SHA_256_Fingerprint__c = accountSo.SHA_256_Fingerprint__c.replace('"','');                  
                    if(accountSo.EV_Policy_OID_s__c !=null && accountSo.EV_Policy_OID_s__c.length() > 0) 
                        accountSo.EV_Policy_OID_s__c = accountSo.EV_Policy_OID_s__c.replace('"','');                   
                    if(accountSo.Removal_Bug_No_or_Date__c !=null && accountSo.Removal_Bug_No_or_Date__c.length() > 0) 
                        accountSo.Removal_Bug_No_or_Date__c = accountSo.Removal_Bug_No_or_Date__c.replace('"','');                       
                    if(accountSo.Approval_Bug__c !=null && accountSo.Approval_Bug__c.length() > 0) 
                        accountSo.Approval_Bug__c = accountSo.Approval_Bug__c.replace('"','');                                                      
                    if(accountSo.NSS_Release_When_First_Included__c !=null && accountSo.NSS_Release_When_First_Included__c.length() > 0) 
                        accountSo.NSS_Release_When_First_Included__c = accountSo.NSS_Release_When_First_Included__c.replace('"','');
                    if(accountSo.Firefox_Release_When_First_Included__c !=null && accountSo.Firefox_Release_When_First_Included__c.length() > 0) 
                        accountSo.Firefox_Release_When_First_Included__c = accountSo.Firefox_Release_When_First_Included__c.replace('"','');
                    if(accountSo.NSS_Release_When_Removed__c !=null && accountSo.NSS_Release_When_Removed__c.length() > 0) 
                        accountSo.NSS_Release_When_Removed__c = accountSo.NSS_Release_When_Removed__c.replace('"','');
                    if(accountSo.Firefox_Release_When_Removed__c !=null && accountSo.Firefox_Release_When_Removed__c.length() > 0) 
                        accountSo.Firefox_Release_When_Removed__c = accountSo.Firefox_Release_When_Removed__c.replace('"','');                    
                    /*if(accountSo.URL_to_Test_Website_or_Example_Cert__c !=null && accountSo.URL_to_Test_Website_or_Example_Cert__c.length() > 0) 
                    accountSo.URL_to_Test_Website_or_Example_Cert__c = accountSo.URL_to_Test_Website_or_Example_Cert__c.replace('"','');   */                
                    if(accountSo.Mozilla_Applied_Constraints__c !=null && accountSo.Mozilla_Applied_Constraints__c.length() > 0) 
                        accountSo.Mozilla_Applied_Constraints__c = accountSo.Mozilla_Applied_Constraints__c.replace('"','');                   
                    if(accountSo.Parent.Company_Website__c !=null && accountSo.Parent.Company_Website__c.length() > 0) 
                        accountSo.Parent.Company_Website__c = accountSo.Parent.Company_Website__c.replace('"','');
                    if(accountSo.Parent.Geographic_Focus__c !=null && accountSo.Parent.Geographic_Focus__c.length() > 0) 
                        accountSo.Parent.Geographic_Focus__c = accountSo.Parent.Geographic_Focus__c.replace('"','');                    
                    /*if(accountSo.Certificate_Policy_CP__c !=null && accountSo.Certificate_Policy_CP__c.length() > 0) 
                        accountSo.Certificate_Policy_CP__c = accountSo.Certificate_Policy_CP__c.replace('"','');                      
                    if(accountSo.Certification_Practice_Statement_CPS__c !=null && accountSo.Certification_Practice_Statement_CPS__c.length() > 0) 
                        accountSo.Certification_Practice_Statement_CPS__c = accountSo.Certification_Practice_Statement_CPS__c.replace('"','');  */                  
                    if(accountSo.Standard_Audit__c !=null && accountSo.Standard_Audit__c.length() > 0) 
                        accountSo.Standard_Audit__c = accountSo.Standard_Audit__c.replace('"','');
                    if(accountSo.BR_Audit__c !=null && accountSo.BR_Audit__c.length() > 0) 
                        accountSo.BR_Audit__c = accountSo.BR_Audit__c.replace('"','');
                    if(accountSo.EV_Audit__c !=null && accountSo.EV_Audit__c.length() > 0) 
                        accountSo.EV_Audit__c = accountSo.EV_Audit__c.replace('"','');                  
                    if(accountSo.Auditor__c !=null && accountSo.Auditor__c.length() > 0) 
                        accountSo.Auditor__c = accountSo.Auditor__c.replace('"',''); 
                    if(accountSo.Comments__c !=null && accountSo.Comments__c.length() > 0) 
                        accountSo.Comments__c = accountSo.Comments__c.replace('"',''); 
                }      
                //fill wrapper
                wrapAccounts wrapAcc = new wrapAccounts();
                string strCP = '';
                string strCPS = '';
                for(PolicyDocumentAssociation_On_Certificate__c PDAC: accountSo.Policy_Document_Associations_OnCert__r){
                    if(PDAC.Document_Type__c != null){
                        if(PDAC.Document_Type__c == 'CP'){
                            if(string.isnotblank(strCP)) strCP += '; ';
                            strCP += PDAC.Document_Link__c;
                        }
                        if(PDAC.Document_Type__c == 'CPS' || PDAC.Document_Type__c == 'CP/CPS'){
                            if(string.isnotblank(strCPS)) strCPS += '; ';
                            strCPS += PDAC.Document_Link__c;
                        }
                    }
                }  
                wrapAcc.objAccount = accountSo;
                wrapAcc.CP = strCP;
                wrapAcc.CPS = strCPS;
                lstwrapAccounts.add(wrapAcc);  
            }
        }
    }
    
    String CurrentDate = ' ';
    // Get current Datetime in long date format   
    public String getCurrentDate() {
        Datetime cDT = System.now();
        CurrentDate = cDT.format('MMMM d, yyyy');
        return CurrentDate;
    }
    
    public class wrapAccounts {
        public string CP {get; set;}
        public string CPS {get; set;}
        public Account objAccount {get; set;}
        public wrapAccounts(){
            CP = '';
            CPS = '';
            objAccount = new Account();
        }
    }
}