objects/Account.object
<CustomObject>
    <fields>
        <fullName>CRL_URL_s__c</fullName>
        <inlineHelpText>URL(s) at which the CRL(s) may be obtained -- for end-entity certs and for intermediate CAs.</inlineHelpText>
        <label>CRL URL(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Common_Name__c</fullName>
        <label>Certificate Issuer Common Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organization__c</fullName>
        <label>Certificate Issuer Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organizational_Unit__c</fullName>
        <label>Certificate Issuer Organizational Unit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Serial_Number__c</fullName>
        <label>Certificate Serial Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Common_Name__c</fullName>
        <description>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</description>
        <inlineHelpText>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</inlineHelpText>
        <label>Certificate Subject Common Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Organization_Unit__c</fullName>
        <label>Certificate Subject Organization Unit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Organization__c</fullName>
        <label>Certificate Subject Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Display_Warning_or_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by VF page to display warnings or messages</description>
        <label>Display Warning or Message</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Webservice_Failed_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by Account trigger helper class</description>
        <label>Display Webservice Failed Message</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Webservice_Not_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by Account trigger helper class</description>
        <label>Display Webservice Not Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Extended_Key_Usage__c</fullName>
        <label>Extended Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Extraction_Results__c</fullName>
        <label>Extraction Results</label>
        <length>6000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Key_Usage__c</fullName>
        <label>Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ProcessPEMInfoBatch_Message__c</fullName>
        <label>ProcessPEMInfoBatch Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Public_Key_Algorithm__c</fullName>
        <label>Public Key Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RSA 1024 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2045 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2046 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2047 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2048 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 3072 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 4096 bits</fullName>
                </value>
                <value>
                    <fullName>EC secp256r</fullName>
                </value>
                <value>
                    <fullName>EC secp256r1</fullName>
                </value>
                <value>
                    <fullName>EC secp384r1</fullName>
                </value>
                <value>
                    <fullName>EC secp512r1</fullName>
                </value>
                <value>
                    <fullName>unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Signature_Hash_Algorithm__c</fullName>
        <label>Signature Hash Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ecdsaWithSHA256</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA384</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA512</fullName>
                </value>
                <value>
                    <fullName>MD2WithRSA</fullName>
                </value>
                <value>
                    <fullName>MD5WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA1WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA256WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA384WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA512WithRSA</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technically_Constrained__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Technically Constrained</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Valid_From_GMT__c</fullName>
        <inlineHelpText>The date from which the root CA certificate is valid.</inlineHelpText>
        <label>Valid From (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProcessPEMInfoBatchHelper.cls
// This is the helper class for the ProcessPEMInfoBatch class. It 
// processes the PEM info and updates the PEM fields on the record. 
// *** Important *** Validation rule 'Check_PEM_Derived_Fields' must be deactivated
// before starting the batch job.

public class ProcessPEMInfoBatchHelper {

// this method processes each intermediate cert and populates the record id of that root on the inter cert record.
// if the intermediate cert record already has the root cert id populated then it is updated only if the new root cert id 
// is different than the root cert id on the record.

 public static Integer processInterCerts(List<Account> accountSolst) {

    List<Account> toBeUpdatedCertsLst = New List<Account>();
    Account tempCertSO;
        Boolean isCertCheckSuccessful;
    DateTime currentDT = DateTime.now();
    String formattedDt = currentDT.format('MM-dd-yyyy hh:mm:ss');
   try{
    // iterate over each intermediate cert and invoke the cert checker webservice and get the response
    for(Account accountSo: accountSoLst){
    
        isCertCheckSuccessful = true;
        accountSo.ProcessPEMInfoBatch_Message__c = '';
            
        if(accountSo.X_509_Certificate_PEM__c != null ) {
        
          tempCertSO = X509CertificateCheckerUtility.x509CertChecker(accountSo.X_509_Certificate_PEM__c);     
          
          if(tempCertSO.Display_Webservice_Not_Available__c || tempCertSO.Display_Webservice_Failed_Message__c) {      
          system.debug('Webservice not available');
          system.debug('accountid='+accountSo.id);
             accountSo.ProcessPEMInfoBatch_Message__c += 'Error: The webservice for parsing cert data is unavailable at the current moment. Please try again later.';
             isCertCheckSuccessful = false;
          }
     
          if(tempCertSO.Extraction_Results__c == '{}')  {      
            accountSo.ProcessPEMInfoBatch_Message__c += 'Error: Parsing of cert data gave no results. Please provided correct PEM format for the certificate.';
            isCertCheckSuccessful = false;
          }
          
          if(!tempCertSO.Extraction_Results__c.contains('issuerCN')) {      
            accountSo.ProcessPEMInfoBatch_Message__c += 'Error: Extraction results does not look right. Please provided correct PEM format for the certificate.';
            isCertCheckSuccessful = false;
          }
      
          if (isCertCheckSuccessful) {
            accountSo.ProcessPEMInfoBatch_Message__c += 'Message: PEM Info parsing completed successful.';
          } 
          
          accountSo.ProcessPEMInfoBatch_Message__c += ' [' + formattedDt + ']';  
          
          accountSo.Name = tempCertSO.Name; 
          accountSo.Extraction_Results__c = tempCertSO.Extraction_Results__c ;
          accountSo.Display_Warning_or_Message__c = tempCertSO.Display_Warning_or_Message__c;
          accountSo.Display_Webservice_Not_Available__c = tempCertSO.Display_Webservice_Not_Available__c;
          accountSo.Display_Webservice_Failed_Message__c = tempCertSO.Display_Webservice_Failed_Message__c;
          accountSo.Certificate_Issuer_Common_Name__c = tempCertSO.Certificate_Issuer_Common_Name__c;
          accountSo.Certificate_Issuer_Organizational_Unit__c = tempCertSO.Certificate_Issuer_Organizational_Unit__c;
          accountSo.Certificate_Issuer_Organization__c = tempCertSO.Certificate_Issuer_Organization__c;
          accountSo.Certificate_Subject_Common_Name__c = tempCertSO.Certificate_Subject_Common_Name__c;
          accountSo.Certificate_Subject_Organization_Unit__c = tempCertSO.Certificate_Subject_Organization_Unit__c;
          accountSo.Certificate_Subject_Organization__c = tempCertSO.Certificate_Subject_Organization__c;
          //accountSo.Certificate_ID__c = tempCertSO.Certificate_ID__c;
          accountSo.Certificate_Serial_Number__c = tempCertSO.Certificate_Serial_Number__c;
          accountSo.SHA_1_Fingerprint__c = tempCertSO.SHA_1_Fingerprint__c;
          accountSo.SHA_256_Fingerprint__c= tempCertSO.SHA_256_Fingerprint__c;
          //accountSo.Certificate_ID__c= tempCertSO.Certificate_ID__c;
          accountSo.Valid_From_GMT__c = tempCertSO.Valid_From_GMT__c;
          accountSo.Valid_To_GMT__c = tempCertSO.Valid_To_GMT__c;
          accountSo.Certificate_Serial_Number__c = tempCertSO.Certificate_Serial_Number__c; 
          accountSo.Signature_Hash_Algorithm__c = tempCertSO.Signature_Hash_Algorithm__c;
          //accountSo.Basic_Constraints__c = tempCertSO.Basic_Constraints__c;
          accountSo.Public_Key_Algorithm__c = tempCertSO.Public_Key_Algorithm__c;
          accountSo.Key_Usage__c = tempCertSO.Key_Usage__c;
          accountSo.Extended_Key_Usage__c = tempCertSO.Extended_Key_Usage__c;
          //accountSo.OCSP_URL_s__c = tempCertSO.OCSP_URL_s__c;
          accountSo.CRL_URL_s__c = tempCertSO.CRL_URL_s__c;
          accountSo.Technically_Constrained__c = tempCertSO.Technically_Constrained__c;    
  
          
          toBeUpdatedCertsLst.add(accountSO);
    
          system.debug('##### toBeUpdatedCertsLst Size='+toBeUpdatedCertsLst.size());
       
      }  
    }
    }
    catch (Exception ex)
    {
     System.debug('linenumer ' + ex.getLineNumber());    
     System.debug('linenumer ' + ex.getMessage());    
     System.debug('linenumer ' + ex.getStackTraceString());    
     
    
    }
    
    // now bulk update records from current batch
    try {
          if(toBeUpdatedCertsLst.size() > 0) {
             update toBeUpdatedCertsLst; 
             system.debug('##### Total number of certs updated from current batch ='+toBeUpdatedCertsLst.size());
          } 
    } catch(Exception e) {
    
        System.debug('An unexpected error has occurred during bulk update: ' + e.getMessage());    
    }
     
    return toBeUpdatedCertsLst.size();
  }

}