objects/Account.object
<CustomObject>
    <fields>
        <fullName>BR_Audit_Statement_Date__c</fullName>
        <description>Date BR Audit Statement Issued</description>
        <inlineHelpText>Date BR Audit Statement Issued</inlineHelpText>
        <label>BR Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>BR Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Statement_Date__c</fullName>
        <description>Date EV SSL Audit Statement Issued</description>
        <inlineHelpText>Date EV SSL Audit Statement Issued</inlineHelpText>
        <label>EV SSL Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit__c</fullName>
        <description>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>EV SSL Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Root_Status__c</fullName>
        <formula>TEXT( Root_Cert_Id__r.Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This formula field derives root status from &apos;Root Cert Id&apos; field. &apos;Root Cert Id&apos; is populated for all intermediate certs by PublicAllIntermediateCerts batch program.</inlineHelpText>
        <label>Root Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Standard Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Date__c</fullName>
        <description>Date Audit Statement Issued</description>
        <inlineHelpText>Date Audit Statement Issued</inlineHelpText>
        <label>Standard Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PublicInterCertsWithOutdatedAuditStCtlr.cls
/********************************************************************************************************************
  PublicInterCertsWithOutdatedAuditStCtlr is a controller for PublicInterCertsWithOutdatedAuditSt VF pages 
  to list intermediate certs ...
  
  Filtered By:
        CA Owner/Certificate Record Type equals Intermediate Certificate
        AND <Root Cert that it chains up to is in Mozilla's root store>
        AND Revocation Status not equal to Revoked,Parent Cert Revoked
        AND Valid To (GMT) greater than TODAY  <i.e. cert is not expired>
        AND Standard Audit Statement Date less than (TODAY - 1 year) <i.e. audits due>
        Sort by Standard Audit Statement Date, with oldest on top

  Report name used is 'Intermediate Certs With Outdated Audit Statements' 
  
  *** Revision History ***
  Create Date: 7/13/2018
  Update Date:
 *********************************************************************************************************************/

public class PublicInterCertsWithOutdatedAuditStCtlr{

    public transient List<Account> accountSoLst {get;set;}
 
    // constructor method for standard controller
    public PublicInterCertsWithOutdatedAuditStCtlr() { 
    
        accountSoLst = [SELECT Name, 
                           CA_Owner__c,
                           Standard_Audit__c,
                           Standard_Audit_Statement_Date__c,
                           Standard_Audit_Period_Start_Date__c,
                           Standard_Audit_Period_End_Date__c, 
                           BR_Audit__c,
                           BR_Audit_Statement_Date__c,
                           EV_Audit__c,
                           EV_Audit_Statement_Date__c                                                                    
                               FROM Account 
                               WHERE Name != '<Fill in Cert Name>'
                               AND Record_Type_Name__c = 'Intermediate Certificate'
                               AND Revocation_Status__c NOT IN ('Revoked', 'Parent Cert Revoked')
                               AND Valid_To_GMT__c > TODAY   
                               AND Standard_Audit_Statement_Date__c < LAST_N_DAYS:365
                               AND Root_Status__c IN  ('Included','Change Requested')                     
                                      ORDER BY Standard_Audit_Statement_Date__c];  
                                                 
         
         // if we are generating a CSV file then we need to replace the double quotes in all text fields with null
         /**  if((ApexPages.currentPage().getUrl().contains('CSV') && accountSoLst !=null && accountSoLst.size() > 0) || Test.IsRunningTest())
           {
              for(Account accountSo : accountSoLst)
              {
                  if(accountSo.Name !=null && accountSo.Name.length() > 0) 
                       accountSo.Name = accountSo.Name.replace('"','');              
                  if(accountSo.CA_Owner__c!=null && accountSo.CA_Owner__c.length() > 0) 
                       accountSo.CA_Owner__c= accountSo.CA_Owner__c.replace('"','');                                     
              }
          }  **/                  
    }
     
    String CurrentDate = ' ';
    
    // Get current Datetime in long date format   
    public String getCurrentDate() {
        Datetime cDT = System.now();
        CurrentDate = cDT.format('MMMM d, yyyy');
        return CurrentDate;
    }
}