objects/Account.object
<CustomObject>
    <fields>
        <fullName>Approval_Bug__c</fullName>
        <label>Mozilla Approval Bug</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organization__c</fullName>
        <label>Certificate Issuer Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organizational_Unit__c</fullName>
        <label>Certificate Issuer Organizational Unit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Policy_CP__c</fullName>
        <description>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certificate Policy (CP)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certification_Practice_Statement_CPS__c</fullName>
        <description>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certification Practice Statement (CPS)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Firefox_Release_When_First_Included__c</fullName>
        <label>Firefox Release When First Included</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Friendly_Name__c</fullName>
        <label>Friendly Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mozilla_Applied_Constraints__c</fullName>
        <label>Mozilla Applied Constraints</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NSS_Release_When_First_Included__c</fullName>
        <label>NSS Release When First Included</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Website_Expired__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with an expired TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Expired</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Website_Revoked__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with a revoked TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Revoked</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IncludedCACertificateReportTestForMSFT.cls
/*******************************************************************************************************
 Name: IncludedCACertificateReportCtlrForMSFT

 Dependencies:  IncludedCACertificateReportCtlrForMSFT controller class, IncludedCACertificateReportTestForMSFT
 test class, IncludedCACertificateReportForMSFT vf page, IncludedCACertificateReportForMSFTCSV  vf page,
 IncludedCACertificateReportForMSFTCSVPEM  vf page

 Description: This is a test class for controller IncludedCACertificateReportCtlrForMSFT which
 generates list all root certificates included by Microsoft.
 
 Instructions: None   
 *******************************************************************************************************
 Revision History:
 
      8/16/2016 - Created new class
 ******************************************************************************************************/

@isTest 
public class IncludedCACertificateReportTestForMSFT{

    static testMethod void validateTest() {
        PageReference pref = Page.IncludedCACertificateReportForMSFTCSV;
        Test.setCurrentPage(pref);
        
        Account caOwnerAcc = TestUtils.getCAOwner();
        insert caOwnerAcc;
        
        Account childAccount = TestUtils.getRootCertificate(caOwnerAcc.id);
        childAccount.Microsoft_Status__c = 'Included';
        childAccount.Friendly_Name__c = 'Test root';
        childAccount.Certificate_Issuer_Organization__c = 'Test IO';
        childAccount.Certificate_Issuer_Organizational_Unit__c = 'Test IOU';
        childAccount.Approval_Bug__c = 'Test';
        childAccount.NSS_Release_When_First_Included__c = 'Test';
        childAccount.Firefox_Release_When_First_Included__c = 'Test';
        childAccount.Mozilla_Applied_Constraints__c = 'Test';
        childAccount.Certificate_Policy_CP__c = 'Test';
        childAccount.Certification_Practice_Statement_CPS__c = 'Test';
        childAccount.Test_Website_Expired__c = 'https://expired.com';
        childAccount.Test_Website_Revoked__c = 'https://revoked.com';
        childAccount.X_509_Certificate_PEM__c = 'Test';
        insert childAccount;
        
        IncludedCACertificateReportCtlrForMSFT certs = new IncludedCACertificateReportCtlrForMSFT();
        certs.getCurrentDate();
    }
}