objects/Account.object
<CustomObject>
    <fields>
        <fullName>CA_Document_Repository__c</fullName>
        <description>URL to where policy documentation specific to this cert may be found</description>
        <inlineHelpText>URL to where policy documentation specific to this cert may be found</inlineHelpText>
        <label>CA Document Repository</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <description>This field is hyperlink to Account Name. Mainly used in reports.</description>
        <formula>HYPERLINK(Id, Name, &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Certificate Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Document_Repository_Description__c</fullName>
        <inlineHelpText>Optional explanation about the CA&apos;s policy documentation</inlineHelpText>
        <label>Document Repository Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Document_Repository__c</fullName>
        <inlineHelpText>URL to where the CA&apos;s policy documentation may be found. More than one URL may be provided as a semicolon - separated list.</inlineHelpText>
        <label>Document Repository</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Documentation__c</fullName>
        <description>Further documentation or information relevant to this cert</description>
        <inlineHelpText>Further documentation or information relevant to this cert</inlineHelpText>
        <label>Policy Documentation</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Policy_Identifiers__c</fullName>
        <label>Policy Identifiers</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CA_Document_Repository__c</fullName>
        <description>URL to where policy documentation specific to the listed root certs may be found</description>
        <inlineHelpText>URL to where policy documentation specific to the listed root certs may be found</inlineHelpText>
        <label>CA Document Repository</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Documentation__c</fullName>
        <description>Further documentation or information relevant to the listed root certs.</description>
        <inlineHelpText>Further documentation or information relevant to the listed root certs.</inlineHelpText>
        <label>Policy Documentation</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Policy_Document_Association_On_Case__c.object
<CustomObject>
    <description>Policy Document Association records on Case</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>Updated by custom process to indicate the action taken on the Policy Document Association record</inlineHelpText>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Policy_Document_Associations_On_Case</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certificate Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Policy_Document_Associations_On_Case</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <formula>Policy_Document__r.Document_Link__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>TEXT (Policy_Document__r.Document_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_Document__c</fullName>
        <label>Document Id</label>
        <referenceTo>Policy_Document_On_Case__c</referenceTo>
        <relationshipName>Policy_Document_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Policy Document Association (On Case)</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Document Associations (On Case)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Policy_Document_On_Case__c.object
<CustomObject>
    <description>Policy Documents on Case</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>Used by custom program to record action performed by the user on the Policy Document record</inlineHelpText>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Associated_Trust_Bits__c</fullName>
        <inlineHelpText>Associated Trust Bits</inlineHelpText>
        <label>Associated Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Secure Email</fullName>
                </value>
                <value>
                    <fullName>Server Authentication</fullName>
                </value>
                <value>
                    <fullName>Client Authentication</fullName>
                </value>
                <value>
                    <fullName>Code Signing</fullName>
                </value>
                <value>
                    <fullName>Document Signing</fullName>
                </value>
                <value>
                    <fullName>Encrypting File System</fullName>
                </value>
                <value>
                    <fullName>IP Security End System</fullName>
                </value>
                <value>
                    <fullName>IP Security IKE Intermediate</fullName>
                </value>
                <value>
                    <fullName>IP Security Tunnel Termination</fullName>
                </value>
                <value>
                    <fullName>IP Security User</fullName>
                </value>
                <value>
                    <fullName>OCSP Signing</fullName>
                </value>
                <value>
                    <fullName>Private Key Archiva</fullName>
                </value>
                <value>
                    <fullName>Time Stamping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Policy Documents (On Case)</relationshipLabel>
        <relationshipName>Policy_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Last_Updated_Date__c</fullName>
        <inlineHelpText>Policy document Last Updated Date must be filled for policy document link</inlineHelpText>
        <label>Document Last Updated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <inlineHelpText>URL to policy documentation specific to the listed root certs. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Document Link</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CP/CPS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Identifiers__c</fullName>
        <label>Policy Identifiers</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Policy Document (On Case)</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Policy Doc Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Documents (On Case)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PolicyDocumentAssociation_On_Certificate__c.object
<CustomObject>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certificate Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Policy Document Associations (On Certificate)</relationshipLabel>
        <relationshipName>Policy_Document_Associations_OnCert</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <formula>Policy_Document__r.Document_Link__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>Text (Policy_Document__r.Document_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_Document__c</fullName>
        <label>Document Id</label>
        <referenceTo>Policy_Document_On_Certificate__c</referenceTo>
        <relationshipLabel>Policy Document Associations</relationshipLabel>
        <relationshipName>Policy_Document_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Policy Document Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Document Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ViewPolicyDocumentsOnCaseController.cls
/*
    Description:Controller is created to ViewPolicyDocumentsOnCase
*/
public without sharing class ViewPolicyDocumentsOnCaseController {
    
    public List<Policy_Document_On_Case__c> lstPolicyDocumentsOnCases {get; set;}
    public List<Policy_Document_Association_On_Case__c> lstPDAssociations {get; set;}
    public boolean isShowDeleted {get; set;}
    public Case objCase{get; set;}
    
    public ViewPolicyDocumentsOnCaseController (Apexpages.standardcontroller controller){
        Id caseId = controller.getID();
        isShowDeleted = false;
        List<Case> lstCases = new List<Case>([select Id, CaseNumber, AccountId, 
                    Policy_Documentation__c, CA_Document_Repository__c,
                    Account.Document_Repository__c, 
                    Account.Document_Repository_Description__c from Case Where Id =: caseId]);
        
        if(lstCases.size() > 0){
            objCase = lstCases [0];
            
            lstPolicyDocumentsOnCases = new List<Policy_Document_On_Case__c>([select Id, Name, Associated_Trust_Bits__c, Action__c,
                        Comments__c, Document_Last_Updated_Date__c, Document_Link__c, Document_Type__c,Policy_Identifiers__c,
                        (Select Id, Name, Certificate_Name__c,Certificate_Name__r.Name, Certificate_Name__r.Status__c,
                        Certificate_Name__r.Microsoft_Status__c, Certificate_Name__r.SHA_256_Fingerprint__c,
                        Policy_Document__c,Action__c from Policy_Document_Associations__r), Document_Verified__c
                        FROM Policy_Document_On_Case__c
                        WHERE Case__c =: objCase.Id Order by Document_Last_Updated_Date__c desc]);
            
        }
    }
    
    public void BindAssociations(){
        lstPDAssociations  = new List<Policy_Document_Association_On_Case__c>();
        if(apexpages.currentpage().getparameters().get('index') != null){
            Integer index = integer.valueof(apexpages.currentpage().getparameters().get('index'));
            if(lstPolicyDocumentsOnCases.size() > index){
                lstPDAssociations = lstPolicyDocumentsOnCases[index].Policy_Document_Associations__r;
            }
        }
    }
}