objects/Account.object
<CustomObject>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CA_Owner_ID__c</fullName>
        <description>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</description>
        <inlineHelpText>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</inlineHelpText>
        <label>CA Owner ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit__c</fullName>
        <label>Code Signing Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Extended_Key_Usage__c</fullName>
        <label>Extended Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Microsoft_Trust_Bits__c</fullName>
        <label>Microsoft Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Server Authentication</fullName>
                </value>
                <value>
                    <fullName>Client Authentication</fullName>
                </value>
                <value>
                    <fullName>Code Signing</fullName>
                </value>
                <value>
                    <fullName>Document Signing</fullName>
                </value>
                <value>
                    <fullName>Encrypting File System</fullName>
                </value>
                <value>
                    <fullName>IP Security End System</fullName>
                </value>
                <value>
                    <fullName>IP Security IKE Intermediate</fullName>
                </value>
                <value>
                    <fullName>IP Security Tunnel Termination</fullName>
                </value>
                <value>
                    <fullName>IP Security User</fullName>
                </value>
                <value>
                    <fullName>OCSP Signing</fullName>
                </value>
                <value>
                    <fullName>Private Key Archival</fullName>
                </value>
                <value>
                    <fullName>Secure Email</fullName>
                </value>
                <value>
                    <fullName>Time Stamping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Identifiers__c</fullName>
        <label>Policy Identifiers</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Standard Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Date__c</fullName>
        <description>Date Audit Statement Issued</description>
        <inlineHelpText>Date Audit Statement Issued</inlineHelpText>
        <label>Standard Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Type__c</fullName>
        <label>Standard Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 101 456</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 101 456</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies same logical certificates in different CA Hierarchies. SHA256(der(subject)+der(spki))</inlineHelpText>
        <label>Subject + SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Standard Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Date__c</fullName>
        <description>Date Audit Statement Issued</description>
        <inlineHelpText>Date Audit Statement Issued</inlineHelpText>
        <label>Standard Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Type__c</fullName>
        <label>Standard Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 101 456</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 101 456</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
                <value>
                    <fullName>WebTrust Equivalent</fullName>
                    <isActive>false</isActive>
                    <label>WebTrust Equivalent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Community_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the contact has customer portal login a trigger on &apos;User&apos; object checks this field.</description>
        <inlineHelpText>Does this contact have customer portal login?</inlineHelpText>
        <label>Is Community User?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>A CA may have more than one person filling the role of Primary Point of Contact (POC), and may use a contractor as one of the POCs.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary POC</fullName>
                </value>
                <value>
                    <fullName>POC</fullName>
                </value>
                <value>
                    <fullName>Auditor</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CPACanada_File__c.object
<CustomObject>
    <description>CPACanada seal id mapping to report id</description>
    <fields>
        <fullName>Report_Id__c</fullName>
        <inlineHelpText>Report Id</inlineHelpText>
        <label>Report Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Report_URL__c</fullName>
        <inlineHelpText>Report URL</inlineHelpText>
        <label>Report URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Seal_URL__c</fullName>
        <inlineHelpText>Seal URL</inlineHelpText>
        <label>Seal URL</label>
        <type>Url</type>
    </fields>
    <label>CPACanada File</label>
    <nameField>
        <label>Seal Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPACanada Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountTriggerHelperTest.cls
/**

Test Case for the AccountTrigger apex trigger and AccountTriggerHelper apex class

**/

@isTest 
public class AccountTriggerHelperTest{
    
    static testMethod void validateAccount() {
    
        Account acc = TestUtils.getCAOwner();
        insert acc;
            
        Contact con = TestUtils.getContact(acc.id);
        con.recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CA Contact').getRecordTypeId();
        insert con;
        
        //UserRole urole = [Select PortalType, PortalAccountId From UserRole where PortalType = 'CustomerPortal' and PortalAccountId != null limit 1];
        
        User user = new User();
        //user.UserRoleId = urole.Id;//UserInfo.getUserRoleId();//
        //user.ProfileID = [Select Id From Profile Where UserType = 'PowerCustomerSuccess' LIMIT 1].id;
        user.ProfileId = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User - CAs' AND UserType = 'PowerCustomerSuccess' LIMIT 1].Id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@test1234098.com';   
        user.CommunityNickname = 'testUser09887123';
        user.Alias = 't1';
        user.Email = 'no@email.com';
        user.IsActive = true;
        user.ContactId = con.Id;
        //user.PortalRole = 'Manager';
        insert user;
        
        AccountShare aShare = new AccountShare();
        aShare.AccountAccessLevel = 'Edit';
        aShare.ContactAccessLevel = 'Edit';
        aShare.OpportunityAccessLevel = 'Edit';
        aShare.RowCause = 'Manual';
        aShare.AccountId = acc.Id;
        aShare.UserOrGroupId = user.Id;
        insert aShare;
        
        System.RunAs(user) {
        
            // create a ROOT CA
            Account rootCA = TestUtils.getRootCertificate(acc.Id); 
            rootCa.X_509_Certificate_PEM__c = 'abc';
            rootCa.Status__c = 'Included';
            rootCa.Trust_Bits__c = 'Websites';
            rootCa.Subject_SPKI_SHA256__c = 'C90FBC2664485F6D3175055A45EF10D2EB6E6C7E027DF1A1D526458C42F4269X';
            insert rootCa;
            
            Test.startTest(); 
            
            // create intermediate CA
            Account testAccount = TestUtils.getIntermediateCertificate(rootCa.Id);
            testAccount.X_509_Certificate_PEM__c = 'abc';
            testAccount.Subject_SPKI_SHA256__c = 'C90FBC2664485F6D3175055A45EF10D2EB6E6C7E027DF1A1D526458C42F4269Y';
            testAccount.Extended_Key_Usage__c = 'ExtKeyUsageEmailProtection,ExtKeyUsageClientAuth';
            insert testAccount;
            testAccount.Revocation_Status__c = 'Not Revoked';
            testAccount.Extended_Key_Usage__c = '1.2.3.4, 2.3.4.5, 3.4.5.6';
            update testAccount;
            
            // create a ROOT CA
            Account rootCA1 = TestUtils.getRootCertificate(acc.Id); 
            rootCa1.X_509_Certificate_PEM__c = 'abc';
            rootCa1.Status__c = 'Included';
            rootCa1.Microsoft_Status__c = 'Included';
            rootCa1.Microsoft_Trust_Bits__c = 'Client Authentication;Code Signing';
            rootCa1.Subject_SPKI_SHA256__c = 'C90FBC2664485F6D3175055A45EF10D2EB6E6C7E027DF1A1D526458C42F4269Z';
            insert rootCa1;
            
            testAccount.X_509_Certificate_PEM__c = 'test';
            testAccount.parentId = rootCa1.id;
            testAccount.Extended_Key_Usage__c = '';
            update testAccount;
            
            acc.Name = 'SymantecAccount';
            update acc;
            
            Test.stopTest();
        }
        
        Account accountSo = New Account(name='SymantecAccount');
        insert accountSo;
        
        accountSo.Name = 'NameChanged';
        update accountSo;
    }
    
    static testMethod void TestInternalUserSharing() {
    
        Account acc = TestUtils.getCAOwner();
        insert acc;
            
        Contact con = TestUtils.getContact(acc.id);
        con.Type__c = 'Primary POC';
        con.Is_Community_User__c = true;
        con.recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CA Contact').getRecordTypeId();
        insert con;
        
        User user = new User();
        user.ProfileId = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User - CAs' AND UserType = 'PowerCustomerSuccess' LIMIT 1].Id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@test1234098.com';   
        user.CommunityNickname = 'testUser09887123';
        user.Alias = 't1';
        user.Email = 'no@email.com';
        user.IsActive = true;
        user.ContactId = con.Id;
        insert user;
        
        // create a ROOT CA
        Account rootCA = TestUtils.getRootCertificate(acc.Id); 
        rootCa.X_509_Certificate_PEM__c = 'abc';
        insert rootCa;
        
        Test.startTest();
        
        rootCa.Name = 'Root 2';
        update rootCa;
        
        // create intermediate CA
        Account testAccount = TestUtils.getIntermediateCertificate(rootCa.Id);
        testAccount.CA_Owner_Id__c = acc.Id;
        testAccount.Audits_Same_as_Parent__c = true;
        insert testAccount;
        
        rootCa.Standard_Audit__c = 'http://google.com';
        rootCa.Standard_Audit_Type__c = 'WebTrust';
        rootCa.Standard_Audit_Statement_Date__c = system.today();
        rootCa.Standard_Audit_Period_Start_Date__c = system.today().addDays(-3);
        rootCa.Standard_Audit_Period_End_Date__c = system.today().addDays(-2);
        update rootCa;
        
        Test.stopTest();
    }
    
    static testMethod void TestValidateAuditInfo() {
        
        Account acc = TestUtils.getCAOwner();
        insert acc;
        
        CPACanada_File__c objCPACanada = new CPACanada_File__c();
        objCPACanada.Name = '10149';
        objCPACanada.Report_Id__c = '225352';
        objCPACanada.Report_URL__c = 'https://www.cpacanada.ca/generichandlers/aptifyattachmenthandler.ashx?attachmentid=225352';
        objCPACanada.Seal_URL__c = 'https://www.cpacanada.ca/webtrustseal?sealid=10149';
        insert objCPACanada;
            
        // create a ROOT CA
        Account rootCA = TestUtils.getRootCertificate(acc.Id);
        rootCa.X_509_Certificate_PEM__c = 'abc';
        rootCa.CA_Owner_ID__c = acc.Id;
        rootCa.Policy_Identifiers__c = 'Test';
        insert rootCa;
        
        // create intermediate CA
        Account testAccount = TestUtils.getIntermediateCertificate(rootCa.Id);
        testAccount.Status__c = 'Removed';
        testAccount.X_509_Certificate_PEM__c = 'abc';
        testAccount.CA_Owner_Id__c = acc.Id;
        testAccount.Policy_Identifiers__c = 'Test1';
        insert testAccount;
        
        try {
            
            testaccount.Standard_Audit__c = '';
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit__c = 'http://google.com';
            testaccount.Standard_Audit_Statement_Date__c = system.today();
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today().addDays(2);
            testAccount.Policy_Identifiers__c = 'Test2';
            update testAccount;
        } catch (Exception ex){}
        
        try {
            testaccount.Standard_Audit__c = '';
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'https://www.cpacanada.ca/webtrustseal?sealid=10149';
            testaccount.Code_Signing_Audit__c = 'http://google.com';
            testaccount.Standard_Audit_Statement_Date__c = system.today();
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.Standard_Audit_Period_Start_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_Start_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
        
        try {
            testaccount.Standard_Audit__c = '';
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit__c = 'https://www.cpacanada.ca/webtrustseal?sealid=10149';
            testaccount.Standard_Audit_Statement_Date__c = system.today();
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.Standard_Audit_Period_Start_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_Start_Date__c = system.today();
            testaccount.Standard_Audit_Period_End_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_End_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
        
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.BR_Audit_Statement_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
        
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = 'https://www.cpacanada.ca/webtrustseal?sealid=10149';
            testaccount.Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.BR_Audit_Statement_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_Start_Date__c = system.today();
            testaccount.BR_Audit_Period_Start_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
        
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.BR_Audit_Statement_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_Start_Date__c = system.today();
            testaccount.BR_Audit_Period_Start_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_End_Date__c = system.today();
            testaccount.BR_Audit_Period_End_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
        
        
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.EV_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.EV_Audit_Statement_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
        
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.EV_Audit__c = 'https://www.cpacanada.ca/webtrustseal?sealid=10149';
            testaccount.Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.EV_Audit_Statement_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Audit_Period_Start_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
        
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.EV_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.EV_Audit_Statement_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Audit_Period_Start_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_End_Date__c = system.today();
            testaccount.EV_Audit_Period_End_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
        
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
        
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Period_Start_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
        
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit__c = 'http://google.com';
            testaccount.Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Period_Start_Date__c = system.today();
            testaccount.Code_Signing_Audit_Period_End_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Period_End_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
        
        
        try {
            testaccount.Standard_Audit__c = '';
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'http://google.com';
            testaccount.BR_Audit__c = 'http://google.com';
            testaccount.Standard_Audit_Statement_Date__c = system.today();
            testaccount.BR_Audit_Statement_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Standard_Audit__c = '';
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'http://google.com';
            testaccount.BR_Audit__c = 'http://google.com';
            testaccount.Standard_Audit_Period_Start_Date__c = system.today();
            testaccount.BR_Audit_Period_Start_Date__c = system.today().addDays(2);
            testaccount.BR_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'http://google.com';
            testaccount.BR_Audit__c = 'http://google.com';
            testaccount.Standard_Audit_Period_End_Date__c = system.today();
            testaccount.BR_Audit_Period_End_Date__c = system.today().addDays(2);
            testaccount.BR_Audit_Period_Start_Date__c = system.today();
            testaccount.BR_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'http://google.com';
            testaccount.EV_Audit__c = 'http://google.com';
            testaccount.Standard_Audit_Statement_Date__c = system.today();
            testaccount.EV_Audit_Statement_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
        
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'http://google.com';
            testaccount.EV_Audit__c = 'http://google.com';
            testaccount.Standard_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Audit_Period_Start_Date__c = system.today().addDays(2);
            testaccount.EV_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'http://google.com';
            testaccount.EV_Audit__c = 'http://google.com';
            testaccount.Standard_Audit_Period_End_Date__c = system.today();
            testaccount.EV_Audit_Period_End_Date__c = system.today().addDays(2);
            testaccount.EV_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'http://google.com';
            testaccount.EV_Code_Signing_Audit__c = 'http://google.com';
            testaccount.Standard_Audit_Statement_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'http://google.com';
            testaccount.EV_Code_Signing_Audit__c = 'http://google.com';
            testaccount.Standard_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Period_Start_Date__c = system.today().addDays(2);
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.Standard_Audit__c = 'http://google.com';
            testaccount.EV_Code_Signing_Audit__c = 'http://google.com';
            testaccount.Standard_Audit_Period_End_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Period_End_Date__c = system.today().addDays(2);
            testaccount.EV_Code_Signing_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = 'http://google1.com';
            testaccount.EV_Audit__c = 'http://google1.com';
            testaccount.BR_Audit_Statement_Date__c = system.today();
            testaccount.EV_Audit_Statement_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = 'http://google1.com';
            testaccount.EV_Audit__c = 'http://google1.com';
            testaccount.BR_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Audit_Period_Start_Date__c = system.today().addDays(2);
            testaccount.EV_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = 'http://google1.com';
            testaccount.EV_Audit__c = 'http://google1.com';
            testaccount.BR_Audit_Period_End_Date__c = system.today();
            testaccount.EV_Audit_Period_End_Date__c = system.today().addDays(2);
            testaccount.EV_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = 'http://google1.com';
            testaccount.EV_Code_Signing_Audit__c = 'http://google1.com';
            testaccount.BR_Audit_Statement_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = 'http://google1.com';
            testaccount.EV_Code_Signing_Audit__c = 'http://google1.com';
            testaccount.BR_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Period_Start_Date__c = system.today().addDays(2);
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = 'http://google1.com';
            testaccount.EV_Code_Signing_Audit__c = 'http://google1.com';
            testaccount.BR_Audit_Period_End_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Period_End_Date__c = system.today().addDays(2);
            testaccount.EV_Code_Signing_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.EV_Audit__c = 'http://google1.com';
            testaccount.EV_Code_Signing_Audit__c = 'http://google1.com';
            testaccount.EV_Audit_Statement_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today().addDays(2);
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.EV_Audit__c = 'http://google1.com';
            testaccount.EV_Code_Signing_Audit__c = 'http://google1.com';
            testaccount.EV_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Period_Start_Date__c = system.today().addDays(2);
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
            
        try {
            testaccount.Code_Signing_Audit__c = '';
            testaccount.BR_Audit__c = '';
            testaccount.EV_Audit__c = '';
            testaccount.EV_Code_Signing_Audit__c = '';
            testaccount.EV_Audit__c = 'http://google1.com';
            testaccount.EV_Code_Signing_Audit__c = 'http://google1.com';
            testaccount.EV_Audit_Period_End_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Period_End_Date__c = system.today().addDays(2);
            testaccount.EV_Code_Signing_Audit_Period_Start_Date__c = system.today();
            testaccount.EV_Code_Signing_Audit_Statement_Date__c = system.today();
            update testAccount;
        } catch (Exception ex){}
        
        try {
            delete rootCa;
        } catch (Exception ex){}
    }
}