objects/Account.object
<CustomObject>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <description>This field is hyperlink to Account Name. Mainly used in reports.</description>
        <formula>HYPERLINK(Id, Name, &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Certificate Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Document_Repository_Description__c</fullName>
        <inlineHelpText>Optional explanation about the CA&apos;s policy documentation</inlineHelpText>
        <label>Document Repository Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Document_Repository__c</fullName>
        <inlineHelpText>URL to where the CA&apos;s policy documentation may be found. More than one URL may be provided as a semicolon - separated list.</inlineHelpText>
        <label>Document Repository</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Policy_Identifiers__c</fullName>
        <label>Policy Identifiers</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Policy_Document_On_Certificate__c.object
<CustomObject>
    <description>Policy Document records on Certificate</description>
    <fields>
        <fullName>Associated_Trust_Bits__c</fullName>
        <label>Associated Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Server Authentication</fullName>
                </value>
                <value>
                    <fullName>Client Authentication</fullName>
                </value>
                <value>
                    <fullName>Code Signing</fullName>
                </value>
                <value>
                    <fullName>Document Signing</fullName>
                </value>
                <value>
                    <fullName>Encrypting File System</fullName>
                </value>
                <value>
                    <fullName>Secure Email</fullName>
                </value>
                <value>
                    <fullName>Time Stamping</fullName>
                </value>
                <value>
                    <fullName>IP Security End System</fullName>
                </value>
                <value>
                    <fullName>IP Security IKE Intermediate</fullName>
                </value>
                <value>
                    <fullName>IP Security Tunnel Termination</fullName>
                </value>
                <value>
                    <fullName>IP Security User</fullName>
                </value>
                <value>
                    <fullName>OCSP Signing</fullName>
                </value>
                <value>
                    <fullName>Private Key Archival</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Last_Updated_Date__c</fullName>
        <inlineHelpText>Policy document Last Updated Date must be filled for policy document link</inlineHelpText>
        <label>Document Last Updated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <inlineHelpText>URL to policy documentation specific to the listed root certs. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Document Link</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CP/CPS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mark when the record is deleted</inlineHelpText>
        <label>Is Deleted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Policy_Identifiers__c</fullName>
        <inlineHelpText>Policy Identifiers</inlineHelpText>
        <label>Policy Identifiers</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Policy Document</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Policy Doc Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PolicyDocumentAssociation_On_Certificate__c.object
<CustomObject>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certificate Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Policy Document Associations (On Certificate)</relationshipLabel>
        <relationshipName>Policy_Document_Associations_OnCert</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <formula>Policy_Document__r.Document_Link__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>Text (Policy_Document__r.Document_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Policy_Document__c</fullName>
        <label>Document Id</label>
        <referenceTo>Policy_Document_On_Certificate__c</referenceTo>
        <relationshipLabel>Policy Document Associations</relationshipLabel>
        <relationshipName>Policy_Document_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WRONG_Source_Policy_Doc_Assoc_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WRONG Case Policy Doc Assoc Id</label>
        <referenceTo>PolicyDocumentAssociation_On_Certificate__c</referenceTo>
        <relationshipLabel>Policy Document Associations</relationshipLabel>
        <relationshipName>Policy_Document_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Policy Document Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Document Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ViewPolicyDocumentsOnRootController.cls
/*
    Description:Controller is created to ViewPolicyDocumentsOnRoot
*/
public without sharing class ViewPolicyDocumentsOnRootController {
    
    public List<Policy_Document_On_Certificate__c> lstPolicyDocumentsOnCertificates {get; set;}
    public boolean isShowDeleted {get; set;}
    public Account objRootCertificate {get; set;}
    
    public ViewPolicyDocumentsOnRootController (Apexpages.standardcontroller controller){
        Id rootID = controller.getID();
        isShowDeleted = false;
        List<Account> lstAccounts = new List<Account>([select Id, Name, ParentId, Parent.Document_Repository__c, 
                    Parent.Document_Repository_Description__c from Account Where Id =: rootId]);
        
        if(lstAccounts.size() > 0){
            objRootCertificate = lstAccounts[0];
            set<Id> setOfPolicyDocIds = new set<Id>();
            List<PolicyDocumentAssociation_On_Certificate__c> lstPolicyDocumentAssociations = new List<PolicyDocumentAssociation_On_Certificate__c>([select 
                        Id, Policy_Document__c from PolicyDocumentAssociation_On_Certificate__c Where Certificate_Name__c =: objRootCertificate.Id]);
            for(PolicyDocumentAssociation_On_Certificate__c PDA: lstPolicyDocumentAssociations){
                setOfPolicyDocIds.add(PDA.Policy_Document__c);
            }
            
            lstPolicyDocumentsOnCertificates = new List<Policy_Document_On_Certificate__c>([select Id, Name, Associated_Trust_Bits__c, Is_Deleted__c,
                        Comments__c, Document_Last_Updated_Date__c, Document_Link__c, Document_Type__c,Policy_Identifiers__c
                        //(Select Id, Name, Certificate_Name__c,Policy_Document__c from Policy_Document_Associations__r)
                        FROM Policy_Document_On_Certificate__c 
                        WHERE Id =: setOfPolicyDocIds Order by Document_Last_Updated_Date__c desc]);
            
        }
        
    }
    
}