objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auditor_New__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Name of Auditor who issued the standard audit statement. See &apos;List All Auditors&apos; below for choices. Send email to support@ccadb.org if your auditor is not listed.</inlineHelpText>
        <label>Auditor</label>
        <referenceTo>Auditor__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>BR Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Period_Start_Date__c</fullName>
        <description>Start date of the period of time of CA operations examined by the auditor.</description>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>BR Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Statement_Date__c</fullName>
        <description>Date BR Audit Statement Issued</description>
        <inlineHelpText>Date BR Audit Statement Issued</inlineHelpText>
        <label>BR Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Type__c</fullName>
        <label>BR Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BR_Audit__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>BR Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CP_CPS_Last_Updated_Date__c</fullName>
        <label>CP/CPS Last Updated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CP_CPS_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if this cert does not have separate policy documentation from the parent cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if this cert does not have separate policy documentation from the parent cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>CP/CPS Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Certificate_Policy_CP__c</fullName>
        <description>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certificate Policy (CP)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>EV SSL Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>EV SSL Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Statement_Date__c</fullName>
        <description>Date EV SSL Audit Statement Issued</description>
        <inlineHelpText>Date EV SSL Audit Statement Issued</inlineHelpText>
        <label>EV SSL Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Type__c</fullName>
        <label>EV SSL Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EV_Audit__c</fullName>
        <description>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>EV SSL Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>EV Code Signing Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>EV Code Signing Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Statement_Date__c</fullName>
        <inlineHelpText>Date EV Code Signing Audit Statement Issued</inlineHelpText>
        <label>EV Code Signing Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Type__c</fullName>
        <label>EV Code Signing Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit__c</fullName>
        <label>EV Code Signing Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Standard Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Date__c</fullName>
        <description>Date Audit Statement Issued</description>
        <inlineHelpText>Date Audit Statement Issued</inlineHelpText>
        <label>Standard Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Type__c</fullName>
        <label>Standard Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 101 456</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 101 456</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subordinate_CA_Owner__c</fullName>
        <inlineHelpText>Enter Subordinate CA’s name as it appears in the provided audit statements. Leave blank if BOTH control of the private key AND domain/IP/email validation activities are performed by the organization listed in the audit statement of the parent certificate.</inlineHelpText>
        <label>Subordinate CA Owner</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AllCertificateRecordsReportController.cls
/*******************************************************************************************************
 Name: AllCertificateRecordsReportController

 Dependencies: AllCertificateRecordsReportController, AllCertificateRecordsCSVFormat, 
 AllCertificateRecordsReportCtlrTest
 
 Description: This report generates list of all root and intermediate certs.

 Instructions: None

 *******************************************************************************************************
 Revision History:
 
     06/24/2017 - Created new
     11/20/2019 - Added Subordinate CA Owner field to the report
     05/26/2020 - Changed for CP/CPS fields and display links for Policy documents
     08/12/2020 - Updated code to user latest last update date for Policy documents
 ******************************************************************************************************/
 
public class AllCertificateRecordsReportController{

    public List<wrapperAccount> lstWrapperAccountSO {get; set;}  
    
    // constructor method for standard controller
    public AllCertificateRecordsReportController() {   
            lstWrapperAccountSO = new List<wrapperAccount>();              
            List<Account> accountSoLst =  [SELECT  
                                    CA_Owner__c,
                                    Id,
                                    Name,
                                    ParentId,
                                    Parent.Name,
                                    Parent.SHA_256_Fingerprint__c,
                                    RecordType.Name,
                                    Subordinate_CA_Owner__c,
                                    Revocation_Status__c,
                                    SHA_256_Fingerprint__c, 
                                    Audits_Same_as_Parent__c,
                                    Auditor_New__r.Name,
                                    Standard_Audit__c,
                                    Standard_Audit_Type__c, 
                                    Standard_Audit_Statement_Date__c,
                                    Standard_Audit_Period_Start_Date__c, 
                                    Standard_Audit_Period_End_Date__c,
                                    BR_Audit__c,
                                    BR_Audit_Type__c, 
                                    BR_Audit_Statement_Date__c,
                                    BR_Audit_Period_Start_Date__c, 
                                    BR_Audit_Period_End_Date__c, 
                                    EV_Audit__c,
                                    EV_Audit_Type__c, 
                                    EV_Audit_Statement_Date__c,
                                    EV_Audit_Period_Start_Date__c, 
                                    EV_Audit_Period_End_Date__c, 
                                    EV_Code_Signing_Audit__c,
                                    EV_Code_Signing_Audit_Type__c, 
                                    EV_Code_Signing_Audit_Statement_Date__c,
                                    EV_Code_Signing_Audit_Period_Start_Date__c, 
                                    EV_Code_Signing_Audit_Period_End_Date__c, 
                                    CP_CPS_Same_as_Parent__c,
                                    CP_CPS_Last_Updated_Date__c,
                                    Certificate_Policy_CP__c,
                                    Certification_Practice_Statement_CPS__c,
                                    Test_Website_Valid__c,
                                    Test_Website_Expired__c,
                                    Test_Website_Revoked__c,
                                    Technically_Constrained__c,
                                    Status__c,
                                    Microsoft_Status__c,
                                    (Select Id, Document_Link__c, Document_Type__c, Document_Last_Update_Date__c from Policy_Document_Associations_OnCert__r Where Is_Deleted__c = false
                                     Order by Document_Last_Update_Date__c desc) 
                                    FROM Account
                                    WHERE Name != '<Fill in Cert Name>' 
                                    AND RecordType.Name In ('Root Certificate','Intermediate Certificate')
                                    ORDER BY CA_Owner__c ASC, RecordType.Name DESC, Name ASC]; 
                                      
                                    
        // if we are generating a CSV file then we need to replace the double quotes in all text fields with null
        //ApexPages.currentPage().getUrl() != null && ApexPages.currentPage().getUrl().contains('CSV') - condition removed because no need - Sunil
        if((Test.isRunningTest() || (ApexPages.currentPage().getUrl() != null && ApexPages.currentPage().getUrl().contains('CSV'))) && accountSoLst !=null && accountSoLst.size() > 0)
        {
            for(Account accountSo : accountSoLst) {
                wrapperAccount objWrap = new wrapperAccount();
                if(accountSo.CA_Owner__c !=null && accountSo.CA_Owner__c.length() > 0) 
                    accountSo.CA_Owner__c = accountSo.CA_Owner__c.replace('"',''); 
                if(accountSo.Name !=null && accountSo.Name.length() > 0) 
                    accountSo.Name = accountSo.Name.replace('"',''); 
                if(accountSo.Subordinate_CA_Owner__c !=null && accountSo.Subordinate_CA_Owner__c.length() > 0) 
                    accountSo.Subordinate_CA_Owner__c = accountSo.Subordinate_CA_Owner__c.replace('"','');          
                if(accountSo.Auditor_New__r.Name !=null && accountSo.Auditor_New__r.Name.length() > 0) 
                    accountSo.Auditor_New__r.Name = accountSo.Auditor_New__r.Name.replace('"','');      
                /*if(accountSo.Certificate_Policy_CP__c !=null && accountSo.Certificate_Policy_CP__c.length() > 0) 
                    accountSo.Certificate_Policy_CP__c = accountSo.Certificate_Policy_CP__c.replace('"',''); 
                if(accountSo.Certification_Practice_Statement_CPS__c !=null && accountSo.Certification_Practice_Statement_CPS__c.length() > 0) 
                    accountSo.Certification_Practice_Statement_CPS__c = accountSo.Certification_Practice_Statement_CPS__c.replace('"',''); */
                
                string dateformat = 'yyyy.MM.dd';
                
                objWrap.objaccountSO = accountSo;
                if (accountSO.CP_CPS_Last_Updated_Date__c !=null) {
                   objWrap.accCPCPSLastUpdateddate = DateTime.NewInstance(accountSO.CP_CPS_Last_Updated_Date__c.year(),
                        accountSO.CP_CPS_Last_Updated_Date__c.month(), accountSO.CP_CPS_Last_Updated_Date__c.day()).format(dateformat);
                }
                string strCP = '';
                string strCPS = '';
                Date CPCPSDate;
                for(PolicyDocumentAssociation_On_Certificate__c PDAC: accountSo.Policy_Document_Associations_OnCert__r){
                    if(PDAC.Document_Type__c != null){
                        if(PDAC.Document_Type__c == 'CP'){
                            if(string.isnotblank(strCP)) strCP += '; ';
                            strCP += PDAC.Document_Link__c;
                        }
                        if(PDAC.Document_Type__c == 'CPS' || PDAC.Document_Type__c == 'CP/CPS'){
                            if(string.isnotblank(strCPS)) strCPS += '; ';
                            strCPS += PDAC.Document_Link__c;
                        }
                    }
                    if(CPCPSDate == null || PDAC.Document_Last_Update_Date__c  > CPCPSDate){
                        CPCPSDate = PDAC.Document_Last_Update_Date__c;
                    }
                } 
                
                objWrap.CP = strCP;
                objWrap.CPS = strCPS;
                if(CPCPSDate != null) {
                    objWrap.CPCPSLastUpdateddate = DateTime.NewInstance(CPCPSDate .year(),
                        CPCPSDate.month(), CPCPSDate.day()).format(dateformat);
                }
                if(accountSo.Standard_Audit_Statement_Date__c != null) {
                    objWrap.SAdate = DateTime.NewInstance(accountSo.Standard_Audit_Statement_Date__c.year(),
                        accountSo.Standard_Audit_Statement_Date__c.month(),accountSo.Standard_Audit_Statement_Date__c.day()).format(dateformat);
                }
                if(accountSo.Standard_Audit_Period_Start_Date__c != null) {
                    objWrap.SAstartdate = DateTime.NewInstance(accountSo.Standard_Audit_Period_Start_Date__c.year(),
                        accountSo.Standard_Audit_Period_Start_Date__c.month(),accountSo.Standard_Audit_Period_Start_Date__c.day()).format(dateformat);
                }
                if(accountSo.Standard_Audit_Period_End_Date__c != null) { 
                    objWrap.SAenddate = DateTime.NewInstance(accountSo.Standard_Audit_Period_End_Date__c.year(),
                        accountSo.Standard_Audit_Period_End_Date__c.month(),accountSo.Standard_Audit_Period_End_Date__c.day()).format(dateformat);
                }
                if(accountSo.BR_Audit_Statement_Date__c != null) {
                    objWrap.BRdate = DateTime.NewInstance(accountSo.BR_Audit_Statement_Date__c.year(),
                        accountSo.BR_Audit_Statement_Date__c.month(),accountSo.BR_Audit_Statement_Date__c.day()).format(dateformat);
                }    
                if(accountSo.BR_Audit_Period_Start_Date__c != null) {
                    objWrap.BRstartdate = DateTime.NewInstance(accountSo.BR_Audit_Period_Start_Date__c.year(),
                        accountSo.BR_Audit_Period_Start_Date__c.month(),accountSo.BR_Audit_Period_Start_Date__c.day()).format(dateformat);
                }
                if(accountSo.BR_Audit_Period_End_Date__c != null) {
                    objWrap.BRenddate = DateTime.NewInstance(accountSo.BR_Audit_Period_End_Date__c.year(),
                        accountSo.BR_Audit_Period_End_Date__c.month(), accountSo.BR_Audit_Period_End_Date__c.day()).format(dateformat);
                }    
                if(accountSo.EV_Audit_Statement_Date__c != null) {
                    objWrap.EVdate = DateTime.NewInstance(accountSo.EV_Audit_Statement_Date__c.year(),
                        accountSo.EV_Audit_Statement_Date__c.month(),accountSo.EV_Audit_Statement_Date__c.day()).format(dateformat);
                } 
                if(accountSo.EV_Audit_Period_Start_Date__c != null) {
                    objWrap.EVSSLstartdate = DateTime.NewInstance(accountSo.EV_Audit_Period_Start_Date__c.year(),
                        accountSo.EV_Audit_Period_Start_Date__c.month(), accountSo.EV_Audit_Period_Start_Date__c.day()).format(dateformat);
                }
                if(accountSo.EV_Audit_Period_End_Date__c != null) {
                    objWrap.EVSSLenddate = DateTime.NewInstance(accountSo.EV_Audit_Period_End_Date__c.year(),
                        accountSo.EV_Audit_Period_End_Date__c.month(),accountSo.EV_Audit_Period_End_Date__c.day()).format(dateformat);
                }
                if(accountSo.EV_Code_Signing_Audit_Statement_Date__c != null) {
                    objWrap.EVCodedate = DateTime.NewInstance(accountSo.EV_Code_Signing_Audit_Statement_Date__c.year(),
                        accountSo.EV_Code_Signing_Audit_Statement_Date__c.month(),accountSo.EV_Code_Signing_Audit_Statement_Date__c.day()).format(dateformat);
                } 
                if(accountSo.EV_Code_Signing_Audit_Period_Start_Date__c != null) {
                    objWrap.EVCodestartdate = DateTime.NewInstance(accountSo.EV_Code_Signing_Audit_Period_Start_Date__c.year(),
                        accountSo.EV_Code_Signing_Audit_Period_Start_Date__c.month(),accountSo.EV_Code_Signing_Audit_Period_Start_Date__c.day()).format(dateformat);
                }
                if(accountSo.EV_Code_Signing_Audit_Period_End_Date__c != null) {
                    objWrap.EVCodeenddate = DateTime.NewInstance(accountSo.EV_Code_Signing_Audit_Period_End_Date__c.year(),
                        accountSo.EV_Code_Signing_Audit_Period_End_Date__c.month(), accountSo.EV_Code_Signing_Audit_Period_End_Date__c.day()).format(dateformat);
                }
                /*if(accountSo.CP_CPS_Last_Updated_Date__c != null) {
                    objWrap.CPCPSLastUpdateddate = DateTime.NewInstance(accountSo.CP_CPS_Last_Updated_Date__c.year(),
                        accountSo.CP_CPS_Last_Updated_Date__c.month(), accountSo.CP_CPS_Last_Updated_Date__c.day()).format(dateformat);
                }*/
                    
                lstWrapperAccountSO.add(objWrap);
            } 
        }                                       
    }
  
     
    String CurrentDate = ' ';
 
    // Get current Datetime in long date format   

    public String getCurrentDate() {
        Datetime cDT = System.now();
        CurrentDate = cDT.format('MMMM d, yyyy');        
        return CurrentDate;        
    } 
    
    public class wrapperAccount {
    
        public string accCPCPSLastUpdateddate {get;set;}
    
        public Account objaccountSO {get; set;}
        public string CP {get; set;}
        public string CPS {get; set;}
        public string SAdate {get;set;}
        public string SAstartdate {get;set;}
        public string SAenddate {get;set;}
        public string BRdate {get;set;}
        public string BRstartdate {get;set;}
        public string BRenddate {get;set;}
        public string EVdate {get;set;}
        public string EVSSLstartdate {get;set;}
        public string EVSSLenddate {get;set;}
        public string EVCodedate {get;set;}
        public string EVCodestartdate {get;set;}
        public string EVCodeenddate {get;set;}
        public string CPCPSLastUpdateddate {get;set;}
        
        public wrapperAccount(){
            objaccountSO = new Account();
            SAdate = '';
            SAstartdate = '';
            SAenddate = '';
            BRdate = '';
            BRstartdate = '';
            BRenddate = '';
            EVdate = '';
            EVSSLstartdate = '';
            EVSSLenddate = '';
            EVCodedate = '';
            EVCodestartdate = '';
            EVCodeenddate = '';
            CPCPSLastUpdateddate = '';
            accCPCPSLastUpdateddate = '';
        }
    }    
}