objects/Account.object
<CustomObject>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CA_Comm_Question__c.object
<CustomObject>
    <fields>
        <fullName>CA_Comm__c</fullName>
        <label>CA Comm</label>
        <referenceTo>CA_Communication__c</referenceTo>
        <relationshipLabel>CA Comm Questions</relationshipLabel>
        <relationshipName>CA_Comm_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Default_Text__c</fullName>
        <inlineHelpText>Default text can be added here for text box</inlineHelpText>
        <label>Default Text</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No.</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single Select (Radio buttons)</fullName>
                </value>
                <value>
                    <fullName>Multi Select (Check boxes)</fullName>
                </value>
                <value>
                    <fullName>Free Text (Multi line text box)</fullName>
                </value>
                <value>
                    <fullName>Date Type</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Response_Option_1__c</fullName>
        <label>Response Option 1</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_2__c</fullName>
        <label>Response Option 2</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CA Comm Question</label>
    <nameField>
        <displayFormat>Q{00000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Comm Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CA_Comm_Response__c.object
<CustomObject>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CA Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CA Comm Responses</relationshipLabel>
        <relationshipName>CA_Comm_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CA Comm Responses</relationshipLabel>
        <relationshipName>CA_Comm_Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Type_Response__c</fullName>
        <label>Date Type Response</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Question_Id__c</fullName>
        <label>Question Id</label>
        <referenceTo>CA_Comm_Question__c</referenceTo>
        <relationshipLabel>CA Comm Responses</relationshipLabel>
        <relationshipName>CA_Comm_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <formula>Question_Id__r.Question_255_chars__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Option_No__c</fullName>
        <label>Response Option No.</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CA Comm Response</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Resposne Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Comm Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CA_Communication__c.object
<CustomObject>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CA Communication (Edit)</label>
    <nameField>
        <label>CA Comm Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CA Communications (Edit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CACommunicationSurveyControllerTest.cls
@isTest
public class CACommunicationSurveyControllerTest {

    private static @testsetup void setupData(){
        
        Account acc = new Account(Name = 'test account', status__c= 'Included', 
        RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('CA Owner').getRecordTypeID());
        insert acc;
        
        Contact con = new Contact(LastName = 'testName', AccountId = acc.Id);
        insert con;
        
        CA_Communication__c survey = new CA_Communication__c(Name = 'test survey0', Expiration_Date__c = System.today().addDays(7),
        Message__c = 'test message');
        insert survey;
        
        CA_Comm_Question__c question1 = new CA_Comm_Question__c(CA_Comm__c = survey.Id, Order_No__c = 1, Question__c = 'que 1', 
        Question_Type__c = 'Single Select (Radio buttons)',
        Required__c = true, Response_Option_1__c = 'Yes', Response_Option_2__c = 'No');
        //insert question1;
        
        CA_Comm_Question__c question2 = new CA_Comm_Question__c(CA_Comm__c = survey.Id, Order_No__c = 2, Question__c = 'que 2', 
        Question_Type__c = 'Multi Select (Check boxes)',
        Required__c = true, Response_Option_1__c = 'Yes', Response_Option_2__c = 'No');
        //insert question2;
        
        CA_Comm_Question__c question3 = new CA_Comm_Question__c(CA_Comm__c = survey.Id, Order_No__c = 3, Question__c = 'que 3', 
        Question_Type__c = 'Free Text (Multi line text box)',
        Required__c = false, Default_Text__c = 'Default_Text__c');
        
        CA_Comm_Question__c question4 = new CA_Comm_Question__c(CA_Comm__c = survey.Id, Order_No__c = 4, Question__c = 'que 4', 
        Question_Type__c = 'Date Type', Required__c = false);
        
        insert new List<CA_Comm_Question__c>{question1, question2, question3, question4};
        
        Test.startTest();
            //this is admin user
            User loggedInUser = new User(Alias = 'standt', Email='loggedin.user1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = UserInfo.getProfileId(), 
            TimeZoneSidKey='America/Los_Angeles', UserName='loggedin.user1@testorg.com');

        System.runAs(loggedInUser) {
                
                Profile p = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus User']; 
                //this is community user
                User communityUser = new User(Alias = 'standt', Email='standardportaluser_mozilla@testorg.com', 
                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, 
                    TimeZoneSidKey='America/Los_Angeles', UserName='standardportaluser_mozilla@testorg.com',
                    ContactId = con.Id, IsActive = true);
                    
                insert communityUser;
        }
        
        Test.stopTest();
    }
    
    static testmethod void test1_WithInternalUser(){
        
        PageReference pref = Page.CACommunicationSurvey;
        Test.setCurrentPage(pref);
        
        CA_Communication__c survey = [SELECT Id FROM CA_Communication__c WHERE Name = 'test survey0' LIMIT 1];
        CACommunicationSurveyController obj = new CACommunicationSurveyController();
        obj.selectedSurveyId = survey.Id;
        
        //lstQuestions
        obj.getUserContact();
        obj.getQuesionnairies();
        
        for(CACommunicationSurveyController.Question que : obj.lstQuestions){
            que.selectedOption = '0';
            que.selectedOptions = new List<String>{'1'};
            que.choices = 'Yes';
        }
        
        obj.submitResults();
        obj.doCancel();
    }
    
    
    static testmethod void test1_WithExternalUser(){
        
        User communityUser = [SELECT Id, ContactId, Contact.AccountId, Profile.Name, UserType FROM User WHERE Email = 'standardportaluser_mozilla@testorg.com' LIMIT 1];
        System.debug('user: '+communityUser);
        System.runAs(communityUser){
        
        PageReference pref = Page.CACommunicationSurvey;
        Test.setCurrentPage(pref);
        
        CA_Communication__c survey = [SELECT Id FROM CA_Communication__c WHERE Name = 'test survey0' LIMIT 1];
        CACommunicationSurveyController obj = new CACommunicationSurveyController();
        obj.selectedSurveyId = survey.Id;
        //lstQuestions
        obj.getUserContact();
        obj.getQuesionnairies();
        
        for(CACommunicationSurveyController.Question que : obj.lstQuestions){
            que.selectedOption = '0';
            que.selectedOptions = new List<String>{'1'};
            que.choices = 'Yes';
        }
        
        obj.submitResults();
        obj.doCancel();
        
        }
    }
    
    
    static testmethod void test1_WithInternalUser_ExistinSurvey(){
        
        User communityUser = [SELECT Id, ContactId, Contact.AccountId, Profile.Name, UserType FROM User WHERE Email = 'standardportaluser_mozilla@testorg.com' LIMIT 1];
        
        CA_Communication__c survey = [SELECT Id FROM CA_Communication__c WHERE Name = 'test survey0' LIMIT 1];
        
        List<CA_Comm_Question__c> lstQue = [SELECT Id, Order_No__c, Question__c, Question_Type__c, Required__c, 
                                            Response_Option_1__c, Response_Option_2__c
                                            FROM CA_Comm_Question__c
                                            WHERE CA_Comm__c = :survey.Id 
                                            ORDER BY Order_No__c];
        
        
        List<CA_Comm_Response__c> lstResponse = new List<CA_Comm_Response__c>();
        for(CA_Comm_Question__c que : lstQue){
            
            CA_Comm_Response__c res1 = new CA_Comm_Response__c();
            res1.CA_Owner__c = communityUser.Contact.AccountId;
            res1.Contact__c = communityUser.ContactId;
            res1.Question_Id__c = que.Id;
            res1.Response__c = 'Yes';
            res1.Response_Option_No__c = '1';
            res1.Date_Type_Response__c = date.today();
            lstResponse.add(res1);
        }
        
        insert lstResponse;
        
        PageReference pref = Page.CACommunicationSurvey;
        Test.setCurrentPage(pref);
        
        ApexPages.currentPage().getParameters().put('CACommunicationId', survey.Id);
        ApexPages.currentPage().getParameters().put('ContactId', [SELECT Id FROM Contact WHERE LastName = 'testName'].Id);
        
        CACommunicationSurveyController obj = new CACommunicationSurveyController();
        obj.selectedSurveyId = survey.Id;
        //lstQuestions
        obj.getUserContact();
        obj.getQuesionnairies();
        
        for(CACommunicationSurveyController.Question que : obj.lstQuestions){
            que.selectedOption = '0';
            que.selectedOptions = new List<String>{'1'};
            que.choices = 'Yes';
        }
        
        obj.submitResults();
        obj.doCancel();
    }
    
    static testmethod void test_blankRequiredValues1_ExistinSurvey(){
        
        User communityUser = [SELECT Id, ContactId, Contact.AccountId, Profile.Name, UserType FROM User WHERE Email = 'standardportaluser_mozilla@testorg.com' LIMIT 1];
        
        CA_Communication__c survey = [SELECT Id FROM CA_Communication__c WHERE Name = 'test survey0' LIMIT 1];
        
        List<CA_Comm_Question__c> lstQue = [SELECT Id, Order_No__c, Question__c, Question_Type__c, Required__c, 
                                            Response_Option_1__c, Response_Option_2__c
                                            FROM CA_Comm_Question__c
                                            WHERE CA_Comm__c = :survey.Id 
                                            ORDER BY Order_No__c];
        
        for(CA_Comm_Question__c que : lstQue){
            que.Required__c = true;
        }
        update lstQue;
        
        List<CA_Comm_Response__c> lstResponse = new List<CA_Comm_Response__c>();
        for(CA_Comm_Question__c que : lstQue){
            
            CA_Comm_Response__c res1 = new CA_Comm_Response__c();
            res1.CA_Owner__c = communityUser.Contact.AccountId;
            res1.Contact__c = communityUser.ContactId;
            res1.Question_Id__c = que.Id;
            res1.Response__c = 'Yes';
            res1.Response_Option_No__c = '1';
            res1.Date_Type_Response__c = date.today();
            lstResponse.add(res1);
        }
        
        insert lstResponse;
        
        PageReference pref = Page.CACommunicationSurvey;
        Test.setCurrentPage(pref);
        
        ApexPages.currentPage().getParameters().put('CACommunicationId', survey.Id);
        ApexPages.currentPage().getParameters().put('ContactId', [SELECT Id FROM Contact WHERE LastName = 'testName'].Id);
        
        CACommunicationSurveyController obj = new CACommunicationSurveyController();
        obj.selectedSurveyId = survey.Id;
        //lstQuestions
        obj.getUserContact();
        obj.getQuesionnairies();
        
        for(CACommunicationSurveyController.Question que : obj.lstQuestions){
            que.required = true;
            que.selectedOption = null;
            que.renderSelectRadio = 'true';
            que.renderSelectCheckboxes = 'true';
            que.selectedOptions = null;
            que.renderFreeText = 'false';
            que.choices = null;
            que.dateResonse.Date_Type_Response__c = null;
        }
        
        obj.submitResults();
        obj.doCancel();
    }
    
    static testmethod void test_blankRequiredValues2_ExistinSurvey(){
        
        User communityUser = [SELECT Id, ContactId, Contact.AccountId, Profile.Name, UserType FROM User WHERE Email = 'standardportaluser_mozilla@testorg.com' LIMIT 1];
        
        CA_Communication__c survey = [SELECT Id FROM CA_Communication__c WHERE Name = 'test survey0' LIMIT 1];
        
        List<CA_Comm_Question__c> lstQue = [SELECT Id, Order_No__c, Question__c, Question_Type__c, Required__c, 
                                            Response_Option_1__c, Response_Option_2__c
                                            FROM CA_Comm_Question__c
                                            WHERE CA_Comm__c = :survey.Id 
                                            ORDER BY Order_No__c];
        
        for(CA_Comm_Question__c que : lstQue){
            que.Required__c = true;
        }
        update lstQue;
        
        List<CA_Comm_Response__c> lstResponse = new List<CA_Comm_Response__c>();
        for(CA_Comm_Question__c que : lstQue){
            
            CA_Comm_Response__c res1 = new CA_Comm_Response__c();
            res1.CA_Owner__c = communityUser.Contact.AccountId;
            res1.Contact__c = communityUser.ContactId;
            res1.Question_Id__c = que.Id;
            res1.Response__c = 'Yes';
            res1.Response_Option_No__c = '1';
            res1.Date_Type_Response__c = date.today();
            lstResponse.add(res1);
        }
        
        insert lstResponse;
        
        PageReference pref = Page.CACommunicationSurvey;
        Test.setCurrentPage(pref);
        
        ApexPages.currentPage().getParameters().put('CACommunicationId', survey.Id);
        ApexPages.currentPage().getParameters().put('ContactId', [SELECT Id FROM Contact WHERE LastName = 'testName'].Id);
        
        CACommunicationSurveyController obj = new CACommunicationSurveyController();
        obj.selectedSurveyId = survey.Id;
        //lstQuestions
        obj.getUserContact();
        obj.getQuesionnairies();
        
        for(CACommunicationSurveyController.Question que : obj.lstQuestions){
            que.required = true;
            que.selectedOption = null;
            que.renderSelectRadio = 'false';
            que.renderSelectCheckboxes = 'true';
            que.selectedOptions = null;
            que.renderFreeText = 'false';
            que.choices = null;
            que.dateResonse.Date_Type_Response__c = null;
        }
        
        obj.submitResults();
        obj.doCancel();
    }
    
    static testmethod void test_blankRequiredValues3_ExistinSurvey(){
        
        User communityUser = [SELECT Id, ContactId, Contact.AccountId, Profile.Name, UserType FROM User WHERE Email = 'standardportaluser_mozilla@testorg.com' LIMIT 1];
        
        CA_Communication__c survey = [SELECT Id FROM CA_Communication__c WHERE Name = 'test survey0' LIMIT 1];
        
        List<CA_Comm_Question__c> lstQue = [SELECT Id, Order_No__c, Question__c, Question_Type__c, Required__c, 
                                            Response_Option_1__c, Response_Option_2__c
                                            FROM CA_Comm_Question__c
                                            WHERE CA_Comm__c = :survey.Id 
                                            ORDER BY Order_No__c];
        
        for(CA_Comm_Question__c que : lstQue){
            que.Required__c = true;
        }
        update lstQue;
        
        List<CA_Comm_Response__c> lstResponse = new List<CA_Comm_Response__c>();
        for(CA_Comm_Question__c que : lstQue){
            
            CA_Comm_Response__c res1 = new CA_Comm_Response__c();
            res1.CA_Owner__c = communityUser.Contact.AccountId;
            res1.Contact__c = communityUser.ContactId;
            res1.Question_Id__c = que.Id;
            res1.Response__c = 'Yes';
            res1.Response_Option_No__c = '1';
            res1.Date_Type_Response__c = date.today();
            lstResponse.add(res1);
        }
        
        insert lstResponse;
        
        PageReference pref = Page.CACommunicationSurvey;
        Test.setCurrentPage(pref);
        
        ApexPages.currentPage().getParameters().put('CACommunicationId', survey.Id);
        ApexPages.currentPage().getParameters().put('ContactId', [SELECT Id FROM Contact WHERE LastName = 'testName'].Id);
        
        CACommunicationSurveyController obj = new CACommunicationSurveyController();
        obj.selectedSurveyId = survey.Id;
        //lstQuestions
        obj.getUserContact();
        obj.getQuesionnairies();
        
        for(CACommunicationSurveyController.Question que : obj.lstQuestions){
            que.required = true;
            que.selectedOption = null;
            que.renderSelectRadio = 'false';
            que.renderSelectCheckboxes = 'false';
            que.selectedOptions = null;
            que.renderFreeText = 'true';
            que.choices = null;
            que.dateResonse.Date_Type_Response__c = null;
        }
        
        obj.submitResults();
        obj.doCancel();
    }
    
    static testmethod void test_blankRequiredValues4_ExistinSurvey(){
        
        User communityUser = [SELECT Id, ContactId, Contact.AccountId, Profile.Name, UserType FROM User WHERE Email = 'standardportaluser_mozilla@testorg.com' LIMIT 1];
        
        CA_Communication__c survey = [SELECT Id FROM CA_Communication__c WHERE Name = 'test survey0' LIMIT 1];
        
        List<CA_Comm_Question__c> lstQue = [SELECT Id, Order_No__c, Question__c, Question_Type__c, Required__c, 
                                            Response_Option_1__c, Response_Option_2__c
                                            FROM CA_Comm_Question__c
                                            WHERE CA_Comm__c = :survey.Id 
                                            ORDER BY Order_No__c];
        
        for(CA_Comm_Question__c que : lstQue){
            que.Required__c = true;
        }
        update lstQue;
        
        List<CA_Comm_Response__c> lstResponse = new List<CA_Comm_Response__c>();
        for(CA_Comm_Question__c que : lstQue){
            
            CA_Comm_Response__c res1 = new CA_Comm_Response__c();
            res1.CA_Owner__c = communityUser.Contact.AccountId;
            res1.Contact__c = communityUser.ContactId;
            res1.Question_Id__c = que.Id;
            res1.Response__c = 'Yes';
            res1.Response_Option_No__c = '1';
            res1.Date_Type_Response__c = date.today();
            lstResponse.add(res1);
        }
        
        insert lstResponse;
        
        PageReference pref = Page.CACommunicationSurvey;
        Test.setCurrentPage(pref);
        
        ApexPages.currentPage().getParameters().put('CACommunicationId', survey.Id);
        ApexPages.currentPage().getParameters().put('ContactId', [SELECT Id FROM Contact WHERE LastName = 'testName'].Id);
        
        CACommunicationSurveyController obj = new CACommunicationSurveyController();
        obj.selectedSurveyId = survey.Id;
        //lstQuestions
        obj.getUserContact();
        obj.getQuesionnairies();
        
        for(CACommunicationSurveyController.Question que : obj.lstQuestions){
            que.required = true;
            que.selectedOption = null;
            que.renderSelectRadio = 'false';
            que.renderSelectCheckboxes = 'false';
            que.selectedOptions = null;
            que.renderFreeText = 'false';
            que.renderDateType = 'true';
            que.choices = null;
            que.dateResonse.Date_Type_Response__c = null;
        }
        
        obj.submitResults();
        obj.doCancel();
    }
    
    static testmethod void test1_WithExternalUser_ExistinSurvey(){
        
        User communityUser = [SELECT Id, ContactId, Contact.AccountId, Profile.Name, UserType FROM User WHERE Email = 'standardportaluser_mozilla@testorg.com' LIMIT 1];
        CA_Communication__c survey = [SELECT Id FROM CA_Communication__c WHERE Name = 'test survey0' LIMIT 1];
        
        List<CA_Comm_Question__c> lstQue = [SELECT Id, Order_No__c, Question__c, Question_Type__c, Required__c, 
                                            Response_Option_1__c, Response_Option_2__c
                                            FROM CA_Comm_Question__c
                                            WHERE CA_Comm__c = :survey.Id 
                                            ORDER BY Order_No__c];
        
        
        List<CA_Comm_Response__c> lstResponse = new List<CA_Comm_Response__c>();
        for(CA_Comm_Question__c que : lstQue){
            
            CA_Comm_Response__c res1 = new CA_Comm_Response__c();
            res1.CA_Owner__c = communityUser.Contact.AccountId;
            res1.Contact__c = communityUser.ContactId;
            res1.Question_Id__c = que.Id;
            res1.Response__c = 'Yes';
            res1.Response_Option_No__c = '1';
            lstResponse.add(res1);
        }
        
        insert lstResponse;
    
        //System.debug('user: '+communityUser);
        
        PageReference pref = Page.CACommunicationSurvey;
        Test.setCurrentPage(pref);
        
        ApexPages.currentPage().getParameters().put('CACommunicationId', survey.Id);
        ApexPages.currentPage().getParameters().put('ContactId', [SELECT Id FROM Contact WHERE LastName = 'testName'].Id);
        
        CACommunicationSurveyController obj = new CACommunicationSurveyController();
        
        //lstQuestions
        obj.selectedSurveyId = survey.Id;
        obj.getUserContact();
        obj.getQuesionnairies();
        
        for(CACommunicationSurveyController.Question que : obj.lstQuestions){
            que.selectedOption = '0';
            que.selectedOptions = new List<String>{'1'};
            que.choices = 'Yes';
        }
        
        obj.submitResults();
        obj.doCancel();
    }
    
    static testmethod void test_SurveyWithNoQuestions(){
        
        User communityUser = [SELECT Id, ContactId, Contact.AccountId, Profile.Name, UserType FROM User WHERE Email = 'standardportaluser_mozilla@testorg.com' LIMIT 1];
        CA_Communication__c survey = new CA_Communication__c(Name = 'test survey1', Expiration_Date__c = System.today().addDays(7));
        insert survey;
        
        PageReference pref = Page.CACommunicationSurvey;
        Test.setCurrentPage(pref);
        
        ApexPages.currentPage().getParameters().put('CACommunicationId', survey.Id);
        ApexPages.currentPage().getParameters().put('ContactId', [SELECT Id FROM Contact WHERE LastName = 'testName'].Id);
        
        CACommunicationSurveyController obj = new CACommunicationSurveyController();
        obj.selectedSurveyId = survey.Id;
        //lstQuestions
        obj.getUserContact();
        obj.getQuesionnairies();
    
        obj.doCancel();
    }
}