objects/Account.object
<CustomObject>
    <fields>
        <fullName>BR_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>BR Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Period_Start_Date__c</fullName>
        <description>Start date of the period of time of CA operations examined by the auditor.</description>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>BR Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Period_End_Date__c</fullName>
        <description>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</description>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Code Signing Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Period_Start_Date__c</fullName>
        <description>Start date of the period of time of CA operations examined by the auditor.</description>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Code Signing Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>EV SSL Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>EV SSL Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>EV Code Signing Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>EV Code Signing Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Standard Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>BR_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>BR Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>BR Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Period_End_Date__c</fullName>
        <label>Code Signing Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Period_Start_Date__c</fullName>
        <label>Code Signing Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>EV SSL Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>EV SSL Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>EV Code Signing Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>EV Code Signing Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>Information verification phases</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Standard Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Root_Case__c.object
<CustomObject>
    <fields>
        <fullName>Apply_BR_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BR Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_Code_Signing_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Code Signing Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_EV_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EV SSL Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_Standard_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CA_Owner_Name_Existing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Previously called Included CA Owner Name</description>
        <label>CA Owner Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Owner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Root Cases</relationshipLabel>
        <relationshipName>Root_Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_No__c</fullName>
        <label>Case No</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Root Cases</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Root_Certificate_Name_Existing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Previously called Included Certificate Name</description>
        <inlineHelpText>The Root Certificate that this Root Case applies to.</inlineHelpText>
        <label>Certificate Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Root</value>
            </filterItems>
            <filterItems>
                <field>Account.Parent.Id</field>
                <operation>equals</operation>
                <valueField>$Source.CA_Owner_Name_Existing__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Root Cases (Included Certificate)</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <inlineHelpText>Select the trust bits you are requesting to be enabled for this root.</inlineHelpText>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Root Case</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Root Case No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AuditRootCaseMessageInlineControllerTest.cls
/*
    Description: Test class for AuditRootCaseMessageInlineController
*/
@isTest
public with sharing class AuditRootCaseMessageInlineControllerTest {
    
    static testmethod void TestAuditRootCaseMessages(){
        //create the parent account  - record type = Owner
        Account parentAccount = SyncParentAccountFromCaseControllerTest.getParentAccount();
        parentAccount.Name = 'parent root account 1';
        insert parentAccount;
        
        // create the contact associated with the parent account
        Contact parentContact = SyncParentAccountFromCaseControllerTest.getParentContact(parentAccount.id);
        parentContact.firstName = 'parent_firstname';
        parentContact.lastName = 'parent_lastname';
        insert parentContact;
        
        // create the child account - record type = Root
        Account childAccount = SyncParentAccountFromCaseControllerTest.getChildAccount(parentAccount.id);
        childAccount.Name = 'child root account 1';
        childAccount.Standard_Audit_Period_End_Date__c = system.today().addDays(-2);
        childAccount.Code_Signing_Audit_Period_End_Date__c = system.today().addDays(-5);
        childAccount.BR_Audit_Period_End_Date__c = system.today().addDays(-3);
        childAccount.EV_Audit_Period_End_Date__c = system.today().addDays(-4);
        childAccount.EV_Code_Signing_Audit_Period_End_Date__c = system.today().addDays(-5);
        insert childAccount;
        
        // create a case
        Case accountCaseA = SyncParentAccountFromCaseControllerTest.getCase(parentAccount.id, parentContact.id);
        accountCaseA.request_status__c  = 'Initial Request Received'; 
        accountCaseA.Standard_Audit_Period_Start_Date__c = system.today().addDays(2);
        accountCaseA.Code_Signing_Audit_Period_Start_Date__c = system.today().addDays(4);
        accountCaseA.BR_Audit_Period_Start_Date__c = system.today().addDays(3);
        accountCaseA.EV_Audit_Period_Start_Date__c = system.today().addDays(4);
        accountCaseA.EV_Code_Signing_Audit_Period_Start_Date__c = system.today().addDays(5);
        insert accountCaseA;
        
        accountCaseA.Request_Status__c = 'Data Verified';
        update accountCaseA;
        
        // create the root case and associate it with the case
        Root_Case__c rootCaseA1 = SyncParentAccountFromCaseControllerTest.getRootCase(accountCaseA.id,parentAccount.Id,childAccount.Id);
        rootCaseA1.request_status__c   = 'Initial Request Received';         
        rootCaseA1.Apply_Standard_Audit__c = true;
        rootCaseA1.Apply_BR_Audit__c = true;
        rootCaseA1.Apply_EV_Audit__c = true;
        rootCaseA1.Apply_Code_Signing_Audit__c = true;         
        rootCaseA1.Case_No__c = accountCaseA.Id;
        rootCaseA1.CA_Owner_Name_Existing__c = parentAccount.Id;
        rootCaseA1.Root_Certificate_Name_Existing__c = childAccount.Id;
        rootCaseA1.RecordTypeId = Schema.SObjectType.Root_Case__c.getRecordTypeInfosByName().get('CA Audit Update Request').getRecordTypeID();
        rootCaseA1.Trust_Bits__c = 'Websites';
        rootCaseA1.Microsoft_Trust_Bits__c = 'Server Authentication';
        insert rootCaseA1;
        
        AuditRootCaseMessageInlineController auditRootCase = new AuditRootCaseMessageInlineController(new Apexpages.standardcontroller(rootCaseA1));
        
    }
    
}