objects/Account.object
<CustomObject>
    <fields>
        <fullName>Problem_Reporting_Mechanism__c</fullName>
        <inlineHelpText>Email address or URL for reporting suspected Private Key Compromise, Certificate misuse, or other types of fraud, compromise, misuse, inappropriate conduct, or any other matter related to Certificates.</inlineHelpText>
        <label>Problem Reporting Mechanism</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recognized_CAA_Domains__c</fullName>
        <inlineHelpText>Certification Authority Authorization (CAA) domain names recognized in a CAA record&apos;s issue and issue wild property tags. Comma-separated list.</inlineHelpText>
        <label>Recognized CAA Domains</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AllCAAIdentifiersReportControllerTest.cls
/*******************************************************************************************************
 Name: AllCAAIdentifiersReportControllerTest

 Dependencies: AllCAAIdentifiersReportController controller class, AllCAAIdentifiersReportControllerTest 
 test class, AllCAAIdentifiersReportController vf page

 Description: This is a test class for AllCAAIdentifiersReportController. Report lists 
 Recognized CAA Domains info for all CA Owner and Intermediate Cert records.
 
 Instructions: None   
 *******************************************************************************************************
 Revision History:
 
     3/3/2018 - Created new class
 ******************************************************************************************************/     

@isTest 
public class AllCAAIdentifiersReportControllerTest {

    static testMethod void validateTest() {
        
        Account acc = new Account(Name='Test Account Name To Test AllCAAIdentifiersReportController',Problem_Reporting_Mechanism__c = 'test@test.com', Status__c = 'Included',Recognized_CAA_Domains__c = 'test.com');
        insert acc;
        
        PageReference pref = Page.AllCAAIdentifiersReport;
        Test.setCurrentPage(pref);
        AllCAAIdentifiersReportController pacrc = new AllCAAIdentifiersReportController();
        pacrc.getCurrentDate();
    }
}