objects/Account.object
<CustomObject>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>BR Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>BR Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OneCRL_Status__c</fullName>
        <label>OneCRL Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to Add</fullName>
                </value>
                <value>
                    <fullName>Added to OneCRL</fullName>
                </value>
                <value>
                    <fullName>Cert Expired</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Root_Cert_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is populated by PublicAllIntermediateCerts batch program for all intermediate cert records.</inlineHelpText>
        <label>Root Cert Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subordinate_CA_Owner__c</fullName>
        <inlineHelpText>Enter Subordinate CA’s name as it appears in the provided audit statements. Leave blank if BOTH control of the private key AND domain/IP/email validation activities are performed by the organization listed in the audit statement of the parent certificate.</inlineHelpText>
        <label>Subordinate CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Technically_Constrained__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Technically Constrained</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Valid_From_YYYY_MMM_DD__c</fullName>
        <description>This formula field converts regular date field to display date in YYYY MMM DD format. Eg: &quot;7/9/1999&quot; shows as &quot;1999 Jul 09&quot;</description>
        <formula>IF ( NOT ISBLANK(Valid_From_GMT__c), 

TEXT(YEAR(Valid_From_GMT__c)) &amp; &quot; &quot; &amp;

CASE(MONTH(Valid_From_GMT__c),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
NULL) &amp; &quot; &quot; &amp;
 
IF (LEN(TEXT(DAY(Valid_From_GMT__c))) = 1,&quot;0&quot; &amp; TEXT(DAY(Valid_From_GMT__c)),TEXT(DAY(Valid_From_GMT__c))),

NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid From [GMT]</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_YYYY_MMM_DD__c</fullName>
        <description>This formula field converts regular date field to display date in YYYY MMM DD format. Eg: &quot;7/9/1999&quot; shows as &quot;1999 Jul 09&quot;</description>
        <formula>IF ( NOT ISBLANK(Valid_To_GMT__c),

TEXT(YEAR(Valid_To_GMT__c)) &amp; &quot; &quot; &amp;

CASE(MONTH(Valid_To_GMT__c),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
NULL) &amp; &quot; &quot; &amp;

IF (LEN(TEXT(DAY(Valid_To_GMT__c))) = 1,&quot;0&quot; &amp; TEXT(DAY(Valid_To_GMT__c)),TEXT(DAY(Valid_To_GMT__c))),

NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid To [GMT]</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IntermediateCertsSeparateAuditsCtrl.cls
/*******************************************************************************************************
 Name: IntermediateCertsSeparateAuditsCtrl 
 
 Dependencies: IntermediateCertsSeparateAudits VF page, IntermediateCertsSeparateAuditsCSV VF page, 
 IntermediateCertsSeparateAuditsCtrlTest 
 
 Description: 'Intermediate Certs's Separate Audits' reports on Intermediate certs which have their own audits.
 
              Filtered By:    

              CA Owner/Certificate Record Type equals Intermediate Certificate
              AND CA Owner/Certificate Owner not equal to <Fill in Cert Name>
              AND Revocation Status equals 'Not Revoked'
              AND OneCRL_Status__c not equals 'Added to OneCRL'
              AND Mozilla Status for the root cert equals Included,Change Requested
              AND Audits Same as Parent equals False
              AND Valid To (GMT) greater than TODAY
              AND Technically Constrained equals False

              Columns: CA Owner, Parent Certificate Name, Certificate Name, SHA-256 Fingerprint, 
                       Valid From [GMT], Valid To [GMT], Standard Audit, Standard Audit Period End Date, 
                       BR Audit, BR Audit Period End Date

              Columns For the non-CSV version, SHA-256 fingerprints links to 
                      https://crt.sh/?q=<SHA256-Fingerprint>
 Instructions: None
   
 *******************************************************************************************************
 Revision History:
 
     3/7/2019 - Created new
     7/9/2019 - Added "Comments" field
     8/12/2019 - Added Subordinate_CA_Owner__c to the report
     8/14/2019 - Added filter condition OneCRL_Status__c = 'Added to OneCRL'
 ******************************************************************************************************/
 
public without sharing class IntermediateCertsSeparateAuditsCtrl {
    
    public List<Account> accountSoLst {get;set;}
 
    public IntermediateCertsSeparateAuditsCtrl(){
        String intermediateCertRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Intermediate Certificate').getRecordTypeId();
        
        accountSoLst =  [SELECT Parent.Name, Name, Subordinate_CA_Owner__c, SHA_256_Fingerprint__c, Valid_From_YYYY_MMM_DD__c, Valid_To_YYYY_MMM_DD__c, 
                         CA_Owner__c, Standard_Audit__c, BR_Audit__c, Standard_Audit_Period_End_Date__c, BR_Audit_Period_End_Date__c, Comments__c
                         FROM  Account 
                         Where RecordTypeId =: intermediateCertRecordTypeId 
                         AND Name != '<Fill in Cert Name>' 
                         AND Revocation_Status__c = 'Not Revoked' 
                         AND OneCRL_Status__c != 'Added to OneCRL'
                         AND Root_Cert_Id__r.Status__c In ('Included','Change Requested') 
                         AND Audits_Same_as_Parent__c = FALSE 
                         AND Valid_To_GMT__c > TODAY 
                         AND Technically_Constrained__c = FALSE
                         ORDER BY CA_Owner__c];
                                    
        // if we are generating a CSV file then we need to replace the double quotes in all text fields with null
        if(Test.IsRunningTest() || (ApexPages.currentPage().getUrl().contains('CSV') && accountSoLst !=null && accountSoLst.size() > 0))
        {
            for(Account accountSo : accountSoLst) {
                if(accountSo.CA_Owner__c !=null && accountSo.CA_Owner__c.length() > 0) 
                    accountSo.CA_Owner__c = accountSo.CA_Owner__c.replace('"',''); 
                if(accountSo.name !=null && accountSo.name.length() > 0) 
                    accountSo.name = accountSo.name.replace('"',''); 
                if(accountSo.parent.name !=null && accountSo.parent.name.length() > 0) 
                    accountSo.parent.name = accountSo.parent.name.replace('"','');
                if(accountSo.Subordinate_CA_Owner__c !=null && accountSo.Subordinate_CA_Owner__c.length() > 0) 
                    accountSo.Subordinate_CA_Owner__c = accountSo.Subordinate_CA_Owner__c.replace('"','');      
                if(accountSo.Comments__c !=null && accountSo.Comments__c.length() > 0) 
                    accountSo.Comments__c = accountSo.Comments__c.replace('"','');    
            }  
        }
    }
    
    public String getCurrentDate() {
        Datetime cDT = System.now();
        string CurrentDate = cDT.format('MMMM d, yyyy');
        return CurrentDate;
    }
}