objects/Account.object
<CustomObject>
    <fields>
        <fullName>Alternate_CRL__c</fullName>
        <inlineHelpText>Only fill this in if this certificate does not contain a CRL URL.</inlineHelpText>
        <label>Alternate CRL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Case_Safe_ID__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Safe ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Serial_Number__c</fullName>
        <label>Certificate Serial Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_of_Revocation__c</fullName>
        <label>Date of Revocation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFC_5280_Revocation_Reason_Code__c</fullName>
        <inlineHelpText>Provide the reason for the certificate revocation. Value 7 is not being used.</inlineHelpText>
        <label>RFC 5280 Revocation Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>(0) unspecified</fullName>
                </value>
                <value>
                    <fullName>(1) keyCompromise</fullName>
                </value>
                <value>
                    <fullName>(2) cACompromise</fullName>
                </value>
                <value>
                    <fullName>(3) affiliationChanged</fullName>
                </value>
                <value>
                    <fullName>(4) superseded</fullName>
                </value>
                <value>
                    <fullName>(5) cessationOfOperation</fullName>
                </value>
                <value>
                    <fullName>(6) certificateHold</fullName>
                </value>
                <value>
                    <fullName>(8) removeFromCRL</fullName>
                </value>
                <value>
                    <fullName>(9) privilegeWithdrawn</fullName>
                </value>
                <value>
                    <fullName>(10) aACompromise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Verification__c</fullName>
        <inlineHelpText>Output from Verify Revocation check</inlineHelpText>
        <label>Revocation Verification</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Root_Cert_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is populated by PublicAllIntermediateCerts batch program for all intermediate cert records.</inlineHelpText>
        <label>Root Cert Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InterCertsRevokedReportForMSFTCtrl.cls
/*******************************************************************************************************
 Name: InterCertsRevokedReportForMSFTCtrl

 Dependencies: InterCertsRevokedReportForMSFTCtrl, InterCertsRevokedReportForMSFTCSV vf page,
 InterCertsRevokedReportForMSFTCtrlTest

 Description: This report generates list of intermediate certs which are revoked for Microsoft.

 Instructions: None

 *******************************************************************************************************
 Revision History:
 
     11/15/2019 - Created new

 ******************************************************************************************************/
 
 public without sharing class InterCertsRevokedReportForMSFTCtrl {
    public Transient List<Account> accountSoLst {get;set;}
    
  
    //constructor method for standard controller
    public InterCertsRevokedReportForMSFTCtrl() {  
    

                                           
        accountSoLst =  [SELECT Name, Case_Safe_ID__c, CA_Owner__c, Root_Cert_Id__r.Parent.id,
                            Subject__c, Certificate_Serial_Number__c, Alternate_CRL__c,
                            SHA_1_Fingerprint__c, SHA_256_Fingerprint__c,
                            Parent.SHA_1_Fingerprint__c, Parent.SHA_256_Fingerprint__c,
                            Root_Cert_Id__r.SHA_1_Fingerprint__c, Root_Cert_Id__r.SHA_256_Fingerprint__c,
                            Revocation_Status__c, Date_of_Revocation__c, RFC_5280_Revocation_Reason_Code__c, 
                            Revocation_Verification__c, Valid_To_GMT__c, X_509_Certificate_PEM__c
                            FROM  Account
                            WHERE Revocation_Status__c In ('Revoked','Parent Cert Revoked') 
                            AND   RecordType.Name = 'Intermediate Certificate' 
                            AND   Root_Cert_Id__r.Microsoft_Status__c in ('Included', 'Change Requested')
                            ORDER BY CA_Owner__c, Name];
                          
        // if we are generating a CSV file then we need to replace the double quotes in all text fields with null
        if(Test.IsRunningTest() || (ApexPages.currentPage().getUrl().contains('CSV') && accountSoLst !=null && accountSoLst.size() > 0)) {
            for(Account accountSo : accountSoLst){
                if(accountSo.name !=null && accountSo.name.length() > 0) 
                    accountSo.name = accountSo.name.replaceall('"','');
                if(accountSo.Subject__c !=null && accountSo.Subject__c.length() > 0) 
                    accountSo.Subject__c = accountSo.Subject__c.replaceall('"',''); 
                if(accountSo.Revocation_Verification__c !=null && accountSo.Revocation_Verification__c.length() > 0) 
                    accountSo.Revocation_Verification__c = accountSo.Revocation_Verification__c.replaceall('"','');        
                if(accountSo.X_509_Certificate_PEM__c!=null && accountSo.X_509_Certificate_PEM__c.length() > 0) 
                    accountSo.X_509_Certificate_PEM__c= accountSo.X_509_Certificate_PEM__c.replaceall('"','');  
            }
        }
    }
    
         
   String sfdcBaseURL = '';
   
   // Get the base URL to build record urls 
    public String getsfdcBaseURL() {
        
        sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();       
        return sfdcBaseURL;
    }
}