objects/Account.object
<CustomObject>
    <fields>
        <fullName>Alternate_CRL__c</fullName>
        <inlineHelpText>Only fill this in if this certificate does not contain a CRL URL.</inlineHelpText>
        <label>Alternate CRL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CRL_URL_s__c</fullName>
        <inlineHelpText>URL(s) at which the CRL(s) may be obtained -- for end-entity certs and for intermediate CAs.</inlineHelpText>
        <label>CRL URL(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Serial_Number__c</fullName>
        <label>Certificate Serial Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_of_Revocation__c</fullName>
        <label>Date of Revocation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OneCRL_Bug_Number__c</fullName>
        <label>OneCRL Bug Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OneCRL_Status__c</fullName>
        <label>OneCRL Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to Add</fullName>
                </value>
                <value>
                    <fullName>Added to OneCRL</fullName>
                </value>
                <value>
                    <fullName>Cert Expired</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFC_5280_Revocation_Reason_Code__c</fullName>
        <inlineHelpText>Provide the reason for the certificate revocation. Value 7 is not being used.</inlineHelpText>
        <label>RFC 5280 Revocation Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>(0) unspecified</fullName>
                </value>
                <value>
                    <fullName>(1) keyCompromise</fullName>
                </value>
                <value>
                    <fullName>(2) cACompromise</fullName>
                </value>
                <value>
                    <fullName>(3) affiliationChanged</fullName>
                </value>
                <value>
                    <fullName>(4) superseded</fullName>
                </value>
                <value>
                    <fullName>(5) cessationOfOperation</fullName>
                </value>
                <value>
                    <fullName>(6) certificateHold</fullName>
                </value>
                <value>
                    <fullName>(8) removeFromCRL</fullName>
                </value>
                <value>
                    <fullName>(9) privilegeWithdrawn</fullName>
                </value>
                <value>
                    <fullName>(10) aACompromise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_YYYY_MMM_DD__c</fullName>
        <description>This formula field converts regular date field to display date in YYYY MMM DD format. Eg: &quot;7/9/1999&quot; shows as &quot;1999 Jul 09&quot;</description>
        <formula>IF ( NOT ISBLANK(Valid_To_GMT__c),

TEXT(YEAR(Valid_To_GMT__c)) &amp; &quot; &quot; &amp;

CASE(MONTH(Valid_To_GMT__c),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
NULL) &amp; &quot; &quot; &amp;

IF (LEN(TEXT(DAY(Valid_To_GMT__c))) = 1,&quot;0&quot; &amp; TEXT(DAY(Valid_To_GMT__c)),TEXT(DAY(Valid_To_GMT__c))),

NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid To [GMT]</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IntermediateCertsInOneCRLController.cls
/*******************************************************************************************************
 Name: IntermediateCertsInOneCRLController

 Dependencies: IntermediateCertsInOneCRLController, IntermediateCertsInOneCRLReport vf page,
 IntermediateCertsInOneCRLReportCSV vf page, IntermediateCertsInOneCRLControllerTest

 Description: This report generates list of intermediate certs which are in OneCRL.

 Instructions: None

 *******************************************************************************************************
 Revision History:
 
     11/19/2019 - Created new

 ******************************************************************************************************/
 
public class IntermediateCertsInOneCRLController{

    public transient List<Account> accountSoLst {get;set;}
    public List<wrapperAccount> lstWrapperAccountSO {get; set;} 
 
    //constructor method for standard controller
    public IntermediateCertsInOneCRLController() { 
    
        lstWrapperAccountSO = new List<wrapperAccount>();   
    
        accountSoLst = [SELECT Name, CA_Owner__c, Parent.Name, Record_Type_Name__c, 
                                        Certificate_Serial_Number__c, SHA_256_Fingerprint__c, 
                                        RFC_5280_Revocation_Reason_Code__c,
                                        Revocation_Status__c, Date_of_Revocation__c,
                                        Valid_To_GMT__c, Valid_To_YYYY_MMM_DD__c, CRL_URL_s__c, Alternate_CRL__c, 
                                        OneCRL_Bug_Number__c, Comments__c 
                                 FROM Account 
                                 WHERE Name != '<Fill in Cert Name>'
                                 AND   Record_Type_Name__c = 'Intermediate Certificate'
                                 AND   OneCRL_Status__c = 'Added to OneCRL'
                                 ORDER BY CA_Owner__c];  
                             
                             
         
        // if we are generating a CSV file then we need to replace the double quotes in all text fields with null
        // if((ApexPages.currentPage().getUrl().contains('CSV') && accountSoLst !=null && accountSoLst.size() > 0) || Test.IsRunningTest())
         if((Test.isRunningTest() || (ApexPages.currentPage().getUrl() != null && ApexPages.currentPage().getUrl().contains('CSV'))) && accountSoLst !=null && accountSoLst.size() > 0)       
         {
            for(Account accountSo : accountSoLst)
            {
                wrapperAccount objWrap = new wrapperAccount();
                
                if(accountSo.Name !=null && accountSo.Name.length() > 0) 
                    accountSo.Name = accountSo.Name.replace('"','');  
                if(accountSo.Parent.Name !=null && accountSo.Parent.Name.length() > 0) 
                    accountSo.Parent.Name = accountSo.Parent.Name.replace('"','');                  
                if(accountSo.CA_Owner__c!=null && accountSo.CA_Owner__c.length() > 0) 
                    accountSo.CA_Owner__c= accountSo.CA_Owner__c.replace('"',''); 
                if(accountSo.CRL_URL_s__c !=null && accountSo.CRL_URL_s__c.length() > 0) 
                    accountSo.CRL_URL_s__c= accountSo.CRL_URL_s__c.replace('"',''); 
                if(accountSo.Alternate_CRL__c !=null && accountSo.Alternate_CRL__c.length() > 0) 
                    accountSo.Alternate_CRL__c= accountSo.Alternate_CRL__c.replace('"','');                                                
                if(accountSo.Comments__c !=null && accountSo.Comments__c.length() > 0) 
                    accountSo.Comments__c= accountSo.Comments__c.replace('"','');  
                    
                // convert date fields for CSV file    
                objWrap.objaccountSO = accountSo;
                string dateformat ='MM/dd/yyyy';
                
                if(accountSo.Valid_To_GMT__c != null) {
                    objWrap.VTGMTdate = DateTime.NewInstance(accountSo.Valid_To_GMT__c.year(),
                                                          accountSo.Valid_To_GMT__c.month(),
                                                          accountSo.Valid_To_GMT__c.day()).format(dateformat);
                }
                
                if(accountSo.Date_of_Revocation__c != null) {
                    objWrap.DRdate = DateTime.NewInstance(accountSo.Date_of_Revocation__c.year(),
                                                          accountSo.Date_of_Revocation__c.month(),
                                                          accountSo.Date_of_Revocation__c.day()).format(dateformat);                                                                                  
                 }
                 
                 lstWrapperAccountSO.add(objWrap); 
           } 
        }
    }
     
    String CurrentDate = ' ';
    // Get current Datetime in long date format   
    public String getCurrentDate() {
        Datetime cDT = System.now();
        CurrentDate = cDT.format('MMMM d, yyyy');
        
        return CurrentDate;
    }
    
    public class wrapperAccount {
    
        public Account objaccountSO {get; set;}        
        public string DRdate {get;set;} 
        public string VTGMTdate {get;set;}      
        
        public wrapperAccount(){
            objaccountSO = new Account();
            DRdate = '';
            VTGMTdate = '';
        } 
    }          
}