objects/Account.object
<CustomObject>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Friendly_Name__c</fullName>
        <label>Friendly Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Valid_From_YYYY_MMM_DD__c</fullName>
        <description>This formula field converts regular date field to display date in YYYY MMM DD format. Eg: &quot;7/9/1999&quot; shows as &quot;1999 Jul 09&quot;</description>
        <formula>IF ( NOT ISBLANK(Valid_From_GMT__c), 

TEXT(YEAR(Valid_From_GMT__c)) &amp; &quot; &quot; &amp;

CASE(MONTH(Valid_From_GMT__c),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
NULL) &amp; &quot; &quot; &amp;
 
IF (LEN(TEXT(DAY(Valid_From_GMT__c))) = 1,&quot;0&quot; &amp; TEXT(DAY(Valid_From_GMT__c)),TEXT(DAY(Valid_From_GMT__c))),

NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid From [GMT]</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_To_YYYY_MMM_DD__c</fullName>
        <description>This formula field converts regular date field to display date in YYYY MMM DD format. Eg: &quot;7/9/1999&quot; shows as &quot;1999 Jul 09&quot;</description>
        <formula>IF ( NOT ISBLANK(Valid_To_GMT__c),

TEXT(YEAR(Valid_To_GMT__c)) &amp; &quot; &quot; &amp;

CASE(MONTH(Valid_To_GMT__c),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
NULL) &amp; &quot; &quot; &amp;

IF (LEN(TEXT(DAY(Valid_To_GMT__c))) = 1,&quot;0&quot; &amp; TEXT(DAY(Valid_To_GMT__c)),TEXT(DAY(Valid_To_GMT__c))),

NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid To [GMT]</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AllRootAndInterCertsReportCtlrForMSFT.cls
/*******************************************************************************************************
 Name: AllRootAndInterCertsReportCtlrForMSFT

 Dependencies: AllRootAndInterCertsReportCtlrForMSFT controller class, 
 AllRootAndInterCertsReportCtlrForMSFT vf page, AllRootAndInterCertsRepCtlrForMSFTTest test class

 Description: This is a controller class for a report which lists all Root and Intermediate Certs in
 CCADB.
 
 Instructions:    
 *******************************************************************************************************
 Revision History:
 
     3/1/2017 - Created new class
 ******************************************************************************************************/
public class AllRootAndInterCertsReportCtlrForMSFT {

    public transient List<Account> accountSoLst {get;set;}
 
    //constructor method for standard controller
    public AllRootAndInterCertsReportCtlrForMSFT() {   
                                          
           accountSoLst =  [select  Name, 
                                    Type,                                    
                                    CA_Owner__c, 
                                    Friendly_Name__c, 
                                    SHA_1_Fingerprint__c, 
                                    SHA_256_Fingerprint__c,
                                    Valid_From_YYYY_MMM_DD__c, 
                                    Valid_To_YYYY_MMM_DD__c, 
                                    Microsoft_Status__c,  
                                    Revocation_Status__c,
                                    Parent.Name, 
                                    Parent.SHA_1_Fingerprint__c,
                                    Parent.SHA_256_Fingerprint__c
                            from  Account
                            where 
                            RecordType.Name In ('Root Certificate','Intermediate Certificate')
                            order by CA_Owner__c, Type, Name];
 
      /***                                
       // if we are generating a CSV file then we need to replace the double quotes in all text fields with null
       if(ApexPages.currentPage().getUrl().contains('CSV') && accountSoLst !=null && accountSoLst.size() > 0)
       {
          for(Account accountSo : accountSoLst)
          {
             if(accountSo.name !=null && accountSo.name.length() > 0) 
                   accountSo.name = accountSo.name.replace('"',''); 
              if(accountSo.parent.name !=null && accountSo.parent.name.length() > 0) 
                   accountSo.parent.name = accountSo.parent.name.replace('"',''); 
              if(accountSo.Friendly_Name__c !=null && accountSo.Friendly_Name__c.length() > 0) 
                   accountSo.Friendly_Name__c = accountSo.Friendly_Name__c.replace('"','');            
          }
       } ***/
     }
     
     String CurrentDate = ' ';
 
    // Get current Datetime in long date format   

    public String getCurrentDate() {

      Datetime cDT = System.now();
      CurrentDate = cDT.format('MMMM d, yyyy');

      return CurrentDate;

   }

     
  }