objects/Account.object
<CustomObject>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mozilla_Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>Information verification phases</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Root_Case__c.object
<CustomObject>
    <fields>
        <fullName>Apply_BR_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BR Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_EV_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EV SSL Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_EV_Code_Signing_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EV Code Signing Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_Standard_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CA_Owner_Name_Existing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Previously called Included CA Owner Name</description>
        <label>CA Owner Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Owner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Root Cases</relationshipLabel>
        <relationshipName>Root_Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_No__c</fullName>
        <label>Case No</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Root Cases</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mozilla_Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Root_Certificate_Name_Existing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Previously called Included Certificate Name</description>
        <inlineHelpText>The Root Certificate that this Root Case applies to.</inlineHelpText>
        <label>Certificate Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Root</value>
            </filterItems>
            <filterItems>
                <field>Account.Parent.Id</field>
                <operation>equals</operation>
                <valueField>$Source.CA_Owner_Name_Existing__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Root Cases (Included Certificate)</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <label>Root Case</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Root Case No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AddUpdateAuditRootCaseController.cls
/*
    Description: This class is created for Audit Cases intermediate page. When a user needs to add a new 
    root case an intermediate page display all root certifcates for user to select and edit fields
*/
public with sharing class AddUpdateAuditRootCaseController {
    
    Id caseOwnerId;
    public Case objCase;
    public boolean isCaseCompleted {get; set;}
    
    public List<WrapperRootCases> lstWrapAllRootCases{get; set;}
    
    public AddUpdateAuditRootCaseController(Apexpages.standardcontroller controller) {
        caseOwnerId = controller.getId();
        isCaseCompleted = false;
        lstWrapAllRootCases = new List<WrapperRootCases>();
        List<Case> lstCases = new List<Case>([select Id,AccountId,CaseNumber,Account.Name,Request_Status__c from Case Where Id =: caseOwnerId]);
        
        //get record type id for root cases
        String RCAuditUpdateRTId = ''; 
        if(Schema.SObjectType.Root_Case__c.getRecordTypeInfosByName().get('CA Audit Update Request') != null){
            RCAuditUpdateRTId = Schema.SObjectType.Root_Case__c.getRecordTypeInfosByName().get('CA Audit Update Request').getRecordTypeId();
        }
        if(lstCases.size() > 0) {
            objCase = lstCases[0];
            if(objCase.Request_Status__c == 'Complete') {
                isCaseCompleted = true;
            }
            map<Id,Root_Case__c> mapExistingRootCases = new map<Id,Root_Case__c>();
            
            //fill map to find existing root cases.
            for(Root_Case__c rc: [Select Id, Root_Certificate_Name_Existing__c, Request_Status__c,
                                         Apply_Standard_Audit__c, Apply_BR_Audit__c, Apply_EV_Audit__c, Apply_EV_Code_Signing_Audit__c,
                                         Mozilla_Status__c, Microsoft_Status__c, SHA_256_Fingerprint__c
                                  from   Root_Case__c Where Case_No__c =: objCase.Id]){
                mapExistingRootCases.put(rc.Root_Certificate_Name_Existing__c,rc);
            }
            
            //loop on all root certificates. 
            for(Account objAccount: [select Id, Name, Status__c, Microsoft_Status__c, SHA_256_Fingerprint__c from 
                            Account Where Type = 'Root' and ParentId =: objCase.AccountId And (Status__c in ('Included','Change Requested') or
                            Microsoft_Status__c In ('Included','Change Requested')) Order By Name]){
                Root_Case__c objRC = new Root_Case__c();
                //boolean isDisable = false;
                boolean isReadOnly = false;
                boolean isSelected = false;
                objRC.Case_No__c = objCase.Id;
                //if existing root case found, disable select option and copy values from existing root cases
                if(mapExistingRootCases.containskey(objAccount.Id)) {
                    objRC = mapExistingRootCases.get(objAccount.Id);
                    if(objRC.Request_Status__c != 'Initial Request Received') {
                        isReadOnly = true;
                    }
                    isSelected = true;
                } else {
                    //for new root certificates
                    objRC.CA_Owner_Name_Existing__c = objCase.AccountId;
                    if(string.isnotblank(RCAuditUpdateRTId)){
                        objRC.RecordTypeId = RCAuditUpdateRTId;
                    }
                    objRC.Root_Certificate_Name_Existing__c = objAccount.Id;
                    // objRC.Apply_Standard_Audit__c = true; do not set default
                }
                lstWrapAllRootCases.add(new WrapperRootCases(isSelected ,isReadOnly ,objRC,objAccount));
            }
        }
    }
    
    //method is used to upsert root cases based on selected root certificates
    public PageReference NextToRootCase(){
        List<Root_Case__c> lstRootCasesToUpsert = new List<Root_Case__c>();
        List<Root_Case__c> lstRootCasesToDelete = new List<Root_Case__c>();
        for(WrapperRootCases objWrap: lstWrapAllRootCases){
            if(objWrap.objRootCase.Apply_Standard_Audit__c || objWrap.objRootCase.Apply_BR_Audit__c ||
                objWrap.objRootCase.Apply_EV_Audit__c || objWrap.objRootCase.Apply_EV_Code_Signing_Audit__c){
                lstRootCasesToUpsert.add(objWrap.objRootCase);
            } else if(objWrap.objRootCase.Id != null) {
                lstRootCasesToDelete.add(objWrap.objRootCase);
            }
        }
        try {
            if(lstRootCasesToUpsert.size() > 0) {
                upsert lstRootCasesToUpsert; // update or insert root case if any Apply field has changed
                ApexPages.AddMessage( new ApexPages.Message( ApexPages.Severity.CONFIRM, 'Root Cases created Successfully.'));
            } else {
                ApexPages.AddMessage( new ApexPages.Message( ApexPages.Severity.Error, 'Please select at least one root certificate to create Root case.'));
                return null;
            }
            if(lstRootCasesToDelete.size() > 0){
                delete lstRootCasesToDelete;  // delete root case if all Apply fields are unchecked
            }
        } catch (Exception ex){
            Apexpages.addMessages(ex);
            return null;
        }
        
        PageReference pg = new Pagereference('/'+objCase.Id);
        pg.setReDirect(true);
        return pg;
    }
    
    //wrapper class for displaying root certificates 
    public class WrapperRootCases {
        public boolean isSelected {get; set;} // For Action column NOT BEING USED 
        //public boolean isDisabled {get; set;}
        public boolean isReadOnly {get; set;}  // depends on Request Status
        public Root_Case__c objRootCase {get; set;} // for Root Case fields
        public Account objAccount {get; set;}  // for account fields like SHA-1 etc
        public WrapperRootCases(boolean isSel, boolean isRead, Root_Case__c objRC, Account objAcc){
            this.isSelected = isSel;
            this.isReadOnly = isRead;
            this.objRootCase = objRC;
            this.objAccount = objAcc;
        }        
    }
    
    
}