objects/Account.object
<CustomObject>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Verification__c</fullName>
        <inlineHelpText>Output from Verify Revocation check</inlineHelpText>
        <label>Revocation Verification</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Root_Cert_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is populated by PublicAllIntermediateCerts batch program for all intermediate cert records.</inlineHelpText>
        <label>Root Cert Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InterCertsRevokedReportForMSFTCtrlTest.cls
/*******************************************************************************************************
 Name: InterCertsRevokedReportForMSFTCtrlTest

 Dependencies: InterCertsRevokedReportForMSFTCtrl, InterCertsRevokedReportForMSFTCSV vf page,
 InterCertsRevokedReportForMSFTCtrlTest

 Description: This is a test class is for InterCertsRevokedReportForMSFTCtrl class. 
 This report generates list of intermediate certs which are revoked for Microsoft.

 Instructions: None

 *******************************************************************************************************
 Revision History:
 
     11/15/2019 - Created new

 ******************************************************************************************************/
@isTest
public with sharing class InterCertsRevokedReportForMSFTCtrlTest {
    static testmethod void TestReport() {
        Account caOwnerAcc = TestUtils.getCAOwner();
        insert caOwnerAcc;
        
        //create root certs
        Account rootAccount = TestUtils.getRootCertificate(caOwnerAcc.id);
        rootAccount.Name = 'child root account 1';       
        rootAccount.Microsoft_Status__c = 'Included';
        rootAccount.SHA_1_Fingerprint__c = '0001';
        rootAccount.SHA_256_Fingerprint__c = '00256';
        insert rootAccount;
 
        //create intermediate certs
        Account intermediatecert = TestUtils.getIntermediateCertificate(rootAccount.Id);
        intermediatecert.Name = 'Test Intermediate Cert 1';
        intermediatecert.Revocation_Status__c = 'Revoked';
        intermediatecert.Root_Cert_Id__c = rootAccount.id;
        intermediatecert.SHA_256_Fingerprint__c = '256';
        intermediatecert.X_509_Certificate_PEM__c = 'ABC';
        intermediatecert.Revocation_Verification__c = 'Verified';
        insert intermediatecert;
        
        //create intermediate certs
        Account intermediatecert2 = TestUtils.getIntermediateCertificate(rootAccount.Id);
        intermediatecert2.Name = 'Test Intermediate Cert 2';
        intermediatecert2.Revocation_Status__c = 'Not Revoked';       
        intermediatecert2.Root_Cert_Id__c = rootAccount.id;
        intermediatecert2.X_509_Certificate_PEM__c = 'XYZ';
        intermediatecert2.SHA_256_Fingerprint__c = '000256';
        intermediatecert2.Revocation_Verification__c = 'Verified';
        insert intermediatecert2;
        
        Test.startTest();
        
        InterCertsRevokedReportForMSFTCtrl controller = new InterCertsRevokedReportForMSFTCtrl ();
        controller.getsfdcBaseURL();
        
        Test.stopTest();
    }
}