objects/Account.object
<CustomObject>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mozilla_Root_Status__c</fullName>
        <inlineHelpText>This is Root Status on Intermediate Cert, updated via batch program</inlineHelpText>
        <label>Mozilla Root Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit_ALV_Found_Cert__c</fullName>
        <inlineHelpText>FAIL means that this certificate&apos;s SHA-256 thumbprint was NOT found in the audit statement.</inlineHelpText>
        <label>Standard Audit ALV Found Cert</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technically_Constrained__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Technically Constrained</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ICFailedALVResultsControllerTest.cls
/*******************************************************************************************************
 Name: ICFailedALVResultsControllerTest

 Dependencies: ICFailedALVResultsController class, ICFailedALVResultsControllerTest
 test class, AllCAAIdentifiersReportController vf page

 Description: This is a test class for ICFailedALVResultsController. Report lists 
 Failed ALV Intermediate certs.
 
 Instructions: None   
 *******************************************************************************************************
 Revision History:
 
     5/22/2020- Created new class
 ******************************************************************************************************/     

@isTest 
public class ICFailedALVResultsControllerTest {

    static testMethod void validateTest() {
        
        Account caOwner = TestUtils.getCAOwner();
        insert caOwner;
        
        Account rootCert = TestUtils.getRootCertificate(caOwner.Id);
        rootCert.Status__c = 'Included';
        insert rootCert;
        
        Account interCert = TestUtils.getIntermediateCertificate(rootCert.Id);
        interCert.Revocation_Status__c = 'Not Revoked';
        interCert.Standard_Audit_ALV_Found_Cert__c = 'FAIL';
        interCert.Technically_Constrained__c = FALSE;
        interCert.Mozilla_Root_Status__c = 'Included';
        insert interCert;
        
        Account interCert1 = TestUtils.getIntermediateCertificate(interCert.Id);
        interCert1.Revocation_Status__c = 'Not Revoked';
        interCert1.Standard_Audit_ALV_Found_Cert__c = 'FAIL';
        interCert1.Technically_Constrained__c = FALSE;
        interCert1.Audits_Same_as_Parent__c = true;
        interCert1.Mozilla_Root_Status__c = 'Included';
        insert interCert1;
        
        ICFailedALVResultsController controller = new ICFailedALVResultsController();
        controller.getCurrentDate();
    }
}