objects/Account.object
<CustomObject>
    <fields>
        <fullName>Approval_Bug__c</fullName>
        <label>Mozilla Approval Bug</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Email_Alias_1__c</fullName>
        <inlineHelpText>CA Email Alias 1 and 2 are used to reach more than one person in your organization tol receive notifications in case the primary contact is out of the office or leaves the organization.</inlineHelpText>
        <label>CA Email Alias 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CA_Email_Alias_2__c</fullName>
        <inlineHelpText>CA Email Alias 1 and 2 are used to reach more than one person in your organization tol receive notifications in case the primary contact is out of the office or leaves the organization.</inlineHelpText>
        <label>CA Email Alias 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Company_Website__c</fullName>
        <inlineHelpText>Website URL</inlineHelpText>
        <label>Company Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Geographic_Focus__c</fullName>
        <label>Geographic Focus</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Case_No__c</fullName>
        <inlineHelpText>Updated by Sync process</inlineHelpText>
        <label>Last Sync Case No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Date_Time__c</fullName>
        <inlineHelpText>Updated by Sync process</inlineHelpText>
        <label>Last Sync Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Organizational_Type__c</fullName>
        <inlineHelpText>Indicate the type of organization operating this CA.</inlineHelpText>
        <label>Organizational Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Private Corporation</fullName>
                </value>
                <value>
                    <fullName>Public Corporation</fullName>
                </value>
                <value>
                    <fullName>Government Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Organization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Market_Customer_Base__c</fullName>
        <inlineHelpText>Indicates what types of customers does the CA serve?
Are there particular vertical market segments in which it operates?
Does the CA focus its activities on a particular country or other geographic region?</inlineHelpText>
        <label>Primary Market / Customer Base</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Problem_Reporting_Mechanism__c</fullName>
        <inlineHelpText>Email address or URL for reporting suspected Private Key Compromise, Certificate misuse, or other types of fraud, compromise, misuse, inappropriate conduct, or any other matter related to Certificates.</inlineHelpText>
        <label>Problem Reporting Mechanism</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recognized_CAA_Domains__c</fullName>
        <inlineHelpText>Certification Authority Authorization (CAA) domain names recognized in a CAA record&apos;s issue and issue wild property tags. Comma-separated list.</inlineHelpText>
        <label>Recognized CAA Domains</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CA_Email_Alias_1__c</fullName>
        <inlineHelpText>CA Email Alias 1 and 2 is needed so that more than one person in your organization will receive notifications in case the primary contact is out of the office or leaves the organization.</inlineHelpText>
        <label>CA Email Alias 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Website__c</fullName>
        <defaultValue>&quot;http://NEED: URL to company website&quot;</defaultValue>
        <description>Website URL</description>
        <inlineHelpText>Website URL</inlineHelpText>
        <label>Company Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geographic_Focus__c</fullName>
        <defaultValue>&quot;NEED: Country or geographic region where CA typically sells certs.&quot;</defaultValue>
        <label>Geographic Focus</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Date_Time__c</fullName>
        <inlineHelpText>Updated by Sync process</inlineHelpText>
        <label>Last Sync Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Link_to_Bugzilla_Bug__c</fullName>
        <inlineHelpText>Link to Bugzilla case request</inlineHelpText>
        <label>Link to Bugzilla Bug</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Organizational_Type__c</fullName>
        <inlineHelpText>Indicate the type of organization operating this CA.</inlineHelpText>
        <label>Organizational Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Private Corporation</fullName>
                </value>
                <value>
                    <fullName>Public Corporation</fullName>
                </value>
                <value>
                    <fullName>Government Agency</fullName>
                </value>
                <value>
                    <fullName>Non-Profit Organization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Market_Customer_Base__c</fullName>
        <defaultValue>&quot;NEED:&quot; + BR() + 
&quot;- Which types of customers does the CA serve? &quot; + BR() + 
&quot;- Are there particular vertical market segments in which it operates? &quot; + BR() + 
&quot;- Does the CA focus its activities on a particular country or other geographic region?&quot;</defaultValue>
        <inlineHelpText>Which types of customers does the CA serve?
Are there particular vertical market segments in which it operates?
Does the CA focus its activities on a particular country or other geographic region?</inlineHelpText>
        <label>Primary  Market / Customer Base</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Problem_Reporting_Mechanism__c</fullName>
        <defaultValue>IF ($RecordType.Name = &quot;CA Root Inclusion Request&quot;, 
&quot;NEED: An email address (that the CA closely monitors) for reporting suspected Private Key Compromise, Certificate misuse, or other types of fraud, compromise, or any other matter related to certificates.&quot;, 
&quot;&quot;)</defaultValue>
        <inlineHelpText>Email address or URL for reporting suspected Private Key Compromise, Certificate misuse, or other types of fraud, compromise, misuse, inappropriate conduct, or any other matter related to Certificates.</inlineHelpText>
        <label>Problem Reporting Mechanism</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recognized_CAA_Domains__c</fullName>
        <defaultValue>IF ($RecordType.Name = &quot;CA Root Inclusion Request&quot;, 
&quot;NEED: Domain names that the CA recognizes in Certification Authority Authorization (CAA) \&quot;issue\&quot; and \&quot;issuewild\&quot; records as permitting it to issue. Comma-separated list.&quot;, 
&quot;&quot;)</defaultValue>
        <inlineHelpText>Certification Authority Authorization (CAA) domain names recognized in a CAA record&apos;s issue and issuewild property tags. Comma-separated list.</inlineHelpText>
        <label>Recognized CAA Domains</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>Information verification phases</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Root_Case__c.object
<CustomObject>
    <fields>
        <fullName>Case_No__c</fullName>
        <label>Case No</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Root Cases</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Date_Time__c</fullName>
        <inlineHelpText>Updated by Sync process</inlineHelpText>
        <label>Last Sync Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Root Case</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Root Case No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SyncParentAccountFromInclusionCaseCtrl.cls
/*******************************************************************************************************
 Name: SyncParentAccountFromInclusionCaseCtrl

 Dependencies: SyncParentAccountFromInclusionCaseCtrl controller class, SyncParentAccountFromInclusionCase 
 vf page, SyncParentAccountFromIncluCaseCtrlTest, SyncRootAccountFromInclusionCaseCtrl, 
 SyncRootAccountFromInclusionCase vf page, SyncRootAccountFromInclusionCaseCtrlTest

 Description: This is the controller class for the SyncParentAccountFromInclusionCase VF page.
 When the "Sync MozillaRootInclusionInfo" button is clicked from any from Case page for Record Type 
 'CA Root Inclusion Request' type "Case", the user is redirected to SyncParentAccountFromInclusionCase VF page. 
 
 Here the user has options to update two sets of records CA Owner record and Root Certificate record: 
 1. Update the displayed fields from the Case record to the Parent Account (or the CA Owner).     
    AND
 2. Update and iterate through the Root Case records which are associated with this Case and
    allow user to update assiciated Root Certificate record on Account.
        
 Sync can be done for CA Owner, Auditor, Audit, CP/CPS, Test Websites fields when data is "Data Verified"
 and Case Status is at any stage.
  
 Mozilla fields can only be synced when Case.Request Status is 'Complete' or 'Included or Pending EV'.
 
 Parent Account (CA Owner) Status is set to 'Included' only if all related Cases are 'Complete' or 'Included, Pending EV'
     
 Instructions: None   
 *******************************************************************************************************
 Revision History:
 
     10/15/2018    Created new class
     6/13/2019     Updated program to reate cseparate sections for auditor, audit, cp/cps fields and 
                   allow users to copy individual sections
 ******************************************************************************************************/

global with sharing class SyncParentAccountFromInclusionCaseCtrl {

    // flag that indicates whether the record was updated. 
    // the next actions that a user could perform are presented on the screen based on the value of this flag
    Boolean isRecordUpdated=false;
   
    // flag that indicates whether the user rejected to update the parent account
    // the next actions that a user could perform are presented on the screen based on the value of this flag
    Boolean isUpdateCancelled=false; 
    
    // object that holds all the details which are fetched using SOQL
    private Case caseDetailsSo;
   
    // the parent account object which is associated with the root case.
    private Account parentAccountSo;   
     
    // boolean flag to check whether the request status is complete or not
    // if the flag is set as true then we do not allow the user to proceed
    // with the sync process, instead we display a message to the user.
    public Boolean isRequestStatusIncludedOrComplete {get;set;}
    
    // constructor method for standard controller
    public SyncParentAccountFromInclusionCaseCtrl(ApexPages.StandardController stdController) {
         
         // query all the details for this record  
         caseDetailsSo = [select AccountId, CaseNumber, CA_Email_Alias_1__c, Link_to_Bugzilla_Bug__c, 
         Company_Website__c, Organizational_Type__c, Geographic_Focus__c, Primary_Market_Customer_Base__c, Request_Status__c, Status,
         Recognized_CAA_Domains__c,Problem_Reporting_Mechanism__c, Street__c, City__c, State__c, Zip_Postal_Code__c, Country__c
         from Case where id = :stdController.getId() limit 1];
         
         isRequestStatusIncludedOrComplete =false;
        
         //if(caseDetailsSo.request_status__c == 'Included, Pending EV'  || caseDetailsSo.request_status__c == 'Complete' ) {
         
             isRequestStatusIncludedOrComplete = true;
             // fetch all the root cases associated with the current case
             // get the parent account details 
             parentAccountSo = [select name, CA_Email_Alias_1__c, CA_Email_Alias_2__c,
                                   approval_bug__c, Organizational_Type__c, company_website__c,  
                                   Geographic_Focus__c, Primary_Market_Customer_Base__c, Status__c,Problem_Reporting_Mechanism__c,
                                   Last_Sync_Case_No__c, Last_Sync_Date_Time__c,Recognized_CAA_Domains__c,
                                   BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry
                                   from account where id =:caseDetailsSo.AccountId and type = 'Owner'];      
         //}
    }

   // update the parent account and redirect to same page showing that the record got updated successfully
   public PageReference syncAccount() {
   
        // if any additional fields need to be synced from case to parent account then 
        // those fields need to be added to this section
        
        this.parentAccountSo.type = 'Owner';
        this.parentAccountSo.Company_Website__c     = this.caseDetailsSo.Company_Website__c;
        this.parentAccountSo.CA_Email_Alias_1__c    = this.caseDetailsSo.CA_Email_Alias_1__c;
        this.parentAccountSo.Organizational_Type__c = this.caseDetailsSo.Organizational_Type__c;
        this.parentAccountSo.Geographic_Focus__c    = this.caseDetailsSo.Geographic_Focus__c;
        this.parentAccountSo.Primary_Market_Customer_Base__c = this.caseDetailsSo.Primary_Market_Customer_Base__c;
        this.parentAccountSo.Recognized_CAA_Domains__c = this.caseDetailsSo.Recognized_CAA_Domains__c;
        this.parentAccountSo.Problem_Reporting_Mechanism__c = this.caseDetailsSo.Problem_Reporting_Mechanism__c;
        
        if(this.caseDetailsSo.Street__c != null && this.caseDetailsSo.Street__c != '')
            this.parentAccountSo.BillingStreet = this.caseDetailsSo.Street__c;
        if(this.caseDetailsSo.City__c != null && this.caseDetailsSo.City__c != '')
            this.parentAccountSo.BillingCity = this.caseDetailsSo.City__c;
        if(this.caseDetailsSo.State__c != null && this.caseDetailsSo.State__c!= '')
            this.parentAccountSo.BillingState = this.caseDetailsSo.State__c;
        if(this.caseDetailsSo.Zip_Postal_Code__c != null && this.caseDetailsSo.Zip_Postal_Code__c != '')
            this.parentAccountSo.BillingPostalCode = this.caseDetailsSo.Zip_Postal_Code__c;
        if(this.caseDetailsSo.Country__c != null && this.caseDetailsSo.Country__c!= '')
            this.parentAccountSo.BillingCountry = this.caseDetailsSo.Country__c;
        
        this.parentAccountSo.Last_Sync_Case_No__c   = this.caseDetailsSo.CaseNumber;
        this.parentAccountSo.Last_Sync_Date_Time__c = System.now();
        
        // Set Parent Account = 'Included' only if all related Cases are 'Complete' or 'Included, Pending EV'
        
        Boolean areAllCasesComplete = true;
        
        for(Case caseSO: [select Request_Status__c from case where accountId = :caseDetailsSo.AccountId]) {
            if(caseSo.request_status__c != 'Complete' && caseSo.request_status__c != 'Included, Pending EV') {
             areAllCasesComplete = false;
            }
        }
        
        if(areAllCasesComplete) {
            this.parentAccountSo.status__c = 'Included' ; 
        }
        
        update parentAccountSo;
        
        // set the flag which would help to indicate the correct message on the page
        isRecordUpdated= true;
        
        // Lastly, set Sync execution date/time on Case record
        this.caseDetailsSo.Last_Sync_Date_Time__c = System.now();
        update caseDetailsSo;
        
        return null;
    }
    
    // if there is no root case then don't 
    // upon user confirmation redirect the user to the next step i.e. to sync the root account
    public PageReference redirectToSyncRootAccount() {
        
        Integer rootCaseCount = [SELECT count() 
                                FROM Root_case__c
                                WHERE case_no__c = :caseDetailsSo.id
                                AND request_status__c NOT IN ('On Hold','Denied')];
                              
        // if there are one or more root cases associated with the current case
        if(rootCaseCount > 0) {
            PageReference caseSoPageRef = new PageReference('/apex/SyncRootAccountFromInclusionCase?id=' +this.caseDetailsSo.id); 
            caseSoPageRef.setRedirect(true);
            return caseSoPageRef;
        }
        return null;
    }
    

  // if the user hits cancel redirect back to the root case
   public PageReference redirectToCase() {
        PageReference caseSoPageRef = new PageReference('/' +this.caseDetailsSo.id);
        caseSoPageRef.setRedirect(true);
        return caseSoPageRef;        
    }
    
  // when the user hits cancel redirect to the same page with the status in URL so that an acknowledgement message is shown to the user.
   public PageReference cancelSyncAccount() {
       isUpdateCancelled = true;
       return null;
    }
    
   public Case getCaseDetailsSo()   {  return this.caseDetailsSo;  }
    
   public Account getParentAccount()  {  return this.parentAccountSo; }
  
   public Boolean getIsRecordUpdated() { return this.isRecordUpdated;  }
     
   public Boolean getIsUpdateCancelled() { return this.isUpdateCancelled;  }
}