objects/Account.object
<CustomObject>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recognized_CAA_Domains__c</fullName>
        <inlineHelpText>Certification Authority Authorization (CAA) domain names recognized in a CAA record&apos;s issue and issue wild property tags. Comma-separated list.</inlineHelpText>
        <label>Recognized CAA Domains</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AllCAAIdentifiersReportController.cls
/*******************************************************************************************************
 Name: AllCAAIdentifiersReportController

 Dependencies: AllCAAIdentifiersReportController controller class, AllCAAIdentifiersReportControllerTest 
 test class, AllCAAIdentifiersReportController vf page

 Description: This is a controller for AllCAAIdentifiersReport VF page. Report lists Recognized CAA Domains
 info for all CA Owner and Intermediate Cert records.
 
 Instructions: None   
 *******************************************************************************************************
 Revision History:
 
     3/3/2018 - Created new class
 ******************************************************************************************************/

public class AllCAAIdentifiersReportController{

    public transient List<Account> accountSoLst {get;set;}
 
    // constructor method for standard controller
    public AllCAAIdentifiersReportController() {   
                                                                  
        List<Account> accSoLst =  [select Name, Parent.Name, Recognized_CAA_Domains__c from  Account
                    where (Status__c In ('Included','Change Requested','Provided by CA','Verified') or
                    Microsoft_Status__c In ('Included','Change Requested'))
                    and   RecordType.Name In ('CA Owner','Intermediate Certificate') and Name != '<Fill in Cert Name>'
                    order by Name]; 
        
        // filter records with non blank 'Recognized_CAA_Domains__c', which is long text field   
        accountSoLst = new List<Account>();          
        for(Account a : accSoLst)
        {
            if (a.Recognized_CAA_Domains__c != null && a.Recognized_CAA_Domains__c.length() > 0) {
                accountSoLst.add(a);
            }
        }                                                        
        
        // if we are generating a CSV file then we need to replace the double quotes in all text fields with null
        if((ApexPages.currentPage().getUrl().contains('CSV') && accountSoLst !=null && accountSoLst.size() > 0) || Test.IsRunningTest())
        {
            for(Account accountSo : accountSoLst)
            {
                if(accountSo.Name !=null && accountSo.Name.length() > 0) 
                    accountSo.Name = accountSo.Name.replace('"',''); 
                if(accountSo.Parent.Name !=null && accountSo.Parent.Name.length() > 0) 
                    accountSo.Parent.Name = accountSo.Parent.Name.replace('"','');          
                if(accountSo.Recognized_CAA_Domains__c !=null && accountSo.Recognized_CAA_Domains__c.length() > 0) 
                    accountSo.Recognized_CAA_Domains__c= accountSo.Recognized_CAA_Domains__c.replace('"','');                                                           
            }
        }     
    } 
         
    // Get current Datetime in long date format   
    public String getCurrentDate() {
    
        Datetime cDT = System.now();
        string CurrentDate = cDT.format('MMMM d, yyyy');
        
        return CurrentDate;
    
    }
    
}