objects/Account.object
<CustomObject>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CP_CPS_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if this cert does not have separate policy documentation from the parent cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if this cert does not have separate policy documentation from the parent cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>CP/CPS Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Certificate_Policy_CP__c</fullName>
        <description>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certificate Policy (CP)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certification_Practice_Statement_CPS__c</fullName>
        <description>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certification Practice Statement (CPS)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Firefox_Release_When_Removed__c</fullName>
        <label>Firefox Release When Removed</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSS_Release_When_Removed__c</fullName>
        <label>NSS Release When Removed</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Root_Cert_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is populated by PublicAllIntermediateCerts batch program for all intermediate cert records.</inlineHelpText>
        <label>Root Cert Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Standard Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Date__c</fullName>
        <description>Date Audit Statement Issued</description>
        <inlineHelpText>Date Audit Statement Issued</inlineHelpText>
        <label>Standard Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Type__c</fullName>
        <label>Standard Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 101 456</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 101 456</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies same logical certificates in different CA Hierarchies. SHA256(der(subject)+der(spki))</inlineHelpText>
        <label>Subject + SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CrossSignedRemovedRootsControllerTest.cls
/*******************************************************************************************************
 Name: CrossSignedRemovedRootsControllertest

 Dependencies: CrossSignedRemovedRootsController controller class, CrossSignedRemovedRootsControllerTest 
 test class, CrossSignedRemovedRootsReport vf page

 Description: This is a test class for CrossSignedRemovedRootsController which reports
 removed Root Certs followed by cross signed Intermediate Certs. Only the inter certs which are not 
 expired and their Revocation Status is not ‘Revoked’ or ‘Parent Cert Revoked’ are listed in the report.
 
 Instructions: None   
 *******************************************************************************************************
 Revision History:
 
     6/5/2018 - Created new class
 ******************************************************************************************************/
 
@isTest
public with sharing class CrossSignedRemovedRootsControllerTest {
    static testMethod void TestCrossSignedRemovedReport() {
    
        Account caOwnerAcc = TestUtils.getCAOwner();
        insert caOwnerAcc;
        
        Account rootAccount1 = TestUtils.getRootCertificate(caOwnerAcc.id);
        rootAccount1.Name = 'child root account 1';
        rootAccount1.Standard_Audit__c = 'https://std.com';
        rootAccount1.Standard_Audit_Type__c = 'WebTrust';
        rootAccount1.Standard_Audit_Statement_Date__c = system.today();
        rootAccount1.Standard_Audit_Period_Start_Date__c = system.today();
        rootAccount1.Standard_Audit_Period_End_Date__c = system.today();
        rootAccount1.Certificate_Policy_CP__c = 'https://cp.com';
        rootAccount1.Certification_Practice_Statement_CPS__c = 'https://cps.com';
        rootAccount1.Status__c = 'Removed';
        rootAccount1.Firefox_Release_When_Removed__c = 'V123';
        rootAccount1.NSS_Release_When_Removed__c = 'N123';
        rootAccount1.Subject_SPKI_SHA256__c = 'C90FBC2664485F6D3175055A45EF10D2EB6E6C7E027DF1A1D526458C42F42696';
        insert rootAccount1;
        
        Account rootAccount2 = TestUtils.getRootCertificate(caOwnerAcc.id);
        rootAccount2.Name = 'child root account 2';
        rootAccount2.Standard_Audit__c = 'https://std.com';
        rootAccount2.Standard_Audit_Type__c = 'WebTrust';
        rootAccount2.Standard_Audit_Statement_Date__c = system.today();
        rootAccount2.Standard_Audit_Period_Start_Date__c = system.today();
        rootAccount2.Standard_Audit_Period_End_Date__c = system.today();
        rootAccount2.Certificate_Policy_CP__c = 'https://cp.com';
        rootAccount2.Certification_Practice_Statement_CPS__c = 'https://cps.com';
        rootAccount2.Status__c = 'Included';
        rootAccount2.Firefox_Release_When_Removed__c = 'V123';
        rootAccount2.NSS_Release_When_Removed__c = 'N234';
        rootAccount2.Subject_SPKI_SHA256__c = 'XXXXC2664485F6D3175055A45EF10D2EB6E6C7E027DF1A1D526458C42F42696';
        insert rootAccount2;
        
        Account interCertAccount1 = TestUtils.getIntermediateCertificate(rootAccount1.id);
        interCertAccount1.Name = 'child Intercert account 1';
        interCertAccount1.Audits_Same_as_Parent__c = true;
        interCertAccount1.CP_CPS_Same_as_Parent__c = true;
        interCertAccount1.Valid_To_GMT__c = system.today().addYears(1);
        interCertAccount1.Revocation_Status__c = 'Not Revoked';
        interCertAccount1.Subject_SPKI_SHA256__c = 'C90FBC2664485F6D3175055A45EF10D2EB6E6C7E027DF1A1D526458C42F42696';
        interCertAccount1.Root_Cert_Id__c = rootAccount2.id; 
        insert interCertAccount1;
        
        CrossSignedRemovedRootsController controller = new CrossSignedRemovedRootsController();
    }
}