objects/Account.object
<CustomObject>
    <fields>
        <fullName>Approval_Bug__c</fullName>
        <label>Mozilla Approval Bug</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CRL_URL_s__c</fullName>
        <inlineHelpText>URL(s) at which the CRL(s) may be obtained -- for end-entity certs and for intermediate CAs.</inlineHelpText>
        <label>CRL URL(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Common_Name__c</fullName>
        <label>Certificate Issuer Common Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organization__c</fullName>
        <label>Certificate Issuer Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organizational_Unit__c</fullName>
        <label>Certificate Issuer Organizational Unit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Policy_CP__c</fullName>
        <description>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certificate Policy (CP)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Common_Name__c</fullName>
        <description>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</description>
        <inlineHelpText>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</inlineHelpText>
        <label>Certificate Subject Common Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Organization__c</fullName>
        <label>Certificate Subject Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certification_Practice_Statement_CPS__c</fullName>
        <description>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certification Practice Statement (CPS)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Firefox_Release_When_First_Included__c</fullName>
        <label>Firefox Release When First Included</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mozilla_Applied_Constraints__c</fullName>
        <label>Mozilla Applied Constraints</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NSS_Release_When_First_Included__c</fullName>
        <label>NSS Release When First Included</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OneCRL_Bug_Number__c</fullName>
        <label>OneCRL Bug Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OneCRL_Status__c</fullName>
        <label>OneCRL Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to Add</fullName>
                </value>
                <value>
                    <fullName>Added to OneCRL</fullName>
                </value>
                <value>
                    <fullName>Cert Expired</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PublicIntermediateCertsRevokedCtlrTest.cls
/**

Test Case for the following Controller Extension:
PublicIntermediateCertsRevokedController

**/

@isTest 
public class PublicIntermediateCertsRevokedCtlrTest{

    static testMethod void validateTest() {
        
        Account parentAccount = new Account();
        parentAccount.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('CA Owner').getRecordTypeID();
        parentAccount.name = 'ParentAccount';
        insert parentAccount;
        
        Account childAccount = new Account();
        childAccount.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Intermediate Certificate').getRecordTypeID();
        childAccount.name = 'ChildAccount';
        childAccount.Status__c = 'Included';
        childAccount.OneCRL_Status__c = 'Ready to Add';
        childAccount.Certificate_Issuer_Organization__c = 'Test IO';
        childAccount.Certificate_Issuer_Organizational_Unit__c = 'Test IOU';
        childAccount.Certificate_Issuer_Common_Name__c = 'Test CName';
        childAccount.Certificate_Subject_Common_Name__c = 'Test SName';
        childAccount.Certificate_Subject_Organization__c = 'Test OName';
        childAccount.OneCRL_Bug_Number__c = '123';
        childAccount.CRL_URL_s__c = 'Test URL';
        //childAccount.OCSP_URL_s__c = 'Test ';
        childAccount.Comments__c = 'Test Comment';
        childAccount.Approval_Bug__c = 'Test';
        childAccount.NSS_Release_When_First_Included__c = 'Test';
        childAccount.Firefox_Release_When_First_Included__c = 'Test';
        childAccount.Mozilla_Applied_Constraints__c = 'Test';
        childAccount.Certificate_Policy_CP__c = 'Test';
        childAccount.Certification_Practice_Statement_CPS__c = 'Test';
        childAccount.X_509_Certificate_PEM__c = 'Test';
        childAccount.Revocation_Status__c = 'Revoked';
        insert childAccount;

    
        PageReference pref = Page.PublicIntermediateCertsRevoked;
        Test.setCurrentPage(pref);
        
        PublicIntermediateCertsRevokedController pacrc = new PublicIntermediateCertsRevokedController();
        pacrc.getCurrentDate();
    }

}