objects/Account.object
<CustomObject>
    <fields>
        <fullName>ALV_Results__c</fullName>
        <label>ALV Results</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ALV_Status__c</fullName>
        <label>ALV Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auditor_New__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Name of Auditor who issued the standard audit statement. See &apos;List All Auditors&apos; below for choices. Send email to support@ccadb.org if your auditor is not listed.</inlineHelpText>
        <label>Auditor</label>
        <referenceTo>Auditor__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BR_Audit_ALV_Comments__c</fullName>
        <label>BR Audit ALV Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BR_Audit_ALV_Found_Cert__c</fullName>
        <inlineHelpText>FAIL means that this certificate&apos;s SHA-256 thumbprint was NOT found in the audit statement.</inlineHelpText>
        <label>BR Audit ALV Found Cert</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BR_Audit_ALV_Results__c</fullName>
        <label>BR Audit ALV Results</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BR_Audit_ALV_Status__c</fullName>
        <label>BR Audit ALV Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>BR Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Period_Start_Date__c</fullName>
        <description>Start date of the period of time of CA operations examined by the auditor.</description>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>BR Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Statement_Date__c</fullName>
        <description>Date BR Audit Statement Issued</description>
        <inlineHelpText>Date BR Audit Statement Issued</inlineHelpText>
        <label>BR Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Type__c</fullName>
        <label>BR Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BR_Audit__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>BR Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Owner_Certificate_No__c</fullName>
        <displayFormat>A{000000}</displayFormat>
        <externalId>true</externalId>
        <label>CA Owner/Certificate No</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_ALV_Comments__c</fullName>
        <label>Code Signing Audit ALV Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_ALV_Results__c</fullName>
        <label>Code Signing Audit ALV Results</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_ALV_Status__c</fullName>
        <label>Code Signing Audit ALV Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Period_End_Date__c</fullName>
        <description>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</description>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Code Signing Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Period_Start_Date__c</fullName>
        <description>Start date of the period of time of CA operations examined by the auditor.</description>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Code Signing Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Statement_Date__c</fullName>
        <description>Date Code Signing Audit Statement Issued</description>
        <inlineHelpText>Date Code Signing Audit Statement Issued</inlineHelpText>
        <label>Code Signing Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Type__c</fullName>
        <label>Code Signing Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit__c</fullName>
        <label>Code Signing Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_ALV_Processed__c</fullName>
        <inlineHelpText>Updated by system each time when ALV processing is completed.</inlineHelpText>
        <label>Date ALV Processed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit__c</fullName>
        <description>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>EV SSL Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_SSL_Audit_ALV_Comments__c</fullName>
        <label>EV SSL Audit ALV Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_SSL_Audit_ALV_Results__c</fullName>
        <label>EV SSL Audit ALV Results</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EV_SSL_Audit_ALV_Status__c</fullName>
        <label>EV SSL Audit ALV Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Extended_Key_Usage__c</fullName>
        <label>Extended Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_ALV_Comments__c</fullName>
        <label>Standard Audit ALV Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_ALV_Found_Cert__c</fullName>
        <inlineHelpText>FAIL means that this certificate&apos;s SHA-256 thumbprint was NOT found in the audit statement.</inlineHelpText>
        <label>Standard Audit ALV Found Cert</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_ALV_Results__c</fullName>
        <label>Standard Audit ALV Results</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_ALV_Status__c</fullName>
        <label>Standard Audit ALV Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Standard Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Date__c</fullName>
        <description>Date Audit Statement Issued</description>
        <inlineHelpText>Date Audit Statement Issued</inlineHelpText>
        <label>Standard Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Type__c</fullName>
        <label>Standard Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 101 456</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 101 456</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject_SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies same logical certificates in different CA Hierarchies. SHA256(der(subject)+der(spki))</inlineHelpText>
        <label>Subject + SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subordinate_CA_Owner__c</fullName>
        <inlineHelpText>Enter Subordinate CA’s name as it appears in the provided audit statements. Leave blank if BOTH control of the private key AND domain/IP/email validation activities are performed by the organization listed in the audit statement of the parent certificate.</inlineHelpText>
        <label>Subordinate CA Owner</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auditor__c.object
<CustomObject>
    <fields>
        <fullName>Alternate_Auditor_Name_s__c</fullName>
        <inlineHelpText>Names must be separated by semicolon &apos;;&apos;</inlineHelpText>
        <label>Alternate Auditor Name(s)</label>
        <type>TextArea</type>
    </fields>
    <label>Auditor</label>
    <nameField>
        <label>Auditor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auditors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RunALVonHierarchyController.cls
/*******************************************************************************************************
 Name: RunALVonHierarchyController

 Dependencies: RunALVonHierarchyController controller class, RunALVonHierarchy vf page, 
 RunALVonHierarchyControllerTest

 Description: This class is created to clear the ALV fields and run ALV on hierarchy from
 a button on root cert for all intermediate certs which have Audits Same As Parent set 
 to True. "Run ALV on Hierarchy" button on root cert page allows root store operators to
 rerun ALV for the certs which are in the hierarchy. One inter cert is sent to ALV for 
 processing at a time. It calls common methods from RunALVForInterCertsBatch.
 
 There is another process that is related to ALV processing on inter certs. When a user makes 
 changes to auditor or audit fields on root or intermediate certificate records, the account 
 trigger (UpdateALVDateProcessed method) will traverse down the hierarchy to clear all of the ALV 
 fields for child (grandchild, etc) records that have "Audits Same as Parent" (includes 
 expired and revoked). There are 3 ways ALV can be rerun for these certs:
 1. A nightly scheduled batch job "ALV Batch for Inter Certs" will automatically pick these
 inter certs and rerun ALV.
 2. A system admin can initiate "ALV Batch for Inter Certs" batch process anytime from 
 "Batch Processes" custom tab.
 3. "Use this "Run ALV on Hierarchy" process from a button on the root cert.

 Instructions: 

 *******************************************************************************************************
 Revision History:
 
     10/26/2019 - Created new 

 ******************************************************************************************************/
public with sharing class RunALVonHierarchyController {
    
    public boolean isRunALV {get; set;}
    public Id accid;
    
    public RunALVonHierarchyController(Apexpages.standardcontroller controller){
        isRunALV = false;
        accId = controller.getId();
    }
    
    public PageReference RunALVForChildAccounts(){
        try {
            isRunALV = true;
            List<string> lstInterCertId = new List<string>();
            if(accId != null){
            
                //query on all intermediate certs which has audits same parent is checked and 
                // fill map with key as parent id.
                
                map<Id, List<Account>> mapInterCertAccounts = new map<Id, List<Account>>();
                for(Account objAcc: [select Id, ParentId,Parent.Name, Name from Account Where RecordType.Name = 'Intermediate Certificate' 
                                        AND Audits_Same_as_Parent__c = true]){
                    if(mapInterCertAccounts.containskey(objAcc.ParentId)){
                        mapInterCertAccounts.get(objAcc.ParentId).add(objAcc);
                    } else {
                        mapInterCertAccounts.put(objAcc.ParentId, new List<Account>{objAcc});
                    }
                }
                
                List<Account> lstAccToUpdate = new List<Account>();
                set<Id> setofAccountIdsToUpdate = new set<Id>();
                set<Id> setOfIdsToCheckChild = new set<Id>();
                setOfIdsToCheckChild.add(accId);
                
                //do while loop to get child and grand childs (n level) with audit same as parent is 
                // checked and clears ALV fields and add in list to update
                while(setOfIdsToCheckChild.size() > 0){
                    for(Id accId: setOfIdsToCheckChild){
                        if(mapInterCertAccounts.containskey(accId)){
                            for(Account acc: mapInterCertAccounts.get(accId)){
                                Account objAcc = new Account(Id = acc.Id);
                                objAcc.Date_ALV_Processed__c = null;
                                objAcc.Standard_Audit_ALV_Status__c = null;
                                objAcc.Standard_Audit_ALV_Results__c = null;
                                objAcc.Standard_Audit_ALV_Comments__c = null;
                                objAcc.Code_Signing_Audit_ALV_Status__c = null;
                                objAcc.Code_Signing_Audit_ALV_Results__c = null;
                                objAcc.Code_Signing_Audit_ALV_Comments__c = null;
                                objAcc.BR_Audit_ALV_Status__c = null;
                                objAcc.BR_Audit_ALV_Results__c = null;
                                objAcc.BR_Audit_ALV_Comments__c = null;
                                objAcc.EV_SSL_Audit_ALV_Status__c = null;
                                objAcc.EV_SSL_Audit_ALV_Results__c = null;
                                objAcc.EV_SSL_Audit_ALV_Comments__c = null;
                                objAcc.ALV_Status__c = null;
                                objAcc.ALV_Results__c= null;
                                objAcc.Standard_Audit_ALV_Found_Cert__c = null;
                                objAcc.BR_Audit_ALV_Found_Cert__c = null;
                                if(!setofAccountIdsToUpdate.contains(objAcc.Id)){
                                    lstInterCertId.add('\''+objAcc.Id+'\'');
                                    lstAccToUpdate.add(objAcc);
                                }
                                setofAccountIdsToUpdate.add(objAcc.Id);
                                if(mapInterCertAccounts.containskey(acc.Id)){
                                    setOfIdsToCheckChild.add(acc.Id);
                                    // system.debug('acc.ParentName ::: '+acc.Name);
                                }
                            }
                        }
                        setOfIdsToCheckChild.remove(accId);
                    }
                    // system.debug('setOfIdsToCheckChild ::: '+setOfIdsToCheckChild);
                }
                if(lstAccToUpdate.size() > 0){
                    AccountTriggerHelper.isRecursiveUpdate = true;
                    
                    // update accounts to clear ALV fields.
                    update lstAccToUpdate;
                    AccountTriggerHelper.isRecursiveUpdate = false;
                    
                    // create query to Run ALV only for intermediate certs which are  
                    // not revoked and not expired and child of this root certificate
                    
                    string allIds = '(' + string.join(lstInterCertId, ',') + ')';
                    string FinalQuery = 'SELECT Id, CA_Owner_Certificate_No__c, Name, CA_Owner__c, Subordinate_CA_Owner__c, ' +
                           'Auditor_New__r.Name, Auditor_New__r.Alternate_Auditor_Name_s__c,Date_ALV_Processed__c, ' +
                           'SHA_1_Fingerprint__c, SHA_256_Fingerprint__c, ParentId, ' +
                           'Audits_Same_as_Parent__c,Subject_SPKI_SHA256__c,Extended_Key_Usage__c, ' +
                           'Standard_Audit__c, Standard_Audit_Type__c, Standard_Audit_Statement_Date__c, ' +  
                           'Standard_Audit_Period_Start_Date__c,Standard_Audit_Period_End_Date__c, ' +             
                           'Code_Signing_Audit__c, Code_Signing_Audit_Type__c, Code_Signing_Audit_Statement_Date__c, ' +
                           'Code_Signing_Audit_Period_Start_Date__c, Code_Signing_Audit_Period_End_Date__c, ' +
                           'BR_Audit__c, BR_Audit_Type__c,BR_Audit_Statement_Date__c, ' +
                           'BR_Audit_Period_Start_Date__c,BR_Audit_Period_End_Date__c, ' +
                           'EV_Audit__c, EV_Audit_Type__c, EV_Audit_Statement_Date__c, ' +
                           'EV_Audit_Period_Start_Date__c, EV_Audit_Period_End_Date__c, ' +
                           'EV_Code_Signing_Audit__c, EV_Code_Signing_Audit_Type__c, EV_Code_Signing_Audit_Statement_Date__c, ' +
                           'EV_Code_Signing_Audit_Period_Start_Date__c, EV_Code_Signing_Audit_Period_End_Date__c, ' +
                           'Standard_Audit_ALV_Status__c, Standard_Audit_ALV_Results__c, ' +
                           'BR_Audit_ALV_Status__c, BR_Audit_ALV_Results__c, ' +
                           'Code_Signing_Audit_ALV_Status__c, Code_Signing_Audit_ALV_Results__c, ' +
                           'EV_SSL_Audit_ALV_Status__c, EV_SSL_Audit_ALV_Results__c,Derived_Trust_Bits__c, ' +
                           'Root_Cert_Id__c,Root_Cert_Id__r.Microsoft_Trust_Bits__c,Root_Cert_Id__r.Microsoft_EV_Enabled__c ' +
                           'FROM Account ' +
                           'WHERE RecordType.Name = \'Intermediate Certificate\' ' +
                           'AND Valid_To_GMT__c > '+system.now().format('YYYY-MM-dd')+' AND Revocation_Status__c = \'Not Revoked\' ' +
                           'AND Id in '+ allIds;
                    
                    // pass this query to batch program which process intermediate certs (one at a time) for ALV processing      
                    RunALVForInterCertsBatch batch = new RunALVForInterCertsBatch(FinalQuery);
                    Database.executeBatch(batch,1);
                    
                    ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.Confirm,'Batch job initiated, please check for ALV results after some time. The batch job can take more than an hour to complete.'));
                } else {
                    ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.Error,'There are no intermediate cert records with "Audits Same As Parent" to process.'));    
                }
                //PageReference pg = new PageReference('/'+accId);
                //return pg;
            }
        } catch (Exception ex){
            Apexpages.addMessages(ex);
        }
        return null;
    }
}