objects/Account.object
<CustomObject>
    <fields>
        <fullName>CRL_URL_s__c</fullName>
        <inlineHelpText>URL(s) at which the CRL(s) may be obtained -- for end-entity certs and for intermediate CAs.</inlineHelpText>
        <label>CRL URL(s)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Common_Name__c</fullName>
        <label>Certificate Issuer Common Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organization__c</fullName>
        <label>Certificate Issuer Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Issuer_Organizational_Unit__c</fullName>
        <label>Certificate Issuer Organizational Unit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Serial_Number__c</fullName>
        <label>Certificate Serial Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Common_Name__c</fullName>
        <description>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</description>
        <inlineHelpText>&apos;CA Owner/Certificate Name&apos; must be same as &apos;Certificate Subject Common Name&apos;</inlineHelpText>
        <label>Certificate Subject Common Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Organization_Unit__c</fullName>
        <label>Certificate Subject Organization Unit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Subject_Organization__c</fullName>
        <label>Certificate Subject Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Version__c</fullName>
        <label>Certificate Version</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Extended_Key_Usage__c</fullName>
        <label>Extended Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Key_Usage__c</fullName>
        <label>Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Public_Key_Algorithm__c</fullName>
        <label>Public Key Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RSA 1024 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2045 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2046 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2047 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 2048 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 3072 bits</fullName>
                </value>
                <value>
                    <fullName>RSA 4096 bits</fullName>
                </value>
                <value>
                    <fullName>EC secp256r</fullName>
                </value>
                <value>
                    <fullName>EC secp256r1</fullName>
                </value>
                <value>
                    <fullName>EC secp384r1</fullName>
                </value>
                <value>
                    <fullName>EC secp512r1</fullName>
                </value>
                <value>
                    <fullName>unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Signature_Hash_Algorithm__c</fullName>
        <label>Signature Hash Algorithm</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ecdsaWithSHA256</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA384</fullName>
                </value>
                <value>
                    <fullName>ecdsaWithSHA512</fullName>
                </value>
                <value>
                    <fullName>MD2WithRSA</fullName>
                </value>
                <value>
                    <fullName>MD5WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA1WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA256WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA384WithRSA</fullName>
                </value>
                <value>
                    <fullName>SHA512WithRSA</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject_SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies same logical certificates in different CA Hierarchies. SHA256(der(subject)+der(spki))</inlineHelpText>
        <label>Subject + SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Technically_Constrained__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Technically Constrained</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Valid_From_YYYY_MMM_DD__c</fullName>
        <description>This formula field converts regular date field to display date in YYYY MMM DD format. Eg: &quot;7/9/1999&quot; shows as &quot;1999 Jul 09&quot;</description>
        <formula>IF ( NOT ISBLANK(Valid_From_GMT__c), 

TEXT(YEAR(Valid_From_GMT__c)) &amp; &quot; &quot; &amp;

CASE(MONTH(Valid_From_GMT__c),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
NULL) &amp; &quot; &quot; &amp;
 
IF (LEN(TEXT(DAY(Valid_From_GMT__c))) = 1,&quot;0&quot; &amp; TEXT(DAY(Valid_From_GMT__c)),TEXT(DAY(Valid_From_GMT__c))),

NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid From [GMT]</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_To_YYYY_MMM_DD__c</fullName>
        <description>This formula field converts regular date field to display date in YYYY MMM DD format. Eg: &quot;7/9/1999&quot; shows as &quot;1999 Jul 09&quot;</description>
        <formula>IF ( NOT ISBLANK(Valid_To_GMT__c),

TEXT(YEAR(Valid_To_GMT__c)) &amp; &quot; &quot; &amp;

CASE(MONTH(Valid_To_GMT__c),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;,
4, &quot;Apr&quot;,
5, &quot;May&quot;,
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
NULL) &amp; &quot; &quot; &amp;

IF (LEN(TEXT(DAY(Valid_To_GMT__c))) = 1,&quot;0&quot; &amp; TEXT(DAY(Valid_To_GMT__c)),TEXT(DAY(Valid_To_GMT__c))),

NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid To [GMT]</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PEMDataForRootCertsReportController.cls
/********************************************************************************************************************

  PEMDataForRootCertsReportController is a controller for PEMDataForRootCertsReportCSV
  to generate report on ALL root certs.
  
  This report was specifically created for Chris to compare CCADB data Firefox,NSS included certs and 
  new TLS Observatory tool PEM->JSON
  
 *********************************************************************************************************************/

public class PEMDataForRootCertsReportController {

 public List<Account> accountSoLst {get;set;}
 
  // constructor method for standard controller
    public PEMDataForRootCertsReportController() {   
                                          
           accountSoLst =  [select  Name,
                                    Parent.Name,
                                    Certificate_Issuer_Common_Name__c,
                                    Certificate_Issuer_Organization__c,
                                    Certificate_Issuer_Organizational_Unit__c,
                                    Certificate_Subject_Common_Name__c, 
                                    Certificate_Subject_Organization__c, 
                                    Certificate_Subject_Organization_Unit__c,
                                    Valid_From_YYYY_MMM_DD__c,
                                    Valid_To_YYYY_MMM_DD__c,
                                    SHA_1_Fingerprint__c,                                   
                                    SHA_256_Fingerprint__c, 
                                    Subject_SPKI_SHA256__c, 
                                    Certificate_Serial_Number__c,  
                                    Subject__c,                                                                                                
                                    Signature_Hash_Algorithm__c,
                                    Public_Key_Algorithm__c,
                                    Certificate_Version__c,
                                    Key_Usage__c,
                                    Extended_Key_Usage__c, 
                                    CRL_URL_s__c, 
                                    Technically_Constrained__c,
                                    X_509_Certificate_PEM__c,                                   
                                    Status__c  
                                          from  Account
                                          where RecordType.Name = 'Root Certificate' and                                                                            
                                                Name != '<Fill in Cert Name>'
                                          order by Parent.Name, Name];  
                                          
                                    /****
                                     Status__c In ('Included','Change Requested') and           
                                     ****/       

   
      // if we are generating a CSV file then we need to replace the double quotes in all text fields with null
       if((ApexPages.currentPage().getUrl().contains('CSV') && accountSoLst !=null && accountSoLst.size() > 0) || Test.IsRunningTest())
       {
          for(Account accountSo : accountSoLst)
          {
              if(accountSo.name !=null && accountSo.name.length() > 0) 
                   accountSo.name = accountSo.name.replace('"',''); 
              if(accountSo.parent.name !=null && accountSo.parent.name.length() > 0) 
                   accountSo.parent.name = accountSo.parent.name.replace('"','');  
              if(accountSo.Certificate_Issuer_Common_Name__c !=null && accountSo.Certificate_Issuer_Common_Name__c.length() > 0) 
                   accountSo.Certificate_Issuer_Common_Name__c = accountSo.Certificate_Issuer_Common_Name__c.replace('"',''); 
              if(accountSo.Certificate_Issuer_Organization__c !=null && accountSo.Certificate_Issuer_Organization__c.length() > 0) 
                   accountSo.Certificate_Issuer_Organization__c = accountSo.Certificate_Issuer_Organization__c.replace('"',''); 
              if(accountSo.Certificate_Subject_Common_Name__c !=null && accountSo.Certificate_Subject_Common_Name__c.length() > 0) 
                   accountSo.Certificate_Subject_Common_Name__c = accountSo.Certificate_Subject_Common_Name__c.replace('"','');               
              if(accountSo.Certificate_Subject_Organization__c !=null && accountSo.Certificate_Subject_Organization__c.length() > 0) 
                   accountSo.Certificate_Subject_Organization__c = accountSo.Certificate_Subject_Organization__c.replace('"','');              
              if(accountSo.Certificate_Subject_Organization_Unit__c !=null && accountSo.Certificate_Subject_Organization_Unit__c.length() > 0) 
                   accountSo.Certificate_Subject_Organization_Unit__c = accountSo.Certificate_Subject_Organization_Unit__c.replace('"','');               
              if(accountSo.Certificate_Issuer_Organizational_Unit__c !=null && accountSo.Certificate_Issuer_Organizational_Unit__c.length() > 0) 
                   accountSo.Certificate_Issuer_Organizational_Unit__c = accountSo.Certificate_Issuer_Organizational_Unit__c.replace('"','');                            
              if(accountSo.Subject__c !=null && accountSo.Subject__c.length() > 0) 
                   accountSo.Subject__c = accountSo.Subject__c.replace('"',''); 
              if(accountSo.Key_Usage__c !=null && accountSo.Key_Usage__c.length() > 0) 
                   accountSo.Key_Usage__c = accountSo.Key_Usage__c.replace('"',''); 
              if(accountSo.Extended_Key_Usage__c !=null && accountSo.Extended_Key_Usage__c.length() > 0) 
                   accountSo.Extended_Key_Usage__c = accountSo.Extended_Key_Usage__c.replace('"','');                 
              if(accountSo.SHA_1_Fingerprint__c !=null && accountSo.SHA_1_Fingerprint__c.length() > 0) 
                   accountSo.SHA_1_Fingerprint__c = accountSo.SHA_1_Fingerprint__c.replace('"',''); 
              if(accountSo.SHA_256_Fingerprint__c !=null && accountSo.SHA_256_Fingerprint__c.length() > 0) 
                   accountSo.SHA_256_Fingerprint__c = accountSo.SHA_256_Fingerprint__c.replace('"','');                    
              if(accountSo.X_509_Certificate_PEM__c!=null && accountSo.X_509_Certificate_PEM__c.length() > 0) 
                   accountSo.X_509_Certificate_PEM__c= accountSo.X_509_Certificate_PEM__c.replace('"','');  
                           
           }
      }    
 }
 
   String CurrentDate = ' ';
      
   // Get current Datetime in long date format   

    public String getCurrentDate() {

      Datetime cDT = System.now();
      CurrentDate = cDT.format('MMMM d, yyyy');

      return CurrentDate;

   }
    
 }