objects/Account.object
<CustomObject>
    <fields>
        <fullName>Issuer__c</fullName>
        <inlineHelpText>Certificate Issuer Common Name + Certificate Issuer Organizational Unit + Certificate Issuer Organization + Certificate Issuer Country</inlineHelpText>
        <label>Issuer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Root_Cert_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is populated by PublicAllIntermediateCerts batch program for all intermediate cert records.</inlineHelpText>
        <label>Root Cert Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MozillaIntermediateCertsReportCtrlTest.cls
/*******************************************************************************************************
 Name: MozillaIntermediateCertsReportCtrlTest

 Dependencies:  MozillaIntermediateCertsReportController controller class,  MozillaIntermediateCertsReportCtrlTest, 
 MozillaIntermediateCertsCSVReport vf page

 Description: This report lists non revoked intermediate certs and Derived Trust Bits contains 'Server Authentication'.
 Firefox directly uses this report to create the intermediate certificate bulk load list.

 
 Instructions:  None

 *******************************************************************************************************
 Revision History:
 
     1/15/2019 - Created new

 ******************************************************************************************************/
 
@isTest
public with sharing class MozillaIntermediateCertsReportCtrlTest {
    static testMethod void validateTest() {
        
        Account acc = TestUtils.getCAOwner();
        insert acc;
        
        Account rootacc = TestUtils.getRootCertificate(acc.Id);
        rootacc.Status__c = 'Included';
        rootacc.Trust_Bits__c = 'Websites';
        insert rootacc;
        
        Account intermediateacc = TestUtils.getIntermediateCertificate(rootacc.Id);
        intermediateacc.Revocation_Status__c = 'Not Revoked';
        intermediateacc.Valid_To_GMT__c = system.today().addDays(10);
        intermediateacc.Root_Cert_Id__c = rootacc.Id;
        intermediateacc.Subject__c = 'SSSSS';
        intermediateacc.Issuer__c = 'IIIIIII';
        intermediateacc.SHA_256_Fingerprint__c = 'AAAAAAAA';
        insert intermediateacc;
        
        MozillaIntermediateCertsReportController objReport = new MozillaIntermediateCertsReportController();
        
    }
}