objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auditor_New__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Name of Auditor who issued the standard audit statement. See &apos;List All Auditors&apos; below for choices. Send email to support@ccadb.org if your auditor is not listed.</inlineHelpText>
        <label>Auditor</label>
        <referenceTo>Auditor__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>BR Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Period_Start_Date__c</fullName>
        <description>Start date of the period of time of CA operations examined by the auditor.</description>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>BR Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Statement_Date__c</fullName>
        <description>Date BR Audit Statement Issued</description>
        <inlineHelpText>Date BR Audit Statement Issued</inlineHelpText>
        <label>BR Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Type__c</fullName>
        <label>BR Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BR_Audit__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>BR Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Owner_Certificate_No__c</fullName>
        <displayFormat>A{000000}</displayFormat>
        <externalId>true</externalId>
        <label>CA Owner/Certificate No</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Period_End_Date__c</fullName>
        <description>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</description>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Code Signing Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Period_Start_Date__c</fullName>
        <description>Start date of the period of time of CA operations examined by the auditor.</description>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Code Signing Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Statement_Date__c</fullName>
        <description>Date Code Signing Audit Statement Issued</description>
        <inlineHelpText>Date Code Signing Audit Statement Issued</inlineHelpText>
        <label>Code Signing Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Type__c</fullName>
        <label>Code Signing Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit__c</fullName>
        <label>Code Signing Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_ALV_Processed__c</fullName>
        <inlineHelpText>Updated by system each time when ALV processing is completed.</inlineHelpText>
        <label>Date ALV Processed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>EV SSL Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>EV SSL Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Statement_Date__c</fullName>
        <description>Date EV SSL Audit Statement Issued</description>
        <inlineHelpText>Date EV SSL Audit Statement Issued</inlineHelpText>
        <label>EV SSL Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Type__c</fullName>
        <label>EV SSL Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EV_Audit__c</fullName>
        <description>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>EV SSL Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>EV Code Signing Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Statement_Date__c</fullName>
        <inlineHelpText>Date EV Code Signing Audit Statement Issued</inlineHelpText>
        <label>EV Code Signing Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Type__c</fullName>
        <label>EV Code Signing Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit__c</fullName>
        <label>EV Code Signing Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Extended_Key_Usage__c</fullName>
        <label>Extended Key Usage</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_1_Fingerprint__c</fullName>
        <label>SHA-1 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_Start_Date__c</fullName>
        <inlineHelpText>Start date of the period of time of CA operations examined by the auditor.</inlineHelpText>
        <label>Standard Audit Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Date__c</fullName>
        <description>Date Audit Statement Issued</description>
        <inlineHelpText>Date Audit Statement Issued</inlineHelpText>
        <label>Standard Audit Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Type__c</fullName>
        <label>Standard Audit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WebTrust</fullName>
                </value>
                <value>
                    <fullName>ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 101 456</fullName>
                </value>
                <value>
                    <fullName>ETSI TS 102 042</fullName>
                </value>
                <value>
                    <fullName>Equivalent WebTrust</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI EN 319 411</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 101 456</fullName>
                </value>
                <value>
                    <fullName>Equivalent ETSI 102 042</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject_SPKI_SHA256__c</fullName>
        <inlineHelpText>Identifies same logical certificates in different CA Hierarchies. SHA256(der(subject)+der(spki))</inlineHelpText>
        <label>Subject + SPKI SHA256</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subordinate_CA_Owner__c</fullName>
        <inlineHelpText>Enter Subordinate CA’s name as it appears in the provided audit statements. Leave blank if BOTH control of the private key AND domain/IP/email validation activities are performed by the organization listed in the audit statement of the parent certificate.</inlineHelpText>
        <label>Subordinate CA Owner</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auditor__c.object
<CustomObject>
    <fields>
        <fullName>Alternate_Auditor_Name_s__c</fullName>
        <inlineHelpText>Names must be separated by semicolon &apos;;&apos;</inlineHelpText>
        <label>Alternate Auditor Name(s)</label>
        <type>TextArea</type>
    </fields>
    <label>Auditor</label>
    <nameField>
        <label>Auditor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auditors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RunALVForInterCertsBatch.cls
/*
    Batch Program is created to run ALV for Intermediate certs.
    
    //WHAT DO
    -> When batch runs, check for all Intermediate certs where subordinate ca owner is not blank, Audit same as Parent not checked, not revoked, not expired. 
    -> It also check if all audits populated and Date ALV Processed is blank or lesser than Audit 
     statement then it runs ALV for that intermediate certs.
    
    //TO RUN THIS BATCH
    RunALVForInterCertsBatch batch = new RunALVForInterCertsBatch('');
    Database.executeBatch(batch,1);
*/
global class RunALVForInterCertsBatch implements Database.Batchable<Sobject>, Database.AllowsCallouts {
    static Date dttoday = system.today(); 
    global final String Query;
    
    global RunALVForInterCertsBatch (String q){
        if(string.isnotblank(q)){
            Query = q;
        } else {
            Query = 'SELECT Id, CA_Owner_Certificate_No__c, Name, CA_Owner__c, Subordinate_CA_Owner__c, ' +
               'Auditor_New__r.Name, Auditor_New__r.Alternate_Auditor_Name_s__c,Date_ALV_Processed__c, ' +
               'SHA_1_Fingerprint__c, SHA_256_Fingerprint__c, ParentId, ' +
               'Audits_Same_as_Parent__c,Subject_SPKI_SHA256__c,Extended_Key_Usage__c, ' +
               'Standard_Audit__c, Standard_Audit_Type__c, Standard_Audit_Statement_Date__c, ' +  
               'Standard_Audit_Period_Start_Date__c,Standard_Audit_Period_End_Date__c, ' +             
               'Code_Signing_Audit__c, Code_Signing_Audit_Type__c, Code_Signing_Audit_Statement_Date__c, ' +
               'Code_Signing_Audit_Period_Start_Date__c, Code_Signing_Audit_Period_End_Date__c, ' +
               'BR_Audit__c, BR_Audit_Type__c,BR_Audit_Statement_Date__c, ' +
               'BR_Audit_Period_Start_Date__c,BR_Audit_Period_End_Date__c, ' +
               'EV_Audit__c, EV_Audit_Type__c, EV_Audit_Statement_Date__c, ' +
               'EV_Audit_Period_Start_Date__c, EV_Audit_Period_End_Date__c, ' +
               'EV_Code_Signing_Audit__c, EV_Code_Signing_Audit_Type__c, EV_Code_Signing_Audit_Statement_Date__c, ' +
               'EV_Code_Signing_Audit_Period_Start_Date__c, EV_Code_Signing_Audit_Period_End_Date__c, ' +
               'Standard_Audit_ALV_Status__c, Standard_Audit_ALV_Results__c, ' +
               'BR_Audit_ALV_Status__c, BR_Audit_ALV_Results__c, ' +
               'Code_Signing_Audit_ALV_Status__c, Code_Signing_Audit_ALV_Results__c, ' +
               'EV_SSL_Audit_ALV_Status__c, EV_SSL_Audit_ALV_Results__c,Derived_Trust_Bits__c, ' +
               'Root_Cert_Id__c,Root_Cert_Id__r.Microsoft_Trust_Bits__c,Root_Cert_Id__r.Microsoft_EV_Enabled__c ' +
               'FROM Account ' +
               'WHERE RecordType.Name = \'Intermediate Certificate\' ' + //Subordinate_CA_Owner__c != null AND Audits_Same_as_Parent__c = false
               'AND Valid_To_GMT__c >: dttoday AND Revocation_Status__c = \'Not Revoked\'';
               //' AND CA_Owner_ID__c = \'0015600000EEeoRAAT\'';//for Testing purpose
        }
        //system.debug('Query  ::: '+Query );
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> lstAccounts){
        if(lstAccounts.size() == 1) {
            Account objAcc = lstAccounts[0];
            boolean isRunALV = false;
            if(!objAcc.Audits_Same_as_Parent__c && objAcc.Subordinate_CA_Owner__c != null && (string.isnotblank(objAcc.Standard_Audit__c) || string.isnotblank(objAcc.BR_Audit__c) || 
                    string.isnotblank(objAcc.Code_Signing_Audit__c) || string.isnotblank(objAcc.EV_Audit__c)) && objAcc.Date_ALV_Processed__c == null){
                isRunALV = true;
            } else if(!objAcc.Audits_Same_as_Parent__c && objAcc.Subordinate_CA_Owner__c != null && objAcc.Date_ALV_Processed__c != null && 
                            ((objAcc.Standard_Audit_Statement_Date__c != null && objAcc.Date_ALV_Processed__c < objAcc.Standard_Audit_Statement_Date__c) || 
                            (objAcc.BR_Audit_Statement_Date__c != null && objAcc.Date_ALV_Processed__c < objAcc.BR_Audit_Statement_Date__c) ||
                            (objAcc.Code_Signing_Audit_Statement_Date__c != null && objAcc.Date_ALV_Processed__c < objAcc.Code_Signing_Audit_Statement_Date__c) ||
                            (objAcc.EV_Audit_Statement_Date__c != null && objAcc.Date_ALV_Processed__c < objAcc.EV_Audit_Statement_Date__c))){
                isRunALV = true;
            } else if(objAcc.Audits_Same_as_Parent__c){
                if(objAcc.Date_ALV_Processed__c == null){
                    isRunALV = true;
                } else if(objAcc.Date_ALV_Processed__c != null){
                    boolean isFound = false;
                    Id accParentId = objAcc.ParentId;
                    Account objParentAccount;
                    while(!isFound){
                        objParentAccount = GetParentAccount(accParentId);
                        if(objParentAccount != null && !objParentAccount.Audits_Same_as_Parent__c) {
                            isFound = true;
                        } else if(objParentAccount == null) {
                            isFound = true;
                        }
                        if(objParentAccount != null) accParentId = objParentAccount.ParentId;
                    }
                    if((objParentAccount.Standard_Audit_Statement_Date__c != null && objAcc.Date_ALV_Processed__c < objParentAccount.Standard_Audit_Statement_Date__c) || 
                        (objParentAccount.BR_Audit_Statement_Date__c != null && objAcc.Date_ALV_Processed__c < objParentAccount.BR_Audit_Statement_Date__c) ||
                        (objParentAccount.Code_Signing_Audit_Statement_Date__c != null && objAcc.Date_ALV_Processed__c < objParentAccount.Code_Signing_Audit_Statement_Date__c) ||
                        (objParentAccount.EV_Audit_Statement_Date__c != null && objAcc.Date_ALV_Processed__c < objParentAccount.EV_Audit_Statement_Date__c)){
                        isRunALV = true;
                    }
                }
            }
            if(isRunALV){
                JixiServiceInterCertsController jixicontroller = new JixiServiceInterCertsController(new Apexpages.standardcontroller(lstAccounts[0]));
                jixicontroller.prepareRequest();
                jixicontroller.doCallOut();
                jixicontroller.postCallActions();
            }
        }
    }
    
    global void finish(Database.BatchableContext BC){
    
    }
    
    public static Account GetParentAccount(string accId){
        List<Account> lstAcc = new List<Account>([select Id, ParentId, RecordType.Name,
                        Certificate_Policy_CP__c, Certification_Practice_Statement_CPS__c,
                        Parent.Certificate_Policy_CP__c, Parent.Certification_Practice_Statement_CPS__c,
                        Standard_Audit__c, Parent.Standard_Audit__c, Code_Signing_Audit__c, Parent.Code_Signing_Audit__c,
                        BR_Audit__c, Parent.BR_Audit__c, EV_Audit__c, Parent.EV_Audit__c, 
                        Audits_Same_as_Parent__c, Parent.Audits_Same_as_Parent__c,
                        CP_CPS_Same_as_Parent__c, Parent.CP_CPS_Same_as_Parent__c,
                        Code_Signing_Audit_Statement_Date__c,EV_Audit_Statement_Date__c,Standard_Audit_Statement_Date__c,BR_Audit_Statement_Date__c
                        from Account Where Id =: accId]);
        if(lstAcc.size() > 0){
            return lstAcc[0];
        }
        return null;
    }
}