objects/Account.object
<CustomObject>
    <fields>
        <fullName>Microsoft_Trust_Bits__c</fullName>
        <label>Microsoft Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Server Authentication</fullName>
                </value>
                <value>
                    <fullName>Client Authentication</fullName>
                </value>
                <value>
                    <fullName>Code Signing</fullName>
                </value>
                <value>
                    <fullName>Document Signing</fullName>
                </value>
                <value>
                    <fullName>Encrypting File System</fullName>
                </value>
                <value>
                    <fullName>IP Security End System</fullName>
                </value>
                <value>
                    <fullName>IP Security IKE Intermediate</fullName>
                </value>
                <value>
                    <fullName>IP Security Tunnel Termination</fullName>
                </value>
                <value>
                    <fullName>IP Security User</fullName>
                </value>
                <value>
                    <fullName>OCSP Signing</fullName>
                </value>
                <value>
                    <fullName>Private Key Archival</fullName>
                </value>
                <value>
                    <fullName>Secure Email</fullName>
                </value>
                <value>
                    <fullName>Time Stamping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Website_Expired__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with an expired TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Expired</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Website_Revoked__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with a revoked TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Revoked</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Website_Valid__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with a valid TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Valid</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>BR_Audit_Statement_Link__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>BR Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Statement_Link__c</fullName>
        <description>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>EV SSL Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>Information verification phases</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Link__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Root_Case__c.object
<CustomObject>
    <fields>
        <fullName>Apply_BR_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BR Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_EV_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EV SSL Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_EV_Code_Signing_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EV Code Signing Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apply_Standard_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Microsoft_Trust_Bits__c</fullName>
        <label>Microsoft Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Server Authentication</fullName>
                </value>
                <value>
                    <fullName>Client Authentication</fullName>
                </value>
                <value>
                    <fullName>Code Signing</fullName>
                </value>
                <value>
                    <fullName>Document Signing</fullName>
                </value>
                <value>
                    <fullName>Encrypting File System</fullName>
                </value>
                <value>
                    <fullName>IP Security End System</fullName>
                </value>
                <value>
                    <fullName>IP Security IKE Intermediate</fullName>
                </value>
                <value>
                    <fullName>IP Security Tunnel Termination</fullName>
                </value>
                <value>
                    <fullName>IP Security User</fullName>
                </value>
                <value>
                    <fullName>OCSP Signing</fullName>
                </value>
                <value>
                    <fullName>Private Key Archival</fullName>
                </value>
                <value>
                    <fullName>Secure Email</fullName>
                </value>
                <value>
                    <fullName>Time Stamping</fullName>
                </value>
                <value>
                    <fullName>Code Signing Signing</fullName>
                    <isActive>false</isActive>
                    <label>Code Signing Signing</label>
                </value>
                <value>
                    <fullName>Secure Secure Email</fullName>
                    <isActive>false</isActive>
                    <label>Secure Secure Email</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Root_Certificate_Name_Existing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Previously called Included Certificate Name</description>
        <inlineHelpText>The Root Certificate that this Root Case applies to.</inlineHelpText>
        <label>Certificate Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Root</value>
            </filterItems>
            <filterItems>
                <field>Account.Parent.Id</field>
                <operation>equals</operation>
                <valueField>$Source.CA_Owner_Name_Existing__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Root Cases (Included Certificate)</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Website_Expired__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with an expired TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Expired</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Website_Revoked__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with a revoked TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Revoked</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Website_Valid__c</fullName>
        <inlineHelpText>REQUIRED by BRs: URL to website with a valid TLS/SSL cert that chains up to the Root Certificate</inlineHelpText>
        <label>Test Website - Valid</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trust_Bits__c</fullName>
        <inlineHelpText>Select the trust bits you are requesting to be enabled for this root.</inlineHelpText>
        <label>Mozilla Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All Trust Bits Turned Off</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Websites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Root Case</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Root Case No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EditTestWebsitesAuditRootCaseController.cls
/*
    Description: This class is created for Audit Cases transient page. "Edit Test Websites" invokes 
    EditTestWebsitesAuditRootCase VF page for users to update Test websites on multiple root cases.
    
    Root Case with Request Status <> "Intial Request Received" are not editable.
    
    If user enters blank or invalid url, an error will display at the top.
*/

public with sharing class EditTestWebsitesAuditRootCaseController {
    
    Id caseOwnerId;
    public Case objCase;
    public boolean isCaseCompleted {get; set;}
    
    public List<Root_Case__c> lstAllRootCases {get; set;}
    
    public EditTestWebsitesAuditRootCaseController(Apexpages.standardcontroller controller) {
        caseOwnerId = controller.getId();
        isCaseCompleted = false;
        
        lstAllRootCases = new List<Root_Case__c>();
        
        List<Case> lstCases = new List<Case>([select Id,AccountId,CaseNumber,Account.Name,
                                                     Standard_Audit_Statement_Link__c, BR_Audit_Statement_Link__c,EV_Audit_Statement_Link__c,
                                                     Request_Status__c
                                               from Case Where Id =: caseOwnerId]);
        
        if(lstCases.size() > 0) {
            objCase = lstCases[0];
            if(objCase.Request_Status__c == 'Complete') {
                isCaseCompleted = true;
            }
            //fill map to find existing root cases.
            lstAllRootCases = [Select Id, Root_Certificate_Name_Existing__c, Root_Certificate_Name_Existing__r.Name, Request_Status__c,
                                          Apply_Standard_Audit__c, Apply_BR_Audit__c, Apply_EV_Audit__c, Apply_EV_Code_Signing_Audit__c,
                                          Test_Website_Valid__c, Test_Website_Revoked__c, Test_Website_Expired__c, SHA_256_Fingerprint__c,
                                          Trust_Bits__c, Microsoft_Trust_Bits__c, Test_Website_Verified__c 
                                   from   Root_Case__c Where Case_No__c =: objCase.Id];
            
        }
    }
    
    //method is used to upsert root cases based on selected root certificates
    public PageReference UpdateRootCases(){
        try {
            if(lstAllRootCases.size() > 0) {
                string ErrorMessage = 'Please provide valid test website link, URL must begin with \'https\' and can only contain letters, numbers and following characters: + & @ # / % ? = ~- _ | ! : , . ; [ ] ( ) ';
                Pattern httpPattern = Pattern.compile('^[hH][tT][tT][pP][sS][0-9A-Za-z+&@#/%?=~\\-_|!:,.;\\[\\]()]*$');
                
                for(Root_Case__c objRC: lstAllRootCases){
                    // The test websites are only required if the CA indicates that the BR and/or EV SSL Audit applies to that root cert.
                    if((objRC.Apply_BR_Audit__c || objRC.Apply_EV_Audit__c) && (string.isblank(objRC.Test_Website_Valid__c) || string.isblank(objRC.Test_Website_Revoked__c) || string.isblank(objRC.Test_Website_Expired__c))) {
                        ApexPages.AddMessage(new ApexPages.Message( ApexPages.Severity.Error, objRC.Root_Certificate_Name_Existing__r.Name + ' - Test website link cannot be blank when BR and/or EV SSL Audit applies'));
                        return null;
                    }
                    if((objRC.Test_Website_Valid__c != null && !httpPattern.matcher(objRC.Test_Website_Valid__c).matches()) || 
                                    (objRC.Test_Website_Revoked__c != null && !httpPattern.matcher(objRC.Test_Website_Revoked__c).matches()) || 
                                    (objRC.Test_Website_Expired__c != null && !httpPattern.matcher(objRC.Test_Website_Expired__c).matches())){
                        ApexPages.AddMessage(new ApexPages.Message( ApexPages.Severity.Error, objRC.Root_Certificate_Name_Existing__r.Name + ' - '+ErrorMessage));
                        return null;
                    }
                }
                
                update lstAllRootCases; // update root case if any Apply field has changed
            } 
        } catch (Exception ex){
            Apexpages.addMessages(ex);
            return null;
        }
        
        PageReference pg = new Pagereference('/'+objCase.Id);
        pg.setReDirect(true);
        return pg;
    }   
}