objects/Account.object
<CustomObject>
    <fields>
        <fullName>CA_Document_Repository__c</fullName>
        <description>URL to where policy documentation specific to this cert may be found</description>
        <inlineHelpText>URL to where policy documentation specific to this cert may be found</inlineHelpText>
        <label>CA Document Repository</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Document_Repository__c</fullName>
        <inlineHelpText>URL to where the CA&apos;s policy documentation may be found. More than one URL may be provided as a semicolon - separated list.</inlineHelpText>
        <label>Document Repository</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Policy_Documentation__c</fullName>
        <description>Further documentation or information relevant to this cert</description>
        <inlineHelpText>Further documentation or information relevant to this cert</inlineHelpText>
        <label>Policy Documentation</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Policy_Identifiers__c</fullName>
        <label>Policy Identifiers</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CA_Document_Repository__c</fullName>
        <description>URL to where policy documentation specific to the listed root certs may be found</description>
        <inlineHelpText>URL to where policy documentation specific to the listed root certs may be found</inlineHelpText>
        <label>CA Document Repository</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Policy_Documentation__c</fullName>
        <description>Further documentation or information relevant to the listed root certs.</description>
        <inlineHelpText>Further documentation or information relevant to the listed root certs.</inlineHelpText>
        <label>Policy Documentation</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Policy_Document_Association_On_Case__c.object
<CustomObject>
    <description>Policy Document Association records on Case</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Policy_Document_Associations_On_Case</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <formula>Policy_Document__r.Document_Link__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>TEXT (Policy_Document__r.Document_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <label>Policy Document Association (On Case)</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Document Associations (On Case)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Policy_Document_On_Case__c.object
<CustomObject>
    <description>Policy Documents on Case</description>
    <fields>
        <fullName>Additional_Policy_Identifiers__c</fullName>
        <inlineHelpText>Additional Policy Identifiers</inlineHelpText>
        <label>Additional Policy Identifiers</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Associated_Trust_Bits__c</fullName>
        <inlineHelpText>Associated Trust Bits</inlineHelpText>
        <label>Associated Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Secure Email</fullName>
                </value>
                <value>
                    <fullName>Server Authentication</fullName>
                </value>
                <value>
                    <fullName>Client Authentication</fullName>
                </value>
                <value>
                    <fullName>Code Signing</fullName>
                </value>
                <value>
                    <fullName>Document Signing</fullName>
                </value>
                <value>
                    <fullName>Encrypting File System</fullName>
                </value>
                <value>
                    <fullName>IP Security End System</fullName>
                </value>
                <value>
                    <fullName>IP Security IKE Intermediate</fullName>
                </value>
                <value>
                    <fullName>IP Security Tunnel Termination</fullName>
                </value>
                <value>
                    <fullName>IP Security User</fullName>
                </value>
                <value>
                    <fullName>OCSP Signing</fullName>
                </value>
                <value>
                    <fullName>Private Key Archiva</fullName>
                </value>
                <value>
                    <fullName>Time Stamping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Policy Documents (On Case)</relationshipLabel>
        <relationshipName>Policy_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Last_Updated_Date__c</fullName>
        <inlineHelpText>Policy document Last Updated Date must be filled for policy document link</inlineHelpText>
        <label>Document Last Updated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <inlineHelpText>URL to policy documentation specific to the listed root certs. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Document Link</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CP/CPS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Identifiers__c</fullName>
        <label>Policy Identifiers</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Policy Document (On Case)</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Policy Doc Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Documents (On Case)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Policy_Document_On_Certificate__c.object
<CustomObject>
    <description>Policy Document records on Certificate</description>
    <fields>
        <fullName>Associated_Trust_Bits__c</fullName>
        <label>Associated Trust Bits</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Server Authentication</fullName>
                </value>
                <value>
                    <fullName>Client Authentication</fullName>
                </value>
                <value>
                    <fullName>Code Signing</fullName>
                </value>
                <value>
                    <fullName>Document Signing</fullName>
                </value>
                <value>
                    <fullName>Encrypting File System</fullName>
                </value>
                <value>
                    <fullName>Secure Email</fullName>
                </value>
                <value>
                    <fullName>Time Stamping</fullName>
                </value>
                <value>
                    <fullName>IP Security End System</fullName>
                </value>
                <value>
                    <fullName>IP Security IKE Intermediate</fullName>
                </value>
                <value>
                    <fullName>IP Security Tunnel Termination</fullName>
                </value>
                <value>
                    <fullName>IP Security User</fullName>
                </value>
                <value>
                    <fullName>OCSP Signing</fullName>
                </value>
                <value>
                    <fullName>Private Key Archival</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Last_Updated_Date__c</fullName>
        <inlineHelpText>Policy document Last Updated Date must be filled for policy document link</inlineHelpText>
        <label>Document Last Updated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <inlineHelpText>URL to policy documentation specific to the listed root certs. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Document Link</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CP/CPS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Identifiers__c</fullName>
        <inlineHelpText>Policy Identifiers</inlineHelpText>
        <label>Policy Identifiers</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Policy Document</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Policy Doc Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PolicyDocumentAssociation_On_Certificate__c.object
<CustomObject>
    <fields>
        <fullName>Document_Link__c</fullName>
        <formula>Policy_Document__r.Document_Link__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>Text (Policy_Document__r.Document_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <label>Policy Document Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Document Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Root_Case__c.object
<CustomObject>
    <fields>
        <fullName>Case_No__c</fullName>
        <label>Case No</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Root Cases</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Root_Certificate_Name_Existing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Previously called Included Certificate Name</description>
        <inlineHelpText>The Root Certificate that this Root Case applies to.</inlineHelpText>
        <label>Certificate Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Root</value>
            </filterItems>
            <filterItems>
                <field>Account.Parent.Id</field>
                <operation>equals</operation>
                <valueField>$Source.CA_Owner_Name_Existing__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Root Cases (Included Certificate)</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Root Case</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Root Case No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SyncPolicyDocumentsController.cls
/*
    Description: Controller is created to Sync Policy Documents
*/
public with sharing class SyncPolicyDocumentsController {
    
    public Case objCase {get; set;}
    public boolean isError {get; set;}
    public Policy_Document_On_Case__c policydocumentcase {get; set;}
    public string policyIdentifiersCase {get; set;}
    public Policy_Document_On_Certificate__c policydocumentcert {get; set;}
    public integer totaldocuments {get; set;}
    public integer curretndocument {get; set;}
    public boolean isRecordUpdated {get; set;}
    public map<Id, Policy_Document_On_Certificate__c> mapPolicyDocumentsCerts;
    public List<Policy_Document_On_Case__c> lstAdditionalPolicyDocs;
    public boolean isSyncOnCAOwner;
    
    public SyncPolicyDocumentsController(Apexpages.standardController controller){
        objCase = (Case)controller.getRecord();
        isError = false;
        policyIdentifiersCase = '';
        isSyncOnCAOwner = false;
        List<Case> lstCase = new List<Case>([select Id,CaseNumber,AccountId,Account.Policy_Identifiers__c,
                        CA_Document_Repository__c,Policy_Documentation__c,
                        (select Id, Root_Certificate_Name_Existing__c from Root_Cases__r)
                        FROM Case where Id =: objCase.Id]);
        if(lstCase.size() > 0){
            objCase = lstCase[0];
            
            lstAdditionalPolicyDocs = new List<Policy_Document_On_Case__c>([select Id, Name, Associated_Trust_Bits__c, Additional_Policy_Identifiers__c,
                    Comments__c, Document_Last_Updated_Date__c, Document_Link__c, Document_Type__c,Policy_Identifiers__c,Action__c,Source_Policy_Doc_Id__c,
                    (Select Id, Name, Certificate_Name__c,Case__c,Policy_Document__c, Certificate_Name__r.Name, Certificate_Name__r.Status__c, Action__c,
                    Certificate_Name__r.Microsoft_Status__c, Certificate_Name__r.Valid_From_GMT__c,Certificate_Name__r.Valid_To_GMT__c,
                    Certificate_Name__r.SHA_256_Fingerprint__c
                    from Policy_Document_Associations__r Order by Certificate_Name__c)
                    FROM Policy_Document_On_Case__c
                    WHERE Case__c =: objCase.Id and Document_Verified__c in ('Data Verified', 'System Verified')]);
                    
            set<Id> setofPolicyDocCertIds = new set<Id>();
            
            for(Policy_Document_On_Case__c PDC: lstAdditionalPolicyDocs){
                if(PDC.Source_Policy_Doc_Id__c != null && string.isnotblank(PDC.Source_Policy_Doc_Id__c)){
                    setofPolicyDocCertIds.add(PDC.Source_Policy_Doc_Id__c);
                }
            }
                    
            mapPolicyDocumentsCerts = new map<Id, Policy_Document_On_Certificate__c>([Select Id, Name, Associated_Trust_Bits__c,Sync_Policy_Doc_Id__r.Name,
                    Comments__c,Document_Last_Updated_Date__c,Document_Link__c,Document_Type__c,Policy_Identifiers__c,Sync_Policy_Doc_Id__c,Is_Deleted__c,
                    (Select Id, Name, Certificate_Name__c,Policy_Document__c, Certificate_Name__r.Name, Certificate_Name__r.Status__c,
                    Certificate_Name__r.Microsoft_Status__c, Certificate_Name__r.Valid_From_GMT__c,Certificate_Name__r.Valid_To_GMT__c,
                    Certificate_Name__r.SHA_256_Fingerprint__c,Is_Deleted__c,Source_Policy_Doc_Assoc_Id__c from Policy_Document_Associations__r Order by Certificate_Name__c) from 
                    Policy_Document_On_Certificate__c Where Id in: setofPolicyDocCertIds]);
            
            if(lstAdditionalPolicyDocs.size() > 0){
                totaldocuments = lstAdditionalPolicyDocs.size();
                curretndocument = 0;
                
                policydocumentcase = lstAdditionalPolicyDocs[0];
                if(policydocumentcase.Policy_Identifiers__c != null){
                    policyIdentifiersCase += policydocumentcase.Policy_Identifiers__c;
                }
                if(policydocumentcase.Additional_Policy_Identifiers__c != null){
                    if(string.isnotblank(policyIdentifiersCase)){
                        policyIdentifiersCase += ';';
                    }
                    List<string> arrAddPI = policydocumentcase.Additional_Policy_Identifiers__c.split(';');
                    List<string> lstPIs = new List<string>();
                    for(string PI: arrAddPI){
                        if(string.isnotblank(PI)){
                            lstPIs.add(PI.trim());
                        }
                    }
                    policyIdentifiersCase += string.join(lstPIs, ';');
                }
                policydocumentcert = new Policy_Document_On_Certificate__c();
                if(mapPolicyDocumentsCerts.containskey(lstAdditionalPolicyDocs[0].Source_Policy_Doc_Id__c)){
                    policydocumentcert = mapPolicyDocumentsCerts.get(lstAdditionalPolicyDocs[0].Source_Policy_Doc_Id__c);
                }
            } else {
                isError = true;
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Info,'No records found with Request Status = "Data Verified" or "System Verified".');
                ApexPages.addMessage(myMsg);
            }
        }
    }
    
    public PageReference nextPolicyDocument(){
        isRecordUpdated = false;
        policyIdentifiersCase = '';
        if(curretndocument < (totaldocuments-1)){
            curretndocument = curretndocument + 1;
            policydocumentcase = lstAdditionalPolicyDocs[curretndocument];
            if(policydocumentcase.Policy_Identifiers__c != null){
                policyIdentifiersCase += policydocumentcase.Policy_Identifiers__c;
            }
            if(policydocumentcase.Additional_Policy_Identifiers__c != null){
                if(string.isnotblank(policyIdentifiersCase)){
                    policyIdentifiersCase += ';';
                }
                List<string> arrAddPI = policydocumentcase.Additional_Policy_Identifiers__c.split(';');
                List<string> lstPIs = new List<string>();
                for(string PI: arrAddPI){
                    if(string.isnotblank(PI)){
                        lstPIs.add(PI.trim());
                    }
                }
                policyIdentifiersCase += string.join(lstPIs, ';');
            }
            policydocumentcert = new Policy_Document_On_Certificate__c(); 
            if(mapPolicyDocumentsCerts.containskey(lstAdditionalPolicyDocs[curretndocument].Source_Policy_Doc_Id__c)){
                policydocumentcert = mapPolicyDocumentsCerts.get(lstAdditionalPolicyDocs[curretndocument].Source_Policy_Doc_Id__c);
            }
            return null;
        } else {
            PageReference pg = new PageReference('/'+objCase.Id);
            return pg;
        }
    }
    
    public void SyncPolicyDocument(){
        SavePoint sp = Database.setSavepoint();
        try {
            //sync policy documents
            boolean isAnyChanged = false;
            string Action = '';
            if(policydocumentcert.Id != null) {
                if(policydocumentcase.Action__c == 'Delete'){
                    Action = 'Deleted Policy Document and its Associations';
                } else {
                    Action = 'Updated from Case';
                }
            } else {
                Action = 'Added from Case';
            } 
            string NotesForChangedFields = '*Synced From Case Number: '+objCase.CaseNumber+'*';
            NotesForChangedFields += '\nCase Policy Document ID: '+ policydocumentcase.Name +' and Root Policy Document ID: '+(policydocumentcert.Id != null ? policydocumentcert.Name : '{NewPDCertId}')+'';
            NotesForChangedFields += '\nSync Action Performed: '+ Action +'\n';
            if(policydocumentcert.Document_Link__c != policydocumentcase.Document_Link__c){
                isAnyChanged = true;
                NotesForChangedFields += 'Updated Document Link from '+policydocumentcert.Document_Link__c + ' to ' + policydocumentcase.Document_Link__c+ '.\n';
            }
            if(policydocumentcert.Document_Type__c != policydocumentcase.Document_Type__c){
                isAnyChanged = true;
                NotesForChangedFields += 'Updated Document Type from '+policydocumentcert.Document_Type__c + ' to ' + policydocumentcase.Document_Type__c+ '.\n';
            }
            if(policydocumentcert.Document_Last_Updated_Date__c != policydocumentcase.Document_Last_Updated_Date__c){
                isAnyChanged = true;
                string caselastupdatedate = 'null';
                string certlastupdatedate = 'null';
                if(policydocumentcert.Document_Last_Updated_Date__c != null) {
                    certlastupdatedate = Datetime.newInstance(policydocumentcert.Document_Last_Updated_Date__c, Time.newInstance(0, 0,0, 0)).format('MM/dd/YYYY');
                }
                if(policydocumentcase.Document_Last_Updated_Date__c != null) {
                    caselastupdatedate = Datetime.newInstance(policydocumentcase.Document_Last_Updated_Date__c, Time.newInstance(0, 0,0, 0)).format('MM/dd/YYYY');
                }
                NotesForChangedFields += 'Updated Document Last Updated Date from '+certlastupdatedate  + ' to ' + caselastupdatedate + '.\n';
            }
            if(policydocumentcert.Associated_Trust_Bits__c != policydocumentcase.Associated_Trust_Bits__c){
                isAnyChanged = true;
                NotesForChangedFields += 'Updated Associated Trust Bits from '+policydocumentcert.Associated_Trust_Bits__c + ' to ' + policydocumentcase.Associated_Trust_Bits__c + '.\n';
            }   
            if(policydocumentcert.Policy_Identifiers__c != policyIdentifiersCase){
                isAnyChanged = true;
                NotesForChangedFields += 'Updated Policy Identifier from '+policydocumentcert.Policy_Identifiers__c + ' to ' + policyIdentifiersCase+ '.\n';
            } 
            if(policydocumentcert.Comments__c != policydocumentcase.Comments__c){
                isAnyChanged = true;
                NotesForChangedFields += 'Updated Comments from '+policydocumentcert.Comments__c + ' to ' + policydocumentcase.Comments__c+ '.\n';
            }
            policydocumentcert.Associated_Trust_Bits__c = policydocumentcase.Associated_Trust_Bits__c;
            policydocumentcert.Comments__c = policydocumentcase.Comments__c;
            policydocumentcert.Document_Last_Updated_Date__c = policydocumentcase.Document_Last_Updated_Date__c;
            policydocumentcert.Document_Link__c = policydocumentcase.Document_Link__c;
            policydocumentcert.Document_Type__c = policydocumentcase.Document_Type__c;
            policydocumentcert.Policy_Identifiers__c = policyIdentifiersCase;
            policydocumentcert.Sync_Policy_Doc_Id__c = policydocumentcase.Id;
            if(policydocumentcert.Id == null || (policydocumentcert.Sync_Policy_Doc_Id__c != policydocumentcase.Id)){
                isAnyChanged = true;
                if(policydocumentcert.Sync_Policy_Doc_Id__c != null) {
                    NotesForChangedFields += 'Updated Case Policy Doc Id from '+policydocumentcert.Sync_Policy_Doc_Id__r.Name + ' to ' + policydocumentcase.Name + '.\n';
                } else {
                    NotesForChangedFields += 'Created Case Policy Doc Id to ' + policydocumentcase.Name + '.\n';
                }
            }
            if(policydocumentcase.Action__c == 'Delete'){
                isAnyChanged = true;
                policydocumentcert.Is_Deleted__c = true;
            } else {
                if(policydocumentcert.Is_Deleted__c){
                    isAnyChanged = true;
                    NotesForChangedFields += '\nUndeleted Policy Document.';
                }
                policydocumentcert.Is_Deleted__c = false;
            }
            upsert policydocumentcert;
            
            
            //update Source on Policy Document Case and complete status
            policydocumentcase.Document_Verified__c = 'Complete';
            policydocumentcase.Source_Policy_Doc_Id__c = policydocumentcert.Id;
            update policydocumentcase;
            
            map<Id, PolicyDocumentAssociation_On_Certificate__c> mapOfExistingAssociation = new map<Id, PolicyDocumentAssociation_On_Certificate__c>();
            for(PolicyDocumentAssociation_On_Certificate__c PDA: policydocumentcert.Policy_Document_Associations__r){
                mapOfExistingAssociation.put(PDA.Certificate_Name__c, PDA);
            }
            //set of root certificates
            List<PolicyDocumentAssociation_On_Certificate__c> lstPDAsToUpsert = new List<PolicyDocumentAssociation_On_Certificate__c>();
            List<PolicyDocumentAssociation_On_Certificate__c> lstPDAsToDelete = new List<PolicyDocumentAssociation_On_Certificate__c>();
            string ChangesforAssociations = '';
            string NotesDeletedAssociations = '';
            for(Policy_Document_Association_On_Case__c PDAC: policydocumentcase.Policy_Document_Associations__r){
                /*if(PDAC.Source_Policy_Doc_Assoc_Id__c != null && PDAC.Source_Policy_Doc_Assoc_Id__c != '' 
                            && setOfExistingAssociationIds.contains(PDAC.Source_Policy_Doc_Assoc_Id__c)){
                    setOfExistingAssociationIds.remove(PDAC.Source_Policy_Doc_Assoc_Id__c);
                    
                }*/
                if(PDAC.Action__c != 'Delete' && policydocumentcase.Action__c != 'Delete'){
                    PolicyDocumentAssociation_On_Certificate__c PDAssociation = new PolicyDocumentAssociation_On_Certificate__c();
                    PDAssociation.Certificate_Name__c = PDAC.Certificate_Name__c;
                    PDAssociation.Source_Policy_Doc_Assoc_Id__c = PDAC.Id;
                    PDAssociation.Is_Deleted__c = false;
                    if(mapOfExistingAssociation.containskey(PDAC.Certificate_Name__c)){
                        PDAssociation.Id = mapOfExistingAssociation.get(PDAC.Certificate_Name__c).Id;
                        mapOfExistingAssociation.remove(PDAC.Certificate_Name__c);
                    } else {
                        PDAssociation.Policy_Document__c = policydocumentcert.Id;
                        ChangesforAssociations += '- '+ PDAC.Certificate_Name__r.Name + ' (SHA-256: '+PDAC.Certificate_Name__r.SHA_256_Fingerprint__c +').\n';
                        isAnyChanged = true;
                    }
                    lstPDAsToUpsert.add(PDAssociation);
                } else if(mapOfExistingAssociation.containskey(PDAC.Certificate_Name__c)) {
                    PolicyDocumentAssociation_On_Certificate__c PDA = mapOfExistingAssociation.get(PDAC.Certificate_Name__c);
                    PDA.Source_Policy_Doc_Assoc_Id__c = PDAC.Id;
                    NotesDeletedAssociations += '- '+ PDA.Certificate_Name__r.Name + ' (SHA-256: '+PDA.Certificate_Name__r.SHA_256_Fingerprint__c +').\n';
                    PDA.Is_Deleted__c = true;
                    lstPDAsToUpsert.add(PDA);
                    isAnyChanged = true;
                }
            }
            //upsert associations
            if(lstPDAsToUpsert.size() > 0){
                upsert lstPDAsToUpsert;
                List<Policy_Document_Association_On_Case__c> lstPolicyDocAssocitionsCases = new List<Policy_Document_Association_On_Case__c>();
                //update source Id for newly created associations
                for(PolicyDocumentAssociation_On_Certificate__c PDA: lstPDAsToUpsert){
                    if(PDA.Source_Policy_Doc_Assoc_Id__c != null) {
                        Policy_Document_Association_On_Case__c PDAC = new Policy_Document_Association_On_Case__c(Id = PDA.Source_Policy_Doc_Assoc_Id__c);
                        PDAC.Source_Policy_Doc_Assoc_Id__c = PDA.Id;
                        lstPolicyDocAssocitionsCases.add(PDAC);
                    }
                }
                update lstPolicyDocAssocitionsCases;
            }
            
            //notes for newly added associations.
            if(string.isnotblank(ChangesforAssociations )){
                NotesForChangedFields += '\nAssociations Added:\n'+ChangesforAssociations;
            }
            
            //delete associations
            /*
            if(mapOfExistingAssociation.size() > 0){
                for(Id certId: mapOfExistingAssociation.keyset()){
                    PolicyDocumentAssociation_On_Certificate__c PDA = mapOfExistingAssociation.get(certId);
                    NotesDeletedAssociations += '- '+ PDA.Certificate_Name__r.Name + ' (SHA-256: '+PDA.Certificate_Name__r.SHA_256_Fingerprint__c +').\n';
                    lstPDAsToDelete.add(PDA);
                    isAnyChanged = true;
                }
            }
            if(lstPDAsToDelete.size() > 0) {
                delete lstPDAsToDelete;
            }*/
            //notes for deleted associations.
            if(string.isnotblank(NotesDeletedAssociations)){
                NotesForChangedFields += '\nAssociations Deleted:\n'+NotesDeletedAssociations;
            }
            //update on CA Owner
            if(!isSyncOnCAOwner){
                List<Account> lstCAOwner = new List<Account>([Select Id,Document_Repository__c ,Document_Repository_Description__c,
                         Policy_Identifiers__c FROM Account Where Id =: objCase.AccountId]);
                List<Account> lstAccToUpdates = new List<Account>();
                for(Account acc: lstCAOwner){
                    boolean isAccUpdate = false;
                    Account newAccToUpdate = new Account(Id = acc.Id);
                    if(acc.Document_Repository__c != objCase.CA_Document_Repository__c ||
                        acc.Document_Repository_Description__c != objCase.Policy_Documentation__c){
                        newAccToUpdate.Document_Repository__c = objCase.CA_Document_Repository__c;
                        newAccToUpdate.Document_Repository_Description__c = objCase.Policy_Documentation__c;
                        isAccUpdate = true;
                    }
                    //update additional policy identifiers on ca owner
                    //system.debug('policydocumentcase.Additional_Policy_Identifiers__c  ::: '+policydocumentcase.Additional_Policy_Identifiers__c);
                    if(policydocumentcase.Additional_Policy_Identifiers__c != null){
                        List<string> lstCAOwnerPolicyIdentifiers = new List<string>();
                        if(acc.Policy_Identifiers__c != null) {
                            if(acc.Policy_Identifiers__c.contains(';')){
                                lstCAOwnerPolicyIdentifiers = acc.Policy_Identifiers__c.split(';');
                            } else if(acc.Policy_Identifiers__c.contains(',')){
                                lstCAOwnerPolicyIdentifiers = acc.Policy_Identifiers__c.split(',');
                            } else {
                                lstCAOwnerPolicyIdentifiers.add(acc.Policy_Identifiers__c);
                            }
                        }
                        List<string> arrAddPI = policydocumentcase.Additional_Policy_Identifiers__c.split(';');
                        Set<String> setCAOwnerPIs = new Set<String>();
                        for(string PI: arrAddPI){
                            if(string.isnotblank(PI)){
                                setCAOwnerPIs.add(PI.trim());
                            }
                        }
                        for(string CAPI: lstCAOwnerPolicyIdentifiers){
                            if(string.isnotblank(CAPI)){
                                setCAOwnerPIs.add(CAPI.trim());
                            }
                        }
                        //system.debug('setCAOwnerPIs ::: '+setCAOwnerPIs);
                        List<string> lst = new List<string>();
                        lst.addall(setCAOwnerPIs);
                        lst.sort();
                        newAccToUpdate.Policy_Identifiers__c = string.join(lst, '; ');
                        isAccUpdate = true;
                    }
                    if(isAccUpdate){
                        lstAccToUpdates.add(newAccToUpdate);
                    }
                }
                if(lstAccToUpdates.size() > 0) {
                    AccountTriggerHelper.isRecursiveUpdate = true;
                    update lstAccToUpdates;
                }
                isSyncOnCAOwner = true;
            }
            policydocumentcert = [Select Id, Name, Associated_Trust_Bits__c,
                    Comments__c,Document_Last_Updated_Date__c,Document_Link__c,Document_Type__c,Policy_Identifiers__c,Sync_Policy_Doc_Id__c,
                    (Select Id, Name, Certificate_Name__c,Policy_Document__c, Certificate_Name__r.Name, Certificate_Name__r.Status__c,
                    Certificate_Name__r.Microsoft_Status__c, Certificate_Name__r.Valid_From_GMT__c,Certificate_Name__r.Valid_To_GMT__c,
                    Certificate_Name__r.SHA_256_Fingerprint__c,Is_Deleted__c,Source_Policy_Doc_Assoc_Id__c from Policy_Document_Associations__r Order by Certificate_Name__r.Name) from 
                    Policy_Document_On_Certificate__c Where Id =: policydocumentcert.Id Limit 1];
            if(NotesForChangedFields.contains('{NewPDCertId}')){
                NotesForChangedFields = NotesForChangedFields.replace('{NewPDCertId}', policydocumentcert.Name);    
            }
            //create notes
            if(isAnyChanged){
                Policy_Document_History__c PDH = new Policy_Document_History__c(Policy_Document__c = policydocumentcert.Id, Notes__c = NotesForChangedFields);
                insert PDH;
            }
            
            isRecordUpdated = true;
        } catch (Exception ex){
            isError = true;
            Database.rollback(sp);
            Apexpages.addMessages(ex);
        }
    }
    
    //This method is used to add only to cover code covarage for deployment
     public static void codecoveragetest() {
    string s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
    s1 = 'this is test code';
   
  }
}