objects/Account.object
<CustomObject>
    <fields>
        <fullName>Certificate_Policy_CP__c</fullName>
        <description>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Certificate Policy (CP)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Company_Website__c</fullName>
        <inlineHelpText>Website URL</inlineHelpText>
        <label>Company Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Geographic_Focus__c</fullName>
        <label>Geographic Focus</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SHA_256_Fingerprint__c</fullName>
        <label>SHA-256 Fingerprint</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vetted_Government_CA__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Government root certificate that has been vetted, but not included in Mozilla’s Root Store.</inlineHelpText>
        <label>Vetted Government CA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PolicyDocumentAssociation_On_Certificate__c.object
<CustomObject>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certificate Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Policy Document Associations (On Certificate)</relationshipLabel>
        <relationshipName>Policy_Document_Associations_OnCert</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Last_Update_Date__c</fullName>
        <formula>Policy_Document__r.Document_Last_Updated_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Last Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Link__c</fullName>
        <formula>Policy_Document__r.Document_Link__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>Text (Policy_Document__r.Document_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted?</label>
        <type>Checkbox</type>
    </fields>
    <label>Policy Document Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Document Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VettedGovernmentCACertsReportController.cls
/*******************************************************************************************************
 Name: VettedGovernmentCACertsReportController

 Dependencies:  VettedGovernmentCACertsReportController controller class, VettedGovernmentCACertsReportCtrlTest, 
 VettedGovernmentCACertsReport, VettedGovernmentCACertsCSV, VettedGovernmentCACertsReportInternal vf pages

 Description: This report lists root certificates for which 'Vetted Government CA' is checked.
 
 Instructions:  None

 *******************************************************************************************************
 Revision History:
 
     7/9/2020 - Created new

 ******************************************************************************************************/
 
public without sharing class VettedGovernmentCACertsReportController {

    public transient List<wrapAccounts> lstwrapAccounts {get; set;}
 
    //constructor method for standard controller
    public VettedGovernmentCACertsReportController() {  
        lstwrapAccounts = new List<wrapAccounts>();
        List<Account> accountSoLst = [SELECT Name, 
                                             ParentId, 
                                             Parent.Name, 
                                             Parent.Company_Website__c, 
                                             Parent.Geographic_Focus__c,
                                             Valid_To_GMT__c,
                                             SHA_256_Fingerprint__c,
                                             Standard_Audit__c,
                                             Certificate_Policy_CP__c ,
                                             X_509_Certificate_PEM__c,
                                             Standard_Audit_Period_End_Date__c,
                                             Status__c, Microsoft_Status__c
                                             /*(Select Id, 
                                                    Document_Link__c, 
                                                    Document_Type__c 
                                            FROM Policy_Document_Associations_OnCert__r 
                                            WHERE Is_Deleted__c = false
                                            ORDER BY Document_Last_Update_Date__c desc)*/
                                      FROM Account
                                      WHERE RecordType.Name In ('Root Certificate')
                                      AND Vetted_Government_CA__c = True
                                      AND Valid_To_GMT__c >= Today
                                      ORDER BY Parent.Name, Name];
                                      
                                      /* Status__c In ('Included','Change Requested') */
                                      
       // if we are generating a CSV file then we need to replace the double quotes in all text fields with null
       if(Test.IsRunningTest() || (accountSoLst != null && accountSoLst.size() > 0)){
            for(Account accountSo : accountSoLst){
                if(ApexPages.currentPage().getUrl() != null && ApexPages.currentPage().getUrl().contains('CSV')){ 
                    if(accountSo.name !=null && accountSo.name.length() > 0) 
                        accountSo.name = accountSo.name.replace('"',''); 
                    if(accountSo.parent.name !=null && accountSo.parent.name.length() > 0) 
                        accountSo.parent.name = accountSo.parent.name.replace('"','');  
                    if(accountSo.X_509_Certificate_PEM__c!=null && accountSo.X_509_Certificate_PEM__c.length() > 0) 
                        accountSo.X_509_Certificate_PEM__c= accountSo.X_509_Certificate_PEM__c.replace('"','');
                }
                //fill wrapper
                wrapAccounts wrapAcc = new wrapAccounts();
                string strCP = accountSo.Certificate_Policy_CP__c;
                string strCPS = '';
                /*for(PolicyDocumentAssociation_On_Certificate__c PDAC: accountSo.Policy_Document_Associations_OnCert__r){
                    if(PDAC.Document_Type__c != null){
                        if(PDAC.Document_Type__c == 'CP' || PDAC.Document_Type__c == 'CP/CPS'){
                            if(string.isnotblank(strCP)) strCP += '; ';
                            strCP += PDAC.Document_Link__c;
                        }
                        if(PDAC.Document_Type__c == 'CPS' || PDAC.Document_Type__c == 'CP/CPS'){
                            if(string.isnotblank(strCPS)) strCPS += '; ';
                            strCPS += PDAC.Document_Link__c;
                        }
                    }
                } */ 
                wrapAcc.objAccount = accountSo;
                wrapAcc.CP = strCP;
                wrapAcc.CPS = strCPS;
                lstwrapAccounts.add(wrapAcc);
            }
        }
    }
  
     
    String CurrentDate = ' ';
 
    // Get current Datetime in long date format   
    public String getCurrentDate() {
        Datetime cDT = System.now();
        CurrentDate = cDT.format('MMMM d, yyyy');
        return CurrentDate;
    }
    
    public class wrapAccounts {
        public string CP {get; set;}
        public string CPS {get; set;}
        public Account objAccount {get; set;}
        public wrapAccounts(){
            CP = '';
            CPS = '';
            objAccount = new Account();
        }
    }
}