objects/Account.object
<CustomObject>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <description>This field is hyperlink to Account Name. Mainly used in reports.</description>
        <formula>HYPERLINK(Id, Name, &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Certificate Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/File_Archive__c.object
<CustomObject>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CA Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>File Archive</relationshipLabel>
        <relationshipName>File_Archive</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Audit</fullName>
                </value>
                <value>
                    <fullName>Code Signing Audit</fullName>
                </value>
                <value>
                    <fullName>BR Audit</fullName>
                </value>
                <value>
                    <fullName>EV SSL Audit</fullName>
                </value>
                <value>
                    <fullName>EV Code Signing Audit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Link__c</fullName>
        <label>External Link</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Internal_Link__c</fullName>
        <label>Internal Link</label>
        <type>TextArea</type>
    </fields>
    <label>File Archive</label>
    <nameField>
        <displayFormat>A{00000}</displayFormat>
        <label>Archive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Archive</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/File_Archive_Association__c.object
<CustomObject>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certificate Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>File Archive Associations</relationshipLabel>
        <relationshipName>File_Archive_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>IF (INCLUDES (File_Archive__r.Document_Type__c , &quot;Standard Audit&quot; ), &quot;Standard Audit; &quot;, null) &amp; 
IF (INCLUDES (File_Archive__r.Document_Type__c, &quot;Code Signing Audit&quot; ), &quot;Code Signing Audit; &quot;, null) &amp;
IF (INCLUDES (File_Archive__r.Document_Type__c, &quot;BR Audit&quot; ), &quot;BR Audit; &quot;, null) &amp; 
IF (INCLUDES (File_Archive__r.Document_Type__c , &quot;EV SSL Audit&quot; ), &quot;EV SSL Audit; &quot;, null) &amp; 
IF (INCLUDES (File_Archive__r.Document_Type__c, &quot;EV Code Signing Audit&quot; ), &quot;EV Code Signing Audit; &quot;, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Archive__c</fullName>
        <label>Archive ID</label>
        <referenceTo>File_Archive__c</referenceTo>
        <relationshipLabel>File Archive Associations</relationshipLabel>
        <relationshipName>File_Archive_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>File Archive Association</label>
    <nameField>
        <displayFormat>AD{000000}</displayFormat>
        <label>Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Archive Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FileArchiveAndAssociationsControllerTest.cls
/*
    Description: Test class for FileArchiveAndAssociationsController
*/
@isTest
public with sharing class FileArchiveAndAssociationsControllerTest {
    public static string strOrgInstance = System.URL.getSalesforceBaseURL().toExternalForm();
    static testmethod void TestFileArchiveAndAssociations(){
        Account caOwnerAccount = TestUtils.getCAOwner();
        insert caOwnerAccount;
        
        Account rootAccount = TestUtils.getRootCertificate(caOwnerAccount.Id);
        insert rootAccount;
        
        File_Archive__c fArc1 = new File_Archive__c(CA_Owner__c = caOwnerAccount.Id, 
        External_Link__c = 'https://cert.webtrust.org/SealFile?seal=1987&file=pdf', 
        Internal_Link__c = ''+strOrgInstance+'/servlet/servlet.FileDownload?file=00P21000000cRRiEAM',
        Document_Type__c = 'Standard Audit; BR Audit');
        insert fArc1;
        
        File_Archive_Association__c fa = new File_Archive_Association__c(File_Archive__c = fArc1.Id, Certificate_Name__c = rootAccount.id);
        insert fa;
        
        FileArchiveAndAssociationsController controller = new FileArchiveAndAssociationsController();
    }
}