objects/Auditor__c.object
<CustomObject>
    <fields>
        <fullName>Auditor_Website__c</fullName>
        <label>Auditor Website</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Public comments</inlineHelpText>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Auditor</label>
    <nameField>
        <label>Auditor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auditors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auditor_Location__c.object
<CustomObject>
    <fields>
        <fullName>Auditor_Qualifications__c</fullName>
        <inlineHelpText>URL to third-party website attesting to the qualifications of this Auditor to issue WebTrust, ETSI EN 319 411, or ETSI TS 102 042 audit statements.</inlineHelpText>
        <label>Auditor Qualifications</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Auditor__c</fullName>
        <label>Auditor</label>
        <referenceTo>Auditor__c</referenceTo>
        <relationshipLabel>Auditor Locations</relationshipLabel>
        <relationshipName>Auditor_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Public comments</inlineHelpText>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Auditor Location</label>
    <nameField>
        <label>Auditor Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auditor Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AuditorQualificationsReportController.cls
/********************************************************************************************************************

  AuditorQualificationsReportController is a controller for AuditorQualificationsReport VF pages to list all 
  Auditors and Auditor Locations. Report name used is'Auditor Qualifications Report'. 
  
 *********************************************************************************************************************/

public class AuditorQualificationsReportController{

    public transient List<Auditor_Location__c> auditorAndLocationSoLst {get;set;}
    
    // constructor method for standard controller
    public AuditorQualificationsReportController() {   
    
        auditorAndLocationSoLst =  [SELECT Auditor__r.Name, 
                                    Auditor__r.Auditor_Website__c,
                                    Auditor_Location__c.Name, 
                                    Auditor_Location__c.Auditor_Qualifications__c,
                                    Auditor_Location__c.Comments__c
                                    FROM Auditor_Location__c
                                    ORDER BY Auditor__r.Name, Name];   
    }
    
    String CurrentDate = ' ';
    // Get current Datetime in long date format   
    public String getCurrentDate() {
    
        Datetime cDT = System.now();
        CurrentDate = cDT.format('MMMM d, yyyy');
        return CurrentDate;
    }
}