objects/CA_Comm_Question__c.object
<CustomObject>
    <fields>
        <fullName>CA_Comm__c</fullName>
        <label>CA Comm</label>
        <referenceTo>CA_Communication__c</referenceTo>
        <relationshipLabel>CA Comm Questions</relationshipLabel>
        <relationshipName>CA_Comm_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Default_Text__c</fullName>
        <inlineHelpText>Default text can be added here for text box</inlineHelpText>
        <label>Default Text</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No.</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single Select (Radio buttons)</fullName>
                </value>
                <value>
                    <fullName>Multi Select (Check boxes)</fullName>
                </value>
                <value>
                    <fullName>Free Text (Multi line text box)</fullName>
                </value>
                <value>
                    <fullName>Date Type</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Response_Option_1__c</fullName>
        <label>Response Option 1</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_2__c</fullName>
        <label>Response Option 2</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CA Comm Question</label>
    <nameField>
        <displayFormat>Q{00000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Comm Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CA_Communication__c.object
<CustomObject>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CA Communication (Edit)</label>
    <nameField>
        <label>CA Comm Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CA Communications (Edit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CACommunicationSurveySampleContlrTest.cls
@isTest
public class CACommunicationSurveySampleContlrTest {
    private static @testsetup void setupData(){
        
        CA_Communication__c survey = new CA_Communication__c(Name = 'test survey0', Expiration_Date__c = System.today().addDays(7),
        Message__c = 'test message');
        insert survey;
        
        CA_Comm_Question__c question1 = new CA_Comm_Question__c(CA_Comm__c = survey.Id, Order_No__c = 1, Question__c = 'que 1', 
        Question_Type__c = 'Single Select (Radio buttons)',
        Required__c = true, Response_Option_1__c = 'Yes', Response_Option_2__c = 'No');
        //insert question1;
        
        CA_Comm_Question__c question2 = new CA_Comm_Question__c(CA_Comm__c = survey.Id, Order_No__c = 2, Question__c = 'que 2', 
        Question_Type__c = 'Multi Select (Check boxes)',
        Required__c = true, Response_Option_1__c = 'Yes', Response_Option_2__c = 'No');
        //insert question2;
        
        CA_Comm_Question__c question3 = new CA_Comm_Question__c(CA_Comm__c = survey.Id, Order_No__c = 3, Question__c = 'que 3', 
        Question_Type__c = 'Free Text (Multi line text box)',
        Required__c = false, Default_Text__c = 'Default_Text__c');
        
        CA_Comm_Question__c question4 = new CA_Comm_Question__c(CA_Comm__c = survey.Id, Order_No__c = 3, Question__c = 'que 4', 
        Question_Type__c = 'Date Type', Required__c = false);
        
        insert new List<CA_Comm_Question__c>{question1, question2, question3, question4};
    }
    
    static testmethod void testCase1(){
        
        PageReference pref = Page.CACommunicationSurveySample;
        Test.setCurrentPage(pref);
        
        CA_Communication__c survey = [SELECT Id FROM CA_Communication__c WHERE Name = 'test survey0' LIMIT 1];
        ApexPages.currentPage().getParameters().put('CACommunicationId', survey.Id);
        
        CACommunicationSurveySampleController obj = new CACommunicationSurveySampleController();
    }
    
    static testmethod void testCase2(){
        
        PageReference pref = Page.CACommunicationSurveySample;
        Test.setCurrentPage(pref);
        CA_Comm_Question__c question1 = [SELECT Id FROM CA_Comm_Question__c LIMIT 1];
        //CA_Communication__c survey = [SELECT Id FROM CA_Communication__c WHERE Name = 'test survey0' LIMIT 1];
        ApexPages.currentPage().getParameters().put('CACommunicationId', question1.Id);
        
        CACommunicationSurveySampleController obj = new CACommunicationSurveySampleController();
    }
    
    static testmethod void testCase3(){
        
        PageReference pref = Page.CACommunicationSurveySample;
        Test.setCurrentPage(pref);
        
        CA_Communication__c survey = [SELECT Id FROM CA_Communication__c WHERE Name = 'test survey0' LIMIT 1];
        ApexPages.currentPage().getParameters().put('CACommunicationId', 'abcd1234');
        
        CACommunicationSurveySampleController obj = new CACommunicationSurveySampleController();
    }
}