objects/CA_Comm_Question__c.object
<CustomObject>
    <fields>
        <fullName>CA_Comm__c</fullName>
        <label>CA Comm</label>
        <referenceTo>CA_Communication__c</referenceTo>
        <relationshipLabel>CA Comm Questions</relationshipLabel>
        <relationshipName>CA_Comm_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Default_Text__c</fullName>
        <inlineHelpText>Default text can be added here for text box</inlineHelpText>
        <label>Default Text</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No.</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single Select (Radio buttons)</fullName>
                </value>
                <value>
                    <fullName>Multi Select (Check boxes)</fullName>
                </value>
                <value>
                    <fullName>Free Text (Multi line text box)</fullName>
                </value>
                <value>
                    <fullName>Date Type</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Response_Option_10__c</fullName>
        <label>Response Option 10</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_11__c</fullName>
        <label>Response Option 11</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_12__c</fullName>
        <label>Response Option 12</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_1__c</fullName>
        <label>Response Option 1</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_2__c</fullName>
        <label>Response Option 2</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_3__c</fullName>
        <label>Response Option 3</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_4__c</fullName>
        <label>Response Option 4</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_5__c</fullName>
        <label>Response Option 5</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_6__c</fullName>
        <label>Response Option 6</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_7__c</fullName>
        <label>Response Option 7</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_8__c</fullName>
        <label>Response Option 8</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Option_9__c</fullName>
        <label>Response Option 9</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CA Comm Question</label>
    <nameField>
        <displayFormat>Q{00000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Comm Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CA_Communication__c.object
<CustomObject>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CA Communication (Edit)</label>
    <nameField>
        <label>CA Comm Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CA Communications (Edit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CACommunicationSurveySampleController.cls
public class CACommunicationSurveySampleController {
    
    public String selectedSurveyId{get; private set;}//selected survey id by user on page
    public List<Question> lstQuestions {get; set;}//list of Question to display on to display on VF page
    public String communicationTitle {get; private set;}//survey title on survey form page
    public String communicationMessage {get; private set;}//survey message on survey form page
    public Boolean hasError{get; private set;}//will be true in case of errors
    
    public class SurveyException extends Exception{}//exceptions
    
    public CACommunicationSurveySampleController(){
         
         this.lstQuestions = new List<Question>();
         this.hasError = true;
         this.selectedSurveyId = ApexPages.currentPage().getParameters().get('CACommunicationId');
         Id surveyId;
         
        try{
            surveyId = Id.valueOf(selectedSurveyId);
            List<CA_Communication__c> communications = [SELECT Id, Name, Message__c, Expiration_Date__c
                                                        FROM CA_Communication__c
                                                        WHERE Id = :surveyId];
             
             if(communications.size() > 0){
                 
                 communicationTitle = communications[0].Name;
                 communicationMessage = communications[0].Message__c != null ? communications[0].Message__c.replaceAll('\n', '<br/>') : null;
                 fetchReadOnlySurvey();
                 this.hasError = false;
             }else{
                 throw new SurveyException('No survey found for specified link.');
             }
             
        }catch(StringException stEx){//this exception will be thrown if the SurveyId is not valid
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Invalid Survey Id.'));
        }catch(SurveyException sExp){//this exception will be thrown if the SurveyId is valid but Survey not found. may be deleted.
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, sExp.getMessage()));
        }catch(Exception exp){//any general exception will be trapped here.
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, exp.getMessage()));
        }
    }
    
    //fetch read only survey
    public void fetchReadOnlySurvey(){
        
        for(CA_Comm_Question__c que : [SELECT Id, Name, CA_Comm__r.Name, CA_Comm__r.Message__c, Required__c, Order_No__c, Question__c, 
                                        Question_Type__c, Response_Option_1__c, Response_Option_2__c, 
                                        Response_Option_3__c, Response_Option_4__c, Response_Option_5__c, Response_Option_6__c, Response_Option_7__c,
                                        Default_Text__c,
                                        Response_Option_8__c, Response_Option_9__c, Response_Option_10__c, Response_Option_11__c, Response_Option_12__c
                                        FROM CA_Comm_Question__c
                                        WHERE CA_Comm__c = :selectedSurveyId
                                        ORDER BY Order_No__c ASC]){
            
            lstQuestions.add(new Question(que));
        }
    }
    
    /** Class: question
    *  Retrieves the question information and puts it in the question object
    */      
    public class Question{
        
      public String Id {get; private set;}
      public String iQuestion {get; private set;}
      public boolean isRequired {get; private set;}//true indicates question is mandatory
      public String renderSelectRadio {get; private set;}
      public String selectedOption {get; set;}//not required I guess
      public List<SelectOption> singleOptions{get; set;}
      public String renderSelectCheckboxes {get; set;}
      public List<String> selectedOptions {get; set;}
      public List<SelectOption> multiOptions {get; set;}
      public String renderFreeText {get; private set;}
      public String choices {get; set;}
      public Date dateResonse{get; set;}
      public String renderDateType{get; set;}
      
     public Question(CA_Comm_Question__c sq) {
        
        Id = sq.Id;
        iQuestion = sq.Question__c != null ? sq.Question__c.replaceAll('\n', '<br/>') : null;
        isRequired = sq.Required__c;
        choices = sq.Default_Text__c;
        selectedOption = '';
        selectedOptions = new List<String>();
        singleOptions = new List<SelectOption>();
        multiOptions = new List<SelectOption>();
        renderDateType = 'false';
        dateResonse = null;
        
        if(sq.Question_Type__c == 'Multi Select (Check boxes)'){
                
            renderSelectCheckboxes = 'true';
            multiOptions = stringToSelectOptions(sq);
            renderSelectRadio='false';
            renderFreeText='false';
            selectedOption = '';
        }
        
        else if(sq.Question_Type__c == 'Single Select (Radio buttons)'){//radio vertical
            
            renderSelectRadio = 'true';
            singleOptions = stringToSelectOptions(sq);
            renderSelectCheckboxes='false';
            renderFreeText = 'false';
            selectedOption = '';
            selectedOptions = new List<String>();
          }
              
        else if (sq.Question_Type__c == 'Free Text (Multi line text box)'){
            
            renderFreeText = 'true';
            renderSelectRadio= 'false';
            renderSelectCheckboxes = 'false';
        }
        
        else if(sq.Question_Type__c == 'Date Type'){
            
            renderSelectRadio = 'false';
            renderSelectCheckboxes='false';
            renderFreeText = 'false';
            renderDateType = 'true';
        }
    }
    //this will prepare the list of options available to user for a particular question (passed as an argument) - there are 12 responses can be available
    public List<SelectOption> stringToSelectOptions(CA_Comm_Question__c questionSO){
        
        Integer index = 0;
        List<SelectOption> lstOptions = new List<SelectOption>();
        
        for(Integer i = 0; i < 12; i++){
            
            String fieldAPI = 'Response_Option_'+String.valueOf(i+1)+'__c';
            fieldAPI = String.valueOf(questionSO.get(fieldAPI));
            if(fieldAPI != '' && fieldAPI != null){
                lstOptions.add(new SelectOption(String.valueOf(i), fieldAPI));
                index++;
            }
        }
        
        return lstOptions;
    }
  }
}