objects/Case.object
<CustomObject>
    <fields>
        <fullName>BR_Audit_Statement_Link__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>BR Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Statement_Link__c</fullName>
        <label>Code Signing Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Statement_Link__c</fullName>
        <description>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>EV SSL Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Statement_Link__c</fullName>
        <label>EV Code Signing Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Link__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseMessageInlinePageControllerTest.cls
/*
    Description: Test class for CaseMessageInlinePageController
    
*/
@isTest
public with sharing class CaseMessageInlinePageControllerTest {

    static testMethod void TestCaseCPACanadaURLChanged() {
        Account caOwnerAcc = TestUtils.getCAOwner();
        insert caOwnerAcc;
        
        Case caseSO = TestUtils.getCase(caOwnerAcc.Id);
        caseSO.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('CA Audit Update Request').getRecordTypeId();
        caseSO.Standard_Audit_Statement_Link__c = 'https://www.cpacanada.ca/generichandlers/aptifyattachmenthandler.ashx?attachmentid=221273';
        caseSO.Code_Signing_Audit_Statement_Link__c = 'https://www.cpacanada.ca/generichandlers/aptifyattachmenthandler.ashx?attachmentid=221273';
        caseSO.BR_Audit_Statement_Link__c = 'https://www.cpacanada.ca/generichandlers/aptifyattachmenthandler.ashx?attachmentid=221273';
        caseSO.EV_Audit_Statement_Link__c = 'https://www.cpacanada.ca/generichandlers/aptifyattachmenthandler.ashx?attachmentid=221273';
        caseSO.EV_Code_Signing_Audit_Statement_Link__c = 'https://www.cpacanada.ca/generichandlers/aptifyattachmenthandler.ashx?attachmentid=221273';
        insert caseSO;
        
        CaseMessageInlinePageController controller = new CaseMessageInlinePageController(new Apexpages.standardcontroller(caseSO));
                 
    }
}