objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auditor_Location_New__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Country where the Auditor who issued the standard audit statement is based out of. See &apos;List All Auditors&apos; below for choices. Send email to support@ccadb.org if your auditor is not listed.</inlineHelpText>
        <label>Auditor Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a valid value for selected Auditor</errorMessage>
            <filterItems>
                <field>Auditor_Location__c.Auditor__c</field>
                <operation>equals</operation>
                <valueField>$Source.Auditor_New__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Auditor_Location__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auditor_New__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Name of Auditor who issued the standard audit statement. See &apos;List All Auditors&apos; below for choices. Send email to support@ccadb.org if your auditor is not listed.</inlineHelpText>
        <label>Auditor</label>
        <referenceTo>Auditor__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auditor_Verified__c</fullName>
        <label>Auditor Verified?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Verified</fullName>
                    <default>true</default>
                    <label>Not Verified</label>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BR_Audit_ALV_Comments__c</fullName>
        <inlineHelpText>Explanation about why audit accepted when ALV status is FAIL </inlineHelpText>
        <label>BR Audit ALV Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Authenticity_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only when authenticity of audit statement has been confirmed </inlineHelpText>
        <label>BR Audit Authenticity Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Auto_Review_Results__c</fullName>
        <inlineHelpText>Results returned by ALV service</inlineHelpText>
        <label>BR Audit ALV Results</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Auto_Review_Status__c</fullName>
        <inlineHelpText>Status returned by ALV service</inlineHelpText>
        <label>BR Audit ALV Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Statement_Link_Verified__c</fullName>
        <inlineHelpText>Root Store Manager to verify data fields in BR Audit section</inlineHelpText>
        <label>BR Audit Verified?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Verified</fullName>
                    <default>true</default>
                    <label>Not Verified</label>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BR_Audit_Statement_Link__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>BR Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BR_Deviation_Comments__c</fullName>
        <label>BR Audit Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BR_Deviation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Issues or qualifications noted in audit statement</description>
        <inlineHelpText>Issues or qualifications noted in audit statement</inlineHelpText>
        <label>BR Audit Deviation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_ALV_Comments__c</fullName>
        <label>Code Signing Audit ALV Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_ALV_Results__c</fullName>
        <label>Code Signing Audit ALV Results</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_ALV_Status__c</fullName>
        <label>Code Signing Audit ALV Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Authenticity_Confirm__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Code Signing Audit Authenticity Confirm</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Statement_Link__c</fullName>
        <label>Code Signing Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Verified__c</fullName>
        <label>Code Signing Audit Verified?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Verified</fullName>
                    <default>true</default>
                    <label>Not Verified</label>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Code_Signing_Deviation_Comments__c</fullName>
        <label>Code Signing Audit Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Deviation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Issues or qualifications noted in audit statement</description>
        <inlineHelpText>Issues or qualifications noted in audit statement</inlineHelpText>
        <label>Code Signing Audit Deviation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Statement_Link__c</fullName>
        <description>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>EV SSL Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_SSL_Audit_ALV_Comments__c</fullName>
        <inlineHelpText>Explanation about why audit accepted when ALV status is FAIL </inlineHelpText>
        <label>EV SSL Audit ALV Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_SSL_Audit_Authenticity_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only when authenticity of audit statement has been confirmed </inlineHelpText>
        <label>EV SSL Audit Authenticity Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EV_SSL_Audit_Auto_Review_Results__c</fullName>
        <inlineHelpText>Results returned by ALV service</inlineHelpText>
        <label>EV SSL Audit ALV Results</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EV_SSL_Audit_Auto_Review_Status__c</fullName>
        <inlineHelpText>Status returned by ALV service</inlineHelpText>
        <label>EV SSL Audit ALV Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_SSL_Deviation_Comments__c</fullName>
        <label>EV SSL Audit Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_SSL_Deviation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Issues or qualifications noted in audit statement</description>
        <inlineHelpText>Issues or qualifications noted in audit statement</inlineHelpText>
        <label>EV SSL Audit Deviation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>Information verification phases</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Audit_ALV_Comments__c</fullName>
        <inlineHelpText>Explanation about why audit accepted when ALV status is FAIL </inlineHelpText>
        <label>Standard Audit ALV Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Authenticity_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only when authenticity of audit statement has been confirmed </inlineHelpText>
        <label>Standard Audit Authenticity Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Auto_Review_Results__c</fullName>
        <inlineHelpText>Results returned by ALV service</inlineHelpText>
        <label>Standard Audit ALV Results</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Auto_Review_Status__c</fullName>
        <inlineHelpText>Status returned by ALV service</inlineHelpText>
        <label>Standard Audit ALV Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Link__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Verified__c</fullName>
        <inlineHelpText>Root Store Manager to verify data fields in Auditor and Standard Audit sections</inlineHelpText>
        <label>Standard Audit Verified?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Verified</fullName>
                    <default>true</default>
                    <label>Not Verified</label>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Deviation_Comments__c</fullName>
        <label>Standard Audit Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Deviation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Issues or qualifications noted in audit statement</description>
        <inlineHelpText>Issues or qualifications noted in audit statement</inlineHelpText>
        <label>Standard Audit Deviation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CloneAuditCaseController.cls
/*
    Description: Class is created to clone audit case
    All case fields get copied except audit links, aududitor location, statuses, ALV fields, 
    Authenticity confirmation, description & comments.
*/
public with sharing class CloneAuditCaseController {
    
    public Id CaseId;
    
    public CloneAuditCaseController(Apexpages.StandardController ctrl) {
        CaseId = ctrl.getId();
    }
    
    public PageReference CloneAuditCase(){
        Id ClonedCaseId = null;
        try {
            DescribeSObjectResult describeResult = CaseId.getSObjectType().getDescribe();
            
            List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
    
            String query = ' SELECT ' + String.join( fieldNames, ',' ) +
                  ' FROM Case WHERE ' + ' id = :CaseId ' + ' LIMIT 1 ';
    
            // return generic list of sobjects or typecast to expected type
            List<Case> lstCases = Database.query( query );
            
            Case objClonedCase = lstCases[0].Clone(false);
             
             
            objClonedCase.Request_Status__c = 'Initial Request Received';   
                     
            objClonedCase.Auditor_Verified__c = 'Not Verified';
            
            // objClonedCase.Auditor_New__c = '';
            // objClonedCase.Auditor_Location_New__c = null;
            
            objClonedCase.Standard_Audit_Statement_Link__c = '';
            objClonedCase.Standard_Audit_Authenticity_Confirmed__c = false;
            objClonedCase.Standard_Audit_Auto_Review_Status__c = '';           
            objClonedCase.Standard_Audit_Auto_Review_Results__c = '';
            objClonedCase.Standard_Audit_ALV_Comments__c = '';
            objClonedCase.Standard_Deviation__c = False;
            objClonedCase.Standard_Deviation_Comments__c = '';
            objClonedCase.Standard_Audit_Verified__c = 'Not Verified';
            
            objClonedCase.Code_Signing_Audit_Statement_Link__c = '';
            objClonedCase.Code_Signing_Audit_Authenticity_Confirm__c = false;
            objClonedCase.Code_Signing_Audit_ALV_Status__c = '';
            objClonedCase.Code_Signing_Audit_ALV_Results__c = '';
            objClonedCase.Code_Signing_Audit_ALV_Comments__c = ''; 
            objClonedCase.Code_Signing_Deviation__c = False;
            objClonedCase.Code_Signing_Deviation_Comments__c = '';
            objClonedCase.Code_Signing_Audit_Verified__c = 'Not Verified';
            
            objClonedCase.BR_Audit_Statement_Link__c = '';
            objClonedCase.BR_Audit_Authenticity_Confirmed__c = false;
            objClonedCase.BR_Audit_Auto_Review_Status__c = '';
            objClonedCase.BR_Audit_Auto_Review_Results__c = '';
            objClonedCase.BR_Audit_ALV_Comments__c = ''; 
            objClonedCase.BR_Deviation__c = False;
            objClonedCase.BR_Deviation_Comments__c = '';
            objClonedCase.BR_Audit_Statement_Link_Verified__c = 'Not Verified';  
            
            objClonedCase.EV_Audit_Statement_Link__c = '';        
            objClonedCase.EV_SSL_Audit_Authenticity_Confirmed__c = false;
            objClonedCase.EV_SSL_Audit_Auto_Review_Status__c = '';
            objClonedCase.EV_SSL_Audit_Auto_Review_Results__c = '';
            objClonedCase.EV_SSL_Audit_ALV_Comments__c = ''; 
            objClonedCase.EV_SSL_Deviation__c = False;
            objClonedCase.EV_SSL_Deviation_Comments__c = '';
            objClonedCase.EV_Audit_Statement_Link_Verified__c = 'Not Verified';
             
            objClonedCase.EV_Code_Signing_Audit_Statement_Link__c = '';           
            objClonedCase.EV_Code_Signing_Audit_Auth_Confirmed__c = false;
            objClonedCase.EV_Code_Signing_Audit_AutoReviewStatus__c = '';
            objClonedCase.EV_Code_Signing_Audit_AutoReviewResults__c = '';
            objClonedCase.EV_Code_Signing_Audit_ALV_Comments__c = '';
            objClonedCase.EV_Code_Signing_Deviation__c = False;
            objClonedCase.EV_Code_Signing_Deviation_Comments__c = '';
            objClonedCase.EV_Code_Signing_Verified__c = 'Not Verified';
            
            objClonedCase.CP_CPS_Links_Verified__c = 'Not Verified';
            
            objClonedCase.Status = 'Open'; 
            objClonedCase.Description = ''; 
            objClonedCase.Comments__c = ''; 
            objClonedCase.Internal_Comments_on_Case__c = ''; 
            objClonedCase.Latest_Case_Comment__c = '';
            
            insert objClonedCase;
            ClonedCaseId = objClonedCase.Id;
        } catch (Exception ex) {
            Apexpages.addmessages(ex);
            return null;
        }
        return new PageReference('/'+ClonedCaseId);
    }
}