objects/Case.object
<CustomObject>
    <fields>
        <fullName>BR_Audit_Statement_Link__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>BR Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Statement_Link__c</fullName>
        <label>Code Signing Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Statement_Link__c</fullName>
        <description>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>EV SSL Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Statement_Link__c</fullName>
        <label>EV Code Signing Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Statement_Link__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://www.ccadb.org/cas/fields#uploading-documents.</inlineHelpText>
        <label>Standard Audit Statement (Link)</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CPACanada_File__c.object
<CustomObject>
    <description>CPACanada seal id mapping to report id</description>
    <fields>
        <fullName>Report_URL__c</fullName>
        <inlineHelpText>Report URL</inlineHelpText>
        <label>Report URL</label>
        <type>Url</type>
    </fields>
    <label>CPACanada File</label>
    <nameField>
        <label>Seal Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPACanada Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseMessageInlinePageController.cls
/*
    Description: Controller for CaseMessageInlinePage
*/
public with sharing class CaseMessageInlinePageController {
    
    public boolean isStandardAuditReportURLNotFound {get; set;}
    public boolean isBRAuditReportURLNotFound {get; set;}
    public boolean isCodeSigningAuditReportURLNotFound {get; set;}
    public boolean isEVSSLAuditReportURLNotFound {get; set;}
    public boolean isEVCodeSigningAuditReportURLNotFound {get; set;}
    
    public CaseMessageInlinePageController (Apexpages.standardcontroller controller){
        Cookie clientSrc = new Cookie('third_party_var', String.valueOf('value'),null,-1,true,'None; Secure');
        
        ApexPages.currentPage().setCookies(new Cookie[]{clientSrc});
        isStandardAuditReportURLNotFound = false;
        isBRAuditReportURLNotFound = false;
        isCodeSigningAuditReportURLNotFound = false;
        isEVSSLAuditReportURLNotFound = false;
        isEVCodeSigningAuditReportURLNotFound = false;
        
        Id caseid = controller.getId();
        
        if(caseid != null) {
            set<string> setofAuditUrls = new set<string>();
            List<Case> lstCases = new List<Case>([select Id,Standard_Audit_Statement_Link__c,Code_Signing_Audit_Statement_Link__c,
                    BR_Audit_Statement_Link__c,EV_Audit_Statement_Link__c,EV_Code_Signing_Audit_Statement_Link__c from Case Where Id =: caseid]);
            if(lstCases.size() > 0){
                Case objCase = lstCases[0];
                if(objCase.Standard_Audit_Statement_Link__c != null && objCase.Standard_Audit_Statement_Link__c.startswith('https://www.cpacanada.ca')){
                    setofAuditUrls.add(objCase.Standard_Audit_Statement_Link__c);
                }
                if(objCase.Code_Signing_Audit_Statement_Link__c != null && objCase.Code_Signing_Audit_Statement_Link__c.startswith('https://www.cpacanada.ca')){
                    setofAuditUrls.add(objCase.Code_Signing_Audit_Statement_Link__c);
                }
                if(objCase.BR_Audit_Statement_Link__c != null && objCase.BR_Audit_Statement_Link__c.startswith('https://www.cpacanada.ca')){
                    setofAuditUrls.add(objCase.BR_Audit_Statement_Link__c);
                }
                if(objCase.EV_Audit_Statement_Link__c != null && objCase.EV_Audit_Statement_Link__c.startswith('https://www.cpacanada.ca')){
                    setofAuditUrls.add(objCase.EV_Audit_Statement_Link__c);
                }
                if(objCase.EV_Code_Signing_Audit_Statement_Link__c != null && objCase.EV_Code_Signing_Audit_Statement_Link__c.startswith('https://www.cpacanada.ca')){
                    setofAuditUrls.add(objCase.EV_Code_Signing_Audit_Statement_Link__c);
                }
                
                if(setofAuditUrls.size() > 0){
                    map<string, Id> mapCPACanadaFiles = new map<string, Id>();
                    for(CPACanada_File__c file: [select Id,Name,Report_URL__c from CPACanada_File__c Where Report_URL__c != null and Report_URL__c in: setofAuditUrls]){
                        mapCPACanadaFiles.put(file.Report_URL__c.tolowercase(), file.Id);
                    }
                    if(objCase.Standard_Audit_Statement_Link__c != null && objCase.Standard_Audit_Statement_Link__c.startswith('https://www.cpacanada.ca') &&
                        !mapCPACanadaFiles.containskey(objCase.Standard_Audit_Statement_Link__c.tolowercase())){
                        isStandardAuditReportURLNotFound = true;
                    }
                    if(objCase.Code_Signing_Audit_Statement_Link__c != null && objCase.Code_Signing_Audit_Statement_Link__c.startswith('https://www.cpacanada.ca') &&
                        !mapCPACanadaFiles.containskey(objCase.Code_Signing_Audit_Statement_Link__c.tolowercase())){
                        isCodeSigningAuditReportURLNotFound = true;
                    }
                    if(objCase.BR_Audit_Statement_Link__c != null && objCase.BR_Audit_Statement_Link__c.startswith('https://www.cpacanada.ca') &&
                        !mapCPACanadaFiles.containskey(objCase.BR_Audit_Statement_Link__c.tolowercase())){
                        isBRAuditReportURLNotFound = true;
                    }
                    if(objCase.EV_Audit_Statement_Link__c != null && objCase.EV_Audit_Statement_Link__c.startswith('https://www.cpacanada.ca') &&
                        !mapCPACanadaFiles.containskey(objCase.EV_Audit_Statement_Link__c.tolowercase())){
                        isEVSSLAuditReportURLNotFound = true;
                    }
                    if(objCase.EV_Code_Signing_Audit_Statement_Link__c != null && objCase.EV_Code_Signing_Audit_Statement_Link__c.startswith('https://www.cpacanada.ca') &&
                        !mapCPACanadaFiles.containskey(objCase.EV_Code_Signing_Audit_Statement_Link__c.tolowercase())){
                        isEVCodeSigningAuditReportURLNotFound = true;
                    }
                    
                }
            }
        }
    }
    
}