objects/Case.object
<CustomObject>
    <fields>
        <fullName>Reason_for_Close_without_Sync__c</fullName>
        <label>Reason for Close without Sync</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>Information verification phases</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Root_Case__c.object
<CustomObject>
    <fields>
        <fullName>Case_No__c</fullName>
        <label>Case No</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Root Cases</relationshipLabel>
        <relationshipName>Root_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Request Received</fullName>
                    <default>true</default>
                    <label>Initial Request Received</label>
                </value>
                <value>
                    <fullName>Information Verification In Process</fullName>
                </value>
                <value>
                    <fullName>In Detailed CP/CPS Review</fullName>
                </value>
                <value>
                    <fullName>In Public Discussion</fullName>
                </value>
                <value>
                    <fullName>Discussion on Hold</fullName>
                </value>
                <value>
                    <fullName>CA Action Items from Discussion</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion</fullName>
                </value>
                <value>
                    <fullName>Approved, Pending Inclusion and EV</fullName>
                </value>
                <value>
                    <fullName>Included, Pending EV</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Request Withdrawn by CA</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Data Verified</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed - CA Unresponsive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Root Case</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Root Case No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CloseAuditCasesWithoutSyncController.cls
/*
    Description: class is used for closeing case
*/
public with sharing class CloseAuditCasesWithoutSyncController {
    
    //flag is used to show case complete section
    public boolean isCaseComplete {get; set;}
    
    //Reason to enter close case
    public string ReasontoCloseCase {get; set;}
    
    //case id
    Id caseid; 
    
    public CloseAuditCasesWithoutSyncController(ApexPages.StandardController controller) {
        caseid = controller.getId();
        
        List<Case> lstCase = new List<Case>([select Id, Request_Status__c, Status from Case Where Id =: caseid]);
        
        //check if case status is complete then set flag to true
        if(lstCase.size() > 0 && lstCase[0].Request_Status__c == 'Complete'){
            isCaseComplete = true;
        }
    }
    
    //method is used to close case and update reason
    public PageReference CloseCaseWithoutSync(){
        try {
            //check if reason is not blank then it should close case
            if(string.isnotblank(ReasontoCloseCase)){
                List<Root_Case__c> lstRootcases = new List<Root_Case__c>([select Id, Request_Status__c from 
                        Root_Case__c Where Case_No__c =: caseid]);
                for(Root_Case__c objRC: lstRootcases){
                    objRC.Request_Status__c = 'Complete';
                }
                if(lstRootcases.size() > 0){
                    //ignore case triggers.
                    CaseTriggerHelper.isCaseRecursive = true;
                    update lstRootcases;
                }
                Case objcase = new Case();
                objcase.Id = caseid;
                objcase.Request_Status__c = 'Complete';
                objcase.Reason_for_Close_without_Sync__c = ReasontoCloseCase;
                objcase.Status = 'Closed';
                update objcase;
                return new PageReference('/'+caseid);
            } else {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please enter reason to close case without syncing.'));
                return null;
            }
        } catch (exception ex){
            apexpages.addMessages(ex);
            return null;
        }
    }
    
}