objects/CPACanada_API_Detail__c.object
<CustomObject>
    <fields>
        <fullName>End_Point__c</fullName>
        <label>End Point</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Grant_Type__c</fullName>
        <label>Grant Type</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>CPACanada API</label>
    <nameField>
        <label>CPACanada API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPACanada API Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CPACanada_File__c.object
<CustomObject>
    <description>CPACanada seal id mapping to report id</description>
    <fields>
        <fullName>Report_Id__c</fullName>
        <inlineHelpText>Report Id</inlineHelpText>
        <label>Report Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Report_URL__c</fullName>
        <inlineHelpText>Report URL</inlineHelpText>
        <label>Report URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Seal_URL__c</fullName>
        <inlineHelpText>Seal URL</inlineHelpText>
        <label>Seal URL</label>
        <type>Url</type>
    </fields>
    <label>CPACanada File</label>
    <nameField>
        <label>Seal Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPACanada Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CPACanadaServiceControllerTest.cls
/*******************************************************************************************************
 Name: CPACanadaServiceControllerTest

 Dependencies: CPACanadaServiceController, CPACanadaServiceDeltaBatch, 
 CPACanadaServiceAllScheduler, CPACanadaServiceDeltaScheduler, CPACanadaServiceControllerTest

 Description: Test class for CPA Canada Controller
 
 Class is created for call API to get CPA Canada report file urls and update in Salesforce.
 
 Program logic is driven by 'parseResponse' parameter, it can be 'All' or 'Delta'
 
 
 Instructions:  
    
 *******************************************************************************************************
 Revision History:
 
     2/19/2019 - Created new class
     
 ******************************************************************************************************/

@isTest
public with sharing class CPACanadaServiceControllerTest {
    
    static testmethod void testCPACanadaAll(){
        
        CPACanada_API_Detail__c cpacanada = new CPACanada_API_Detail__c();
        cpacanada.Name = 'CPACanada API';
        cpacanada.End_Point__c = 'https://test.com';
        cpacanada.Grant_Type__c = 'xxxxxx';
        cpacanada.Password__c = 'xxxxxx';
        cpacanada.Username__c = 'xxxxxx';
        insert cpacanada; 
        
        CPACanada_File__c file = new CPACanada_File__c();
        file.name = '499';
        file.Report_Id__c = '221273';
        file.Seal_URL__c= 'https://www.cpacanada.ca/webtrustseal?sealid=499';
        file.Report_URL__c = 'https://www.cpacanada.ca/generichandlers/aptifyattachmenthandler.ashx?attachmentid=221273';
        insert file;
        
        CPACanadaServiceController.getAllCPACanadaFiles();
        
        file.Report_Id__c = '2212734';
        update file;
        
        CPACanadaServiceController.getAllCPACanadaFiles();
        
        CPACanadaServiceAllScheduler.scheduleMe('CPACanada Sync All Files'+System.now());
    }
    
    static testmethod void testCPACanadaDelta(){
        
        CPACanada_API_Detail__c cpacanada = new CPACanada_API_Detail__c();
        cpacanada.Name = 'CPACanada API';
        cpacanada.End_Point__c = 'https://test.com';
        cpacanada.Grant_Type__c = 'xxxxxx';
        cpacanada.Password__c = 'xxxxxx';
        cpacanada.Username__c = 'xxxxxx';
        insert cpacanada; 
        
        CPACanada_File__c file = new CPACanada_File__c();
        file.name = '499';
        file.Report_Id__c = '221273';
        file.Seal_URL__c= 'https://www.cpacanada.ca/webtrustseal?sealid=499';
        file.Report_URL__c = 'https://www.cpacanada.ca/generichandlers/aptifyattachmenthandler.ashx?attachmentid=221273';
        insert file;
        
        CPACanadaServiceController.getDeltaCPACanadaFiles();
        
        file.Report_Id__c = '2212734';
        update file;
        
        CPACanadaServiceController.getDeltaCPACanadaFiles();
        
        CPACanadaServiceDeltaScheduler.scheduleMe('CPACanada Sync Delta Files '+System.now());
        
        CPACanadaServiceDeltaBatch batch = new CPACanadaServiceDeltaBatch();
        Database.executebatch(batch, 1);
        
        CPACanadaServiceController.sendEmail('CPACanada API is not giving correct response.');
    }
}