objects/Custom_Reports_and_Processes__c.object
<CustomObject>
    <description>Documentation on processes and reports</description>
    <fields>
        <fullName>Deprecated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deprecated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>List the logic for the process/report</inlineHelpText>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lightning_Enabled__c</fullName>
        <label>Lightning Enabled</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Indicate if this report is internal only or public-facing. If public-facing, which web pages provide links to the report.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Batch Program</fullName>
                </value>
                <value>
                    <fullName>Custom Button</fullName>
                </value>
                <value>
                    <fullName>Custom Form</fullName>
                </value>
                <value>
                    <fullName>Custom Process</fullName>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                </value>
                <value>
                    <fullName>Custom Tab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Used_By__c</fullName>
        <label>Used By</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Mozilla Internal</fullName>
                </value>
                <value>
                    <fullName>Mozilla Public</fullName>
                </value>
                <value>
                    <fullName>Microsoft Internal</fullName>
                </value>
                <value>
                    <fullName>Microsoft Public</fullName>
                </value>
                <value>
                    <fullName>CAs Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Reports and Processes</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Reports and Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomReportsAndProcessesController.cls
/*
    Description: Shows all Documentation 
    
    Allow to filter with Used By, Type, Lightning Enabled, Deprecated, 
    
    Note: Only System Administrator and Standard User - Mozilla profiles users can edit Documentation from page.
*/
public with sharing class CustomReportsAndProcessesController {
    
    public List<Custom_Reports_and_Processes__c> lstDocumentation {get; set;}
    
    public Custom_Reports_and_Processes__c objDocumentFilter {get; set;}
    public List<SelectOption> lstUsedBy {get; set;}
    public string strUsedBy {get; set;}
    public boolean isEditAllow {get; set;}
    public boolean isEditDocument {get; set;}
    public Custom_Reports_and_Processes__c objEditDocument {get; set;}
    
    public CustomReportsAndProcessesController(){
        objDocumentFilter = new Custom_Reports_and_Processes__c();
        
        isEditAllow = false;
        List<Profile> lstProfiles = new List<Profile>([select Id,Name from Profile Where Name in ('System Administrator - Mozilla','Standard User - Mozilla') 
                                                        and Id =: UserInfo.getProfileId()]);
        if(lstProfiles.size() > 0) {
            isEditAllow = true;
        }
        lstUsedBy = new List<SelectOption>();
        lstUsedBy.add(new SelectOption('All', 'All'));
        lstUsedBy.add(new SelectOption('Mozilla Internal', 'Mozilla Internal'));
        lstUsedBy.add(new SelectOption('Microsoft Internal', 'Microsoft Internal'));
        lstUsedBy.add(new SelectOption('Mozilla Public', 'Mozilla Public'));
        lstUsedBy.add(new SelectOption('Microsoft Public', 'Microsoft Public'));
        filterDocumentation();
    }
    
    public void filterDocumentation(){
        if(objDocumentFilter != null || string.isnotblank(strUsedBy)){
            string strQuery = 'select Id,Name,Description__c,Name__c,URL__c,Used_By__c, Lightning_Enabled__c,Type__c,Deprecated__c from Custom_Reports_and_Processes__c Where ';
            boolean deprecated = objDocumentFilter.Deprecated__c;
            strQuery += ' Deprecated__c =: deprecated ';
            if(string.isnotblank(strUsedBy) && strUsedBy != 'All'){
                strQuery += ' AND Used_By__c INCLUDES (\'' + strUsedBy +  '\') ';
            }
            if(objDocumentFilter.Type__c != null){
                string type = objDocumentFilter.Type__c;
                strQuery += ' AND Type__c =: type ';
            }
            if(objDocumentFilter.Lightning_Enabled__c != null){
                string strLightningEnabled = objDocumentFilter.Lightning_Enabled__c;
                strQuery += ' AND Lightning_Enabled__c =: strLightningEnabled ';
            }
            system.debug('strQuery  ::: '+strQuery );
            lstDocumentation = new List<Custom_Reports_and_Processes__c>();
            lstDocumentation = Database.Query(strQuery);
        }
    }
    
    public void EditDocument(){
        if(Apexpages.currentpage().getparameters().get('index') != null) {
            Integer index = Integer.valueof(Apexpages.currentpage().getparameters().get('index'));
            if(lstDocumentation.size() > 0) {
                isEditDocument = true;
                objEditDocument = lstDocumentation[index];
            }
        }
    }
    
    public void SaveDocument() {
        try {
            update objEditDocument;
            isEditDocument = false;
            filterDocumentation();
        } catch(Exception ex) {
            Apexpages.addMessages(ex);
        }
    }
    
    public void CancelDocument(){
        isEditDocument = false;
        filterDocumentation();
    }
    
    String CurrentDate = ' ';
    // Get current Datetime in long date format   
    public String getCurrentDate() {
        Datetime cDT = System.now();
        CurrentDate = cDT.format('MMMM d, yyyy');
        return CurrentDate;
    }
}