objects/Custom_Reports_and_Processes__c.object
<CustomObject>
    <description>Documentation on processes and reports</description>
    <fields>
        <fullName>Lightning_Enabled__c</fullName>
        <label>Lightning Enabled</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Indicate if this report is internal only or public-facing. If public-facing, which web pages provide links to the report.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Batch Program</fullName>
                </value>
                <value>
                    <fullName>Custom Button</fullName>
                </value>
                <value>
                    <fullName>Custom Form</fullName>
                </value>
                <value>
                    <fullName>Custom Process</fullName>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                </value>
                <value>
                    <fullName>Custom Tab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Used_By__c</fullName>
        <label>Used By</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Mozilla Internal</fullName>
                </value>
                <value>
                    <fullName>Mozilla Public</fullName>
                </value>
                <value>
                    <fullName>Microsoft Internal</fullName>
                </value>
                <value>
                    <fullName>Microsoft Public</fullName>
                </value>
                <value>
                    <fullName>CAs Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Reports and Processes</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Reports and Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomReportsAndProcessesControllerTest.cls
/*
    Descrption: Test class for CustomReportsAndProcessesController
*/
@isTest
public with sharing class CustomReportsAndProcessesControllerTest {
    
    static testmethod void TestDocumentation(){
        
        Custom_Reports_and_Processes__c document = new Custom_Reports_and_Processes__c();
        document.Name__c = 'Report 1';
        document.Used_By__c = 'Mozilla Internal';
        document.Type__c = 'Custom Report';
        document.Lightning_Enabled__c = 'Yes';
        insert document;
        
        CustomReportsAndProcessesController controller = new CustomReportsAndProcessesController();
        controller.strUsedBy = 'Mozilla Internal';
        controller.objDocumentFilter.Type__c = 'Custom Report';
        controller.objDocumentFilter.Lightning_Enabled__c = 'Yes';
        controller.filterDocumentation();
        Apexpages.currentpage().getparameters().put('index','0');
        controller.EditDocument();
        controller.SaveDocument();
        controller.CancelDocument();
        controller.getCurrentDate();
    }
    
}