objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Alternate_CA_Name_s__c</fullName>
        <inlineHelpText>Legal Organization name as it appears in your CA’s CP/CPS and audit statements.</inlineHelpText>
        <label>Alternate CA Name(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CP_CPS_document_URLs__c</fullName>
        <inlineHelpText>URLs to the CA’s CP/CPS documents.</inlineHelpText>
        <label>CP/CPS document URLs</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reason_for_Denial__c</fullName>
        <label>Reason for Denial</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sponsored_By__c</fullName>
        <inlineHelpText>Which root store you are sponsored by, or will be applying for inclusion to.</inlineHelpText>
        <label>Sponsored By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Microsoft</fullName>
                </value>
                <value>
                    <fullName>Mozilla</fullName>
                </value>
                <value>
                    <fullName>Apple</fullName>
                    <isActive>false</isActive>
                    <label>Apple</label>
                </value>
                <value>
                    <fullName>Cisco</fullName>
                    <isActive>false</isActive>
                    <label>Cisco</label>
                </value>
                <value>
                    <fullName>Google</fullName>
                    <isActive>false</isActive>
                    <label>Google</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/LeadActionControllerTest.cls
/*******************************************************************************************************
 Name: LeadActionControllerTest

 Dependencies: LeadActionController controller class, LeadAction VF page, LeadActionTest class

 Description: Test class is created for LeadAction class. Once the Lead is converted, email is sent
 to the CA (Lead Convert email template). Another email is sent to admin@ccadb.org to issue license (no 
 template used). Lead conversion creates CA Owner and a Contact records.
 
 Instructions: Lead standard fields are automatically mapped by the lead conversion process.
 *******************************************************************************************************
 Revision History:
 
     4/30/2019 - Created new class
 *******************************************************************************************************/
 
@isTest
public with sharing class LeadActionControllerTest {
    
    static testMethod void TestLeadAction() {
        LeadActionController controller = new LeadActionController(new Apexpages.standardcontroller(new Lead()));
        controller.BackToRecord();
        
        Lead lead = new Lead(LastName = 'Test Lead',Company = 'Test Company', Email = 'test@gmail.com');
        insert lead;
        
        Apexpages.currentPage().getParameters().put('type','close');
        controller = new LeadActionController(new Apexpages.standardcontroller(lead));
        controller.CloseLeadWOConvert();
        controller.objLead.Reason_for_Denial__c = 'Test Reason';
        controller.CloseLeadWOConvert();
        
        lead = new Lead(LastName = 'Test Lead 1', Company = 'Test Company 1', Email = 'test1@gmail.com',
                        Alternate_CA_Name_s__c = 'Legal Company Name', Sponsored_By__c = 'Mozilla', 
                        CP_CPS_document_URLs__c = 'CP/CPS Document URLs');
        insert lead;
        Apexpages.currentPage().getParameters().put('type','convert');
        controller = new LeadActionController(new Apexpages.standardcontroller(lead));
        controller.BackToRecord();
    }
}