objects/Project_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity Desc</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <formula>Project_Goal__r.Goal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Goal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <inlineHelpText>1 = 1 hr
.75 = 45 min
.50 = 30 min
.25 = 15 min</inlineHelpText>
        <label>Hours</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Goal__c</fullName>
        <label>Goal Id</label>
        <referenceTo>Project_Goal__c</referenceTo>
        <relationshipLabel>Project Activities</relationshipLabel>
        <relationshipName>Project_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Goal__r.Project_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Activity Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Started</fullName>
                </value>
                <value>
                    <fullName>Work In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                    <default>true</default>
                    <label>Complete</label>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Activity</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Activity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Budgeted_Hours__c</fullName>
        <inlineHelpText>As planned in SOW</inlineHelpText>
        <label>Budgeted Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <inlineHelpText>As planned in SOW</inlineHelpText>
        <label>Goal</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>Give a number to identify the relative importance of this goal</inlineHelpText>
        <label>Priority</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <referenceTo>Project_Tracker__c</referenceTo>
        <relationshipLabel>Project Goals</relationshipLabel>
        <relationshipName>Project_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Started</fullName>
                    <default>true</default>
                    <label>Not Yet Started</label>
                </value>
                <value>
                    <fullName>Work In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Goal</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Budgeted_Hours__c</fullName>
        <inlineHelpText>Sum of Budgeted Hours for all goals related to this project
* Should not exceed Max Hours *</inlineHelpText>
        <label>Budgeted Hours</label>
        <summarizedField>Project_Goal__c.Budgeted_Hours__c</summarizedField>
        <summaryForeignKey>Project_Goal__c.Project_Name__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project Tracker</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProjectTimesheetControllerTest.cls
@isTest
public Class ProjectTimesheetControllerTest{
    
    public static testmethod void testTimesheet(){
        
        Project_Tracker__c project = new Project_Tracker__c(Name = 'Jixi');
        insert project;
        
        Project_Goal__c pg = new Project_Goal__c(Project_Name__c = project.Id, Status__c = 'Work In Progress', Priority__c = 1, Goal__c = 'Jixi Service', Budgeted_Hours__c = 100);
        insert pg;
        
        Project_Activity__c pa1 = new Project_Activity__c(Project_Goal__c = pg.Id, Hours__c = 2, Activity__c = 'Activity 1', Activity_Date__c = System.today().addDays(-5), Status__c = 'Not Yet Started');
        Project_Activity__c pa2 = new Project_Activity__c(Project_Goal__c = pg.Id, Hours__c = 4, Activity__c = 'Activity 2', Activity_Date__c = System.today().addDays(-5), Status__c = 'Complete');
        Project_Activity__c pa3 = new Project_Activity__c(Project_Goal__c = pg.Id, Hours__c = 6, Activity__c = 'Activity 3', Activity_Date__c = System.today(), Status__c = 'Work In Progress');
        Project_Activity__c pa4 = new Project_Activity__c(Project_Goal__c = pg.Id, Hours__c = 8, Activity__c = 'Activity 4', Activity_Date__c = System.today(), Status__c = 'Incomplete');
        Project_Activity__c pa5 = new Project_Activity__c(Project_Goal__c = pg.Id, Hours__c = 10, Activity__c = 'Activity 5', Activity_Date__c = System.today().addDays(-3), Status__c = 'Complete');
        
        insert new List<Project_Activity__c>{pa1, pa2, pa3, pa4, pa5};
        
        ProjectTimesheetController obj = new ProjectTimesheetController();
            
        System.assertEquals(obj.lstActivities.size(), 3);
    }
}