objects/Root_Case__c.object
<CustomObject>
    <fields>
        <fullName>X_509_Certificate_PEM__c</fullName>
        <label>X.509 Certificate (PEM)</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Root Case</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Root Case No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cases</pluralLabel>
    <recordTypes>
        <fullName>CA_Root_Inclusion_Request</fullName>
        <active>true</active>
        <description>Creation of the CA Root inclusion request</description>
        <label>CA Root Inclusion Request</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RootCasePEMParserBatchController.cls
/*
    Description: PEMParserBatchController is used to Run Batch from VF page.
*/
public with sharing class RootCasePEMParserBatchController {
    
    public String errorText { get; set; }
    
    public PageReference startBatch() {
        errorText = ' ';
        Id batchId = Database.executeBatch(new RootCasePEMParserBatch('select Id,Name,X_509_Certificate_PEM__c from Root_Case__c Where RecordType.DeveloperName = \'CA_Root_Inclusion_Request\''), 1);
        System.debug('batchId: '+batchId);
        return null;
    }
}